"""Chapter 17 content for the RDODI build: sources, findings, taxonomy and section bodies.
The book's chapter (3rd edition, chapter 17, PDF and Word Documents) was read on automatetheboringstuff.com on 2026-10-01 from its
published HTML page, fetched with curl through the session proxy and converted to text; its 12 practice questions and 3 practice
programs were read there. The book's downloadable files (Recursion_Chapter1.pdf, watermark.pdf, demo.docx, zophie.png,
guests.txt, dictionary.txt) were NOT opened, so every program that needs them is stated here as not executed; small stand-in PDF
and Word files were written by the scripts instead. The Python documentation pages (docs.python.org/3.14, which carried the
release number 3.14.8 when read), the pypdf 6.19.0 and python-docx 1.2.0 documentation, the pdfminer.six documentation and the
PyPI JSON metadata were read online on 2026-10-01. Every behaviour of the standard library was executed under Python 3.14.4.
Every behaviour of pypdf 6.19.0, python-docx 1.2.0 and pdfminer.six 20260107 was executed under Python 3.14.4 by
08-tooling/sen0414_ch17_library_run_v1_0_0.py after installing the three packages into a scratch folder; its printed lines are
kept in 08-tooling/sen0414_ch17_library_run_output_v1_0_0.txt and are what the findings below quote. The three packages are not
installed in the course interpreter, so the checks of this module run only the standard-library examples. Not executed at all:
the book's own sample files, a real Word or LibreOffice display of any file, a PDF viewer, the language model clean-up, the
Mu/IDE steps, and a brute-force attack on a real encrypted PDF. A claim not in this file was not made."""
__version__ = "1.0.0"
CH = 17
DATE = "2026-10-01"
PYVER = "3.14.4"
TITLE = "PDF and Word documents for an advanced course: chapter 17 of the 3rd edition and today's Python"
QUESTION = "What does chapter 17 of the 3rd edition teach about reading and writing PDF and Word documents with PyPDF and Python-Docx, which of its printed outputs and programs still hold with current releases of the packages under Python 3.14.4, and what must an advanced course add so that it matches current practice?"
CQS = ("Which operations read a document, which build a new one from parts of others, and which can be done at all, given that PDF and Word files are made for people to read and not for programs to parse?",
       "Which printed outputs, names and programs of the chapter differ in current releases of the packages, and on what source?")
PUBS = [
 ("P01","Automate the Boring Stuff with Python, 3rd edition - Chapter 17, PDF and Word Documents (Al Sweigart, No Starch Press, 2025)","https://automatetheboringstuff.com/3e/chapter17.html",True),
 ("P02","pypdf 6.19.0 user guide, Extract Text from a PDF (pypdf contributors, 2026)","https://pypdf.readthedocs.io/en/stable/user/extract-text.html",False),
 ("P03","pypdf 6.19.0 user guide, Post-Processing of Text Extraction (pypdf contributors, 2026)","https://pypdf.readthedocs.io/en/stable/user/post-processing-in-text-extraction.html",False),
 ("P04","pypdf 6.19.0 user guide, Extract Images (pypdf contributors, 2026)","https://pypdf.readthedocs.io/en/stable/user/extract-images.html",False),
 ("P05","pypdf 6.19.0 user guide, Merging PDF files (pypdf contributors, 2026)","https://pypdf.readthedocs.io/en/stable/user/merging-pdfs.html",False),
 ("P06","pypdf 6.19.0 user guide, Encryption and Decryption of PDFs (pypdf contributors, 2026)","https://pypdf.readthedocs.io/en/stable/user/encryption-decryption.html",False),
 ("P07","pypdf 6.19.0 user guide, Adding a Stamp or Watermark to a PDF (pypdf contributors, 2026)","https://pypdf.readthedocs.io/en/stable/user/add-watermark.html",False),
 ("P08","pypdf 6.19.0 user guide, Installation - optional dependencies for encryption and images (pypdf contributors, 2026)","https://pypdf.readthedocs.io/en/stable/user/installation.html",False),
 ("P09","pypdf 6.19.0 user guide, Security (pypdf contributors, 2026)","https://pypdf.readthedocs.io/en/stable/user/security.html",False),
 ("P10","python-docx 1.2.0 documentation, Quickstart (Canny, 2013)","https://python-docx.readthedocs.io/en/latest/user/quickstart.html",False),
 ("P11","python-docx 1.2.0 documentation, Working with Text - paragraphs and runs (Canny, 2013)","https://python-docx.readthedocs.io/en/latest/user/text.html",False),
 ("P12","python-docx 1.2.0 documentation, Understanding Styles (Canny, 2013)","https://python-docx.readthedocs.io/en/latest/user/styles-understanding.html",False),
 ("P13","python-docx 1.2.0 documentation, Working with Styles (Canny, 2013)","https://python-docx.readthedocs.io/en/latest/user/styles-using.html",False),
 ("P14","python-docx 1.2.0 documentation, API: Document objects - add_heading, add_page_break, add_picture (Canny, 2013)","https://python-docx.readthedocs.io/en/latest/api/document.html",False),
 ("P15","python-docx 1.2.0 documentation, API: Text objects - Run and its tri-state properties (Canny, 2013)","https://python-docx.readthedocs.io/en/latest/api/text.html",False),
 ("P16","pdfminer.six documentation (pdfminer.six contributors, 2026)","https://pdfminersix.readthedocs.io/en/latest/",False),
 ("P17","PyPI JSON metadata of pypdf, python-docx, docx, pdfminer.six, pdfplumber, reportlab, pdfrw, PyMuPDF, pdfkit and borb (Python Package Index, 2026)","https://pypi.org/pypi/pypdf/json",False),
 ("P18","The Python Standard Library, zipfile - Work with ZIP archives (Python 3.14 documentation source)","https://docs.python.org/3.14/library/zipfile.html",False),
 ("P19","The Python Standard Library, xml.etree.ElementTree (Python 3.14 documentation source)","https://docs.python.org/3.14/library/xml.etree.elementtree.html",False),
 ("P20","The Python Standard Library, os - listdir and walk (Python 3.14 documentation source)","https://docs.python.org/3.14/library/os.html",False),
 ("P21","The Python Standard Library, hashlib - password hashing and key derivation (Python 3.14 documentation source)","https://docs.python.org/3.14/library/hashlib.html",False),
 ("P22","Sorting Techniques - key functions (Python 3.14 documentation source)","https://docs.python.org/3.14/howto/sorting.html",False),
 ("P23","The Python Standard Library, Built-in Types - ranges (Python 3.14 documentation source)","https://docs.python.org/3.14/library/stdtypes.html",False),
 ("P24","The Python Standard Library, tempfile and io (Python 3.14 documentation source)","https://docs.python.org/3.14/library/tempfile.html",False),
 ("P25","PDF, Version 1.7 (ISO 32000-1:2008) - Sustainability of Digital Formats (Library of Congress, 2019)","https://www.loc.gov/preservation/digital/formats/fdd/fdd000277.shtml",False),
]
CONCEPTS = [("Section",x) for x in ("PDF Documents","Extracting Text","Post-Processing with AI","Extracting Images","Creating PDFs from Other Pages","Rotating Pages","Inserting Blank Pages","Adding Watermarks and Overlays","Encrypting and Decrypting PDFs","Project 12: Combine Select Pages from Many PDFs","Word Documents","Reading Word Documents","Getting the Full Text from a .docx File","Styling Paragraph and Run Objects","Applying Run Attributes","Writing Word Documents","Adding Headings","Adding Line and Page Breaks","Adding Pictures","Summary","Practice Questions","Practice Programs")] + \
 [("Concept",x) for x in ("PDF","PyPDF","Python-Docx","PdfReader","PdfWriter","Page object","Document object","Paragraph object","Run object","style","watermark","overlay","user password","owner password","brute-force password attack")] + \
 [("Method",x) for x in ("extract_text()","append()","merge()","rotate()","add_blank_page()","insert_blank_page()","merge_page()","encrypt()","decrypt()","add_paragraph()","add_run()","add_heading()","add_break()","add_picture()")] + \
 [("Function",x) for x in ("pdfminer.high_level.extract_text()","get_text()","docx.shared.Inches()","docx.shared.Cm()")]
FINDINGS = [
 ("F1","Background","Chapter 17 of the 3rd edition teaches two file formats that hold text for people to read: PDF with the PyPDF package (extract text, extract images, copy pages into a new file, rotate, insert blank pages, merge a watermark or overlay, encrypt and decrypt) and Word .docx with the Python-Docx package (Document, Paragraph and Run objects, styles, run attributes, new paragraphs, headings, breaks, pictures), with the project Combine Select Pages from Many PDFs, twelve practice questions and three practice programs: PDF Paranoia, Custom Invitations and PDF Password Breaker.",["P01"]),
 ("F2","Comparative analysis","The chapter's printed PyPDF behaviours reproduce with pypdf 6.19.0 under Python 3.14.4 on a stand-in six-page PDF: append with the tuple (0, 5) gives 5 pages, with (0, 5, 2) gives 3, with the list [0, 5] gives 2 pages (page one and page six), write() returns (False, the file object), merge at position 2 works, rotating needs a multiple of 90 and raises ValueError for 45, an encrypted file reports is_encrypted True, reading its pages raises FileNotDecryptedError with the message File has not been decrypted, a wrong password gives NOT_DECRYPTED and the right one OWNER_PASSWORD, and a copy made from the decrypted reader is not encrypted and keeps all pages.",["P01","P05","P06"]),
 ("F3","Comparative analysis","The chapter's Python-Docx behaviours reproduce with python-docx 1.2.0 on a stand-in document: a paragraph built from three text parts has four runs, bold is None on a run that never set it and True on the one that did, add_heading(text, 0) gives the Title style and levels 1 to 9 give Heading 1 to Heading 9, a run takes the linked style Quote Char while the paragraph style Quote is refused for a run with ValueError, a page break is one w:br element of type page, add_picture with Inches(1) and Cm(4) gives a width of 914400 and a height of 1440000 units, and Document() on a PDF raises PackageNotFoundError.",["P01","P10","P14","P15"]),
 ("F4","Comparative analysis","Project 12 as printed does not run: the loop appends to pdf_files, a name never defined, and Python 3.14.4 answers NameError: name 'pdf_files' is not defined, suggesting pdf_filenames; with that name corrected it combines A_cover.pdf, b_report.pdf and c_one.pdf into 3 pages (the pages after each first page, nothing from the one-page file), but run a second time in the same folder it reads its own combined.pdf as an input and writes 5 pages, so the program must skip its output file.",["P01","P20"]),
 ("F5","Comparative analysis","Several statements of the chapter differ from the current packages: the heading levels are given as 0 to 4 and then as 1 to 9 while add_heading accepts 0 to 9 and raises ValueError outside it; the list of default style names contains List Number with a trailing space and MacroText, neither of which exists in the default template, where the names are List Number and macro; strike, double_strike, outline and rtl are listed as Run attributes but work only on run.font (assigning run.strike = True raises no error and changes nothing), while bold, italic and underline work on both; the method insert_blank_page is printed with a stray space; and the chapter says only styles of the default set or already in the document can be used, while python-docx can add a style with styles.add_style and refuses a name the file does not define with KeyError.",["P01","P10","P12","P13","P14","P15"]),
 ("F6","Comparative analysis","Two optional dependencies and a default that the chapter does not mention matter in practice: page.images needs Pillow and raises ImportError otherwise, AES encryption needs the cryptography package, and encrypt() without an algorithm writes the legacy RC4 encryption (encryption dictionary version 2, revision 3) while algorithm='AES-256' writes version 5, revision 6; the pypdf documentation warns that RC4 is insecure, warns that image names can contain arbitrary characters and must be sanitised before they are used as file names, and lists AES-256-R5 as its recommendation beside the AES-256 the chapter uses.",["P04","P06","P08","P09"]),
 ("F7","Comparative analysis","Text extraction is weaker than the chapter's tone suggests and the gap is documented: the pages' texts are run together with no separator when they are added one after another as the chapter does, pypdf says post-processing is outside its scope and offers recipes whose dehyphenation leaves a space in follow ing when the row ends in a space and a hyphen, the pdfminer.six fallback returns form-feed-separated pages (for the stand-in PDF 'Page one text', two newlines, a form feed, 'Page two text'), and a PDF that holds only images yields little text without OCR.",["P01","P02","P03","P16"]),
 ("F8","Contemporary developments","The packages have moved on since the chapter's examples: PdfWriter.append takes the pages to copy as a keyword pages (its second positional parameter is now called outline_item, and a tuple given there is still read as a page range), PdfWriter can start from a reader with clone_from, merge_transformed_page can scale or move a stamp, python-docx has add_page_break, add_table and styles.add_style, a character can be told from a paragraph style by the style's type, and the package named docx on the Python Package Index is a different, older project (0.2.4) from python-docx (1.2.0), as the chapter warns.",["P05","P07","P10","P13","P17"]),
 ("F9","Conclusion","For an advanced course, chapter 17 is best taught as a limit on what can be automated: a PDF is a page description made for display and a .docx is a zip of XML parts, so a program can copy, reorder, rotate, stamp, encrypt, read the paragraphs and runs of and append to such files, but cannot reliably recover reading order, paragraphs or tables from a PDF and cannot edit a Word document in the middle without care; the chapter's printed outputs hold, and optional dependencies, the defaults of encryption, the rerun trap of Project 12, file-name hygiene, style handling and human review of every extraction are what the chapter leaves for the course to add.",["P01","P02","P05","P06","P11","P12","P18","P25"]),
]
# (top, mid, leaf, exemplar, definition, io-or-None)
TAX = [
 ("PdfFiles","PdfReading","PdfReaderObject","reader = pypdf.PdfReader('Recursion_Chapter1.pdf')","A PdfReader object stands for one PDF file, and its pages attribute is a list-like collection of page objects whose length is the page count: a six-page stand-in file gave 6 in the chapter 17 library run, and the book's 18-page sample file was not opened.",None),
 ("PdfFiles","PdfReading","TextExtraction","text += page.extract_text()","A page's extract_text() returns that page's text as one string, and adding the strings one after another joins the last word of a page to the first of the next with no separator; the stand-in below finds the text-showing operator of a content stream with a regular expression instead of with pypdf.",("(lambda s: __import__('re').findall(rb'\\((.*?)\\) Tj', s))(b'BT /F1 18 Tf 72 720 Td (Hello) Tj ET')","[b'Hello']")),
 ("PdfFiles","PdfReading","ExtractionFallback","pdfminer.high_level.extract_text(PDF_FILENAME)","When pypdf raises on a file, the chapter falls back on the pdfminer.six package, whose extract_text() function returns the whole file as one string; on the stand-in file it separated the pages with a form feed.",None),
 ("PdfFiles","PdfReading","TextPostProcessing","follow -\\ning the execution","Extracted text keeps a newline after every printed row and hyphenated words at row ends, and cleaning that up is a separate natural language task that pypdf leaves to the program; a regular expression joins the chapter's split word, while the pypdf documentation recipe leaves a space in it.",("__import__('re').sub(r' ?-\\n(\\w+)', r'\\1', 'follow -\\ning the execution')","'following the execution'")),
 ("PdfFiles","PdfReading","ImageExtraction","for image in page.images: file.write(image.data)","Each page has an images collection of image objects with a name and the bytes of the image, which the chapter writes to files opened in binary write mode; the names are not unique, may hold arbitrary characters, and need the optional Pillow package, so the chapter counts them with image_num and a page number.",None),
 ("PdfFiles","PdfWriting","PdfWriterObject","writer = pypdf.PdfWriter()","A PdfWriter object stands for a new PDF that starts with no pages and gets pages copied from other files, never text typed in; its write() method saves it to a file opened in binary write mode, and an empty writer cannot add a blank page because it has no page size to copy.",None),
 ("PdfFiles","PdfWriting","PageSelection","writer.append('Recursion_Chapter1.pdf', (0, 5))","A tuple of two or three integers given to append() selects pages the way range() does, counting from page index 0 and stopping before the last number, so (0, 5) copies the first five pages and (0, 5, 2) every second one.",("(list(range(0, 5)), list(range(0, 5, 2)))","([0, 1, 2, 3, 4], [0, 2, 4])")),
 ("PdfFiles","PdfWriting","TupleVersusList","writer.append(file, [0, 5])","For append() a tuple means a range of page indexes and a list means exactly the pages it names, so [0, 5] copies page index 0 and page index 5 only (2 pages in the library run) and a list may repeat a page.",("(lambda sel: list(range(*sel)) if isinstance(sel, tuple) else list(sel))([0, 5])","[0, 5]")),
 ("PdfFiles","PdfWriting","AppendVersusMerge","writer.merge(2, 'Recursion_Chapter1.pdf', (0, 5))","append() adds the copied pages at the end of the writer, while merge() takes a position first and inserts them there, shifting the pages that were at and after that position back; the list method append() of the same name only adds one item.",("(lambda pages: pages[:2] + ['new'] + pages[2:])(['p0', 'p1', 'p2'])","['p0', 'p1', 'new', 'p2']")),
 ("PdfFiles","PdfWriting","PageRotation","writer.pages[i].rotate(90)","A page's rotate() takes a multiple of 90, positive for clockwise and negative for counterclockwise, and raises ValueError for any other angle; successive calls add, so 90 and then 270 left the stored rotation at 360 in the library run.",("[a % 90 == 0 for a in (90, 180, 270, -90, 45)]","[True, True, True, True, False]")),
 ("PdfFiles","PdfWriting","BlankPages","writer.insert_blank_page(index=2)","add_blank_page() appends and insert_blank_page() inserts a page of the same size as the preceding page, and insert_blank_page wants its index given by name in the chapter's example; a blank page can later receive an overlay or a watermark.",None),
 ("PdfFiles","PdfWriting","WatermarkAndStamp","page.merge_page(watermark_page, over=False)","merge_page() lays the content of one page on another: over=True puts it on top as a stamp or overlay and over=False underneath as a watermark or underlay, and on the stand-in file the underlay text came first in the extracted text ('DRAFTPage one text') and the overlay text last.",None),
 ("PdfFiles","PdfProtection","PdfEncryption","writer.encrypt('swordfish', algorithm='AES-256')","encrypt() makes the written file unreadable without a password; with algorithm='AES-256' the library run wrote encryption version 5 revision 6, while a call without an algorithm wrote the older RC4 encryption, version 2 revision 3, and AES needs the cryptography package to be installed.",None),
 ("PdfFiles","PdfProtection","PdfDecryption","reader.decrypt('swordfish').name","A reader reports is_encrypted, refuses to give pages until decrypt() succeeds, and decrypt() returns a password type whose name is NOT_DECRYPTED for a wrong password, USER_PASSWORD or OWNER_PASSWORD for a right one; the two passwords are the first and second arguments of encrypt(), and one argument serves for both.",None),
 ("PdfFiles","PdfProtection","PasswordStrength","a password of around 14 to 16 characters that is not a dictionary word","The encryption is only as strong as the password, a PDF has no password-reset mechanism, and the chapter's own swordfish is named as a poor password because it is a dictionary word, which is what the practice program that tries 88,000 forms of 44,000 words exploits.",("2 * 44000","88000")),
 ("WordFiles","WordStructure","DocxPackage","zipfile.ZipFile('demo.docx')","A .docx file is a ZIP archive of XML parts, and a zip archive is recognised by the signature PK at the start of its records; the stand-in below checks the 22 bytes of an empty archive, and Document() on a PDF raises PackageNotFoundError in python-docx 1.2.0.",("__import__('zipfile').is_zipfile(__import__('io').BytesIO(b'PK\\x05\\x06' + bytes(18)))","True")),
 ("WordFiles","WordStructure","DocumentObject","doc = docx.Document('demo.docx')","A Document object stands for the whole .docx file, opened from a filename or, when the filename is omitted, a blank document built on the default template, and it holds the list of its paragraphs and the methods that add to its end.",None),
 ("WordFiles","WordStructure","ParagraphObject","doc.paragraphs[1].text","A Paragraph object is one block of text that begins where the user pressed Enter, with a text attribute holding its text without styling, a style, and a list of runs.",None),
 ("WordFiles","WordStructure","RunObject","doc.paragraphs[1].runs[1].text","A Run object is a contiguous stretch of text in one style inside a paragraph, so a paragraph holding plain, bold, plain and italic text has four runs; the stand-in below builds such a paragraph in XML and counts its runs with the standard library.",None),
 ("WordFiles","WordReading","ParagraphList","len(doc.paragraphs)","The paragraphs attribute of a document is a list of Paragraph objects in order, so len() counts them and an index picks one, and each paragraph's runs attribute lists its Run objects the same way.",None),
 ("WordFiles","WordReading","RunText","doc.paragraphs[1].runs[0].text","A Run object's text attribute holds only the text of that run, which is why text that changes style is split over several runs and why a search for a phrase in a paragraph's text is safer than a search in single runs.",None),
 ("WordFiles","WordReading","FullText","'\\n'.join(full_text)","The chapter's get_text() collects every paragraph's text in a list and joins it with newlines; indenting each paragraph or joining with two newlines changes the spacing, and the styling is lost.",("'\\n'.join(['Document Title', 'A plain paragraph'])","'Document Title\\nA plain paragraph'")),
 ("WordFiles","WordStyling","StyleKinds","doc.paragraphs[0].style = 'Normal'","A style is a named set of text attributes, and there are paragraph styles for Paragraph objects, character styles for Run objects and linked styles that exist in both forms; setting style to None associates none, and python-docx refuses a name the file does not define with KeyError.",None),
 ("WordFiles","WordStyling","LinkedStyle","doc.paragraphs[1].runs[0].style = 'Quote Char'","A linked style has a paragraph form and a character form, and the character form for a run is named with ' Char' added, so the paragraph style Quote is applied to a run as Quote Char; giving a run the paragraph style itself raised ValueError in the library run.",None),
 ("WordFiles","WordStyling","DefaultStyleNames","'Heading 1', 'List Bullet', 'Quote', 'Title'","The default template of python-docx 1.2.0 defines 36 paragraph styles, 27 character styles and 100 table styles; most names of the chapter's list exist, but List Number with a trailing space and MacroText do not (List Number and macro do).",None),
 ("WordFiles","WordStyling","CustomStyles","doc.styles.add_style('Citation', WD_STYLE_TYPE.PARAGRAPH)","The chapter says custom styles must be made in Word and then read from the style attribute, while python-docx can also add a style to the document in code with styles.add_style; a style that is not in the file is not applied.",None),
 ("WordFiles","WordStyling","RunAttributes","doc.paragraphs[1].runs[1].underline = True","A run's text attributes such as bold, italic and underline are set directly on the Run object in python-docx, while strike, double_strike, all_caps, small_caps, shadow, outline, rtl, imprint and emboss are set on its font attribute, because assigning them to the Run itself raises no error and changes nothing.",None),
 ("WordFiles","WordStyling","TriStateAttribute","run.bold = None","A text attribute is True (always on), False (always off) or None (taken from the run's style), so None is the way to hand the decision back to the style.",("[(lambda r, s: s if r is None else r)(v, True) for v in (True, False, None)]","[True, False, True]")),
 ("WordFiles","WordWriting","NewDocument","doc = docx.Document()","Calling Document() without a filename returns a blank document built on the default template, and save() writes it to a file named by a string.",None),
 ("WordFiles","WordWriting","AddParagraph","doc.add_paragraph('Hello, world!', 'Title')","add_paragraph() adds a paragraph at the end of the document and returns it, add_run() on that paragraph adds more text to its end and returns the Run, and both accept a style name as an optional second argument.",None),
 ("WordFiles","WordWriting","AddHeading","doc.add_heading('Header 1', 1)","add_heading() adds a paragraph in a heading style: level 0 is the Title style and 1 to 9 are Heading 1 to Heading 9, and python-docx raises ValueError outside 0 to 9, although the chapter names 0 to 4 and then 1 to 9.",("['Title' if n == 0 else 'Heading %d' % n for n in (0, 1, 4, 9)]","['Title', 'Heading 1', 'Heading 4', 'Heading 9']")),
 ("WordFiles","WordWriting","BreaksInDocument","doc.paragraphs[0].runs[0].add_break(docx.enum.text.WD_BREAK.PAGE)","add_break() on a Run adds a line break by default and a page break when given WD_BREAK.PAGE, which becomes one w:br element of type page after that run; python-docx also has add_page_break() on the document.",None),
 ("WordFiles","WordWriting","AddPicture","doc.add_picture('zophie.png', width=docx.shared.Inches(1), height=docx.shared.Cm(4))","add_picture() adds an image at the end of the document at its native size or at the width and height given, and Inches() and Cm() give lengths that Word stores in English metric units, 914400 to the inch and 360000 to the centimetre.",("(914400 * 1, 360000 * 4)","(914400, 1440000)")),
 ("Automation","CombineProject","FindPdfFiles","pdf_filenames.sort(key=str.lower)","The project lists the working folder with os.listdir, keeps names that end in .pdf and sorts them with key=str.lower because a plain sort puts every uppercase name before every lowercase one; the documentation says listdir returns names in arbitrary order.",("sorted(['alpha.pdf', 'Zeta.pdf'], key=str.lower) == ['alpha.pdf', 'Zeta.pdf'] and sorted(['alpha.pdf', 'Zeta.pdf']) == ['Zeta.pdf', 'alpha.pdf']","True")),
 ("Automation","CombineProject","CopyAfterFirstPage","writer.append(pdf_filename, (1, len(reader.pages)))","To drop each cover sheet the project copies page indexes 1 up to the page count, so a three-page file adds pages 1 and 2, and a one-page file adds none.",("[list(range(1, n)) for n in (3, 2, 1)]","[[1, 2], [1], []]")),
 ("Automation","CombineProject","RerunTrap","combined.pdf","The project writes combined.pdf into the same folder it reads, so a second run lists that file as an input and copies its pages after the first into the new result; in the library run the result grew from 3 to 5 pages until the output name was skipped.",None),
 ("Automation","PracticePrograms","PdfParanoia","os.walk('.') then name_encrypted.pdf","The first practice program walks a folder and its subfolders with os.walk, encrypts each PDF to a new name with _encrypted.pdf added before the extension, reads and decrypts the copy to check it, and only then deletes the original.",("__import__('os').path.splitext('sub/c.pdf')[0] + '_encrypted.pdf'","'sub/c_encrypted.pdf'")),
 ("Automation","PracticePrograms","CustomInvitations","add_break() after each invitation","The second program writes one invitation per guest to a Word document from a styled blank file and puts a page break after each one; a break after every invitation, the last included, makes one page more than the guests need, which the stand-in below counts and the library run confirmed as 5 breaks for 5 guests.",None),
 ("Automation","PracticePrograms","PasswordBreaker","for word in words: decrypt(word.lower()), decrypt(word.upper())","The third program tries the lower and upper case of each of over 44,000 dictionary words in decrypt(), 88,000 tries in all, which is a brute-force password attack and is why a dictionary word makes a poor password; the book's dictionary.txt and a real encrypted file were not used here.",("2 * 44000","88000")),
 ("Automation","Limits","PresentationFormat","PDF: a page description, .docx: a zip of XML","PDF was made for printing and displaying pages and Word for editing by people, so neither is designed to be parsed into paragraphs, tables and reading order by a program, which is the reason the chapter gives for its limits and the one that the next chapter's CSV, JSON and XML formats answer.",None),
 ("Automation","Limits","HumanReview","a human must always review the output","The chapter suggests a large language model to clean up extracted text and insists that a person reviews the result, since its own trial removed a chapter number that was meant to stay; the model step was not run here.",None),
 ("Automation","Limits","OtherPdfLibraries","pdfplumber, ReportLab, pdfrw, PyMuPDF, pdfkit, borb","The chapter's summary names six other PDF packages to search for on PyPI, and all six were found there with their current release: pdfplumber 0.11.10, reportlab 5.0.1, pdfrw 0.4, PyMuPDF 1.28.2, pdfkit 1.0.0 and borb 3.0.9.",None),
 ("Automation","Limits","PackageNames","pip install python-docx, import docx","The package to install is python-docx (1.2.0) and the module to import is docx; a different, older package named docx exists on PyPI (0.2.4), and pypdf is installed as pypdf and, for AES or images, with its crypto or image extras.",None),
]
ERRORS = []
CLAIMS = [
 ("(list(range(0, 5)), list(range(0, 5, 2)), list(range(1, 1)))", "([0, 1, 2, 3, 4], [0, 2, 4], [])"),
 ("sorted(['b.pdf', 'A.pdf', 'C.pdf'])", "['A.pdf', 'C.pdf', 'b.pdf']"),
 ("sorted(['b.pdf', 'A.pdf', 'C.pdf'], key=str.lower)", "['A.pdf', 'b.pdf', 'C.pdf']"),
 ("(lambda l: (l.append('x'), l))([])", "(None, ['x'])"),
 ("isinstance(range(3), list)", "False"),
 ("__import__('hashlib').sha256(b'SWORDFISH').hexdigest() == __import__('hashlib').sha256(b'swordfish'.upper()).hexdigest()", "True"),
 ("(1 * 914400) / 360000", "2.54"),
 ("hasattr(__import__('hashlib'), 'pbkdf2_hmac') and hasattr(__import__('hashlib'), 'scrypt')", "True"),
]
S = "(Sweigart, 2025)"; PY = "(pypdf contributors, 2026)"; DX = "(Canny, 2013)"; PM = "(pdfminer.six contributors, 2026)"; PSF = "(Python Software Foundation, 2026)"; LOC = "(Library of Congress, 2019)"; PIP = "(Python Package Index, 2026)"
BODY = {
 "PdfFiles": "PDF files are read, written and protected through the PyPDF package, whose reader and writer objects the chapter presents " + S + " " + PY + ".",
 "PdfReading": "Reading a PDF means opening it with a reader, asking each page for its text or images, and accepting that the result may be imperfect " + S + " " + PY + ".",
 "PdfReaderObject": "pypdf.PdfReader('Recursion_Chapter1.pdf') returns a reader whose pages attribute is list-like and can be measured with len(), 18 for the book's sample file " + S + "; in the chapter 17 library run a stand-in file of six pages gave 6 with pypdf 6.19.0 under Python 3.14.4, and the book's own sample file was not opened " + PY + ".",
 "TextExtraction": "The program extractpdftext.py loops over reader.pages and adds page.extract_text() to a string, then writes the string with open(TEXT_FILENAME, 'w', encoding='utf-8') " + S + "; joining the pages this way leaves no separator, 'Page one textPage two text' for two stand-in pages, whereas '\\n'.join keeps them apart, and the pypdf documentation adds extraction modes, a visitor function and a memory warning for very large content streams " + PY + ".",
 "ExtractionFallback": "If pypdf raises an exception on a file, the program calls pdfminer.high_level.extract_text(PDF_FILENAME), which returns the whole text as one string " + S + "; on the stand-in file it returned the two pages separated by a form feed (pdfminer.six 20260107), and its documentation describes the package as one for extracting information from PDF documents " + PM + ".",
 "TextPostProcessing": "The extracted text keeps a newline after each row and hyphenated words such as follow -\\ning, and the chapter asks a language model to clean it up and a person to review the result " + S + "; the pypdf documentation says post-processing is outside its scope and gives a dehyphenation recipe that, run on the chapter's row, leaves follow ing, while a regular expression that also takes the space gives following " + PY + ".",
 "ImageExtraction": "Each page's images attribute gives objects with a name and data, which extractpdfimages.py writes to files named from a counter, the page number and the image name, catching exceptions so that one failing page does not stop the program " + S + "; in pypdf 6.19.0 reading page.images without Pillow raised ImportError asking for pypdf[image], and the documentation warns that image names can contain arbitrary characters and must be sanitised before they become file names " + PY + ".",
 "PdfWriting": "Writing a PDF with PyPDF means copying, rotating, inserting and merging pages from other files into a writer and then saving it " + S + " " + PY + ".",
 "PdfWriterObject": "pypdf.PdfWriter() is a blank document with no pages, PyPDF cannot write arbitrary text to it, and write() saves it to a file opened with 'wb', returning a tuple that the chapter prints as (False, <_io.BufferedWriter name='first_five_pages.pdf'>), which the library run reproduced " + S + "; add_blank_page() on an empty writer raised PageSizeNotDefinedError " + PY + ".",
 "PageSelection": "writer.append('Recursion_Chapter1.pdf', (0, 5)) copies the first five pages, and (0, 5, 2) skips like range(), so list(range(0, 5)) is [0, 1, 2, 3, 4] and list(range(0, 5, 2)) is [0, 2, 4] " + S + "; the library run gave 5 and 3 pages, and in pypdf 6.19.0 the second positional parameter is called outline_item while pages is the keyword for the selection " + PY + " " + PSF + ".",
 "TupleVersusList": "append() reads the tuple (0, 5) as a range and the list [0, 1, 2, 3, 4] as the pages to copy, so the list [0, 5] copies page index 0 and page index 5 only " + S + "; the library run gave 2 pages, 'Page one text' and 'Page six', and the pypdf documentation shows a list that repeats a page, [0, 1, 0, 2, 0] " + PY + ".",
 "AppendVersusMerge": "append() adds the copied pages at the end and merge() inserts them at a position, shifting the original pages back " + S + "; merge(2, 'a.pdf', (0, 5)) on a five-page writer gave 11 pages in the library run with no warning, and the documentation still shows merge with a position and a pages keyword " + PY + ".",
 "PageRotation": "rotate(90), rotate(180) and rotate(270) turn a page clockwise and negative values counterclockwise, only in increments of 90 " + S + "; the library run gave a rotation of 90, then 0 after rotate(-90) on a rotated page, then 360 after rotate(270) on a rotated page, and ValueError: Rotation angle must be a multiple of 90 for 45 " + PY + ".",
 "BlankPages": "add_blank_page() appends a page and insert_blank_page(index=2) puts one at page index 2, both of the size of the preceding page " + S + "; the library run gave a page box of [0.0, 0.0, 612, 792] for a blank page after pages of that size and 12 pages after the insertion into a writer of 11 " + PY + ".",
 "WatermarkAndStamp": "page.merge_page(watermark_page, over=False) puts the watermark PDF's first page under each page and over=True puts it on top, for a stamp or overlay " + S + "; on the stand-in file the text of the underlay came before the page text, 'DRAFTPage one text', and the overlay after it, 'Page one textDRAFT', and the documentation adds merge_transformed_page for scaled or moved stamps " + PY + ".",
 "PdfProtection": "A PDF can be encrypted with a password and read again only by giving that password " + S + " " + PY + ".",
 "PdfEncryption": "writer.encrypt('swordfish', algorithm='AES-256') makes the saved file unreadable without the password, and the chapter advises a password of different character types and 14 to 16 characters that is not a dictionary word " + S + "; the library run wrote encryption version 5 revision 6 for AES-256 and version 2 revision 3 when no algorithm was given, the documentation says RC4 is the default, calls it insecure and recommends AES, and AES needs the cryptography package " + PY + ".",
 "PdfDecryption": "reader.is_encrypted is True for the encrypted file, reader.pages[0] raises FileNotDecryptedError, decrypt('an incorrect password').name is 'NOT_DECRYPTED' and decrypt('swordfish').name is 'OWNER_PASSWORD' " + S + "; all four reproduced, a file encrypted with the two passwords 'user' and 'owner' gave USER_PASSWORD and OWNER_PASSWORD, and appending the decrypted reader to a writer gave an unencrypted file of six pages " + PY + ".",
 "PasswordStrength": "The chapter notes that an encrypted PDF can never be read again if the password is forgotten and that swordfish is a poor password because it is a dictionary word " + S + "; hashlib's documentation recommends the key derivation functions pbkdf2_hmac and scrypt for storing passwords, and the plain hash used in the stand-in below is only a teaching device " + PSF + ".",
 "WordFiles": "Word files with the .docx extension are read and written through the Python-Docx package, whose three data types are Document, Paragraph and Run " + S + " " + DX + ".",
 "WordStructure": "A .docx file is a structured document: a Document holds Paragraph objects and each Paragraph holds Run objects " + S + " " + DX + ".",
 "DocxPackage": "The chapter treats a .docx file as more than text, with font, size and colour attached to the text " + S + "; it is a zip archive of XML parts, which the library run listed as [Content_Types].xml, _rels/.rels, docProps/core.xml, docProps/app.xml, word/document.xml and word/_rels/document.xml.rels, and docx.Document('a.pdf') raised PackageNotFoundError " + DX + " " + PSF + ".",
 "DocumentObject": "docx.Document('demo.docx') returns a Document object for the file, and docx.Document() returns a new blank one " + S + "; the book's demo.docx was not opened, and a stand-in document was built in the library run with python-docx 1.2.0 " + DX + ".",
 "ParagraphObject": "A new paragraph begins whenever the user presses Enter, a Paragraph object's text attribute holds its text, and the chapter prints 'Document Title' and 'A plain paragraph with some bold text and some italic' for the first two paragraphs of demo.docx, in one place without the space as 'DocumentTitle' " + S + "; a paragraph is the block-level object and a run the inline one " + DX + ".",
 "RunObject": "A Run object is a contiguous run of text with the same style, and the chapter's second paragraph has four runs: 'A plain paragraph with some ', 'bold', ' and some ' and 'italic' " + S + "; built with add_run the library run gave the same four texts, and the printed third run ' text and some ' in the book's prose differs from the printed output ' and some ' " + DX + ".",
 "WordReading": "Reading a Word document means listing its paragraphs, their runs and their text " + S + " " + DX + ".",
 "ParagraphList": "len(doc.paragraphs) is 7 for the book's demo.docx, and doc.paragraphs[1].runs has length 4 " + S + "; the book's file was not opened, and the stand-in paragraph built with add_run in three parts of text had 4 runs, read back in the order they were added " + DX + ".",
 "RunText": "doc.paragraphs[1].runs[1].text is 'bold' and runs[3].text is 'italic' " + S + "; on the stand-in document the run that set bold gave bold True and the others None, so the formatting lives on the run and not in the paragraph's text " + DX + ".",
 "FullText": "get_text(filename) opens the document, appends every paragraph's text to a list and returns '\\n'.join(full_text), which the chapter prints as six lines for demo.docx, and changing the append to '  ' + para.text indents while joining with '\\n\\n' double-spaces the result " + S + "; the stand-in run gave 'A plain paragraph with some bold and some italic' for the joined runs " + DX + ".",
 "WordStyling": "Styles and run attributes give the same look to many paragraphs or runs, and python-docx reads and sets them by name " + S + " " + DX + ".",
 "StyleKinds": "Word has paragraph styles for Paragraph objects, character styles for Run objects and linked styles for both; to style a paragraph or run its style attribute is set to the style's name, and None removes the association " + S + "; in python-docx 1.2.0 the name of a style the file does not define raised KeyError: \"no style with name 'NoSuchStyle'\", while the documentation says Word silently ignores such a style, and a built-in style appears in the file only once it is used " + DX + ".",
 "LinkedStyle": "A linked style for a Run takes ' Char' after its name, so Paragraph style 'Quote' is Run style 'Quote Char' " + S + "; the library run gave run style Quote Char of type CHARACTER and ValueError: assigned style is type PARAGRAPH (1), need type CHARACTER (2) for the paragraph style Quote on a run " + DX + ".",
 "DefaultStyleNames": "The chapter lists the default Word style names from Normal and Body Text to Title, including 'List Number ' with a trailing space and 'MacroText' " + S + "; the default template of python-docx 1.2.0 holds 36 paragraph, 27 character and 100 table styles and does not define those two names but List Number and macro, and the documentation says built-in styles are found by their English names " + DX + ".",
 "CustomStyles": "The chapter tells the reader to define custom styles in the Word application and read them from a paragraph or run " + S + "; python-docx 1.2.0 can add a paragraph style to a document with styles.add_style('Citation', WD_STYLE_TYPE.PARAGRAPH), which the library run did, and a style can be given a base style " + DX + ".",
 "RunAttributes": "Table 17-1 lists twelve text attributes of Run objects: bold, italic, underline, strike, double_strike, all_caps, small_caps, shadow, outline, rtl, imprint and emboss " + S + "; in python-docx 1.2.0 the Run object defines bold, italic and underline and all twelve are attributes of run.font, and the library run showed that run.strike = True raises no error yet adds no w:strike element to the XML, while run.font.strike = True does " + DX + ".",
 "TriStateAttribute": "Each attribute is True (always on), False (always off) or None (whatever the run's style says) " + S + "; the library run set bold to True, False and None in turn and read back True, False and None, and the documentation states that None means the value is inherited from the style hierarchy " + DX + ".",
 "WordWriting": "Writing a Word document means creating a blank document, adding paragraphs, runs, headings, breaks and pictures to its end, and saving it " + S + " " + DX + ".",
 "NewDocument": "docx.Document() returns a blank Word document and doc.save('helloworld.docx') writes it " + S + "; the library run saved the stand-in documents to memory and to files, and the rendering in Word or LibreOffice that the chapter's figures show was not checked " + DX + ".",
 "AddParagraph": "doc.add_paragraph('Hello, world!') adds a paragraph and returns it, para.add_run(' This text...') adds text to its end, and a second argument such as 'Title' gives the style " + S + "; the library run gave style Title for doc.add_paragraph('Hello, world!', 'Title') " + DX + ".",
 "AddHeading": "doc.add_heading('Header 0', 0) to doc.add_heading('Header 4', 4) add headings, 0 being the Title style, and the chapter says the argument ranges from 0 to 4 and then that 1 to 9 are heading levels " + S + "; python-docx accepts 0 to 9 and raised ValueError: level must be in range 0-9, got 10 for 10 " + DX + ".",
 "BreaksInDocument": "add_break() on a Run adds a line break and, given docx.enum.text.WD_BREAK.PAGE, a page break, as in the two-page example twoPage.docx " + S + "; the library run found one page-break element in the first run's XML, and the document also has add_page_break() " + DX + ".",
 "AddPicture": "doc.add_picture('zophie.png', width=docx.shared.Inches(1), height=docx.shared.Cm(4)) returns an InlineShape, and the width and height default to the image's normal size " + S + "; the library run gave a width of 914400 and a height of 1440000, Inches(1) and Cm(4) in English metric units, and a native size computed from pixels and a dpi of 72 when the image carries none, which the book's zophie.png was not used to check " + DX + ".",
 "Automation": "Programs that combine, protect and produce PDF and Word files put the chapter's objects to work, inside limits that the formats impose " + S + ".",
 "CombineProject": "Project 12 combines all the PDFs of the working folder, sorted alphabetically, dropping each first page, into combined.pdf " + S + ".",
 "FindPdfFiles": "The program lists the folder with os.listdir('.'), keeps the names ending in .pdf and sorts them with sort(key=str.lower) so that uppercase does not come first " + S + "; the listing is in arbitrary order and sort() is stable " + PSF + ".",
 "CopyAfterFirstPage": "For each file the program calls writer.append(pdf_filename, (1, len(reader.pages))) to copy page index 1 to the end and leave out the cover sheet " + S + "; with the stand-in files of 2, 3 and 1 pages the combined result had 3 pages, and the one-page file added none " + PSF + ".",
 "RerunTrap": "The chapter's listing as printed appends to pdf_files, which is not defined, and Python 3.14.4 answers NameError: name 'pdf_files' is not defined. Did you mean: 'pdf_filenames'? " + S + "; with the name corrected, a second run in the same folder read combined.pdf as an input and wrote 5 pages instead of 3, and skipping that file gave 3 again " + PSF + ".",
 "PracticePrograms": "The chapter ends with twelve practice questions and three practice programs " + S + ".",
 "PdfParanoia": "PDF Paranoia asks for an os.walk over a folder tree that encrypts each PDF with a password given on the command line, saves it with _encrypted.pdf added, reads and decrypts the copy to check it before the original is deleted, and a second program that decrypts every encrypted PDF it finds and prints a message for a wrong password " + S + "; only the file-naming and the check-before-delete logic were run here, with a toy reversible transformation in place of PDF encryption " + PSF + ".",
 "CustomInvitations": "Custom Invitations reads guests.txt and writes a Word document with one invitation per guest, using styles that already exist in a blank Word file and add_break() after the last paragraph of each invitation " + S + "; with the five guests of the book's example the library run wrote 5 page breaks, one after the last invitation as well, and the stand-in counted 6 pages against 5 for a break only between invitations " + DX + ".",
 "PasswordBreaker": "PDF Password Breaker reads dictionary.txt of over 44,000 words and passes the lowercase and uppercase form of each to decrypt(), 88,000 tries, which took a couple of minutes on the author's laptop " + S + "; the book's file and a real encrypted PDF were not used, and the stand-in tried the forms of four words against a SHA-256 digest and found SWORDFISH on the sixth try " + PSF + ".",
 "Limits": "The chapter closes on why PDF and Word are hard to automate and where the reader can go next " + S + ".",
 "PresentationFormat": "The summary says that many limits come from formats meant to display nicely for human readers and not to be parsed by software " + S + "; the Library of Congress describes PDF as a format for formatted, page-oriented documents, and a .docx is a zip of XML parts " + LOC + " " + PSF + ".",
 "HumanReview": "The chapter's language model prompt asks for paragraphs on single lines, headers and footers removed and hyphens at row ends joined, and its trial output lost the chapter number 1 " + S + "; the model step was not run here.",
 "OtherPdfLibraries": "The summary recommends searching PyPI for pdfplumber, ReportLab, pdfrw, PyMuPDF, pdfkit and borb " + S + "; the PyPI metadata read on 2026-10-01 listed pdfplumber 0.11.10, reportlab 5.0.1, pdfrw 0.4, PyMuPDF 1.28.2, pdfkit 1.0.0 and borb 3.0.9 " + PIP + ".",
 "PackageNames": "The warning says to install Python-Docx and not Docx, and to write import docx " + S + "; PyPI lists python-docx 1.2.0 and a separate docx 0.2.4, and pypdf 6.19.0, which asks for extras for AES and images " + PIP + " " + PY + ".",
}

# (what, program, printed output) - each executed under Python 3.14.4 with only the standard library
BEH = [
 ['a PDF is a file of objects that stdlib code can write and read back', 'import re\ndef make_pdf(pages):\n    objs = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [%s] /Count %d >>" % (" ".join("%d 0 R" % (4 + 2 * i) for i in range(len(pages))), len(pages)), "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"]\n    for i, t in enumerate(pages):\n        s = "BT /F1 18 Tf 72 720 Td (%s) Tj ET" % t\n        objs.append("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents %d 0 R >>" % (5 + 2 * i))\n        objs.append("<< /Length %d >>\\nstream\\n%s\\nendstream" % (len(s), s))\n    out = "%PDF-1.4\\n"\n    for i, o in enumerate(objs, 1):\n        out += "%d 0 obj\\n%s\\nendobj\\n" % (i, o)\n    return (out + "%%EOF\\n").encode("latin-1")\ndata = make_pdf(["Page one", "Page two", "Page three"])\nprint(data[:8], type(data).__name__)\nprint(len(re.findall(rb"/Type /Page\\b", data)))\nprint(re.findall(rb"\\((.*?)\\) Tj", data))\n', "b'%PDF-1.4' bytes\n3\n[b'Page one', b'Page two', b'Page three']"],
 ['extract_text per page, then join: pages run together without a separator', 'pages = ["Page one text", "Page two text"]\ntext = ""\nfor page in pages:\n    text += page\nprint(repr(text))\nprint(repr("\\n".join(pages)))\n', "'Page one textPage two text'\n'Page one text\\nPage two text'"],
 ['the chapter example of a hyphenated row, and the pypdf documentation recipe', 'import re\nraw = "Most new programmers trace through what a program does by follow -\\ning the execution. It\'s an easy way to read code."\nprint(repr(re.sub(r" ?-\\n(\\w+)", r"\\1", raw)))\ndef dehyphenate(lines, line_no):\n    next_line = lines[line_no + 1]\n    word_suffix = next_line.split(" ")[0]\n    lines[line_no] = lines[line_no][:-1] + word_suffix\n    lines[line_no + 1] = lines[line_no + 1][len(word_suffix):]\n    return lines\ndef remove_hyphens(text):\n    lines = [line.rstrip() for line in text.split("\\n")]\n    line_numbers = [n for n, line in enumerate(lines[:-1]) if line.endswith("-")]\n    for n in line_numbers:\n        lines = dehyphenate(lines, n)\n    return "\\n".join(lines)\nprint(repr(remove_hyphens(raw)))\nprint(repr(remove_hyphens("a well-\\nknown fact")))\n', '"Most new programmers trace through what a program does by following the execution. It\'s an easy way to read code."\n"Most new programmers trace through what a program does by follow ing\\n the execution. It\'s an easy way to read code."\n\'a wellknown\\n fact\''],
 ['a tuple names a range of page indexes and a list names the pages one by one', 'def pages_copied(selection):\n    if isinstance(selection, tuple):\n        return list(range(*selection))\n    return list(selection)\nprint(pages_copied((0, 5)), pages_copied((0, 5, 2)), pages_copied([0, 5]), pages_copied([0, 1, 0, 2, 0]))\nprint(list(range(0, 5)) == pages_copied((0, 5)), list(range(0, 5)) == pages_copied([0, 5]))\n', '[0, 1, 2, 3, 4] [0, 2, 4] [0, 5] [0, 1, 0, 2, 0]\nTrue False'],
 ['Project 12 copies pages from index 1, so a one-page file adds nothing', 'for count in (3, 2, 1):\n    print(count, list(range(1, count)))\n', '3 [1, 2]\n2 [1]\n1 []'],
 ['listing a folder and picking PDFs: sort with key=str.lower, and the output file joins the list on a second run', 'import os, tempfile\nwith tempfile.TemporaryDirectory() as folder:\n    for name in ("b_report.pdf", "Zeta.pdf", "notes.txt", "alpha.pdf"):\n        open(os.path.join(folder, name), "w").close()\n    def pick():\n        names = [f for f in os.listdir(folder) if f.endswith(".pdf")]\n        names.sort(key=str.lower)\n        return names\n    first = pick()\n    print(first, sorted(first))\n    open(os.path.join(folder, "combined.pdf"), "w").close()\n    print(pick())\n    print([f for f in pick() if f != "combined.pdf"])\n', "['alpha.pdf', 'b_report.pdf', 'Zeta.pdf'] ['Zeta.pdf', 'alpha.pdf', 'b_report.pdf']\n['alpha.pdf', 'b_report.pdf', 'combined.pdf', 'Zeta.pdf']\n['alpha.pdf', 'b_report.pdf', 'Zeta.pdf']"],
 ['a .docx file is a zip of XML parts, read here with zipfile and ElementTree (a real file has more parts)', 'import io, zipfile\nimport xml.etree.ElementTree as ET\nW = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"\nbody = (\'<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>\'\n        \'<w:p><w:pPr><w:pStyle w:val="Title"/></w:pPr><w:r><w:t>Document Title</w:t></w:r></w:p>\'\n        \'<w:p><w:r><w:t xml:space="preserve">A plain paragraph with some </w:t></w:r><w:r><w:rPr><w:b/></w:rPr><w:t>bold</w:t></w:r>\'\n        \'<w:r><w:t xml:space="preserve"> and some </w:t></w:r><w:r><w:rPr><w:i/></w:rPr><w:t>italic</w:t></w:r></w:p></w:body></w:document>\')\nbuf = io.BytesIO()\nwith zipfile.ZipFile(buf, "w") as z:\n    z.writestr("word/document.xml", body)\nz = zipfile.ZipFile(io.BytesIO(buf.getvalue()))\nprint(z.namelist())\nparagraphs = ET.fromstring(z.read("word/document.xml")).findall(".//" + W + "p")\nprint(len(paragraphs))\nruns = paragraphs[1].findall(W + "r")\nprint(len(runs), [r.find(W + "t").text for r in runs])\nprint([r.find(W + "rPr/" + W + "b") is not None for r in runs])\nprint(paragraphs[0].find(W + "pPr/" + W + "pStyle").get(W + "val"))\n', "['word/document.xml']\n2\n4 ['A plain paragraph with some ', 'bold', ' and some ', 'italic']\n[False, True, False, False]\nTitle"],
 ['get_text joins paragraph texts, and the join string sets the spacing', 'paragraphs = ["Document Title", "A plain paragraph with some bold and some italic", "Heading, level 1"]\ndef get_text(items, joiner="\\n"):\n    return joiner.join(items)\nprint(repr(get_text(paragraphs)))\nprint(repr(get_text(["  " + p for p in paragraphs])))\nprint(repr(get_text(paragraphs, "\\n\\n")))\n', "'Document Title\\nA plain paragraph with some bold and some italic\\nHeading, level 1'\n'  Document Title\\n  A plain paragraph with some bold and some italic\\n  Heading, level 1'\n'Document Title\\n\\nA plain paragraph with some bold and some italic\\n\\nHeading, level 1'"],
 ['lengths in a Word file are whole numbers of EMU', 'EMU_PER_INCH = 914400\nEMU_PER_CM = 360000\nprint(EMU_PER_INCH * 1, EMU_PER_CM * 4, EMU_PER_INCH / EMU_PER_CM)\n', '914400 1440000 2.54'],
 ['a run attribute is True, False or None, and None hands the choice to the style', 'def shown(run_value, style_value):\n    return style_value if run_value is None else run_value\nprint([shown(v, True) for v in (True, False, None)], [shown(v, False) for v in (True, False, None)])\n', '[True, False, True] [True, False, False]'],
 ['a page break after every invitation leaves a blank last page', 'guests = ["Prof. Plum", "Miss Scarlet", "Col. Mustard", "Al Sweigart", "RoboCop"]\nBREAK = \'<w:r><w:br w:type="page"/></w:r>\'\nxml = "".join("<w:p><w:r><w:t>%s</w:t></w:r>%s</w:p>" % (g, BREAK) for g in guests)\npages = xml.count(\'w:type="page"\') + 1\nprint(len(guests), xml.count(\'w:type="page"\'), pages)\nxml2 = BREAK.join("<w:p><w:r><w:t>%s</w:t></w:r></w:p>" % g for g in guests)\nprint(xml2.count(\'w:type="page"\') + 1)\n', '5 5 6\n5'],
 ['the brute-force loop tries the lower and upper case of every word', 'import hashlib\nwords = ["aardvark", "abacus", "swordfish", "zebra"]\nsecret = hashlib.sha256(b"SWORDFISH").hexdigest()\ntries = 0\nfound = None\nfor word in words:\n    for guess in (word.lower(), word.upper()):\n        tries += 1\n        if hashlib.sha256(guess.encode()).hexdigest() == secret:\n            found = guess\n            break\n    if found:\n        break\nprint(found, tries, 2 * 44000)\n', 'SWORDFISH 6 88000'],
 ['PDF Paranoia: os.walk finds every PDF and the new name adds _encrypted before the extension', 'import os, tempfile\nwith tempfile.TemporaryDirectory() as root:\n    os.makedirs(os.path.join(root, "sub"))\n    for rel in ("a.pdf", "b.txt", os.path.join("sub", "c.pdf")):\n        open(os.path.join(root, rel), "w").close()\n    found = []\n    for folder, subfolders, filenames in os.walk(root):\n        for name in filenames:\n            if name.endswith(".pdf"):\n                found.append(os.path.relpath(os.path.join(folder, name), root))\n    print(sorted(found))\n    print([os.path.splitext(n)[0] + "_encrypted.pdf" for n in sorted(found)])\n', "['a.pdf', 'sub/c.pdf']\n['a_encrypted.pdf', 'sub/c_encrypted.pdf']"],
 ['verify before deleting: the copy must decrypt back to the original', 'def toy_lock(data, key):\n    return bytes(b ^ key for b in data)\noriginal = b"cover sheet"\nlocked = toy_lock(original, 7)\nprint(locked != original, toy_lock(locked, 7) == original, toy_lock(locked, 8) == original)\n', 'True True False'],
]
