#!/usr/bin/env python3
"""SEN0414 chapter 6 (Lists) - corpus text, part D, version 1.0.0: the branch 'Random choices and programs'.

Same contract as parts A to C. The programs of the chapter (Magic 8 Ball, the Matrix screensaver, Comma Code and Coin Flip
Streaks) are run as separate processes by the claims below; random output is checked by property (membership, length, range),
never by a seeded value, because a seeded sequence is not guaranteed to be the same in every Python version.
"""
__version__ = "1.0.0"
from sen0414_ch06_helpers_v1_0_0 import W, Y, E, H, K, C, PROG

RAW = []
CHECKS = []
RAISES = []

MAGIC = ("import random\n\nmessages = ['It is certain',\n    'It is decidedly so',\n    'Yes definitely',\n    'Reply hazy try again',\n    'Ask again later',\n"
         "    'Concentrate and ask again',\n    'My reply is no',\n    'Outlook not so good',\n    'Very doubtful']\n\nprint('Ask a yes or no question:')\ninput('>')\nprint(messages[random.randint(0, len(messages) - 1)])\n")
MSGS = ['It is certain', 'It is decidedly so', 'Yes definitely', 'Reply hazy try again', 'Ask again later', 'Concentrate and ask again', 'My reply is no', 'Outlook not so good', 'Very doubtful']
RUN = "__import__('subprocess').run([__import__('sys').executable, '-c', %r], capture_output=True, text=True, input=%r).stdout"
MATRIX = ("import random\nWIDTH = 70\ncolumns = [0] * WIDTH\nrows = []\nfor n in range(200):\n    row = ''\n    for i in range(WIDTH):\n        if random.random() < 0.02:\n            columns[i] = random.randint(4, 14)\n"
          "        if columns[i] == 0:\n            row += ' '\n        else:\n            row += str(random.choice([0, 1]))\n            columns[i] -= 1\n    rows.append(row)\n"
          "print(set(len(r) for r in rows), set(''.join(rows)) <= set(' 01'), any(r.strip() for r in rows))\n")
COMMA = ("def comma_code(items):\n    if len(items) == 0:\n        return ''\n    if len(items) == 1:\n        return items[0]\n    return ', '.join(items[:-1]) + ', and ' + items[-1]\n\n")
STREAK = ("import random\nnumber_of_streaks = 0\nfor experiment_number in range(10000):\n    flips = []\n    for i in range(100):\n        flips.append(random.choice(['H', 'T']))\n"
          "    for i in range(len(flips) - 5):\n        if flips[i:i + 6] == ['H'] * 6 or flips[i:i + 6] == ['T'] * 6:\n            number_of_streaks += 1\n            break\n"
          "print(78 < number_of_streaks / 100 < 83)\n")

RAW += [
 ("RandomPrograms", "Random choices and programs", 1, None, None, [
  (W, "The last branch of the chapter puts the list to work. It begins with the two functions of the random module that take a list, random.choice and random.shuffle, and then walks through four programs: the Magic 8 Ball that picks an answer from a list, the Matrix screensaver that keeps one counter per column in a list, and two practice programs, Comma Code and Coin Flip Streaks [SW]. The programs are the test of the chapter: each one uses the list operations of the earlier branches for a purpose."),
  (Y, "A language is learned by writing programs in it, and a list is understood when the programs that need one become shorter and easier to change because of it. The Magic 8 Ball of this chapter replaces the nine nearly identical branches of the version in chapter 4 by one list, and adding a tenth answer needs no change to the code. That is the benefit of putting data in a list and the code around it."),
  (E, "Choosing at random from a list is the heart of games, simulations, sampling and the testing of programs with generated data. The shuffle is how a deck of cards is dealt. The counter list of the Matrix screensaver is the same idea as the lists of counts that the later chapters use to tally the words of a text or the rows of a table."),
  (H, "The branch has two groups. Random lists explains random.choice and random.shuffle. Programs shows the four programs of the chapter, each as a short list-based solution that is run in the course tooling, with the output it produces."),
 ], None),
 ("RandomLists", "Random selection and ordering", 2, "RandomPrograms", None, [
  (W, "The random module has a couple of functions that accept lists for arguments. The random.choice function returns a randomly selected item from the list, and the random.shuffle function reorders the items of a list in place [SW]. A third, random.sample, picks several different items without changing the list."),
  (Y, "Both functions replace code that a beginner would write with index arithmetic. They are shorter and they are correct, since the module takes care of the range of the random index and of the fairness of the reordering."),
  (H, "The first concept explains random.choice as the shorter form of an index chosen at random. The second explains random.shuffle, which changes the list in place and returns None."),
 ], None),
 ("RandomChoice", "random.choice", 3, "RandomLists", ("random.choice(pets)", "The function random.choice returns one randomly selected item of a non-empty sequence without changing it; on an empty sequence it raises an IndexError.", ("__import__('random').choice(['Dog', 'Cat', 'Moose']) in ['Dog', 'Cat', 'Moose']", "True")), [
  (W, "The random.choice function will return a randomly selected item from the list. After import random and pets = ['Dog', 'Cat', 'Moose'], three calls to random.choice(pets) may return 'Cat', 'Cat' and 'Dog', as in the chapter's session, because each call chooses again and the same item may be chosen twice [SW]. You can consider random.choice(some_list) to be a shorter form of some_list[random.randint(0, len(some_list) - 1)]. The documentation says it returns a random element from the non-empty sequence [PSF]."),
  (Y, "The index form has a trap that the short form removes: the largest index is the length minus one, and an off-by-one in the upper bound of randint either never picks the last item or raises an IndexError. With random.choice, the programmer does not compute any index, so the program also keeps working when items are added to or removed from the list."),
  (E, "In the executed examples every result of random.choice(['Dog', 'Cat', 'Moose']) is one of the three items, and after 200 calls the three items have all appeared. The list is not changed by the call. The function works on any sequence, so random.choice('abc') gives one letter and random.choice((1, 2)) gives one number, but not on a set, since a set has no positions: random.choice({1, 2}) raises a TypeError. The Matrix screensaver uses random.choice([0, 1]) to print a binary digit."),
  (H, "The function asks the generator for a random integer below the length of the sequence and returns the item at that position. Every item has the same chance, and the call does not remember earlier calls. On an empty sequence there is nothing to choose, and the function raises an IndexError whose message is Cannot choose from an empty sequence."),
  (K, "Random results cannot be tested by comparing with one expected value; test them by property, as the executed examples do, or fix the generator's seed with random.seed, remembering that a seeded sequence is only repeatable for the same version of Python. And random.choice picks with replacement: to pick several different items use random.sample, which raises a ValueError if more items are asked for than the list holds."),
 ]),
 ("RandomShuffle", "random.shuffle", 3, "RandomLists", ("random.shuffle(people)", "The function random.shuffle reorders the items of a list in place into a random order and returns None; it raises a TypeError for a tuple or a string.", ("(lambda people: (__import__('random').shuffle(people), sorted(people))[1])(['Alice', 'Bob', 'Carol', 'David'])", "['Alice', 'Bob', 'Carol', 'David']")), [
  (W, "The random.shuffle function reorders the items in a list in place. With people = ['Alice', 'Bob', 'Carol', 'David'], the call random.shuffle(people) may leave ['Carol', 'David', 'Alice', 'Bob'], and a second call may leave ['Alice', 'David', 'Bob', 'Carol'], the chapter's two examples of the result. The function modifies the list in place, rather than returning a new list [SW]."),
  (Y, "A shuffle is how a program deals cards, draws lots, randomises the order of quiz questions and splits data into groups. Because it changes the list in place and returns None, it belongs to the same family as sort and reverse of the earlier branch, and the same mistake applies: writing people = random.shuffle(people) replaces the list with None."),
  (E, "In the executed examples, after the shuffle the list still holds exactly the same four items, because sorting it gives ['Alice', 'Bob', 'Carol', 'David'] again, and the call returns None. The function works only on a mutable sequence: random.shuffle(('a', 'b')) and random.shuffle('ab') raise a TypeError, because a tuple and a string do not support item assignment. When the original order must be kept, random.sample(people, k=len(people)) returns a new list in random order and leaves people unchanged."),
  (H, "The standard algorithm for a fair shuffle goes through the list from the end to the front and swaps each item with an item chosen at random from the positions up to and including its own; it is the method that Durstenfeld published in 1964 as a computer version [DUR] of the pencil-and-paper method of Fisher and Yates [FY], and Knuth described it in his book on seminal numerical algorithms [KNU]. Every one of the possible orders is equally likely, which a naive scheme that swaps every item with any item does not achieve."),
  (K, "A program that needs only some random items should not shuffle the whole list and take the first ones when the list is long; random.sample does that directly. Do not shuffle a list while a loop reads it, for the same reason that it must not be changed during a loop. And do not write a shuffle by hand with random.randint swaps, since the plausible versions are biased."),
 ]),
 ("Programs", "Programs with lists", 2, "RandomPrograms", None, [
  (W, "The four programs of this group are small, and each is built round one list. Magic 8 Ball keeps its answers in a list and chooses one. The Matrix screensaver keeps a counter for each column in a list. Comma Code turns a list into a sentence, and Coin Flip Streaks looks for a run of equal items in a list of simulated flips. The chapter ends with the Magic 8 Ball, the Matrix screensaver and the practice programs Comma Code and Coin Flip Streaks [SW]."),
  (Y, "Reading and running complete programs shows how the separate operations of the branches combine. It also gives a model of the habits to copy: data in a list, a constant for its size, a loop over it, and a test that the program does the right thing on the empty list and on the one-item list."),
  (H, "Each concept gives the program, says what the list does in it, and states what the run prints. The outputs are produced by the course tooling and quoted as they are."),
 ], None),
 ("MagicEightBall", "Magic 8 Ball with a list", 3, "Programs", ("messages[random.randint(0, len(messages) - 1)]", "The program keeps its nine answers in a list and prints the item at a random index from 0 to len(messages) - 1, so answers can be added or removed without changing any other line.", ("len(" + repr(MSGS) + ")", "9")), [
  (W, "Using lists, you can write a much more elegant version of the Magic 8 Ball program of chapter 4. Instead of several lines of nearly identical elif statements, you create a single list that the code works with [SW]. The list messages holds nine answers, from 'It is certain' to 'Very doubtful'; the program prints Ask a yes or no question:, waits for the user to press Enter with input('>'), and prints the item of messages at a random index."),
  (Y, "The program separates the data from the logic. The call random.randint(0, len(messages) - 1) produces a random number to use for the index, regardless of the size of messages, so the benefit is that strings can be added and removed without changing other lines of code. If you later update your code, you have to change fewer lines, and fewer changes mean fewer chances to introduce bugs [SW]."),
  (E, "In the executed run the program prints Ask a yes or no question: on the first line and, on the second, the prompt character > followed directly by the chosen answer, because input shows its prompt but the user's typed text is not echoed when the input comes from a file. The answer is always one of the nine messages. Selecting a random item from a list is common enough that Python has random.choice(messages), which does the same thing as the randint form."),
  (H, "The index is an integer from 0 to the length minus one, both ends included, because randint, unlike a slice, includes its upper bound; that is why the call subtracts one. The list is written over several lines, which Python allows between square brackets whatever the indentation. Replacing the last line by print(random.choice(messages)) gives the same behaviour with no index arithmetic."),
  (K, "The classic slip is the upper bound: random.randint(0, len(messages)) sometimes returns len(messages), and the program then ends with an IndexError. Test the program by running it many times and checking that every output is in the list, rather than by running it once."),
 ]),
 ("MatrixScreensaver", "Matrix screensaver", 3, "Programs", ("columns = [0] * WIDTH", "The program keeps one counter per output column in a list of WIDTH zeros: a counter above zero means that a stream of binary digits is running in that column and counts the digits left to print.", ("(lambda W: (len([0] * W), set([0] * W)))(70)", "(70, {0})")), [
  (W, "In the science fiction film The Matrix, computer monitors display streams of glowing green numbers, like digital rain pouring down a glass window. The chapter's screensaver imitates it with a list: the list columns holds 70 integers, one for each column of output, and the number of columns is the constant WIDTH [SW]. When an integer in columns is 0, the program prints an empty space for that column; when it is greater than 0, it prints a random 1 or 0 and counts the integer down."),
  (Y, "The program shows the list as a set of counters, a use that is quite different from a list of names. The list's length is fixed by the width of the window and only its values change, so the design is simple: each column is independent and the whole screen is the list read from left to right. The constant WIDTH has an all-uppercase name by convention, so that columns = [0] * WIDTH explains itself better than columns = [0] * 70 [PEP8]."),
  (E, "The infinite loop prints one row per pass. For each column, there is a two percent chance, tested by random.random() < 0.02, that the integer is set to a random number between 4 and 14; random.randint(4, 14) gives it. Then the column prints a space if its counter is 0, and otherwise a random choice from [0, 1] and decrements the counter. A pause of a tenth of a second between rows, time.sleep(0.1), and the handling of KeyboardInterrupt by an except block that calls sys.exit() end the program. In the executed run of 200 rows every row has exactly 70 characters, only spaces, 0 and 1 appear, and some rows are not blank."),
  (H, "Python builds the list by replicating [0] seventy times, which is safe because the items are integers and cannot be changed through a shared reference. The loop for i in range(WIDTH) visits the indexes of the columns, and columns[i] -= 1 is an augmented assignment on an item. Each stream starts at a random column, runs for 4 to 14 rows and stops by itself when its counter reaches 0, which is the whole animation."),
  (K, "The program runs for ever until the user presses Ctrl-C, so never run it in a test without a bound. Changing WIDTH to more characters than the window is wide makes the lines wrap and spoils the picture. And the constant is only a convention: nothing in Python prevents the program from changing WIDTH later, so the programmer must not."),
 ]),
 ("CommaCode", "Comma Code", 3, "Programs", ("comma_code(['apples', 'bananas', 'tofu', 'cats'])", "The Comma Code function joins the items of any list into one string, separated by commas, with and before the last item, and must work for the empty list and the one-item list.", ("(lambda items: ', '.join(items[:-1]) + ', and ' + items[-1])(['apples', 'bananas', 'tofu', 'cats'])", "'apples, bananas, tofu, and cats'")), [
  (W, "The first practice program of the chapter asks for a function that takes a list value as an argument and returns a string with all the items separated by a comma and a space, with and inserted before the last item. For the list ['apples', 'bananas', 'tofu', 'cats'] the function returns 'apples, bananas, tofu, and cats'. The function should work with any list passed to it, and the chapter asks the reader to test the case where an empty list is passed [SW]."),
  (Y, "The task is small and it contains the whole skill of the chapter: slices for the first items and the last, len for the special cases, and a decision about the empty list. Writing it makes a student face the edge cases that every real function has, and the answer shows how much a slice shortens a loop."),
  (E, "A solution joins all items except the last with ', ', and then adds ', and ' and the last item. In the executed examples the function returns 'apples, bananas, tofu, and cats' for the four-item list, 'apples' for a one-item list and '' for the empty list. For two items the same rule gives 'apples, and bananas'; the chapter does not say how a list of two should read, so the program states its own rule and the course asks the reader to decide whether the comma before and is wanted."),
  (H, "The function tests len(items): zero gives an empty string, one gives the item itself, and any other length takes the slice items[:-1] for the first items, joins them with ', ' and appends ', and ' and items[-1]. The slice items[:-1] is a new list, so the argument is not changed, which matters because of the rule that a function receives the caller's list."),
  (K, "The empty list is the case that the chapter asks to test, because items[-1] on it raises an IndexError. The one-item list is the second edge, where the rule would otherwise produce a lone ', and '. Check also that the function does not change its argument, by comparing the list before and after the call."),
 ]),
 ("CoinFlipStreaks", "Coin Flip Streaks", 3, "Programs", ("some_list[i:i + 6] == ['H'] * 6", "The Coin Flip Streaks program simulates 10,000 experiments of 100 coin flips and counts those with a streak of six equal results, found by comparing slices of six items with a list of six H or six T.", ("(lambda c: [c.append(sum(c[-5:])) for _ in range(95)] and round(100 * (1 - c[-1] / 2**100), 2))([2, 4, 8, 16, 32])", "80.68")), [
  (W, "The second practice program is an experiment. If you flip a coin 100 times and write down an H for each heads and a T for each tails, you create a list like T T T T H H H H T T. A human asked to make up 100 random flips will alternate too much, which looks random to people but is not. The program finds out how often a streak of six heads or six tails comes up in a randomly generated list of 100 flips, and it repeats the experiment 10,000 times so that it can estimate the chance [SW]."),
  (Y, "The program is a simulation, a method that the later chapters use for many questions: when the exact answer is hard to work out, run the experiment many times and count. The chapter notes that some knowledge of mathematics could give the exact answer, but programmers are notoriously bad at math. Here the list does two jobs, as the record of one experiment and as the thing searched by slices."),
  (E, "The chapter's hint is to build the list with a loop that appends random.choice(['H', 'T']) 100 times, and to find a streak by slicing some_list[i:i + 6] and comparing it with ['H'] * 6 and ['T'] * 6. The executed program prints that its estimate lies between 78 and 83 percent. The exact answer, computed from a recurrence for the number of sequences of 100 flips that have no streak of six, is about 80.68 percent, so a streak of six in 100 flips is likelier than not by a wide margin."),
  (H, "For each of 10,000 experiments the program builds a list of 100 flips and looks at every window of six: the starting indexes run from 0 to len(flips) - 6, so range(len(flips) - 5), since the last window must still have six items. The first window that matches counts the experiment and the break ends the search. The final estimate is the number of experiments with a streak divided by 100, which converts a count out of 10,000 to a percentage."),
  (K, "Watch the end of the range: using range(len(flips)) would let the slice run past the end and compare shorter lists, which never match, so the last windows would be silently wasted. Count an experiment once, not once for every streak in it, which is what the break does. The estimate varies from run to run, so test it by a range and not by an exact value."),
 ]),
]

CHECKS += [("(lambda c: all(r in ['Dog', 'Cat', 'Moose'] for r in [c(['Dog', 'Cat', 'Moose']) for _ in range(200)]))(__import__('random').choice)", "True"),
           ("(lambda c: set(c(['Dog', 'Cat', 'Moose']) for _ in range(200)))(__import__('random').choice) == {'Dog', 'Cat', 'Moose'}", "True"),
           ("(lambda r: (lambda pets: (r.choice(pets), pets)[1])(['Dog', 'Cat', 'Moose']))(__import__('random'))", "['Dog', 'Cat', 'Moose']"),
           ("(__import__('random').choice('abc') in 'abc', __import__('random').choice((1, 2)) in (1, 2))", "(True, True)"),
           ("(lambda people: (__import__('random').shuffle(people), sorted(people))[1])(['Alice', 'Bob', 'Carol', 'David'])", "['Alice', 'Bob', 'Carol', 'David']"),
           ("__import__('random').shuffle(['a', 'b'])", "None"),
           ("(lambda p: (lambda q: (sorted(q), p))(__import__('random').sample(p, k=len(p))))(['a', 'b', 'c'])", "(['a', 'b', 'c'], ['a', 'b', 'c'])"),
           PROG("import random\nmessages = ['It is certain', 'Yes']\nfor i in range(300):\n    assert 0 <= random.randint(0, len(messages) - 1) <= 1\nprint('ok')\n", "ok\n"),
           (RUN % (MAGIC, "Will it rain?\n") + ".splitlines()[0]", "'Ask a yes or no question:'"),
           ("(lambda out: (len(out.splitlines()), out.splitlines()[1][0], out.splitlines()[1][1:] in " + repr(MSGS) + "))(" + RUN % (MAGIC, "Will it rain?\n") + ")", "(2, '>', True)"),
           ("len(" + repr(MSGS) + ")", "9"),
           PROG("import random\nmessages = ['a', 'b']\nbad = 0\nfor i in range(500):\n    try:\n        messages[random.randint(0, len(messages))]\n    except IndexError:\n        bad += 1\nprint(bad > 0)\n", "True\n"),
           ("(RUNMATRIX := " + RUN % (MATRIX, None) + ").strip()", "'{70} True True'"),
           ("(lambda W: (len([0] * W), set([0] * W)))(70)", "(70, {0})"),
           ("(lambda c: (c.__setitem__(0, 5), c.__setitem__(0, c[0] - 1), c[:2]))([0] * 70)[2]", "[4, 0]"),
           ("(lambda r: (0.0 <= r.random() < 1.0, 4 <= r.randint(4, 14) <= 14))(__import__('random'))", "(True, True)"),
           (RUN % ("import random\nrandom.seed(0)\n" + STREAK, None) + ".strip()", "'True'"),
           PROG(COMMA + "print(comma_code(['apples', 'bananas', 'tofu', 'cats']))\nprint(repr(comma_code(['apples'])))\nprint(repr(comma_code([])))\nprint(comma_code(['apples', 'bananas']))\ns = ['x', 'y', 'z']\ncomma_code(s)\nprint(s)\n", "apples, bananas, tofu, and cats\n'apples'\n''\napples, and bananas\n['x', 'y', 'z']\n"),
           ("(lambda c: [c.append(sum(c[-5:])) for _ in range(95)] and round(100 * (1 - c[-1] / 2**100), 2))([2, 4, 8, 16, 32])", "80.68"),
           ("(lambda c: (c[5], 2**6 - 2))([2, 4, 8, 16, 32, 62])", "(62, 62)"),
           PROG("try:\n    __import__('random').choice([])\nexcept IndexError as e:\n    print(e)\n", "Cannot choose from an empty sequence\n")]
RAISES += [("__import__('random').choice([])", "IndexError"), ("__import__('random').choice({1, 2})", "TypeError"), ("__import__('random').shuffle(('a', 'b'))", "TypeError"),
           ("__import__('random').shuffle('ab')", "TypeError"), ("__import__('random').sample([1, 2, 3], k=5)", "ValueError")]
