"""SEN0414 chapter 7, corpus text B (version 1.0.0): the branches 'Views and loops' and 'Counting and grouping'.
Every output, error message and number quoted below is in CHECKS, RAISES or the leaf's own input-output example and is executed by
sen0414_ch07_corpus_v1_0_0.py. The citation tokens are resolved there."""
__version__ = "1.0.0"
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sen0414_ch07_corpus_base_v1_0_0 import *

# ============================================================ Views and loops
RAW += [
 ("ViewsAndLoops", "Views and loops", 1, None, None, [
  (W, "Views and loops is the branch of the chapter about going through a dictionary: asking it for its keys, its values or its pairs, walking over them in a for loop, and building a new dictionary from what the loop finds. The chapter teaches it in its section on the keys(), values() and items() methods, where it says that the three methods return list-like values that are not true lists but can be used in for loops [SW]."),
  (Y, "A dictionary that can only be asked for one key at a time is of little use. Reports, totals, searches and copies all need to look at every pair, and the views are the way the language provides for it. The branch also removes a small mystery: why the console shows dict_keys(['color', 'age']) where a learner expects a list."),
  (E, "Loops over dictionaries are in the chapter's picnic program, which goes over the guests with items(), in the inventory exercises, which go over the items, and in every program that prints, totals or filters records. The same views are what the json module and the pprint module walk when they print a dictionary."),
  (H, "The branch has three parts. Views explains what keys(), values() and items() return and how they stay joined to the dictionary. Looping covers the for loop over each of them, sorted and reversed order, and the rule against changing a dictionary while a loop is walking it. Building shows the dictionary comprehension, which makes a dictionary from a loop in one expression."),
 ], None),
 ("Views", "Dictionary views", 2, "ViewsAndLoops", None, [
  (W, "Dictionary views are the objects returned by the methods keys(), values() and items(). A view is a window onto the dictionary and not a copy of it: it shows what the dictionary holds at the moment it is looked at. The documentation calls them dictionary view objects and says that they provide a dynamic view on the dictionary's entries, which means that when the dictionary changes, the view reflects these changes [PSF]."),
  (Y, "Knowing that a view is a window and not a list explains three facts that would otherwise look arbitrary: why it cannot be indexed or appended to, why it is cheap to create even for a large dictionary, and why a view created early shows pairs added later. It also explains the form of the console output, which names the kind of view."),
  (H, "Two concepts follow. The first describes the three views and what each holds. The second describes what is special about them: they are live, and the keys and the pairs behave like sets."),
 ], None),
 ("KeysValuesItems", "keys(), values() and items()", 3, "Views", ("spam.keys(), spam.values(), spam.items()", "The methods keys(), values() and items() return views of the keys, of the values and of the (key, value) tuples of a dictionary, which can be looped over, counted and tested with in but not indexed or modified.", ("(lambda spam: (repr(spam.keys()), repr(spam.values()), repr(spam.items()), list(spam.keys()), len(spam.items())))({'color': 'red', 'age': 42})", "(\"dict_keys(['color', 'age'])\", \"dict_values(['red', 42])\", \"dict_items([('color', 'red'), ('age', 42)])\", ['color', 'age'], 2)")), [
  (W, "The method keys() returns a view of the keys of a dictionary, values() a view of its values, and items() a view of its pairs, each pair as a tuple of two. For spam = {'color': 'red', 'age': 42}, the console shows dict_keys(['color', 'age']), dict_values(['red', 42]) and dict_items([('color', 'red'), ('age', 42)]). The chapter says that the values returned by these methods are not true lists: they cannot be modified and have no append() method, but they can be used in for loops [SW]."),
  (Y, "Each view answers a different question. The keys say what the dictionary knows about, the values say what it holds, and the items say which belongs to which. A program picks the one that matches the loop it needs, and the shortest loop is usually the one over items(), which hands out both halves of a pair at once."),
  (E, "The views appear in the first lines of nearly every loop over a dictionary, in the membership tests 'color' in spam.keys() and 'red' in spam.values() that the chapter shows, in len(spam.items()), and in conversions such as list(spam.keys()), with which the chapter turns a view into a true list [SW]."),
  (H, "Each method creates a small object that keeps a reference to the dictionary and does not copy any pair. The object can report its length, be iterated, be tested with in, and be reversed, since Python 3.8. It is not a sequence, so spam.keys()[0] is a TypeError with the message that dict_keys is not subscriptable. To get a list, wrap the view in list(), which makes a copy of the keys at that moment."),
  (K, "A view prints as its kind and a list of its content, which looks like a list but is not one. Do not append to it, do not index it and do not assume that a list made from it stays in step with the dictionary: the list is a snapshot. The loop for k in spam and the loop for k in spam.keys() do the same thing, and the shorter form is the usual one."),
 ]),
 ("LiveAndSetLikeViews", "Live views and set-like views", 3, "Views", ("keys = spam.keys(); spam['name'] = 'Pooka'", "A view is live: it shows later changes to its dictionary; and the keys view and the items view behave like sets, so they can be intersected, subtracted and compared with &, - and ==.", ("(lambda spam: (lambda keys: (spam.__setitem__('name', 'Pooka'), list(keys), sorted(keys & {'age', 'x'}), sorted(keys - {'age'}), keys == {'color', 'age', 'name'})[1:])(spam.keys()))({'color': 'red', 'age': 42})", "(['color', 'age', 'name'], ['age'], ['color', 'name'], True)")), [
  (W, "A view is live and, for the keys and the items, set-like. Live means that it reflects the dictionary as it is now: a keys view created before a pair was added includes the new key afterwards. Set-like means that it supports the operations of mathematical sets, such as intersection with &, difference with -, union with | and comparison with ==. The documentation states both properties and notes that values views are not treated as set-like, because their entries are not guaranteed to be unique or hashable [PSF]."),
  (Y, "The live behaviour is convenient, because a program can keep one view and look at it again after the dictionary changes. It is also the source of one surprise, since a view looked at inside a loop that changes the dictionary is a view of a changing thing. The set operations make questions about keys short: which keys do two dictionaries share, which are missing from one, are the keys exactly these."),
  (E, "The set-like operations are used to compare configurations (a.keys() - b.keys() gives the settings that only a has), to validate input (the keys of a record must equal the expected set), and to find the common entries of two dictionaries with a.items() & b.items()."),
  (H, "A keys view holds a reference to the dictionary and asks it, each time it is used, for its current keys, which is why the later pair appears. The operators on a keys view build an ordinary set, not a view, so the result is a copy and its order is not defined; call sorted() when the order matters. Comparison with a set ignores order, as sets do."),
  (K, "The result of keys() & other is a set, and a set has no insertion order, so print sorted(result) in programs and tests. An items view is set-like only while the values are hashable; with a list as a value the operations raise TypeError. A snapshot is wanted, not a view, whenever the dictionary will be changed during the loop, and list(spam) makes one."),
 ]),
 ("Looping", "Looping over a dictionary", 2, "ViewsAndLoops", None, [
  (W, "Looping over a dictionary is the use of a for loop to visit its keys, its values or its pairs. The loop variable takes one entry at a time, and the dictionary supplies them in the order in which the keys were inserted. The chapter shows the three loops one after another and then the multiple assignment trick, with which a loop over items() puts the key into one variable and the value into another [SW]."),
  (Y, "Almost everything a program does with a collection is a loop, and a loop over a dictionary has more choices than a loop over a list: which half of the pair is needed, in which order, and whether the dictionary may be changed meanwhile. Choosing the right form gives code that reads like the sentence it implements."),
  (H, "Three concepts follow. The items loop is the everyday form with two loop variables. Sorted and reversed loops control the order. Changing while looping explains the one thing a loop must not do."),
 ], None),
 ("ItemsLoop", "The items loop", 3, "Looping", ("for k, v in spam.items():", "A for loop over items() unpacks each (key, value) tuple into two loop variables, so both halves of every pair are available in the body without a second lookup.", ("(lambda spam: ['Key: ' + str(k) + ' Value: ' + str(v) for k, v in spam.items()])({'color': 'red', 'age': 42})", "['Key: color Value: red', 'Key: age Value: 42']")), [
  (W, "The items loop is the loop for k, v in spam.items(). Each pass of the loop takes the next pair, which items() provides as a tuple such as ('color', 'red'), and assigns its first member to k and its second to v. This is the multiple assignment trick of the chapter, which assigns several variables from a tuple in one statement [SW]. For spam = {'color': 'red', 'age': 42} the two passes print Key: color Value: red and Key: age Value: 42."),
  (Y, "The form gives a name to each half of the pair, so the body of the loop reads as intended, as v.get(item, 0) does in the picnic program of this chapter, where k is the guest and v the guest's dictionary. The alternative, a loop over the keys with a lookup in the body, searches the dictionary again for a value the loop already had."),
  (E, "It is the loop of the picnic program, of the inventory display in the practice section, and of nearly every report that prints a table from a dictionary. It is also the loop inside the standard json and pprint modules and inside dict(d.items()) and the dictionary comprehension that the next concept introduces."),
  (H, "The loop asks items() for an iterator and takes pairs from it one by one. Because each pair is a tuple of two, the assignment k, v = pair unpacks it. The names k and v are only conventions; guest, basket would read better in a real program. A loop over the dictionary itself, for k in spam, takes keys only, and a loop over values() takes values only."),
  (K, "If a loop over items() is given a single variable, that variable holds the whole tuple, which is often a puzzling output. And if the keys are tuples themselves, the pattern for (a, b), v in d.items() is needed to unpack both levels. The loop variables keep their last value after the loop, as all loop variables do."),
 ]),
 ("SortedAndReversedLoops", "Sorted and reversed loops", 3, "Looping", ("for k in sorted(spam):  and  reversed(spam)", "A dictionary loop follows insertion order; sorted() gives the keys, or the pairs, in order of their values, and reversed() gives the newest key first.", ("(lambda s: (sorted(s), list(reversed(s)), sorted(s.items(), key=lambda kv: kv[1]), sorted(s.items(), key=lambda kv: kv[1], reverse=True)[0]))({'b': 2, 'a': 3, 'c': 1})", "(['a', 'b', 'c'], ['c', 'a', 'b'], [('c', 1), ('b', 2), ('a', 3)], ('a', 3))")), [
  (W, "The order of a loop over a dictionary is the insertion order, and two built-in functions change it. The function sorted() returns a new list of the keys in ascending order, or, applied to items() with a key function, a list of pairs in the order of the values. The function reversed(), available for dictionaries since Python 3.8, goes through the keys from the most recently inserted to the first [PSF]."),
  (Y, "Reports usually need a meaningful order: alphabetical, or biggest first. Insertion order is the order of arrival and says nothing about size or name, so the program asks for the order it wants. The chapter's older statement that a dictionary has no order is the reason its programs never depend on one; present Python lets programs depend on insertion order and still sort when the output has to be sorted."),
  (E, "The forms appear in leaderboards (sorted by count, largest first), in alphabetical listings, in the character count shown sorted by letter, and in printing the last item added. The key argument of sorted() takes the function that picks the sort value out of each item, and sorted(spam.items(), key=lambda kv: kv[1]) uses the value."),
  (H, "The function sorted() reads all the entries, builds a list and sorts it, leaving the dictionary unchanged. With key=lambda kv: kv[1] it compares the second member of each pair, and reverse=True turns the order around. With the dictionary {'b': 2, 'a': 3, 'c': 1}, sorted(s) is ['a', 'b', 'c'], list(reversed(s)) is ['c', 'a', 'b'], and sorting the items by value starts with ('c', 1)."),
  (K, "Sorting needs keys that can be compared. A dictionary whose keys mix numbers and strings makes sorted() raise TypeError, because 1 < 'a' is not defined. Sorting does not change the dictionary: to keep the sorted order, build a new dictionary with dict(sorted(spam.items())), which then has the new insertion order."),
 ]),
 ("ChangeWhileLooping", "Changing while looping", 3, "Looping", ("for k in spam: spam[k + 'x'] = 1", "Adding or deleting keys while a loop walks over the dictionary raises RuntimeError, because the walk would lose its place; replacing the values of existing keys is allowed, and looping over list(spam) gives a snapshot that is safe to change.", ("(lambda d: (d.update({k: v * 2 for k, v in d.items()}), [d.__delitem__(k) for k in list(d) if d[k] > 2], d)[2])({'a': 1, 'b': 2, 'c': 3})", "{'a': 2}")), [
  (W, "The rule against changing a dictionary while looping is the rule that the loop must not add or remove keys of the dictionary it is walking. The documentation says that iterating views while adding or deleting entries in the dictionary may raise a RuntimeError or fail to iterate over all entries [PSF]. The message that Python prints is: dictionary changed size during iteration."),
  (Y, "The dictionary keeps its pairs in an internal array that the loop reads by position. A pair added or removed moves the positions under the loop, so the loop could skip pairs or show one twice. Python protects the program by checking the size at every pass and raising an error, which turns a silent mistake into a loud one."),
  (E, "The mistake appears when a program tries to remove the pairs that fail a test while it is testing them, or to add a derived key for every key. The error is met in cleaning of data, in games that remove defeated pieces, and in caches that remove old entries."),
  (H, "Two cases are harmless. Replacing the value of a key that already exists does not change the size, so for k in d: d[k] = d[k] * 2 is allowed. And a loop over a copy of the keys, for k in list(d), walks a separate list, so the dictionary may then be changed freely; deleting the pairs that fail a test is done this way. The other way is to build a new dictionary with a comprehension, which is the clearest of the three."),
  (K, "The error is raised at the next pass after the change, not at the change itself, so a loop that changes the size on its last pass may end without an error and leave the problem unseen. Changing the size and then breaking out of the loop at once is also safe. Never rely on the exception to find a bug: write the loop so that it cannot happen."),
 ]),
 ("Building", "Building dictionaries from loops", 2, "ViewsAndLoops", None, [
  (W, "Building dictionaries from loops is the use of a loop to produce a new dictionary instead of changing an old one. Python offers a one-expression form of it, the dictionary comprehension, which is the dictionary relative of the list comprehension and was added to the language in Python 2.7 and 3.0 by PEP 274 [PEP274]."),
  (Y, "Many tasks are of the form: for each of these things, make a pair. The comprehension states the task in one line and leaves out the empty dictionary, the loop and the assignment that the longer form needs. It also keeps the original data untouched, which is safer than changing it in place."),
  (H, "One concept follows, the dictionary comprehension, with the filter and the inversion of a dictionary as its two commonest uses."),
 ], None),
 ("DictComprehension", "Dictionary comprehension", 3, "Building", ("{v: k for k, v in spam.items()}", "A dictionary comprehension builds a new dictionary from a loop in one expression, key: value for item in iterable, with an optional if to filter; it can invert a dictionary, filter its pairs or index a list.", ("(lambda d: ({v: k for k, v in d.items()}, {k: v for k, v in d.items() if v > 1}, {c: ord(c) for c in 'ab'}, {w[0]: w for w in ['apple', 'avocado']}))({'a': 1, 'b': 2, 'c': 3})", "({1: 'a', 2: 'b', 3: 'c'}, {'b': 2, 'c': 3}, {'a': 97, 'b': 98}, {'a': 'avocado'})")), [
  (W, "A dictionary comprehension is an expression in curly brackets of the form {key: value for item in iterable}, optionally followed by if and a condition. It evaluates the key and the value for each item and collects the pairs into a new dictionary. PEP 274 proposed it as the same syntax as the list comprehension with a colon between the key and the value [PEP274]. For d = {'a': 1, 'b': 2, 'c': 3}, the comprehension {v: k for k, v in d.items()} is {1: 'a', 2: 'b', 3: 'c'}."),
  (Y, "The comprehension replaces a loop of four lines by a line that says what the result is. It is the usual way to invert a dictionary, to keep only the pairs that satisfy a test, to give every item of a list a key, and to make a lookup table from a function applied to a range. Because it creates a new dictionary, the source is left as it was, which also solves the problem of changing a dictionary while looping."),
  (E, "It is used for lookup tables such as {c: ord(c) for c in 'ab'}, which is {'a': 97, 'b': 98}, for indexing records by an identifier, and for the filter {k: v for k, v in d.items() if v > 1}. The documentation of fromkeys recommends it for building a dictionary with a separate list for every key [PSF]."),
  (H, "Python runs the loop part first, takes each item, evaluates the key expression and the value expression, and stores the pair, so the later pair wins when two items produce the same key: {w[0]: w for w in ['apple', 'avocado']} is {'a': 'avocado'}. The loop variables belong to the comprehension and do not exist after it, unlike the variables of an ordinary for loop."),
  (K, "Inverting a dictionary is safe only when the values are distinct and hashable. If two keys share a value, one pair is lost silently, as {v: k for k, v in {'a': 1, 'b': 1}.items()} shows with {1: 'b'}. A comprehension with several loops or conditions soon becomes hard to read; a plain loop is better then."),
 ]),
]
CHECKS += [("(lambda spam: (repr(spam.keys()), repr(spam.values()), repr(spam.items())))({'color': 'red', 'age': 42})", "(\"dict_keys(['color', 'age'])\", \"dict_values(['red', 42])\", \"dict_items([('color', 'red'), ('age', 42)])\")"),
           ("(lambda spam: list(spam.keys()))({'color': 'red', 'age': 42})", "['color', 'age']"),
           ("(lambda spam: ([v for v in spam.values()], [k for k in spam.keys()], [i for i in spam.items()]))({'color': 'red', 'age': 42})", "(['red', 42], ['color', 'age'], [('color', 'red'), ('age', 42)])"),
           ("{}.keys().__class__.__name__", "'dict_keys'"), ("{}.items().__class__.__name__", "'dict_items'"),
           ("hasattr({}.keys(), 'append')", "False"), ("list(reversed({'a': 1, 'b': 2}))", "['b', 'a']"), ("list(reversed({'a': 1, 'b': 2}.values()))", "[2, 1]"),
           ("(lambda spam: (lambda keys: (spam.__setitem__('name', 'Pooka'), list(keys))[1])(spam.keys()))({'color': 'red', 'age': 42})", "['color', 'age', 'name']"),
           ("(lambda spam: (lambda lst: (spam.__setitem__('name', 'Pooka'), lst)[1])(list(spam.keys())))({'color': 'red', 'age': 42})", "['color', 'age']"),
           ("(lambda k: (sorted(k & {'age', 'x'}), sorted(k - {'age'}), sorted(k | {'z'}), k == {'color', 'age'}))({'color': 'red', 'age': 42}.keys())", "(['age'], ['color'], ['age', 'color', 'z'], True)"),
           ("({'a': 1, 'b': 2}.items() & {'a': 1, 'b': 3}.items())", "{('a', 1)}"), ("type({'a': 1}.keys() & {'a'}).__name__", "'set'"),
           ("sorted({'a': 1}.keys() - {'b': 2}.keys())", "['a']"),
           ("{'a': 1}.values().__class__.__name__ in ('dict_values',)", "True"),
           ("(lambda spam: ['Key: ' + str(k) + ' Value: ' + str(v) for k, v in spam.items()])({'color': 'red', 'age': 42})", "['Key: color Value: red', 'Key: age Value: 42']"),
           ("[pair for pair in {'color': 'red'}.items()]", "[('color', 'red')]"),
           ("(lambda s: (sorted(s), list(reversed(s))))({'b': 2, 'a': 3, 'c': 1})", "(['a', 'b', 'c'], ['c', 'a', 'b'])"),
           ("sorted({'b': 2, 'a': 3, 'c': 1}.items(), key=lambda kv: kv[1])", "[('c', 1), ('b', 2), ('a', 3)]"),
           ("sorted({'b': 2, 'a': 3, 'c': 1}.items(), key=lambda kv: kv[1], reverse=True)[0]", "('a', 3)"),
           ("dict(sorted({'b': 2, 'a': 3}.items()))", "{'a': 3, 'b': 2}"),
           ("(lambda d: ([d.__setitem__(k, d[k] * 2) for k in d], d)[1])({'a': 1, 'b': 2})", "{'a': 2, 'b': 4}"),
           ("(lambda d: ([d.__delitem__(k) for k in list(d) if d[k] > 2], d)[1])({'a': 1, 'b': 2, 'c': 3})", "{'a': 1, 'b': 2}"),
           ("{v: k for k, v in {'a': 1, 'b': 2, 'c': 3}.items()}", "{1: 'a', 2: 'b', 3: 'c'}"),
           ("{k: v for k, v in {'a': 1, 'b': 2, 'c': 3}.items() if v > 1}", "{'b': 2, 'c': 3}"),
           ("{c: ord(c) for c in 'ab'}", "{'a': 97, 'b': 98}"), ("{w[0]: w for w in ['apple', 'avocado']}", "{'a': 'avocado'}"),
           ("{v: k for k, v in {'a': 1, 'b': 1}.items()}", "{1: 'b'}"),
           PROG(LOOPS, LOOPS_OUT)]
RAISES += [("{'a': 1}.keys()[0]", "TypeError"), ("(lambda d: [d.__setitem__(k + 'x', 1) for k in d])({'a': 1})", "RuntimeError"),
           ("sorted({1: 'a', 'b': 2})", "TypeError"), ("{'a': [1]}.items() & {('a', 1)}", "TypeError")]
CHECKS += [PROG("d = {'a': 1}\ntry:\n    for k in d:\n        d[k + 'x'] = 2\nexcept RuntimeError as e:\n    print(e)\n", "dictionary changed size during iteration\n"),
           PROG("try:\n    {'a': 1}.keys()[0]\nexcept TypeError as e:\n    print(e)\n", "'dict_keys' object is not subscriptable\n"),
           PROG("try:\n    sorted({1: 'a', 'b': 2})\nexcept TypeError as e:\n    print(e)\n", "'<' not supported between instances of 'str' and 'int'\n")]

# ============================================================ Counting and grouping
RAW += [
 ("CountingAndGrouping", "Counting and grouping", 1, None, None, [
  (W, "Counting and grouping is the branch about the two jobs for which dictionaries are most often used in practice: counting how many times each thing occurs, and collecting the things that share a label. The chapter's first big example, characterCount.py, counts the characters of a sentence, and the techniques it introduces carry over to words, votes, votes per party, orders per customer and every tally that a program keeps [SW]."),
  (Y, "Both jobs have the same difficulty: the first time a label is seen, its entry does not exist yet. A program that forgets this stops with KeyError on the first character. The branch shows the three standard ways of solving it, the setdefault pattern of the book, the Counter class and the defaultdict, and says when each is the better choice."),
  (E, "The jobs are met in text analysis, in logs (how many errors of each kind), in surveys, in games (how many of each piece), in inventory and in every report that ends in a table of totals. A programmer who has learnt the patterns will write the same few lines in all of them."),
  (H, "The branch has two parts. Counting describes the book's character count, the Counter class from the standard library, and the defaultdict. Grouping describes how a dictionary of lists collects items under their labels, and how a subclass can supply a value for a missing key."),
 ], None),
 ("Counting", "Counting with dictionaries", 2, "CountingAndGrouping", None, [
  (W, "Counting with dictionaries is the pattern in which each distinct item is a key and the number of times it was seen is the value. The pattern needs only two steps for each item: make sure that its key exists, starting at zero, and add one. Three tools do it in the standard library, and the chapter shows the first."),
  (Y, "The pattern turns a long sequence into a short table, and the table is what a person reads. It also scales: the time for each item does not depend on the number of different items, which is the property of hashing that the earlier branch described."),
  (H, "Three concepts follow: the character count of the book, the Counter class that packages the pattern, and the defaultdict that supplies the zero automatically."),
 ], None),
 ("CharacterCount", "The character count program", 3, "Counting", ("count.setdefault(character, 0); count[character] += 1", "The program characterCount.py counts how often each character occurs in a string by making sure the key exists with setdefault and then adding one, and ends with a dictionary of letter counts.", ("(lambda message: (lambda count: ([count.__setitem__(c, count.get(c, 0) + 1) for c in message], count['c'], count[' '], count['A'], len(count), sum(count.values()))[1:])({}))('It was a bright cold day in April, and the clocks were striking thirteen.')", "(3, 13, 1, 23, 73)")), [
  (W, "The character count program counts how many times each character occurs in a sentence. It starts with an empty dictionary, goes over the characters of the string with a for loop, and for each character runs two statements: count.setdefault(character, 0) makes sure the key exists with the value 0, and count[character] = count[character] + 1 adds one [SW]. It uses the sentence 'It was a bright cold day in April, and the clocks were striking thirteen.', a line from the opening of George Orwell's novel Nineteen Eighty-Four."),
  (Y, "Run on this sentence it shows that the letter c occurs 3 times, the space 13 times and the capital A once. The chapter points out that the program would work just as well if the string held millions of characters, even though the sentence is short [SW]. The dictionary has 23 keys for 73 characters, because the number of keys grows with the number of different characters and not with the length of the text."),
  (E, "The same program, with the characters replaced by words, is the first step of a word frequency analysis. Counting letters is used in cryptanalysis, in compression and in spelling tools, and the idea of counting by key is the core of the 'word count' example with which large-scale data processing is usually introduced."),
  (H, "On the first pass, for the character 'I', setdefault finds no key, stores 'I' with 0, and the next line makes it 1. On a later pass for ' ', the key exists, setdefault changes nothing, and the next line adds to the existing count. Because the loop goes through the message from left to right, the keys of the final dictionary are in order of first appearance, I, t, space, w and so on."),
  (K, "The book's output was written for the older reading of dictionaries, and the order of its pairs looks arbitrary there; in Python 3.7 and later the order is the order of first appearance, and the printed dictionary above is the one every run produces. Upper and lower case letters are different keys, so 'I' and 'i' are counted apart. The two lines can be shortened to count[character] = count.get(character, 0) + 1."),
 ]),
 ("CounterClass", "The Counter class", 3, "Counting", ("collections.Counter('abracadabra')", "The Counter class of the collections module is a dictionary made for counting: it counts the items of an iterable in one call, returns 0 for a missing item without adding it, adds and subtracts counts, and lists the commonest items with most_common.", ("(lambda C: (C('abracadabra').most_common(2), C('abracadabra')['z'], C(a=3) + C(a=1, b=2), C(a=1) - C(a=5)))(__import__('collections').Counter)", "([('a', 5), ('b', 2)], 0, Counter({'a': 4, 'b': 2}), Counter())")), [
  (W, "The Counter class, in the collections module of the standard library, is a dictionary subclass for counting hashable objects: the elements are stored as keys and their counts are stored as values. Counter('abracadabra') counts the characters of the string in one call. The documentation describes it as a collection where elements are stored as dictionary keys and their counts are stored as dictionary values [PSF]."),
  (Y, "A Counter packages the two-line pattern of the character count and adds what counting programs need next. A missing element has the count 0 instead of raising KeyError, most_common(n) returns the n commonest elements with their counts, and counters can be added and subtracted, so totals from several sources combine in one expression. The program is shorter and the intention is clearer."),
  (E, "Counters are used for word frequencies, for histograms of votes, for tallies of log levels and in tests that compare two collections without regard to order. The two counters Counter('aab') and Counter('aba') are equal, which a plain list comparison would deny."),
  (H, "A Counter is a dict, so every dictionary operation works on it. Counter(iterable) loops once over the iterable and adds one for each element. Looking up an absent element returns 0 and does not store it, so the key is not added by being looked at. Sums keep only the positive counts: Counter(a=1) - Counter(a=5) is an empty Counter, because the result would be negative. The method update adds to the counts instead of replacing them, unlike dict.update. Among elements with equal counts, most_common keeps the order in which they were first met."),
  (K, "The Counter looks like a dictionary and behaves like one with a different update rule, so Counter.update(other) adds counts and dict.update(other) replaces values. Counts may be zero or negative when set directly, and the + and - operators drop such entries. For counting where a different starting value than zero is needed, use defaultdict or the setdefault pattern."),
 ]),
 ("DefaultdictCounting", "The defaultdict class", 3, "Counting", ("collections.defaultdict(int)", "A defaultdict calls a factory function to create the value for a missing key and stores it, so defaultdict(int) starts every count at 0 and lets count[key] += 1 work on a key that has never been seen.", ("(lambda dd: (dd.__setitem__('x', dd['x'] + 1), dd['y'], dict(dd), dd.default_factory.__name__, dd.get('q'), 'q' in dd)[2:])(__import__('collections').defaultdict(int))", "({'x': 1, 'y': 0}, 'int', None, False)")), [
  (W, "A defaultdict is a dictionary from the collections module that has a rule for missing keys. It is made with a factory, a function that takes no arguments, such as int, list or set. When a key is looked up with square brackets and is not there, the defaultdict calls the factory, stores the result under the key and returns it. The documentation describes the first argument, default_factory, as the value for the attribute of that name, initialized to None if absent [PSF]."),
  (Y, "The factory removes the 'does the key exist yet' step from the program. With defaultdict(int), the whole body of the character count is count[character] += 1, because int() is 0. With defaultdict(list), a dictionary of lists needs no setup. The cost is a side effect that learners must know: looking at a missing key creates it."),
  (E, "The defaultdict is used for counters, for dictionaries of lists, and for dictionaries of sets, where the factory is int, list or set. It is common in code that reads files line by line and files each line under a key."),
  (H, "The special rule is part of the subscript operation and nothing else. In count['y'], a defaultdict(int) sees the missing key, calls int(), stores 0 under 'y' and returns 0, so afterwards 'y' is in the dictionary. The method get does not use the factory: dd.get('q') is None and leaves the dictionary as it was, and the test 'q' in dd is False. The class is a subclass of dict, so the usual operations and printing work, with dict(dd) available when a plain dictionary is needed."),
  (K, "A lookup that creates keys can fill a dictionary with unwanted entries: a mistyped key in a read-only report quietly becomes a pair with value 0. Use the method get or the in test to look without creating. And pass the factory itself, int, not a call, int(), since the argument must be a function that Python can call later."),
 ]),
 ("Grouping", "Grouping items under labels", 2, "CountingAndGrouping", None, [
  (W, "Grouping items under labels is the pattern in which each key leads to a list of the items that share it, such as words under their first letters or orders under their customers. The value is a collection, and the main step is to put the item into the collection of its key, creating the collection the first time."),
  (Y, "Grouping organises raw data for reading and for later steps: totals per group, the biggest group, the groups that are empty. It is the same step as counting, with a list in place of a number, and it is solved with the same tools."),
  (H, "Two concepts follow. The first is the dictionary of lists built with setdefault or defaultdict. The second is the __missing__ hook with which a dictionary subclass decides what a missing key means."),
 ], None),
 ("GroupingIntoLists", "A dictionary of lists", 3, "Grouping", ("groups.setdefault(word[0], []).append(word)", "Grouping puts each item into the list stored under its label; setdefault(label, []) creates the list on the first sight of a label and returns it, so .append can follow in the same statement, and a defaultdict(list) does the same without the call.", ("(lambda w: (lambda g: ([g.setdefault(x[0], []).append(x) for x in w], g)[1])({}))(['apple', 'avocado', 'banana', 'blueberry', 'cherry', 'apricot'])", "{'a': ['apple', 'avocado', 'apricot'], 'b': ['banana', 'blueberry'], 'c': ['cherry']}")), [
  (W, "A dictionary of lists maps a label to the list of all the items that carry the label. For the words apple, avocado, banana, blueberry, cherry and apricot, grouped by first letter, the result is {'a': ['apple', 'avocado', 'apricot'], 'b': ['banana', 'blueberry'], 'c': ['cherry']}. The statement groups.setdefault(word[0], []).append(word) builds it: setdefault returns the list stored under the letter, creating it first if needed, and append adds the word to that list."),
  (Y, "Each label is seen many times and its list must be created only once. The setdefault method solves it in one line, which is the use that its documentation example suggests, and a defaultdict(list) solves it even more simply with same[word[0]].append(word). The two give equal dictionaries."),
  (E, "The pattern groups log lines by level, students by class, transactions by account, files by extension and words by length. It is the first half of a 'group by' in a database and of the groupby of a spreadsheet, and the second half is a summary of each list, such as len or sum."),
  (H, "Both versions rest on the same fact: a list is mutable, so appending to the list found under the key changes the list inside the dictionary. Python does not need to store the list again. The groups appear in the order in which their labels were first met, and within a group the items stay in the order of the input."),
  (K, "The default list must be a new object for every key. The call setdefault(label, []) writes a new empty list each time, and all but the first are thrown away, which is harmless but slow. The mistake to avoid is dict.fromkeys(labels, []), which makes one list shared by all keys, as an earlier concept showed."),
 ]),
 ("MissingKeyHook", "The __missing__ hook", 3, "Grouping", ("class Zero(dict): def __missing__(self, key): return 0", "A dictionary subclass that defines the method __missing__ decides what d[key] means for an absent key; the lookup calls it, while get() and the in test do not, and what it returns is not stored unless the method stores it.", ("(lambda Z: (Z()['a'], 'a' in Z(), Z().get('a'), len(Z())))(type('Z', (dict,), {'__missing__': lambda self, key: 0}))", "(0, False, None, 0)")), [
  (W, "The __missing__ method is the hook through which a subclass of dict decides what happens when the subscript meets an absent key. The documentation says that if a subclass of dict defines a method __missing__() and key is not present, the d[key] operation calls that method with the key as argument, and that the key lookup then returns or raises whatever the method returns or raises [PSF]. A hook is a method that Python calls at a fixed moment so that a program can change what happens there."),
  (Y, "The hook is the general mechanism behind the defaultdict, which is implemented with it, and it allows rules that a factory cannot express: a default that depends on the key, a friendlier error message, a value that is computed and stored the first time and found afterwards. A dictionary that remembers its own computed results is a cache."),
  (E, "It is used in classes that offer a dictionary with a fallback, as in configuration objects that return a default for unknown settings, in caches that compute on first use, and in tools that translate a missing key into a clearer message than KeyError."),
  (H, "The subscript d[key] first looks the key up as usual. If it finds nothing and the dictionary's class defines __missing__, Python calls d.__missing__(key) and returns its result. The hook is called only by the subscript: d.get(key) and key in d never reach it, which is why they report None and False for the example of this concept, and why the dictionary stays empty unless the hook stores the value itself."),
  (K, "The hook is looked up on the class, so a function assigned to the instance is not used. A hook that stores its result must do the storing itself with self[key] = value. Remember also that the hook applies to d[key] only: counts read with get() will not show the default, and code that mixes the two ways of looking up will behave in two ways."),
 ]),
]
CHECKS += [("(lambda message: (lambda count: ([count.setdefault(c, 0) is None for c in message], [count.__setitem__(c, count[c] + 1) for c in message], count['c'], count[' '], count['A'], len(count), sum(count.values()))[2:])({}))('It was a bright cold day in April, and the clocks were striking thirteen.')", "(3, 13, 1, 23, 73)"),
           ("len('It was a bright cold day in April, and the clocks were striking thirteen.')", "73"),
           ("(lambda C: (C('abracadabra').most_common(2), C('abracadabra')['z'], C(a=3) + C(a=1, b=2), C(a=1) - C(a=5)))(__import__('collections').Counter)", "([('a', 5), ('b', 2)], 0, Counter({'a': 4, 'b': 2}), Counter())"),
           ("(lambda C: (C('aab') == C('aba'), 'z' in (lambda c: (c['z'], c)[1])(C('a'))))(__import__('collections').Counter)", "(True, False)"),
           ("(lambda C: (lambda c: (c.update('bcc'), c)[1])(C('aab')))(__import__('collections').Counter)", "Counter({'a': 2, 'b': 2, 'c': 2})"),
           ("__import__('collections').Counter.__mro__[1].__name__", "'dict'"),
           ("(lambda dd: (dd.__setitem__('x', dd['x'] + 1), dd['y'], dict(dd), dd.default_factory.__name__, dd.get('q'), 'q' in dd)[2:])(__import__('collections').defaultdict(int))", "({'x': 1, 'y': 0}, 'int', None, False)"),
           ("(lambda dl: (dl['k'].append(1), dl['k'].append(2), dict(dl))[2])(__import__('collections').defaultdict(list))", "{'k': [1, 2]}"),
           ("__import__('collections').defaultdict.__mro__[1].__name__", "'dict'"),
           ("(lambda w: (lambda g: ([g.setdefault(x[0], []).append(x) for x in w], g)[1])({}))(['apple', 'avocado', 'banana', 'blueberry', 'cherry', 'apricot'])", "{'a': ['apple', 'avocado', 'apricot'], 'b': ['banana', 'blueberry'], 'c': ['cherry']}"),
           ("(lambda w, D: (lambda g: ([g[x[0]].append(x) for x in w], dict(g))[1])(D(list)))(['apple', 'avocado', 'banana', 'blueberry', 'cherry', 'apricot'], __import__('collections').defaultdict)", "{'a': ['apple', 'avocado', 'apricot'], 'b': ['banana', 'blueberry'], 'c': ['cherry']}"),
           ("(lambda Z: (Z()['a'], 'a' in Z(), Z().get('a'), len(Z())))(type('Z', (dict,), {'__missing__': lambda self, key: 0}))", "(0, False, None, 0)"),
           ("(lambda Z: (lambda z: (z['a'], list(z)))(Z()))(type('Z', (dict,), {'__missing__': lambda self, key: self.setdefault(key, 7)}))", "(7, ['a'])"),
           PROG(CHARACTER_COUNT, CHARACTER_COUNT_OUT), PROG(CHARCOUNT_SHORT, "3 13 1\n23 different characters in 73 characters\n"), PROG(GROUPING, GROUPING_OUT)]
RAISES += [("__import__('collections').defaultdict(int())", "TypeError")]
