"""SEN0414 chapter 7, corpus text C (version 1.0.0): the branches 'Structuring data' and 'Practice work'.
Every output, error message and number quoted below is in CHECKS, RAISES or the leaf's own input-output example and is executed by
sen0414_ch07_corpus_v1_0_0.py. The citation tokens are resolved there."""
__version__ = "1.0.0"
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sen0414_ch07_corpus_base_v1_0_0 import *

_START = ("{**{c + '1': 'w' + p for c, p in zip('abcdefgh', 'RNBQKBNR')}, **{c + '2': 'wP' for c in 'abcdefgh'}, "
          "**{c + '8': 'b' + p for c, p in zip('abcdefgh', 'RNBQKBNR')}, **{c + '7': 'bP' for c in 'abcdefgh'}}")
_BOOK = "{'h1': 'bK', 'c6': 'wQ', 'g2': 'bB', 'h5': 'bQ', 'e3': 'wK'}"
_VAL_DEF = VALIDATOR.split("book_board =")[0]
_INV_DEF = INVENTORY.split("display_inventory(stuff)")[0]
_ALL = "{'Alice': {'apples': 5, 'pretzels': 12}, 'Bob': {'ham sandwiches': 3, 'apples': 2}, 'Carol': {'cups': 3, 'apple pies': 1}}"

# ============================================================ Structuring data
RAW += [
 ("StructuringData", "Structuring data", 1, None, None, [
  (W, "Structuring data is the branch about designing the dictionary before writing the code that uses it: deciding what the keys are, what the values are, how values nest, and how the result is shown or stored. The chapter's section is titled Model Real-World Things Using Data Structures, and its claim is that we can model all real-world objects or processes by designing data structures and writing functions to work with those data structures [SW]."),
  (Y, "A data structure is a decision, and the decision shapes the program. With a good one the code is short and obvious, as the chessboard printer is once the board is a dictionary of squares; with a poor one every operation needs a workaround. The chapter's advice to beginners is not to worry about the right way, because the important thing is that the model works for the program's needs [SW]."),
  (E, "Every program that stands for something outside itself uses a model: a game board, a customer record, a shopping basket, a map. Real data also leaves the program as text, for a person to read or for another program to parse, which is why the branch ends with the notations in which a structure is written down."),
  (H, "The branch has three parts. Modelling a chessboard walks through the interactive chessboard simulator of the chapter, from the data structure to the commands. Nested structures treats dictionaries that hold dictionaries, with the picnic program and the difference between kinds of copy. Written notation covers pretty-printing, JSON text, typed records and the match statement's mapping pattern."),
 ], None),
 ("Modelling", "Modelling a chessboard", 2, "StructuringData", None, [
  (W, "Modelling a chessboard is the worked example with which the chapter shows the design of a data structure. Chess is described by squares named with a letter and a number and by pieces named with a colour and a letter, and the program has to hold the position, draw it and change it on command. The chapter builds an interactive chessboard simulator in which the whole position is one dictionary."),
  (Y, "A complete small program shows every part of the work: choosing the representation, writing a function that draws it, and writing the commands that change it. It also shows that the program does not need to know the rules of chess: it holds a position and does what the user says, which is all that a simulator has to do [SW]."),
  (H, "Six concepts follow, in the order of the program: the idea of a data structure, the board as a dictionary, the text template of the board, the function that fills the template, the star syntax that it uses, and the command loop."),
 ], None),
 ("DataStructureModel", "A data structure as a model", 3, "Modelling", ("{'h1': 'bK', 'c6': 'wQ', 'g2': 'bB', 'h5': 'bQ', 'e3': 'wK'}", "A data structure models a real thing when its parts stand for the parts of the thing; the five pairs of this dictionary stand for five pieces on a chessboard, with each square as a key and each piece as its value.", ("(lambda b: (len(b), b['c6'], 'a1' in b))(" + _BOOK + ")", "(5, 'wQ', False)")), [
  (W, "A data structure is a way of arranging values in memory, and a model is a data structure that stands for something outside the program. The chapter uses chess to show the idea: the dictionary {'h1': 'bK', 'c6': 'wQ', 'g2': 'bB', 'h5': 'bQ', 'e3': 'wK'} stands for a board with a black king on h1, a white queen on c6, a black bishop on g2, a black queen on h5 and a white king on e3 [SW]. Each key is a square and each value is a piece."),
  (Y, "Designing a model means asking what must be remembered and what can be found out. A chessboard needs to remember which piece is on which square; it need not remember which squares are empty, because the empty ones are the ones that are not mentioned. The chapter states this design choice: the absence of a key in the dictionary represents an empty square [SW]."),
  (E, "The same step is taken in every program that represents the world: an address book is a dictionary from names to numbers, a spreadsheet is a dictionary from cell names to contents, a weather record is a dictionary from place and time to measurements. The chapter points to a second example of modelling a game board, in the author's other book, which holds a tic-tac-toe position [SW]."),
  (H, "In the model the five pieces are five pairs, so len(board) is 5 and board['c6'] is 'wQ'. The test 'a1' in board is False, because no piece stands on a1. Any operation on the position becomes an operation on the dictionary: moving a piece changes two pairs, taking a piece removes one."),
  (K, "A model is only as good as the questions it can answer. This one answers 'what is on e3' at once and 'where is the white queen' only by looking at every pair. If the second question mattered more, the model would be turned around, with pieces as keys and squares as values, and another set of problems would appear because there can be several pawns of one colour."),
 ]),
 ("ChessboardModel", "The board as a dictionary", 3, "Modelling", ("STARTING_PIECES", "The chessboard simulator keeps the position as a dictionary from square names a1 to h8 to piece names such as wR, with a constant STARTING_PIECES holding the 32 pieces of the starting position and a copy of it made whenever the board is reset.", ("(lambda S: (len(S), S['d1'], S['e8'], sorted(set(S.values())), sum(p[0] == 'w' for p in S.values())))(" + _START + ")", "(32, 'wQ', 'bK', ['bB', 'bK', 'bN', 'bP', 'bQ', 'bR', 'wB', 'wK', 'wN', 'wP', 'wQ', 'wR'], 16)")), [
  (W, "The chessboard dictionary has string keys from 'a1' to 'h8' for the squares and two-letter string values for the pieces: the first letter is the colour, w or b, and the second is the kind, P for pawn, N for knight, B for bishop, R for rook, Q for queen and K for king. The chapter notes that the keys are always two characters long, with the letter lowercase and before the number, and that the program relies on that [SW]. The constant STARTING_PIECES holds the starting position."),
  (Y, "A name written in capitals marks a constant, a value that the program does not change. Keeping the starting position as a constant and handing out copies means that the board can always be reset. The start position has 32 pieces, 16 of each colour, and so the dictionary has 32 keys: the chapter's own figures say that each player starts with 16 pieces [SW]."),
  (E, "The squares are those of algebraic chess notation, the notation used by players to write down games and to play by post, as the chapter describes [SW]. The same representation, a dictionary from board coordinates to contents, is used for any board game, for a map in a role-playing game and for a sparse spreadsheet, where most cells are empty."),
  (H, "The dictionary can be written out as in the book, in four rows of eight pairs, or generated from the rules: the back rank is the string RNBQKBNR, the second rank is all pawns, and the black side repeats them on ranks 8 and 7. Either way there are 32 pairs, the white queen stands on d1 and the black king on e8. Because a dictionary is a mutable value, the program takes copy.copy(STARTING_PIECES) as its working board, and a change to the working board does not reach the constant."),
  (K, "The model allows positions that chess does not: two kings of one colour, a pawn on the first rank, or a piece on a square named 'i9'. The chapter says so, since the program does not even enforce how pieces move [SW]; a function that checks a board against the rules is the first of the practice programs."),
 ]),
 ("BoardTemplate", "The board template string", 3, "Modelling", ("BOARD_TEMPLATE.format(*squares)", "The board is drawn from a template, a multi-line string with 64 empty pairs of curly brackets, one for each square, which the format method fills with 64 strings in order.", ("'| {} | {} |'.format('wK', 'bK')", "'| wK | bK |'")), [
  (W, "A template string is a string with holes. In the chessboard program the string BOARD_TEMPLATE spreads over many lines and draws the frame of the board in text characters; wherever a square belongs, it has the pair of curly brackets {}. The string method format() replaces the first {} with its first argument, the second {} with its second, and so on [PSF]. There are 64 pairs, one for each square."),
  (Y, "The template separates the look of the board from the logic. The function that prints the board does not draw lines and corners; it only has to say what goes into each square, and the template does the rest. Changing the picture of the board means editing one string and leaves the code alone. The book's remark that the output assumes a black background explains why the white squares are drawn with filled characters."),
  (E, "The same technique writes form letters, invoices and web pages: the fixed text is a template and the changing parts are filled in. The format method is the older cousin of the f-string, which fills holes with expressions written inside the string itself."),
  (H, "Calling BOARD_TEMPLATE.format(*squares) makes a new string in which each {} has been replaced, left to right and top to bottom, so the order of the 64 values matters as much as their number. The program prints that string, and the board appears. With too few arguments, format raises IndexError; with too many, the extra ones are ignored."),
  (K, "Each filled square must have the same width as the hole, or the frame breaks: the pieces are two characters wide and so are the white and black empty squares ('||' and two spaces). A literal curly bracket in a template must be doubled, as {{ and }}. The number of holes and the number of squares are one fact seen twice, and the program counts on it."),
 ]),
 ("ChessboardPrinter", "The printing function", 3, "Modelling", ("print_chessboard(board)", "The function print_chessboard builds a list of 64 strings by looping over the ranks 8 to 1 and the files a to h, taking the piece from the dictionary when the square is a key and an empty-square string otherwise, with a Boolean tracking the colour of the square.", ("(lambda board: (lambda sq: (len(sq), sq[0], sq[1], sq[63]))([board[x + y] if x + y in board else ('||' if (i + j) % 2 == 0 else '  ') for i, y in enumerate('87654321') for j, x in enumerate('abcdefgh')]))(" + _BOOK + ")", "(64, '||', '  ', 'bK')")), [
  (W, "The function print_chessboard(board) turns a chessboard dictionary into a picture. It makes an empty list called squares. Two nested for loops visit the 64 squares, the outer one over the characters of '87654321' and the inner one over those of 'abcdefgh', which starts at the upper left, and for each square the function appends one string [SW]. If the key x + y, for example 'c6', is in the board, the string is the piece; otherwise it is WHITE_SQUARE ('||') or BLACK_SQUARE (two spaces) according to the colour."),
  (Y, "The function is where the choice of model pays off. It does not search for pieces; it asks the dictionary one question per square, and the dictionary answers at once. The absent key is the empty square, so a single test, x + y in board.keys(), decides between the two branches. The colour of an empty square only matters for the picture, so it is carried by a Boolean variable, is_white_square, that flips at every square."),
  (E, "A nested loop over the rows and columns of a grid is the standard way to visit every cell of a table, an image or a game board. The colours of a chessboard alternate along a row and, because the board has 8 columns, the flip at the end of each row has to be done a second time so that the next row starts with the opposite colour; the program does this with a second flip after the inner loop."),
  (H, "For the board {'h1': 'bK', 'c6': 'wQ', ...} the list has 64 strings: the first is '||' for the empty white square a8, the second is two spaces for the black square b8, and the last, for h1, is 'bK'. The letters and digits are joined with +, and the test uses in on the dictionary's keys, as the earlier branch described. The list is handed to format with a star."),
  (K, "The loops must run over '87654321' and not '12345678', since the picture shows rank 8 at the top. The function uses the colour flip and the template in step, so changing one without the other garbles the board. And it only prints: a function that returned the string would be easier to test."),
 ]),
 ("StarSyntax", "Star syntax", 3, "Modelling", ("BOARD_TEMPLATE.format(*squares)  and  print(*spam)", "A star before a list in a call passes the list's items as separate arguments, and a double star before a dictionary passes its pairs as keyword arguments, so format(*squares) gives format 64 arguments instead of one list.", ("(lambda spam: ('{} {} {}'.format(*spam), '{a}-{b}'.format(**{'a': 1, 'b': 2})))(['cat', 'dog', 'rat'])", "('cat dog rat', '1-2')")), [
  (W, "Star syntax is the name the chapter gives to the asterisk in a call such as BOARD_TEMPLATE.format(*squares). The star unpacks a list, which means that it hands the items to the function one at a time. The chapter explains it with spam = ['cat', 'dog', 'rat']: print(spam) prints the list with its brackets and quotes, and print(*spam) is the same as print('cat', 'dog', 'rat') and prints cat dog rat [SW]. The language reference calls it an iterable unpacking in a call, and the double star its mapping counterpart [PSF]."),
  (Y, "The method format wants one argument for each hole, and the program has a list. Without the star the call would give format a single argument, a list, for the first hole and nothing for the other 63, and Python would raise an error. With it, a list of any length becomes an argument list, which is how a program fills a template whose size it does not know when the code is written."),
  (E, "The double-star form passes a dictionary as keyword arguments: '{a}-{b}'.format(**{'a': 1, 'b': 2}) is '1-2', because each key becomes the name of an argument. It is the way a record held in a dictionary is handed to a function, and it is the reason keys that will become argument names must be strings. The same star in a literal, as in {**a, **b}, merges two dictionaries, as the earlier branch showed [PEP448]."),
  (H, "At the call, Python takes the items of the list in order and puts them in the argument slots from left to right. The star works on any iterable, a list, a tuple or a string, and the function sees only the separate values. Calling '{} {}'.format(['a', 'b']) without the star raises IndexError: Replacement index 1 out of range for positional args tuple."),
  (K, "The star at a call is not multiplication and not the star in a def line, where it gathers arguments into a tuple; the two are opposites. Unpacking a very long list into a call can be slow, and a function with a fixed number of parameters receives an error when the count is wrong."),
 ]),
 ("ChessboardCommands", "The command loop", 3, "Modelling", ("input('> ').split()", "The simulator reads a line, splits it into words with split(), and chooses the action from the first word: move copies and deletes a pair, remove deletes, set assigns, reset copies the starting position, clear makes an empty dictionary, fill sets all 64 squares, and quit ends the program.", ("(lambda response: (response, response[0], response[1:]))('move e2 e4'.split())", "(['move', 'e2', 'e4'], 'move', ['e2', 'e4'])")), [
  (W, "The command loop is the end of the chessboard program: an infinite while loop that prints the board, reads a line with input('> '), splits it into a list of words with the split() method, and acts on the first word. For example, move e2 e4 gives the list ['move', 'e2', 'e4'], and the program stores it in response [SW]. An if and elif chain compares response[0] with the command names."),
  (Y, "Each command is one of the dictionary operations of the earlier branch, which is the point of the project. Move is an assignment followed by a del; remove is a del; set is an assignment; reset replaces the working board with a fresh copy of the starting position; clear replaces it with the empty dictionary; fill sets every square in a nested loop; quit leaves the program through sys.exit(). Nothing in the loop knows about chess."),
  (E, "The shape of the loop, read a line, split it into words, dispatch on the first word, is the shape of command interpreters everywhere: shells, game consoles, database clients and chat bots. A dictionary of functions is a common later replacement for the long elif chain."),
  (H, "After each command the loop returns to its top and prints the changed board. Move copies main_board[response[1]] to main_board[response[2]] and then deletes the old key. The reset command rebinds the name main_board to a new copy, copy.copy(STARTING_PIECES), so the changes made before it are dropped without being undone one by one. The deck runs the same commands on a small position and prints the squares that hold pieces after each one."),
  (K, "The program does not check the user's input: move on an empty square raises KeyError, and a line with too few words raises IndexError, and either stops the program. It does not check chess rules either, so a pawn may be moved to any square. These are left in because the chapter's aim is the data model; the practice program on validation takes up one half of the problem."),
 ]),
 ("Nesting", "Nested structures", 2, "StructuringData", None, [
  (W, "Nested structures are dictionaries and lists that contain other dictionaries and lists. The chapter says that as you model more complicated things, you may need dictionaries and lists that contain other dictionaries and lists, and it gives the picnic example, a dictionary of guests in which every guest has a dictionary of items [SW]."),
  (Y, "Real data has levels: a guest brings several items, a class has several students, a student has several grades. Nesting lets the data structure have the same levels. It also brings the problem of copying, because an inner value may be shared between copies."),
  (H, "Three concepts follow. The first is the nested dictionary with its chained lookups. The second is the total_brought function of the picnic program, which walks the two levels. The third is the difference between an alias, a shallow copy and a deep copy."),
 ], None),
 ("NestedDictionaries", "Nested dictionaries", 3, "Nesting", ("all_guests['Bob']['apples']", "A nested dictionary holds dictionaries as values, and a lookup is chained, one pair of brackets for each level: all_guests['Bob']['apples'] first finds Bob's dictionary and then the apples in it.", ("(lambda all_guests: (all_guests['Bob']['apples'], 'cups' in all_guests['Bob'], sorted(all_guests['Carol']), len(all_guests)))(" + _ALL + ")", "(2, False, ['apple pies', 'cups'], 3)")), [
  (W, "A nested dictionary is a dictionary whose values are dictionaries. In the picnic program, all_guests maps each guest's name to a dictionary of the items that guest brings: Alice brings 5 apples and 12 pretzels, Bob brings 3 ham sandwiches and 2 apples, and Carol brings 3 cups and 1 apple pie [SW]. Values can also be lists, so a dictionary of lists, or a list of dictionaries, are other forms of the same idea."),
  (Y, "Nesting is how a program keeps the structure of its data. Without it the picnic would need a dictionary of strings such as 'Alice apples', which the program would have to build and cut apart. With it, each level has its own meaning: the outer keys are people, the inner keys are things, and the numbers are quantities."),
  (E, "Nested dictionaries are what a program obtains when it reads JSON from a web service, a configuration file or a database, and nearly all structured data comes in this shape. Moving through the levels is written with chained brackets, all_guests['Bob']['apples'], which is 2."),
  (H, "Python evaluates the chain from left to right. The first lookup, all_guests['Bob'], gives Bob's dictionary, which is an ordinary dictionary value; the second lookup is made in that dictionary. Each level can fail on its own: all_guests['Dave']['apples'] raises KeyError for 'Dave', and all_guests['Bob']['cups'] raises KeyError for 'cups'. The method get at the last level, as in v.get(item, 0), protects against the second kind."),
  (K, "A deeply nested structure is hard to read and to check. When the number of levels grows past three, a class, a named tuple or a TypedDict is usually clearer. Beware of assuming that every inner dictionary has the same keys: in the picnic data they do not, and the code has to cope."),
 ]),
 ("TotalBrought", "The total_brought function", 3, "Nesting", ("total_brought(all_guests, 'apples')", "The function total_brought loops over the guests with items() and adds v.get(item, 0) from each guest's dictionary, so a guest who does not bring the item adds zero, and the call for apples returns 7.", ("(lambda all_guests: [sum(v.get(item, 0) for k, v in all_guests.items()) for item in ('apples', 'cups', 'cakes', 'ham sandwiches', 'apple pies')])(" + _ALL + ")", "[7, 3, 0, 3, 1]")), [
  (W, "The function total_brought(guests, item) adds up how many of one item all the guests are bringing. It starts a total at 0, loops over the pairs of the outer dictionary with for k, v in guests.items(), and adds v.get(item, 0), the quantity from the guest's own dictionary or zero when that dictionary has no such key [SW]. For the picnic data the totals are 7 apples, 3 cups, 0 cakes, 3 ham sandwiches and 1 apple pie."),
  (Y, "The function is where the earlier tools meet: the items loop gives the two halves of each pair, and the get method removes the need to ask first whether the guest brings the item. The chapter makes the point that the same function could easily handle a dictionary with thousands of guests bringing thousands of different items, and the data structure saves a lot of time [SW]."),
  (E, "Totals over groups are the daily work of a program that holds records: total sales per product, total hours per employee, total votes per party. The two-level loop is also written as a single expression, sum(v.get(item, 0) for v in guests.values()), once the key k, which the function does not use, is dropped."),
  (H, "For item 'apples', the loop visits Alice (adds 5), Bob (adds 2) and Carol (adds 0 because get returns the fallback), so the returned total is 7. For 'cakes' all three guests add 0 and the result is 0, which is the honest answer: nobody is bringing cakes. The function does not change the dictionary; get only reads."),
  (K, "The variable k is never used, and a reader may take that for a bug; the loop over values() says it better. A typing mistake in the item name does not raise an error but returns 0, which looks like a real answer. The function sums quantities and does not know what they mean: apples and apple pies are separate keys, and 'apple' would match neither."),
 ]),
 ("CopyingDictionaries", "Copying dictionaries", 3, "Nesting", ("copy.copy(original)  and  copy.deepcopy(original)", "An assignment makes a second name for the same dictionary; copy.copy makes a new outer dictionary that still shares the inner ones; copy.deepcopy copies every level, so changing an inner value of the original reaches the alias and the shallow copy but not the deep copy.", ("(lambda copy, o: (lambda s, d: (o['Alice'].__setitem__('apples', 99), s['Alice']['apples'], d['Alice']['apples'], s['Alice'] is o['Alice'], d['Alice'] is o['Alice'])[1:])(copy.copy(o), copy.deepcopy(o)))(__import__('copy'), {'Alice': {'apples': 5}})", "(99, 5, True, False)")), [
  (W, "Copying a dictionary can mean three different things. An assignment, alias = original, copies nothing: both names refer to one dictionary. A shallow copy, made by copy.copy(original) or original.copy() or dict(original), makes a new outer dictionary whose values are the same objects as the old ones. A deep copy, made by copy.deepcopy(original), makes new copies at every level. The documentation of the copy module defines the first two in exactly these terms [PSF]."),
  (Y, "The chessboard program resets the board with copy.copy(STARTING_PIECES), and the book's choice is right there, because the values are strings, which cannot change, so sharing them does no harm. For a nested structure it would be wrong: the picnic data's inner dictionaries are mutable, and a shallow copy shares them, so a change made through the copy appears in the original."),
  (E, "Copying matters whenever a program wants to try a change and keep the old state: undo in an editor, a game that looks ahead at moves, a test that must not change its input. The error is met as data that changes 'by itself', when two parts of a program unknowingly share one inner dictionary."),
  (H, "After original['Alice']['apples'] = 99, the alias shows 99 because it is the original, the shallow copy shows 99 because its 'Alice' value is the very same inner dictionary (s['Alice'] is o['Alice'] is True), and the deep copy still shows 5 because it built its own inner dictionaries. Reassigning a whole key in the original, as in original['Alice'] = {...}, would not reach the shallow copy, which has its own outer pairs."),
  (K, "Shallow is enough only when every value is immutable. If in doubt, deepcopy, at the cost of time and memory for large structures. Remember that a copy of an object that refers to itself, or to an open file, may fail or behave strangely, and that the copy module copies the data and not the identity of the program's other references."),
 ]),
 ("Notation", "Written notation", 2, "StructuringData", None, [
  (W, "Written notation is the set of ways in which a data structure is written down as text or described in a program's source: pretty-printed Python, JSON text, a typed record class and the match statement's patterns for dictionaries. The chapter asks about the first in its practice questions and leaves the others to the reader."),
  (Y, "A structure that is hard to read cannot be debugged, and a structure that cannot leave the program cannot be stored or sent. Each notation answers one of those needs: to look at a dictionary, to save it, to say which keys it must have, and to take it apart by its shape."),
  (H, "Four concepts follow: the pprint module, the json module, the TypedDict class and the mapping pattern."),
 ], None),
 ("PrettyPrinting", "Pretty-printing", 3, "Notation", ("pprint.pprint(spam)", "The pprint module prints a dictionary in a readable layout, with the keys in sorted order by default and nested structures broken over lines when they are wider than the line width; pformat returns the same text as a string.", ("(lambda p: (p.pformat({'b': 1, 'a': 2}), p.pformat({'b': 1, 'a': 2}, sort_dicts=False)))(__import__('pprint'))", "(\"{'a': 2, 'b': 1}\", \"{'b': 1, 'a': 2}\")")), [
  (W, "Pretty-printing is printing a data structure in a layout that a person can read. The practice questions of the chapter ask which module and function can be used to pretty-print dictionary values [SW]; the answer is the pprint module and its pprint() function. The documentation says that the pprint module provides a capability to print arbitrary Python data structures in a form which can be used as input to the interpreter, and its pformat() function returns the text as a string [PSF]."),
  (Y, "The print function puts a large dictionary on a single line that scrolls out of sight. The pprint function breaks it where the line would be too wide, indents the nested levels under their keys, and sorts the keys, so that two runs of the program print the same text and two dictionaries can be compared by eye. It is the quickest way to inspect nested data while debugging."),
  (E, "It is used when a program prints a configuration, a response from a web service or the contents of a nested dictionary like the picnic data. The default of sorting keys is on: pformat({'b': 1, 'a': 2}) is \"{'a': 2, 'b': 1}\", and sort_dicts=False, available since Python 3.8, keeps the insertion order."),
  (H, "The function pprint.pprint(spam) works out the width of the text, which is 80 characters by default and can be changed with the width argument. If the whole structure fits, it is printed on one line; otherwise each key goes on its own line and the values that are too wide are broken again. The text it makes is valid Python, so it can be copied back into a program."),
  (K, "Sorting the keys hides the insertion order, which the earlier branch made a feature, and so a program that wants to show the order sets sort_dicts=False. Pretty-printing is for people; a program that stores data should use a format with a standard, such as JSON. And pprint prints, so the string form needs pformat."),
 ]),
 ("JsonText", "JSON text", 3, "Notation", ("json.dumps(spam) and json.loads(text)", "JSON is a text notation whose objects and arrays correspond to dictionaries and lists; json.dumps turns a structure into text and json.loads turns text back, with the limits that JSON keys are always strings and a tuple comes back as a list.", ("(lambda j: (j.dumps({'b': 1, 'a': [1, 2]}), j.loads(j.dumps({1: 'a'})), j.loads(j.dumps({'t': (1, 2)}))))(__import__('json'))", '''('{"b": 1, "a": [1, 2]}', {'1': 'a'}, {'t': [1, 2]})''')), [
  (W, "JSON, JavaScript Object Notation, is a text format for data with objects written in curly brackets with string keys, arrays in square brackets, strings, numbers, true, false and null. Its structure is the structure of Python's dictionaries and lists, and the json module converts between the two: json.dumps(obj) returns the text, and json.loads(text) returns the Python value [PSF]. Python's dictionary becomes a JSON object, a list becomes an array, True becomes true and None becomes null."),
  (Y, "A dictionary lives only as long as the program does. JSON is the way to keep a dictionary in a file, which would cure the weakness the chapter's birthdays program admits to, or to send it to another program, even one written in another language; nearly every web service speaks it. It is readable by people as well as by machines."),
  (E, "JSON is met in configuration files, in the responses of web services, in logs and in the files of editors. The module json is in the standard library, so no installation is needed. The dictionary and the JSON text it produces look similar but are not the same: JSON uses double quotes and null where Python uses single quotes and None."),
  (H, "The function dumps walks the structure and writes each part in JSON's notation, in insertion order, giving '{\"b\": 1, \"a\": [1, 2]}' for the example. The function loads parses the text back, so loads('{\"a\": [1, 2], \"b\": null}') is {'a': [1, 2], 'b': None}. The conversion is not an exact round trip: an integer key 1 is written as the string \"1\" and comes back as '1', and a tuple is written as an array and comes back as a list."),
  (K, "A key that is a tuple cannot be written: json.dumps({(1, 2): 1}) raises TypeError with the message that keys must be str, int, float, bool or None, not tuple. Never build JSON by joining strings, and never load JSON from an untrusted source and execute it; json.loads parses only data and is safe in that sense, but the data it returns still needs checking."),
 ]),
 ("TypedModels", "Typed records with TypedDict", 3, "Notation", ("class Cat(TypedDict): size: str; age: int", "A TypedDict class declares which keys a dictionary should have and what type each value should be, for a type checker to verify; at run time the object is still an ordinary dict.", ("(lambda T: (T(size='fat', age=17), type(T(size='fat', age=17)).__name__, sorted(T.__required_keys__)))(__import__('typing').TypedDict('Cat', {'size': str, 'age': int}))", "({'size': 'fat', 'age': 17}, 'dict', ['age', 'size'])")), [
  (W, "A TypedDict is a class that describes the keys of a dictionary and the type of each value. PEP 589 introduced it to type dictionaries used as records, with a fixed set of keys, such as the cat of the chapter's opening example, {'size': 'fat', 'color': 'gray', 'age': 17} [PEP589]. It is declared in the typing module, in a class body with one annotation for each key."),
  (Y, "A record held in a plain dictionary gives no protection against a mistyped key or a value of the wrong type; the program fails later and elsewhere. The declaration documents the shape of the record, and a static type checker such as mypy or pyright can find the mistake before the program runs. It keeps the convenience of a dictionary."),
  (E, "TypedDict is used for the records read from JSON, for settings and for the arguments of functions that take a dictionary. It is common in code bases that are type-checked. The chapter's cat would be declared with size, color and age."),
  (H, "At run time a TypedDict does nothing: Cat(size='fat', age=17) creates an ordinary dictionary, its type is dict, and Python does not check the keys or types. The declaration is stored, and Cat.__required_keys__ lists the keys that must be present, here age and size. All keys are required unless marked otherwise. The checking is done by tools outside the interpreter."),
  (K, "The word typed suggests a check that does not happen when the program runs. Assigning a string to age is accepted by Python and is reported only by the type checker. For checks at run time, use the in test, a validator function like the one in the practice programs, or a library that validates data."),
 ]),
 ("MappingPattern", "The mapping pattern", 3, "Notation", ("match command: case {'type': 'move', 'from': a, 'to': b}:", "The match statement can take a dictionary apart by its shape: a mapping pattern matches when the keys it names are present, binds the values it names, and ignores any other keys.", ("(lambda ns: (exec('def f(p):' + chr(10) + ' match p:' + chr(10) + '  case {1: a, 2: b}:' + chr(10) + '   return (a, b)' + chr(10) + '  case _:' + chr(10) + '   return None', ns), ns['f']({1: 'e2', 2: 'e4', 3: 'extra'}), ns['f']({}))[1:])({})", "(('e2', 'e4'), None)")), [
  (W, "A mapping pattern is a pattern of the match statement that is written like a dictionary: {'type': 'move', 'from': a, 'to': b}. It matches a value that is a mapping, such as a dictionary, if all the keys of the pattern are present and the value for each key matches the sub-pattern written after it; a bare name, like a, binds the value to that name. PEP 634 specifies it and states that extra keys in the subject are ignored [PEP634]."),
  (Y, "Data that arrives as nested dictionaries, a command received from a network, a record from JSON, is awkward to take apart with chains of if and in. A mapping pattern says in one place what shape each kind of record has and what to do with it, and the names it binds can be used in the branch at once."),
  (E, "The mapping pattern is useful where the chessboard commands could be sent as dictionaries instead of typed text: {'type': 'move', 'from': 'e2', 'to': 'e4'} is matched by the first case and gives a = 'e2' and b = 'e4', {'type': 'quit'} is matched by the second, and anything else goes to the case with an underscore."),
  (H, "Python tries the cases from top to bottom. For a mapping pattern it checks that the subject is a mapping, checks that every key of the pattern is present, matches the value patterns, and only then binds the names. Keys in the pattern must be literals or constants; the subject may have more keys, as 'extra' shows. The pattern does not call __missing__ and does not add keys to a defaultdict."),
  (K, "The pattern is not a test for equality: {'type': 'quit'} also matches a dictionary with a dozen other keys, and an empty mapping pattern {} matches any mapping. Put the more specific case first. A name that is bound by a failed case may be left bound, and an underscore is the catch-all that binds nothing."),
 ]),
]
CHECKS += [("(lambda b: (len(b), b['c6'], 'a1' in b))(" + _BOOK + ")", "(5, 'wQ', False)"),
           ("(" + _START + ")['d1']", "'wQ'"),
           ("(lambda S: (len(S), S['d1'], S['e8'], sorted(set(S.values())), sum(p[0] == 'w' for p in S.values())))(" + _START + ")", "(32, 'wQ', 'bK', ['bB', 'bK', 'bN', 'bP', 'bQ', 'bR', 'wB', 'wK', 'wN', 'wP', 'wQ', 'wR'], 16)"),
           ("'| {} | {} |'.format('wK', 'bK')", "'| wK | bK |'"), ("'{{}} {}'.format('x')", "'{} x'"),
           ("'{} {}'.format('a', 'b', 'c')", "'a b'"),
           ("(lambda board: (lambda sq: (len(sq), sq[0], sq[1], sq[63]))([board[x + y] if x + y in board else ('||' if (i + j) % 2 == 0 else '  ') for i, y in enumerate('87654321') for j, x in enumerate('abcdefgh')]))(" + _BOOK + ")", "(64, '||', '  ', 'bK')"),
           ("(lambda spam: ('{} {} {}'.format(*spam), '{a}-{b}'.format(**{'a': 1, 'b': 2})))(['cat', 'dog', 'rat'])", "('cat dog rat', '1-2')"),
           ("(lambda spam: (' '.join(spam), [*spam]))(['cat', 'dog', 'rat'])", "('cat dog rat', ['cat', 'dog', 'rat'])"),
           ("(lambda response: (response, response[0], response[1:]))('move e2 e4'.split())", "(['move', 'e2', 'e4'], 'move', ['e2', 'e4'])"),
           ("'fill wP'.split()", "['fill', 'wP']"), ("'reset'.split()", "['reset']"),
           ("(lambda all_guests: (all_guests['Bob']['apples'], 'cups' in all_guests['Bob'], sorted(all_guests['Carol']), len(all_guests)))(" + _ALL + ")", "(2, False, ['apple pies', 'cups'], 3)"),
           ("(lambda all_guests: [sum(v.get(item, 0) for k, v in all_guests.items()) for item in ('apples', 'cups', 'cakes', 'ham sandwiches', 'apple pies')])(" + _ALL + ")", "[7, 3, 0, 3, 1]"),
           ("(lambda all_guests: sum(v.get('apples', 0) for v in all_guests.values()))(" + _ALL + ")", "7"),
           ("(lambda copy, o: (lambda s, d: (o['Alice'].__setitem__('apples', 99), s['Alice']['apples'], d['Alice']['apples'], s['Alice'] is o['Alice'], d['Alice'] is o['Alice'])[1:])(copy.copy(o), copy.deepcopy(o)))(__import__('copy'), {'Alice': {'apples': 5}})", "(99, 5, True, False)"),
           ("(lambda o: (o.copy() == o, o.copy() is o, dict(o) == o))({'a': 1})", "(True, False, True)"),
           ("(lambda p: (p.pformat({'b': 1, 'a': 2}), p.pformat({'b': 1, 'a': 2}, sort_dicts=False)))(__import__('pprint'))", "(\"{'a': 2, 'b': 1}\", \"{'b': 1, 'a': 2}\")"),
           ("__import__('pprint').pformat({'a': {'b': [1, 2, 3], 'z': 1}, 'age': 8, 'name': 'Zophie', 'tricks': ['sit', 'roll']}, width=30)", "\"{'a': {'b': [1, 2, 3],\\n       'z': 1},\\n 'age': 8,\\n 'name': 'Zophie',\\n 'tricks': ['sit', 'roll']}\""),
           ("(lambda j: (j.dumps({'b': 1, 'a': [1, 2]}), j.loads('{\"a\": [1, 2], \"b\": null}'), j.loads(j.dumps({1: 'a'})), j.loads(j.dumps({'t': (1, 2)}))))(__import__('json'))", "('{\"b\": 1, \"a\": [1, 2]}', {'a': [1, 2], 'b': None}, {'1': 'a'}, {'t': [1, 2]})"),
           ("__import__('json').dumps({'ok': True, 'none': None})", "'{\"ok\": true, \"none\": null}'"),
           ("(lambda T: (T(size='fat', age=17), type(T(size='fat', age=17)).__name__, sorted(T.__required_keys__)))(__import__('typing').TypedDict('Cat', {'size': str, 'age': int}))", "({'size': 'fat', 'age': 17}, 'dict', ['age', 'size'])"),
           ("(lambda T: T(size='fat', age='old'))(__import__('typing').TypedDict('Cat', {'size': str, 'age': int}))", "{'size': 'fat', 'age': 'old'}"),
           ("(lambda ns: (exec(\"def f(p):\\n    match p:\\n        case {'type': 'move', 'from': a, 'to': b}:\\n            return (a, b)\\n        case {'type': 'quit'}:\\n            return 'quit'\\n        case _:\\n            return None\\n\", ns), ns['f']({'type': 'move', 'from': 'e2', 'to': 'e4', 'extra': 1}), ns['f']({'type': 'quit', 'x': 1}), ns['f']({}))[1:])({})", "(('e2', 'e4'), 'quit', None)"),
           PROG(CHESSBOARD.split("print('Interactive")[0] + "print(len(STARTING_PIECES), BOARD_TEMPLATE.count('{}'))\n", "32 64\n"),
           PROG(GUEST_PICNIC, GUEST_PICNIC_OUT), PROG(COPYING, COPYING_OUT), PROG(CHESS_MOVES, "after move e2 e4: ['a1', 'd7', 'e1', 'e4', 'e8', 'h8']\nafter remove and set: ['a1', 'd5', 'e1', 'e4', 'e8', 'h8']\nafter reset: 6 pieces, e2 holds wP\nafter clear: 0 pieces\n"),
           PROG(CHESSBOARD, 0, stream="returncode", inp="quit\n")]
RAISES += [("'{} {}'.format(['a', 'b'])", "IndexError"), ("__import__('json').dumps({(1, 2): 1})", "TypeError"),
           ("(lambda all_guests: all_guests['Dave']['apples'])(" + _ALL + ")", "KeyError"), ("(lambda all_guests: all_guests['Bob']['cups'])(" + _ALL + ")", "KeyError"),
           ("(lambda b: b['e5'])(" + _BOOK + ")", "KeyError"), ("'move'.split()[2]", "IndexError")]
CHECKS += [PROG("try:\n    '{} {}'.format(['a', 'b'])\nexcept IndexError as e:\n    print(e)\n", "Replacement index 1 out of range for positional args tuple\n"),
           PROG("import json\ntry:\n    json.dumps({(1, 2): 1})\nexcept TypeError as e:\n    print(e)\n", "keys must be str, int, float, bool or None, not tuple\n")]

# ============================================================ Practice work
RAW += [
 ("PracticeWork", "Practice work", 1, None, None, [
  (W, "Practice work is the branch for the exercises with which the chapter ends: eight practice questions on the vocabulary and operations of dictionaries, and three practice programs, a chessboard validator, a fantasy game inventory and the conversion of a list of loot into an inventory. Each concept here gives the task, the answer and a working solution that was executed [SW]."),
  (Y, "The exercises use what the chapter taught on a new problem, which is the test of whether it was learnt. The three programs are also the three ordinary jobs of a dictionary: checking a structure against rules, displaying a structure, and building a structure from a list."),
  (E, "The tasks belong to the chapter and to the course's own practice sheets. The solutions are not the only possible ones, and a learner's own program that prints the same output is as good."),
  (H, "Two parts follow. Review questions gathers the answers to the eight questions in one concept. Practice programs has one concept for each of the three programs."),
 ], None),
 ("ReviewQuestions", "Review questions", 2, "PracticeWork", None, [
  (W, "The review questions are the eight questions at the end of the chapter. They ask for the empty dictionary, a dictionary with the key 'foo' and the value 42, the difference between a dictionary and a list, the result of a missing key, the difference between the in operator on the dictionary and on its keys or values, the shortcut for setting a default, and the module that pretty-prints."),
  (Y, "Each question is answered by a sentence or by a line of code, and each answer points back to one concept of the chapter. Answering them from memory shows which concepts are secure."),
  (H, "One concept follows, with the answer to each question and the line of code that shows it."),
 ], None),
 ("PracticeQuestions", "The eight questions answered", 3, "ReviewQuestions", ("spam.setdefault('color', 'black')", "The eight practice questions are answered by the empty dictionary {}, the pair {'foo': 42}, keys instead of indexes, KeyError for a missing key, in on keys with or without keys(), in on values, setdefault as the shortcut, and the pprint module.", ("(lambda spam: ({}, {'foo': 42}, spam.setdefault('color', 'black'), spam))({})", "({}, {'foo': 42}, 'black', {'color': 'black'})")), [
  (W, "The answers to the eight questions are these. An empty dictionary is {}. A dictionary with the key 'foo' and the value 42 is {'foo': 42}. The main difference between a dictionary and a list is that a dictionary is accessed by keys of many types, with no order of position, where a list is accessed by integer positions. Accessing spam['foo'] when spam is {'bar': 100} raises KeyError: 'foo'. The expressions 'cat' in spam and 'cat' in spam.keys() are the same question. The expression 'cat' in spam.values() asks about the values instead of the keys. The shortcut for the three lines that set 'color' if it is missing is spam.setdefault('color', 'black'). The module is pprint and the function is pprint()."),
  (Y, "The first two answers test notation, the third the idea of the chapter, the fourth the error message, the fifth and sixth the distinction between keys and values that most often goes wrong, the seventh the setdefault method, and the eighth the module for readable output. A learner who can answer all eight has met every branch of the chapter once."),
  (E, "The questions are the review that the chapter itself sets and the base of the course's question bank for this chapter. They are best answered by typing each into the interpreter rather than by recall."),
  (H, "The executed example answers three of them at once: {} and {'foo': 42} are the two literals, and calling setdefault on an empty dictionary stores and returns 'black', leaving the dictionary {'color': 'black'}. The error of the fourth question is shown by the earlier concept on KeyError, and the eighth by the concept on pretty-printing."),
  (K, "Question 5 has a trap of its own: 'cat' in spam and 'cat' in spam.keys() give the same answer, so the difference the question seeks is that there is none. Question 3 is often answered with 'order', which is no longer the whole truth in Python 3.7 and later, since a dictionary remembers insertion order but has no positions."),
 ]),
 ("PracticePrograms", "The three practice programs", 2, "PracticeWork", None, [
  (W, "The practice programs are three tasks that apply the chapter to games. The chess dictionary validator checks a board against the rules of the chapter's model. The fantasy game inventory displays a dictionary of item counts. The list-to-dictionary loot conversion adds a list of found items to an inventory."),
  (Y, "They are small but not trivial: each needs a loop over the pairs, a lookup with a fallback and an accumulating total. The first adds validation, the second display, the third counting, so the same dictionary is checked, shown and built."),
  (H, "Three concepts follow, one for each program, each with a solution that runs."),
 ], None),
 ("ChessValidator", "The chess dictionary validator", 3, "PracticePrograms", ("is_valid_chessboard(board)", "The validator checks that every key is a square from a1 to h8, every value is a colour letter and a piece letter, each side has exactly one king, at most eight pawns and at most sixteen pieces, and returns True or False.", ("(lambda valid, b: (valid(b), valid({**b, 'a1': 'wK'}), valid({**b, 'i9': 'wP'}), valid({**b, **{c + '2': 'wP' for c in 'abcdefgh'}, 'a3': 'wP'})))(lambda b: all(len(s) == 2 and s[0] in 'abcdefgh' and s[1] in '12345678' and len(p) == 2 and p[0] in 'wb' and p[1] in 'PNBRQK' for s, p in b.items()) and all(list(b.values()).count(c + 'K') == 1 and list(b.values()).count(c + 'P') <= 8 and sum(p[0] == c for p in b.values()) <= 16 for c in 'wb'), %s)" % _BOOK, "(True, False, False, False)")), [
  (W, "The validator is a function that takes a chessboard dictionary and returns True when the board could be a position in a real game and False when a bug has produced an improper one. The task asks for exactly one king of each colour, at most 16 pieces for each player, of which at most eight are pawns, and every piece on a valid square [SW]. The task's own text writes the squares as '1a' to '8h' and the piece names as 'wpawn' and similar, while the chapter's model uses 'a1' to 'h8' and 'wP'; the solution follows the chapter's model."),
  (Y, "The model of the chapter accepts anything, so a function must guard it. Validation is the usual companion of a data structure: the more freely the structure can be changed, the more a check is needed before the data is trusted. A bug in a move command, such as a lost piece or a second king, shows up as a False."),
  (E, "Validators are in forms that check an e-mail address, in programs that check a loaded file and in tests that check an invariant. The invariant of the board, the statement that is always true of a legal board, is the list of rules above."),
  (H, "The function loops over board.items(). For each pair it checks the shape of the key, a letter a to h and a digit 1 to 8, and of the value, a letter w or b and one of PNBRQK, returning False at the first failure. It counts the pieces in a dictionary with count[piece] = count.get(piece, 0) + 1 and then checks, for each colour, that the count of the king is exactly 1, that of the pawn is at most 8, and the total at most 16. The book's board gives True; a second white king, a pawn on i9 and nine white pawns each give False."),
  (K, "The checks are not complete: a pawn on the first rank or two bishops on squares of one colour are not detected, and the task says that the list is close enough for the exercise. A board that passes is not a position that can be reached in a game. Check for the shape of every key and value before counting, or the count may be of nonsense."),
 ]),
 ("FantasyInventory", "The fantasy game inventory", 3, "PracticePrograms", ("display_inventory(stuff)", "The function display_inventory loops over items(), prints each count and item and adds the counts into a total, which for the inventory of rope, torch, gold coin, dagger and arrow is 62.", ("(lambda stuff: (sum(stuff.values()), [str(v) + ' ' + k for k, v in stuff.items()][:2]))({'rope': 1, 'torch': 6, 'gold coin': 42, 'dagger': 1, 'arrow': 12})", "(62, ['1 rope', '6 torch'])")), [
  (W, "The inventory of the fantasy game is a dictionary whose keys describe the items and whose values count them: {'rope': 1, 'torch': 6, 'gold coin': 42, 'dagger': 1, 'arrow': 12} means one rope, six torches, 42 gold coins, one dagger and twelve arrows. The task is the function display_inventory(inventory), which prints a heading, a line with the count and the name of each item, and the total number of items [SW]."),
  (Y, "The exercise is the items loop in its plainest use. Inside the loop k is the item and v the count, so the line is str(v) + ' ' + k, and the total grows by v. The book's hint is to use a for loop to go through all the keys. The program that results is short, which is what a good data structure buys."),
  (E, "Inventories, baskets and stock lists are in every game and shop. The same loop prints a receipt, a report of stock and the contents of a bag. The order of the lines follows the order of insertion, so this output lists the items as they were written in the dictionary, where the order printed in the book is the older, arbitrary one."),
  (H, "The function starts item_total at 0, prints 'Inventory:', loops over inventory.items(), prints each line and adds the count, and finally prints 'Total number of items: 62'. For the five items the counts 1, 6, 42, 1 and 12 add up to 62. Because items() follows insertion order, the lines appear as rope, torch, gold coin, dagger, arrow."),
  (K, "The task prints and does not return, so it cannot be tested without capturing output; a version that returns the text is easier to check. A count of zero still prints a line unless the loop skips it. The names are printed as stored, so 'Gold coin' and 'gold coin' would be two lines."),
 ]),
 ("LootConversion", "List-to-dictionary loot conversion", 3, "PracticePrograms", ("add_to_inventory(inv, dragon_loot)", "The function add_to_inventory takes an inventory dictionary and a list of found items, possibly with repeats, adds one for each occurrence with setdefault and returns the updated dictionary; the Counter class does the same count in one call.", ("(lambda add: add({'gold coin': 42, 'rope': 1}, ['gold coin', 'dagger', 'gold coin', 'gold coin', 'ruby']))(lambda inv, items: ([inv.__setitem__(i, inv.get(i, 0) + 1) for i in items], inv)[1])", "{'gold coin': 45, 'rope': 1, 'dagger': 1, 'ruby': 1}")), [
  (W, "The loot conversion is the second function of the fantasy game: add_to_inventory(inventory, added_items) takes the player's inventory and a list of items, such as ['gold coin', 'dagger', 'gold coin', 'gold coin', 'ruby'], and returns the inventory updated with the list [SW]. The list may contain the same item several times, and each occurrence counts."),
  (Y, "The task is the character count of this chapter in disguise: instead of characters in a string, there are items in a list. The same two lines work: inventory.setdefault(item, 0) makes sure the key exists, and inventory[item] = inventory[item] + 1 adds one. A learner who sees that the two problems are the same has learnt the pattern, not the program."),
  (E, "Merging a list of events into a table of totals is the daily work of programs that read logs, orders and sensor readings. In the standard library the whole function can be replaced by Counter(inventory) + Counter(added_items), which gives the same counts, and a defaultdict(int) would remove the setdefault line."),
  (H, "With the inventory {'gold coin': 42, 'rope': 1} and the dragon's loot, the three gold coins add 3 to the existing 42 and give 45, the dagger and the ruby are new keys with the count 1, and the rope is unchanged. The result is {'gold coin': 45, 'rope': 1, 'dagger': 1, 'ruby': 1} with 48 items in total, and display_inventory prints it in that order, the new keys at the end. The book's sample output lists the ruby before the dagger, which is the arbitrary order of the older reading."),
  (K, "The function changes the dictionary that the caller passed in, and also returns it; a program that wants the old inventory kept must pass a copy. The loop adds one per occurrence, so a list that holds counts as well, such as ('gold coin', 3), needs a different program. Spelling counts: the same item under two names is two entries."),
 ]),
]
CHECKS += [("(lambda spam: ({}, {'foo': 42}, spam.setdefault('color', 'black'), spam))({})", "({}, {'foo': 42}, 'black', {'color': 'black'})"),
           ("(lambda spam: (spam.get('foo'), len(spam)))({'bar': 100})", "(None, 1)"),
           ("(lambda ns: (exec(%r, ns), (lambda b: (ns['is_valid_chessboard'](b), ns['is_valid_chessboard']({**b, 'a1': 'wK'}), ns['is_valid_chessboard']({**b, 'i9': 'wP'}), ns['is_valid_chessboard']({**b, **{c + '2': 'wP' for c in 'abcdefgh'}, 'a3': 'wP'})))(%s))[1])({})" % (_VAL_DEF, _BOOK), "(True, False, False, False)"),
           ("(lambda ns: (exec(%r, ns), sum({'rope': 1, 'torch': 6, 'gold coin': 42, 'dagger': 1, 'arrow': 12}.values()))[1])({})" % _INV_DEF, "62"),
           ("(lambda ns: (exec(%r, ns), (lambda inv: sum(inv.values()))(ns['add_to_inventory']({'gold coin': 42, 'rope': 1}, ['gold coin', 'dagger', 'gold coin', 'gold coin', 'ruby'])))[1])({})" % _INV_DEF, "48"),
           ("(lambda C: dict(C({'gold coin': 42, 'rope': 1}) + C(['gold coin', 'dagger', 'gold coin', 'gold coin', 'ruby'])))(__import__('collections').Counter)", "{'gold coin': 45, 'rope': 1, 'dagger': 1, 'ruby': 1}"),
           PROG(INVENTORY, INVENTORY_OUT), PROG(VALIDATOR, VALIDATOR_OUT), PROG(LOOKUP, LOOKUP_OUT)]
