"""Chapter 14 content for the RDODI build: sources, findings, taxonomy and section bodies.
The book's chapter (3rd edition, chapter 14, Excel Spreadsheets) was read on automatetheboringstuff.com on 2026-10-01 from its
published HTML page, which the WebFetch tool declined to reproduce and which was therefore fetched with curl through the session
proxy (103,056 bytes) and converted to text; its 18 practice questions and 2 practice programs were read there. The chapter's figures
(14-1 to 14-11) are images and were NOT viewed, and the book's downloadable files (example3.xlsx, censuspopdata.xlsx,
produceSales3.xlsx) were NOT opened: small stand-in workbooks were written by the scripts instead, with the values of Table 14-1 typed
in from the page. The openpyxl documentation pages (headed 3.1.3, generated 2024-05-29), the PyPI JSON record of openpyxl and the
Python documentation pages (docs.python.org, which carried the release number 3.14.8 when read) were read online on 2026-10-01.
Every behaviour of the standard library was executed under Python 3.14.4. Every behaviour of openpyxl 3.1.5 (with et_xmlfile 2.0.0;
lxml, defusedxml and pillow not installed) was executed under Python 3.14.4 by 08-tooling/sen0414_ch14_library_run_v1_0_0.py after
installing the package into a scratch folder; its printed lines are kept in 08-tooling/sen0414_ch14_library_run_output_v1_0_0.txt and
are what the findings below quote. openpyxl is not installed in the course interpreter, so the checks of this module run only the
standard-library examples. Not executed at all: Microsoft Excel, LibreOffice Calc or Office 365 (so no formula was ever calculated by a
spreadsheet application and nothing was looked at on screen), the charts as drawn, saving over a file that is open in Excel, pandas and
NumPy, the lxml and defusedxml options, the command-line form of the two practice programs (chapter 12 is not built), and the book's
downloadable spreadsheets. A claim not in this file was not made."""
__version__ = "1.0.0"
CH = 14
DATE = "2026-10-01"
PYVER = "3.14.4"
TITLE = "Excel spreadsheets for an advanced course: chapter 14 of the 3rd edition, openpyxl and today's Python"
QUESTION = "What does chapter 14 of the 3rd edition teach about reading, changing and writing Excel workbooks with openpyxl, which of its printed outputs and programs still hold with openpyxl 3.1.5 under Python 3.14.4, and what must an advanced course add so that it matches current practice?"
CQS = ("Which calls read a workbook, which change it in memory and which write it to a file, and what decides whether a formula shows a value?",
       "Which printed outputs and claims of the chapter differ in openpyxl 3.1.5 under Python 3.14.4, and on what source?")
PUBS = [
 ("P01","Automate the Boring Stuff with Python, 3rd edition - Chapter 14, Excel Spreadsheets (Al Sweigart, No Starch Press, 2025)","https://automatetheboringstuff.com/3e/chapter14.html",True),
 ("P02","openpyxl - A Python library to read/write Excel 2010 xlsx/xlsm files - documentation home page, including the security note (Gazoni and Clark, 2024; the page was headed 3.1.3)","https://openpyxl.readthedocs.io/en/stable/",False),
 ("P03","openpyxl Tutorial - workbooks, worksheets, cells, saving and loading (Gazoni and Clark, 2024; headed 3.1.3)","https://openpyxl.readthedocs.io/en/stable/tutorial.html",False),
 ("P04","openpyxl Optimised Modes - read-only and write-only workbooks (Gazoni and Clark, 2024; headed 3.1.3)","https://openpyxl.readthedocs.io/en/stable/optimized.html",False),
 ("P05","openpyxl Parsing Formulas - the Tokenizer and translating formulas (Gazoni and Clark, 2024; headed 3.1.3)","https://openpyxl.readthedocs.io/en/stable/formula.html",False),
 ("P06","openpyxl Dates and Times - serial numbers, the 1900 and 1904 date systems, timezones (Gazoni and Clark, 2024; headed 3.1.3)","https://openpyxl.readthedocs.io/en/stable/datetime.html",False),
 ("P07","openpyxl Charts - creating a chart, chart types and anchors (Gazoni and Clark, 2024; headed 3.1.3)","https://openpyxl.readthedocs.io/en/stable/charts/introduction.html",False),
 ("P08","openpyxl.chart.reference module - the Reference class and its arguments (Gazoni and Clark, 2024; headed 3.1.3)","https://openpyxl.readthedocs.io/en/stable/api/openpyxl.chart.reference.html",False),
 ("P09","openpyxl.worksheet.worksheet module - Worksheet methods and properties (Gazoni and Clark, 2024; headed 3.1.3)","https://openpyxl.readthedocs.io/en/stable/api/openpyxl.worksheet.worksheet.html",False),
 ("P10","openpyxl Additional Worksheet Properties - views and folding (Gazoni and Clark, 2024; headed 3.1.3)","https://openpyxl.readthedocs.io/en/stable/worksheet_properties.html",False),
 ("P11","openpyxl Working with Pandas and NumPy (Gazoni and Clark, 2024; headed 3.1.3)","https://openpyxl.readthedocs.io/en/stable/pandas.html",False),
 ("P12","The Python Package Index record of openpyxl in JSON - release list, upload times, supported Python versions (Python Package Index, 2026)","https://pypi.org/pypi/openpyxl/json",False),
 ("P13","The Python Standard Library, zipfile - work with ZIP archives (Python 3.14.4 documentation source)","https://docs.python.org/3/library/zipfile.html",False),
 ("P14","The Python Standard Library, xml.etree.ElementTree - the ElementTree XML API (Python 3.14.4 documentation source)","https://docs.python.org/3/library/xml.etree.elementtree.html",False),
 ("P15","The Python Standard Library, pprint - data pretty printer (Python 3.14.4 documentation source)","https://docs.python.org/3/library/pprint.html",False),
 ("P16","The Python Standard Library, datetime - basic date and time types (Python 3.14.4 documentation source)","https://docs.python.org/3/library/datetime.html",False),
 ("P17","The Python Standard Library, Built-in Types - mapping types, dict.setdefault (Python 3.14.4 documentation source)","https://docs.python.org/3/library/stdtypes.html",False),
 ("P18","The Python Standard Library, io - BytesIO and StringIO (Python 3.14.4 documentation source)","https://docs.python.org/3/library/io.html",False),
 ("P19","Installing Python modules - pip and virtual environments (Python 3.14.4 documentation source)","https://docs.python.org/3/installing/index.html",False),
]
CONCEPTS = [("Section",x) for x in ("Reading Excel Files","Writing Excel Documents","Setting the Font Style of Cells","Formulas","Adjusting Rows and Columns","Charts","Summary","Practice Questions","Practice Programs")] + \
 [("Concept",x) for x in ("Workbook and sheet","Cell access","Saving changes","Presentation")] + \
 [("Method",x) for x in ("openpyxl.load_workbook","openpyxl.Workbook","save","cell","create_sheet","merge_cells","unmerge_cells")] + \
 [("Function",x) for x in ("get_column_letter","Font")]
FINDINGS = [
 ("F1","Background","Chapter 14 of the 3rd edition, Excel Spreadsheets, teaches the third-party module openpyxl: opening a workbook with load_workbook, reading sheets by name and the active sheet, reading cells by name and with cell(row, column), max_row and max_column, column letters and numbers, slices and the rows and columns attributes, then Project 9 (county totals from a census workbook) and Project 10 (correcting prices in a produce workbook); creating, renaming, adding and deleting sheets, writing cell values and saving; Font objects; formulas as strings and data_only; row height, column width, merging cells and freeze panes; and bar charts from a Reference and a Series, closing with 18 practice questions and 2 practice programs, a multiplication table and a blank row inserter.",["P01"]),
 ("F2","Comparative analysis","The chapter's printed outputs reproduce with openpyxl 3.1.5 under Python 3.14.4 when the book's spreadsheets are replaced by stand-ins holding Table 14-1: the type of the workbook, the sheet names, the active sheet, the repr of a cell, the datetime of A1, the row, column and coordinate of B1, the loop over every other row, max_row 7 and max_column 3, the column letters 'A', 'B', 'AA' and 'AHP' and the numbers 1 and 27, the tuple of three tuples of cells for A1 to C3, the seven values of column B, the sheet names after create_sheet and del, the merged and unmerged ranges, and the freeze_panes settings of Table 14-3; both projects ran as printed on stand-in data, with the dictionary written by pprint and imported back.",["P01","P03"]),
 ("F3","Comparative analysis","The chapter's statement that an unspecified font name or size falls back to the openpyxl defaults of Calibri and 11 does not hold for a Font object: a new cell's font is Calibri 11, but Font(size=24, italic=True) has no name, Font(name='Times New Roman', bold=True) has no size, and the styles part of the saved file lists for the first only italic and a size of 24 and no name; what Excel shows for the missing attributes was not tested because Excel was not available. A Font cannot be changed after creation - setting bold on one raises AttributeError - so a different style means a new Font assigned to the cell.",["P01","P03"]),
 ("F4","Comparative analysis","The chapter's account of Reference is wrong in two places: it says the function takes five arguments and lists three, and it says the first integer of a cell position is the row, whereas the documented signature is Reference(worksheet, min_col, min_row, max_col, max_row) and Reference(sheet, 2, 3, 4, 5) printed as the range B3 to D5 of the sheet, columns first. The chapter's own example, Reference(sheet, 1, 1, 1, 10), is column 1 and rows 1 to 10, so it runs as printed, and the chart part written for it names the range A1 to A10.",["P01","P07","P08"]),
 ("F5","Comparative analysis","Three practice questions ask for more than the chapter's text shows or for something slightly different: question 10 asks for the string name of row 14, but rows are numbered and the function the chapter teaches that returns a letter name is get_column_letter, which gives 'N' for 14; question 16 asks how to hide column C, which the chapter's introduction mentions and no example shows, and column_dimensions['C'].hidden = True was saved and read back as True; question 18 asks for five functions and methods of a bar chart, which are Reference, Series, BarChart, append and add_chart. The chapter's price list in Project 10 also says lemons while its dictionary key is 'Lemon', so a key of 'Lemons' would match nothing.",["P01","P03","P09"]),
 ("F6","Comparative analysis","The chapter's explanation of formulas holds and needs two additions: openpyxl stores a formula as text without a value, so a file it has written and no spreadsheet application has opened gives None for that cell under data_only=True, as the run showed for the chapter's =SUM(A1:A2) and for the stand-in produce workbook after its prices were corrected; and any text that starts with an equal sign is taken for a formula, including the text =not a formula(, unless the data type of the cell is set to string. The chapter's 500 appears only after Excel has saved the file and was not reproduced.",["P01","P03","P05"]),
 ("F7","Contemporary developments","Reading a cell creates it: on a new sheet, reading A1 and C5 left two cells and max_row 5 and max_column 3, and reading only the value of A100 made max_row 100, which the tutorial warns about; the chapter's loops of range(2, sheet.max_row + 1) depend on max_row, so code that touches a far cell first makes them run over empty rows. For large files the documentation adds a read-only mode (lazy, cells of another type, no iter_cols, must be closed) and a write-only mode (no sheets at the start, rows added only with append, saved once), which the run confirmed by the errors they raise.",["P03","P04","P09"]),
 ("F8","Contemporary developments","Current practice adds to the chapter: iter_rows and values with values_only=True for plain values, insert_rows and delete_rows, which move cells but leave a formula's text as it was (=SUM(B1:B4) moved from C5 to C7 unchanged, while Translator from openpyxl.formula.translate gave =SUM(B3:B6) for that move), copy_worksheet, dates stored as numbers in the 1900 or 1904 date system with the 1900 leap-year error and no timezones (a timezone-aware datetime is accepted on assignment and fails when the file is saved), and the refusal of old .xls files and of files that are not zip archives.",["P03","P05","P06","P09"]),
 ("F9","Contemporary developments","The library's own status matters to a course: the PyPI record lists 3.1.5, uploaded 2024-06-28, as the newest release, requiring Python 3.8 or later and naming Python versions up to 3.11 in its classifiers, and also lists a beta 3.2.0b1 uploaded in 2022; the documentation the chapter points to was headed 3.1.3. The operations executed ran without a warning under Python 3.14.4 with warnings turned into errors, apart from the sheet-title warning the script provoked. The documentation's home page also says openpyxl does not guard by default against quadratic blowup or billion laughs XML attacks and advises defusedxml, which matters because an .xlsx file is a zip archive of XML.",["P02","P03","P12"]),
 ("F10","Comparative analysis","The chapter writes the county totals with pprint.pformat as the text of a Python module and imports it: pformat sorts dictionary keys by default, so the printed order is alphabetical, the generated file parses and imports back to the same dictionary (the Anchorage entry printed as {'pop': 9020, 'tracts': 2} for the stand-in rows, one population given as text and converted with int), and reading the data back by import executes the statements of the file, so such a file is to be trusted like a program.",["P01","P15","P17"]),
 ("F11","Conclusion","For an advanced course, chapter 14 is best taught through what an .xlsx file is - a zip archive of XML parts in which a cell is a number, a string or a formula with no cached value - so that the chapter's calls read as operations on that structure: load_workbook reads it, the Workbook and Worksheet objects change it in memory, save writes it, and only a spreadsheet application fills in formula results. The chapter's outputs hold with openpyxl 3.1.5; the font default, the Reference arguments, reading creating cells, data_only giving None, formulas that do not move, dates, optimised modes and XML safety are what the course adds, and every statement about Excel itself remains unverified here.",["P01","P03","P12","P13"]),
]
# (top, mid, leaf, exemplar, definition, io-or-None)
TAX = [
 ("WorkbookModel","WorkbookStructure","WorkbookFile","wb = openpyxl.load_workbook('example3.xlsx')","A workbook is an Excel document saved in a file with the .xlsx extension, and load_workbook returns a Workbook object for it; the file itself is a zip archive of XML parts.",("(lambda b: (__import__('zipfile').ZipFile(b, 'w').close(), b.getvalue()[:2])[1])(__import__('io').BytesIO())","b'PK'")),
 ("WorkbookModel","WorkbookStructure","SheetNames","sheet = wb['Sheet3']","The sheetnames attribute lists the names of the workbook's sheets, and a sheet is fetched by its name with square brackets like a dictionary key, which gives a Worksheet whose title attribute is that name.",None),
 ("WorkbookModel","WorkbookStructure","ActiveSheet","another_sheet = wb.active","The active attribute is the sheet that is on top when the workbook is opened, which is the first sheet unless the workbook says otherwise.",None),
 ("WorkbookModel","CellReferences","CellByName","c = sheet['A1']","A sheet is indexed by a cell name such as 'A1' to get a Cell object, whose value attribute holds the number, text or date stored there.",None),
 ("WorkbookModel","CellReferences","CellByNumbers","c = sheet.cell(row=1, column=2)","The cell method takes the row and the column as integers counted from 1, so a loop can step through rows and pick a column without converting letters; passing a value also writes it.",("list(range(1, 8, 2))","[1, 3, 5, 7]")),
 ("WorkbookModel","CellReferences","CellAttributes","where = c.coordinate","A Cell knows its value, its row and column as integers and its coordinate as text, which together can be printed back as a sentence such as Row 1, Column 2 is Apples.",("(lambda row, col, v: f'Row {row}, Column {col} is {v}')(1, 2, 'Apples')","'Row 1, Column 2 is Apples'")),
 ("WorkbookModel","CellReferences","SheetSize","last_row = sheet.max_row","The max_row and max_column attributes are integers giving the largest row and column that hold data, so the letter of the last column needs a conversion.",("(lambda rows: (len(rows), max(len(r) for r in rows)))([(1, 'Apples', 73)] * 7)","(7, 3)")),
 ("WorkbookModel","CellReferences","CellCreationOnRead","sheet['A100'].value","A cell that does not exist yet is created when it is first accessed, even only to read it, so touching a far cell makes max_row larger and walking over a region creates every cell in it.",None),
 ("WorkbookModel","Addresses","ColumnLetters","get_column_letter(27), column_index_from_string('AA')","Two functions of openpyxl.utils convert between column numbers and letters, 27 and 'AA' for instance, and need no workbook; the letters are a base-26 numbering without a zero.",("(lambda f, g: (f(f, 1), f(f, 27), f(f, 900), g('AA'), g('M')))(lambda f, n: '' if n == 0 else f(f, (n - 1) // 26) + chr(65 + (n - 1) % 26), lambda s: __import__('functools').reduce(lambda a, c: a * 26 + ord(c) - 64, s, 0))","('A', 'AA', 'AHP', 27, 13)")),
 ("WorkbookModel","Addresses","CellCoordinate","'AB12'","A cell's coordinate is its column letters followed by its row number, which can be split with a pattern into the two parts.",("__import__('re').fullmatch(r'([A-Z]+)(\\d+)', 'AB12').groups()","('AB', '12')")),
 ("WorkbookModel","RangesAndValues","RangeSlice","area = sheet['A1':'C3']","Slicing a sheet with two coordinates gives a tuple of rows, each a tuple of the Cell objects from the left to the right of the area, so two nested loops visit every cell.",("tuple(tuple(c + str(r) for c in 'ABC') for r in range(1, 4))","(('A1', 'B1', 'C1'), ('A2', 'B2', 'C2'), ('A3', 'B3', 'C3'))")),
 ("WorkbookModel","RangesAndValues","RowsAndColumns","column_b = list(sheet.columns)[1]","The rows and columns attributes give the cells row by row and column by column, and once turned into lists they can be indexed; columns are rows turned on their side.",("list(zip(*[(1, 'a'), (2, 'b'), (3, 'c')]))","[(1, 2, 3), ('a', 'b', 'c')]")),
 ("WorkbookModel","RangesAndValues","ValuesOnly","for row in sheet.iter_rows(values_only=True): print(row)","The iter_rows method and the values property give plain values instead of Cell objects, which is the shortest way to read a region into Python data; the chapter as read does not present them.",None),
 ("WorkbookModel","RangesAndValues","DateValues","sheet['A1'].value","A date or time cell comes back as a Python datetime, because the file stores it as a number of days with a date format.",("__import__('datetime').datetime(1899, 12, 30) + __import__('datetime').timedelta(days=45000)","datetime.datetime(2023, 3, 15, 0, 0)")),
 ("ReadingProject","CensusNumbers","CountyStructure","county_data[state][county]['pop']","Project 9 keeps its totals in a dictionary of dictionaries keyed by state abbreviation and county name, each county holding a tract count and a population, and reads the population cell as text that int() converts.",("(lambda d: sum(c['pop'] for c in d['AK'].values()))({'AK': {'Anchorage': {'pop': 291826, 'tracts': 55}, 'Juneau': {'pop': 31275, 'tracts': 7}}})","323101")),
 ("ReadingProject","CensusNumbers","DefaultEntries","county_data.setdefault(state, {})","The setdefault method creates a missing key with a starting value and does nothing when the key exists, so it can be called on every row before the counters are incremented.",("(lambda d: (d.setdefault('AK', {}), d.setdefault('AK', {'x': 1}), d))({})","({}, {}, {'AK': {}})")),
 ("ReadingProject","CensusNumbers","GeneratedModule","'allData = ' + pprint.pformat(county_data)","The project writes its dictionary as the text of a Python module with pformat, which sorts the keys, so that import census2010 gives the data back; importing runs the file as code.",("(lambda s: __import__('ast').literal_eval(s.split(' = ', 1)[1]))('allData = ' + __import__('pprint').pformat({'b': {'pop': 1, 'tracts': 2}, 'a': {'pop': 3, 'tracts': 1}}))","{'a': {'pop': 3, 'tracts': 1}, 'b': {'pop': 1, 'tracts': 2}}")),
 ("WritingWorkbooks","AddingAndRemoving","NewWorkbook","wb = openpyxl.Workbook()","The Workbook function makes a blank workbook that starts with one sheet named Sheet, whose title attribute can be replaced.",None),
 ("WritingWorkbooks","AddingAndRemoving","SheetCreation","new_sheet = wb.create_sheet(index=0, title='First Sheet')","The create_sheet method adds a sheet at the end under the next free name, or at a given index and with a given title.",None),
 ("WritingWorkbooks","AddingAndRemoving","SheetRemoval","del wb['Sheet1']","A sheet is removed from the workbook with the del operator and its name, as a key is removed from a dictionary, or with the remove method and the sheet object.",None),
 ("WritingWorkbooks","SavingAndOutput","SaveMethod","wb.save('example3_copy.xlsx')","Nothing reaches the disk until the save method is called, and it overwrites an existing file without asking, so the chapter saves edited workbooks under a new name to keep the original.",None),
 ("WritingWorkbooks","SavingAndOutput","CellWriting","sheet['A1'] = 'Hello, world!'","Assigning to a cell name or to a cell's value writes it like a dictionary entry, and the Python type of the value decides how the cell is stored.",None),
 ("WritingWorkbooks","PriceUpdate","UpdateLoop","if produce_name in PRICE_UPDATES:","Project 10 holds the corrected prices in a dictionary and loops over the rows from 2 on, changing the price cell of every row whose produce name is a key, then saves to a new file.",("[n in {'Garlic': 3.07, 'Celery': 1.19, 'Lemon': 1.27} for n in ('Lemon', 'Lemons')]","[True, False]")),
 ("WritingWorkbooks","PriceUpdate","FormulaSurvival","=ROUND(B2*C2, 2)","The total column of the produce workbook holds formulas, which stay formulas when only the price cells are changed, because openpyxl writes them back as text and does not recalculate.",None),
 ("Presentation","FontStyle","FontObject","Font(name='Times New Roman', size=24, bold=True, italic=True)","A Font object is made from the openpyxl.styles module with the keyword arguments name, size, bold and italic, and holds only the attributes it was given.",None),
 ("Presentation","FontStyle","FontAssignment","sheet['A1'].font = italic_24_font","A cell is styled by assigning a Font object to its font attribute, and the Font cannot be changed afterwards, so a new look needs a new Font.",None),
 ("Presentation","FontStyle","FontDefaults","Font(size=24, italic=True)","A new cell's font is Calibri 11, but a Font object made with some keyword arguments has no value for the others, so the chapter's claim that it falls back to Calibri and 11 is not what the saved file holds.",None),
 ("Presentation","SizeMeasures","RowAndColumnSize","sheet.row_dimensions[1].height = 70","The row_dimensions and column_dimensions attributes are dictionary-like, indexed by row number and by column letter, and set the height of a row and the width of a column.",None),
 ("Presentation","SizeMeasures","HiddenColumn","sheet.column_dimensions['C'].hidden = True","A column is hidden by setting hidden on its dimension object; the chapter promises hiding and its practice question 16 asks for it, but no example shows it.",None),
 ("Presentation","MergedAndFrozenPositions","MergeCells","sheet.merge_cells('A1:D3')","The merge_cells method joins the rectangle named by its top-left and bottom-right cells into one cell whose value is set in the top-left cell, and unmerge_cells splits it again.",("(lambda a: (ord(a[3]) - ord(a[0]) + 1) * (int(a[4]) - int(a[1]) + 1))('A1:D3')","12")),
 ("Presentation","MergedAndFrozenPositions","FreezePanes","sheet.freeze_panes = 'A2'","A freeze pane keeps rows and columns visible while the sheet scrolls: setting freeze_panes to a cell freezes every row above it and every column to its left, and setting it to A1 or None removes the freeze.",("[(lambda s: (int(s[1:]) - 1, ord(s[0]) - 65))(x) for x in ('A2', 'B1', 'C1', 'C2', 'A1')]","[(1, 0), (0, 1), (0, 2), (1, 2), (0, 0)]")),
 ("FormulasAndCharts","FormulaCells","FormulaString","sheet['A3'] = '=SUM(A1:A2)'","A formula is written into a cell as text that starts with an equal sign, in the same way as any other value.",None),
 ("FormulasAndCharts","FormulaCells","NoCalculation","a formula written by openpyxl","The module does not calculate formulas, and the result that a spreadsheet application would show has to be worked out separately, here by Python.",("sum([200, 300])","500")),
 ("FormulasAndCharts","FormulaCells","CachedResult","load_workbook('writeFormula3.xlsx', data_only=True)","Loading with data_only=True gives the value that a spreadsheet application stored the last time it saved the file, and gives None when no application has calculated the formula.",None),
 ("FormulasAndCharts","FormulaCells","FormulaTranslation","Translator('=SUM(B1:B4)', origin='C5').translate_formula('C7')","The Translator class rewrites a formula for another position, moving its relative references, which the row-moving methods of a sheet do not do; the chapter as read does not present it.",None),
 ("FormulasAndCharts","ChartSequence","ChartRecipe","sheet.add_chart(chart_obj, 'C5')","A chart is built from a Reference to a block of cells, a Series made from it, a chart object such as BarChart to which the series is appended, and a call of add_chart with the cell where its top-left corner goes.",None),
 ("FormulasAndCharts","ChartSequence","ReferenceObject","openpyxl.chart.Reference(sheet, 1, 1, 1, 10)","A Reference names a block of cells by the sheet and then the first column, first row, last column and last row, in that order.",("(lambda L, a, b, c, d: '$%s$%d:$%s$%d' % (L(a), b, L(c), d))(lambda n: chr(64 + n), 2, 3, 4, 5)","'$B$3:$D$5'")),
 ("BeyondTheChapter","LargeDataSources","ReadOnlyMode","load_workbook('big.xlsx', read_only=True)","Read-only mode loads rows lazily with little memory, returns cells of a lighter type, offers no iter_cols, cannot be saved and must be closed.",None),
 ("BeyondTheChapter","LargeDataSources","WriteOnlyMode","Workbook(write_only=True)","Write-only mode starts with no sheets, accepts rows only through append, keeps memory use low and can be saved only once.",None),
 ("BeyondTheChapter","FormatDetails","OldFormatRefusal","load_workbook('old.xls')","The module reads the xlsx family of formats only: an old .xls file, a file that is not a zip archive and a missing file each stop with an error that says which.",None),
 ("BeyondTheChapter","FormatDetails","XmlSafety","defusedxml","An xlsx file is XML inside a zip, and the documentation says openpyxl does not by default guard against quadratic blowup or billion laughs attacks and advises installing defusedxml before reading files from others.",None),
 ("BeyondTheChapter","FormatDetails","LibraryStatus","openpyxl 3.1.5","The newest openpyxl on the Python Package Index is 3.1.5 of 2024-06-28, which ran under Python 3.14.4 although its classifiers stop at Python 3.11.",None),
 ("BeyondTheChapter","FormatDetails","DateSerials","epoch = wb.epoch","Dates are stored as day numbers counted from an epoch, 1899-12-30 for the usual 1900 date system, and the system wrongly counts 1900 as a leap year, so the plain epoch sum is right only from 1 March 1900 on and no timezone can be stored.",("(__import__('datetime').datetime(1900, 3, 1) - __import__('datetime').datetime(1899, 12, 30)).days","61")),
 ("BeyondTheChapter","PracticePrograms","MultiplicationTable","multiplicationTable.py 6","Practice program 1 builds an N by N multiplication table with the labels in row 1 and column A set in bold.",("[[None] + list(range(1, 4))] + [[r] + [r * c for c in range(1, 4)] for r in range(1, 4)]","[[None, 1, 2, 3], [1, 1, 2, 3], [2, 2, 4, 6], [3, 3, 6, 9]]")),
 ("BeyondTheChapter","PracticePrograms","BlankRowInserter","blankRowInserter.py 3 2 myProduce.xlsx","Practice program 2 inserts M blank rows at row N by copying the first rows unchanged and writing every later row M rows lower.",("[r if r < 3 else r + 2 for r in range(1, 6)]","[1, 2, 5, 6, 7]")),
]
ERRORS = []
CLAIMS = [
 ("__import__('pprint').pformat({'b': 1, 'a': 2})", "\"{'a': 2, 'b': 1}\""),
 ("__import__('pprint').pformat({'b': 1, 'a': 2}, sort_dicts=False)", "\"{'b': 1, 'a': 2}\""),
 ("(lambda e: (e + __import__('datetime').timedelta(days=61)).date().isoformat())(__import__('datetime').datetime(1899, 12, 30))", "'1900-03-01'"),
 ("[__import__('zipfile').is_zipfile(__import__('io').BytesIO(b)) for b in (b'a,b', b'PK\\x05\\x06' + bytes(18))]", "[False, True]"),
 ("(lambda f: [f(f, n) for n in (14, 26, 52, 702, 703, 16384, 18278)])(lambda f, n: '' if n == 0 else f(f, (n - 1) // 26) + chr(65 + (n - 1) % 26))", "['N', 'Z', 'AZ', 'ZZ', 'AAA', 'XFD', 'ZZZ']"),
 ("{'Garlic': 3.07, 'Celery': 1.19, 'Lemon': 1.27}.get('Lemons', 'no match')", "'no match'"),
 ("[r * c for r in (6,) for c in (6,)]", "[36]"),
]
S = "(Sweigart, 2025)"; OX = "(Gazoni and Clark, 2024)"; PSF = "(Python Software Foundation, 2026)"; PPI = "(Python Package Index, 2026)"
RUN = "in the run of openpyxl 3.1.5 under Python 3.14.4"
BODY = {
 "WorkbookModel": "The chapter reads a workbook file into a Workbook object that holds sheets, and a sheet that holds cells addressed by column letter and row number " + S + " " + OX + ".",
 "WorkbookStructure": "The chapter starts from the file, the workbook object, its sheets and the active sheet " + S + ".",
 "WorkbookFile": "An Excel document is a workbook, saved with the .xlsx extension, and openpyxl.load_workbook('example3.xlsx') returns a value of type openpyxl.workbook.workbook.Workbook, as the chapter prints " + S + "; the book's example3.xlsx was not opened, and a stand-in with the seven rows of Table 14-1 was written and loaded instead. The file is a zip archive of XML parts, which the tutorial states and the run showed by listing the members of a saved file: docProps/app.xml, docProps/core.xml, xl/theme/theme1.xml, one xl/worksheets part per sheet, xl/styles.xml, _rels/.rels, xl/workbook.xml, xl/_rels/workbook.xml.rels and [Content_Types].xml " + OX + "; a zip archive written in memory starts with the two bytes PK " + PSF + ". openpyxl operates on files and not on the Excel application, which the chapter says and which was not tested here " + S + ".",
 "SheetNames": "For the stand-in, wb.sheetnames is ['Sheet1', 'Sheet2', 'Sheet3'], wb['Sheet3'] is a Worksheet of type openpyxl.worksheet.worksheet.Worksheet whose title is 'Sheet3', and a name that is not in the workbook raises KeyError with the text Worksheet Nope does not exist. " + S + " " + OX + " (" + RUN + ").",
 "ActiveSheet": "wb.active is the Worksheet of Sheet1 for the stand-in; the chapter calls it the sheet on top when the workbook is opened, and the tutorial adds that the property is set to 0 by default, so the first worksheet is returned unless it is changed, and that a new workbook always has at least one worksheet " + S + " " + OX + ".",
 "CellReferences": "A cell is reached by its name or by its row and column numbers, and the Cell tells where it is " + S + ".",
 "CellByName": "sheet['A1'] is a Cell object, and its value is datetime.datetime(2035, 4, 5, 13, 34, 2) for the stand-in, while sheet['B1'].value is 'Apples' and sheet['C1'].value is 73 " + S + "; the tutorial says that indexing returns the cell or creates one if it does not exist yet " + OX + ".",
 "CellByNumbers": "sheet.cell(row=1, column=2) is the same cell as B1 and takes integers counted from 1; the chapter's loop over range(1, 8, 2) printed 1 Apples, 3 Pears, 5 Apples and 7 Strawberries, and a row or column of 0 raises ValueError with the text Row or column values must be at least 1 " + S + " (" + RUN + "). The method also takes a value, so cell(row=1, column=1, value=5) writes 5 and returns the cell " + OX + ".",
 "CellAttributes": "For B1 of the stand-in the value is 'Apples', the row 1, the column 2 and the coordinate 'B1', and the chapter's f-strings print Row 1, Column 2 is Apples and Cell B1 is Apples; the letters that openpyxl uses for the kinds of cell content were d for A1, s for B1 and n for C1 " + S + " (" + RUN + ").",
 "SheetSize": "sheet.max_row is 7 and sheet.max_column is 3 for the stand-in, both of type int, as the chapter says; the documentation defines them as the largest row and column index that contain data, counted from 1, and a new empty sheet reported 1 and 1 " + S + " " + OX + " (" + RUN + ").",
 "CellCreationOnRead": "On a new sheet, reading A1 and C5 left two cells in memory and made max_row 5 and max_column 3, and reading only the value of A100 made max_row 100 and returned None; the tutorial warns that scrolling through cells instead of accessing them directly creates them all in memory, and the chapter as read does not mention it, so a loop over range(2, sheet.max_row + 1) also visits empty rows once some code has touched a far cell " + OX + " (" + RUN + ").",
 "Addresses": "Columns are named with letters and counted with numbers, and two functions convert between them " + S + ".",
 "ColumnLetters": "get_column_letter gives 'A', 'B', 'AA' and 'AHP' for 1, 2, 27 and 900 and column_index_from_string gives 1 for 'A' and 27 for 'AA', as the chapter prints, and 'M' is 13 " + S + "; practice question 10 asks for the string name of row 14, but rows are numbered and the function that returns a letter name is get_column_letter, which gives 'N' for 14. The functions accept names from A to ZZZ: 'AAAA' raises ValueError, 0 raises ValueError with the text Invalid column index 0, and 16384 is 'XFD' and 18278 is 'ZZZ' (" + RUN + "). A plain Python version of the two conversions round-trips every number from 1 to 18278 " + PSF + ".",
 "CellCoordinate": "A coordinate such as 'AB12' is the column letters then the row number and splits into 'AB' and '12' with a pattern; a row number of 0 or of 1048577 raises ValueError with the text Row numbers must be between 1 and 1048576 " + OX + " (" + RUN + ").",
 "RangesAndValues": "A block of cells is taken by slicing, by the rows and columns attributes or by the methods that give values " + S + ".",
 "RangeSlice": "sheet['A1':'C3'] is a tuple of 3 tuples of 3 Cell objects, rows first, and the chapter's two loops print A1 2035-04-05 13:34:02, B1 Apples, C1 73 and then the rows 2 and 3 with the line --- END OF ROW --- after each " + S + "; sheet['B'] gave the 7 cells of column B and sheet[2] the 3 cells of row 2 (" + RUN + "), while the forms sheet['C:D'] and sheet[5:10] are in the tutorial and were not run " + OX + ".",
 "RowsAndColumns": "list(sheet.rows) holds 7 tuples of 3 cells and list(sheet.columns) 3 tuples of 7 cells, and the cells of list(sheet.columns)[1] have the values Apples, Cherries, Pears, Oranges, Apples, Bananas and Strawberries, as the chapter prints " + S + "; the documentation notes that columns is not available in read-only mode " + OX + " (" + RUN + ").",
 "ValuesOnly": "iter_rows(min_row=1, max_row=2, max_col=3, values_only=True) gave the first two rows as tuples of plain values, and the first row of sheet.values was (datetime.datetime(2035, 4, 5, 13, 34, 2), 'Apples', 73); the chapter as read does not present iter_rows or values, and the documentation lists them, with values used to build a pandas DataFrame, which was not run " + OX + " (" + RUN + ").",
 "DateValues": "Column A comes back as datetime values, as the chapter says " + S + "; the stored cell has the type n and a number format of yyyy-mm-dd h:mm:ss, and the day number 45000 added to the epoch 1899-12-30 is 2023-03-15 " + OX + " " + PSF + " (" + RUN + ").",
 "ReadingProject": "Project 9 reads a census workbook, counts tracts and adds populations for each county, and writes the result as Python source " + S + ".",
 "CensusNumbers": "The project has three steps: read the rows, fill a nested dictionary, write it to a file " + S + ".",
 "CountyStructure": "The chapter's county_data is keyed county_data[state abbrev][county]['tracts'] and ['pop'], so county_data['AK']['Anchorage']['pop'] is 291826 and ['tracts'] is 55 in the chapter's excerpt; the book's censuspopdata.xlsx was not opened, and a stand-in with six tract rows of which one population was text ran the chapter's loop and gave AL Autauga 3 tracts and 7455, AL Baldwin 1 and 1948, and AK Anchorage 2 and 9020, which shows why the chapter converts with int() " + S + " (" + RUN + ").",
 "DefaultEntries": "county_data.setdefault(state, {}) and county_data[state].setdefault(county, {'tracts': 0, 'pop': 0}) make the keys before they are incremented, and the second call with another default changes nothing; without them county_data['AK']['Anchorage'] = 1 on an empty dictionary raises KeyError: 'AK', which is the error the chapter predicts " + S + " " + PSF + ".",
 "GeneratedModule": "pprint.pformat(county_data) gives text that is valid Python, the chapter writes it after 'allData = ' to census2010.py and imports it, and for the stand-in census2010.allData['AK']['Anchorage'] printed {'pop': 9020, 'tracts': 2}; pformat sorts dictionary keys by default (sort_dicts=True), so the file is in alphabetical order, and importing the file executes its statements, so a file written this way is trusted like a program " + S + " " + PSF + " (" + RUN + ").",
 "WritingWorkbooks": "The chapter creates workbooks and sheets, writes values, saves, and in Project 10 edits cells of an existing workbook " + S + ".",
 "AddingAndRemoving": "A workbook is created blank and its sheets are added and removed by name " + S + ".",
 "NewWorkbook": "openpyxl.Workbook() gives a workbook with one sheet, so wb.sheetnames is ['Sheet'] and sheet.title is 'Sheet', and setting sheet.title = 'Spam Bacon Eggs Sheet' makes wb.sheetnames ['Spam Bacon Eggs Sheet'], as the chapter prints " + S + " (" + RUN + ").",
 "SheetCreation": "create_sheet() on a new workbook returned a Worksheet named Sheet1 after ['Sheet'], create_sheet(index=0, title='First Sheet') put it first and create_sheet(index=2, title='Middle Sheet') gave ['First Sheet', 'Sheet', 'Middle Sheet', 'Sheet1'], as the chapter prints " + S + "; beyond the chapter, a second sheet titled Mysheet became Mysheet1, an index of -1 puts the sheet before the last one, a title of 32 characters is accepted with a UserWarning that says some applications may not read the file, a title containing / raises ValueError, and copy_worksheet made a sheet titled Sheet1 Copy " + OX + " (" + RUN + ").",
 "SheetRemoval": "del wb['Middle Sheet'] and del wb['Sheet1'] left ['First Sheet', 'Sheet'] as the chapter prints, wb.remove(wb['Sheet']) then left ['First Sheet'], and del of a name that is not there raises KeyError " + S + " (" + RUN + ").",
 "SavingAndOutput": "Edits are kept in memory until save, and values are written by assignment " + S + ".",
 "SaveMethod": "After the stand-in's sheet was retitled Spam Spam Spam and saved as example3_copy.xlsx, the copy had the new title and the original file still had Sheet1, as the chapter explains; save overwrites an existing file without warning, since a blank workbook saved over a file of 4954 bytes left one of 4784 bytes, and the tutorial says the same " + S + " " + OX + " (" + RUN + "). That save fails while Excel has the file open was not tested.",
 "CellWriting": "sheet['A1'] = 'Hello, world!' makes sheet['A1'].value that text; the kinds stored were s for text, n for a number, b for True, d for a datetime with the format yyyy-mm-dd h:mm:ss and d for a date with yyyy-mm-dd; a list as a value raises ValueError with the text Cannot convert [1, 2] to Excel, and a datetime with a timezone is accepted on assignment and raises TypeError only when the file is saved, with the text Excel does not support timezones in datetimes, which agrees with the documentation that only naive datetimes can be stored " + S + " " + OX + " (" + RUN + ").",
 "PriceUpdate": "Project 10 corrects prices in a produce workbook while its total column holds formulas " + S + ".",
 "UpdateLoop": "With PRICE_UPDATES = {'Garlic': 3.07, 'Celery': 1.19, 'Lemon': 1.27} and a loop over range(2, sheet.max_row + 1), a stand-in of seven rows (the book's produceSales3.xlsx was not opened) came out with Celery 1.19, Garlic 3.07 and Lemon 1.27 in the saved updatedProduceSales3.xlsx and the other prices unchanged, while the original file still held 1.9 for Celery " + S + " (" + RUN + "); the chapter's prose says lemons and its key is 'Lemon', and 'Lemon' in the dictionary is True while 'Lemons' is False, and its step 1 pseudo-code cell_obj = 1.19 would only rebind a name and not change a cell " + S + ".",
 "FormulaSurvival": "After the update all seven total cells still had the kind f and the text =ROUND(B2*C2, 2) and so on for their rows, and opening the updated file with data_only=True gave None for them, because the stand-in had never been calculated by a spreadsheet application; whether Excel recalculates them on opening was not tested " + S + " (" + RUN + ").",
 "Presentation": "Fonts, sizes of rows and columns, merged cells and frozen rows change how a sheet looks and scrolls " + S + ".",
 "FontStyle": "A Font object is made once and assigned to cells " + S + ".",
 "FontObject": "Font(name='Times New Roman', bold=True) and Font(size=24, italic=True) are made with the keyword arguments of Table 14-2, name as text, size as a number and bold and italic as Booleans, and the size read back as 24.0 " + S + " (" + RUN + ").",
 "FontAssignment": "Setting sheet['A1'].font to the Font and then sheet['A1'] = 'Hello, world!' saved and reloaded as size 24.0, italic True, bold False and the text; setting the attribute bold on an existing Font raised AttributeError with the text Style objects are immutable and cannot be changed, and the font read from the cell is equal to the Font assigned but is not the same object " + S + " (" + RUN + ").",
 "FontDefaults": "The chapter says that a Font without a name uses the openpyxl default Calibri and one without a size uses 11; in the run a new cell had the font Calibri 11.0, but the Font made with size=24 and italic=True had name None, the one made with name and bold had size None, and the styles part of the saved file listed the first font with only italic and a size of 24; what Excel displays for the missing attributes was not tested " + S + " (" + RUN + ").",
 "SizeMeasures": "Row heights, column widths and hidden columns are set through dimension objects " + S + ".",
 "RowAndColumnSize": "row_dimensions is a DimensionHolder of RowDimension objects and column_dimensions one of ColumnDimension objects; sheet.row_dimensions[1].height = 70 and sheet.column_dimensions['B'].width = 20 were read back as 70.0 and 20.0 after saving, row 5 set to 100 gave 100.0, and a column left alone reported 13.0, which fits the chapter's remark that default sizes vary between versions " + S + " (" + RUN + ").",
 "HiddenColumn": "Practice question 16 asks how to hide column C; column_dimensions['C'].hidden = True was saved, written as a hidden column in the sheet part, and read back as True, and the documentation shows grouping with hidden=True as well " + S + " " + OX + " (" + RUN + ").",
 "MergedAndFrozenPositions": "Merging joins cells into one, and freezing keeps headers in view " + S + ".",
 "MergeCells": "merge_cells('A1:D3') joins 12 cells and merge_cells('C5:D5') two, sheet.merged_cells.ranges listed ['A1:D3', 'C5:D5'], a cell inside a merged area such as B2 is a MergedCell whose value is None and whose assignment raises AttributeError with the text 'MergedCell' object attribute 'value' is read-only, unmerge_cells('A1:D3') and ('C5:D5') left no merged ranges and B2 an ordinary Cell, and unmerging a range that is not merged raises ValueError " + S + " (" + RUN + ").",
 "FreezePanes": "Practice question 17 asks what a freeze pane is: it keeps rows and columns visible while the sheet scrolls; the freeze_panes settings of Table 14-3 were all read back as set, A1 and None both gave None, a Cell object was accepted (B3 gave a split of 1 column and 2 rows), and the counts of frozen rows and columns follow from the coordinate: A2 freezes 1 row, B1 1 column, C1 2 columns, C2 1 row and 2 columns " + S + " (" + RUN + ").",
 "FormulasAndCharts": "Formulas are strings that start with an equal sign, and charts are built from references to cells " + S + ".",
 "FormulaCells": "A formula is stored as text in a cell and calculated only by a spreadsheet application " + S + ".",
 "FormulaString": "sheet['A3'] = '=SUM(A1:A2)' after 200 and 300 in A1 and A2 gave the kind f, and the saved sheet part holds the formula without a value, so a reloaded A3 is '=SUM(A1:A2)' as the chapter prints; text that starts with = is always taken for a formula, including '=not a formula(', while '123' stays text with the kind s, and setting the data type of the cell to s keeps a formula-looking text as text " + S + " (" + RUN + ").",
 "NoCalculation": "The chapter says openpyxl cannot calculate formulas, so the 500 that Excel shows for =SUM(A1:A2) is not produced by the module; Python's sum([200, 300]) is 500, but no spreadsheet application was run here to show what Excel would display, and the chapter's example of a long nested formula is offered as a reason to prefer Python code " + S + ".",
 "CachedResult": "Loaded without data_only the cell gave the text =SUM(A1:A2), and loaded with data_only=True it gave None, because no spreadsheet application had opened the file; the chapter's 500 needs the file to be opened and saved in Excel first, which answers practice question 14, and was not reproduced; the tutorial defines data_only as choosing between the formula and the value stored the last time Excel read the sheet " + S + " " + OX + " (" + RUN + ").",
 "FormulaTranslation": "insert_rows(3, 2) moved a formula cell from C5 to C7 and left its text =SUM(B1:B4) as it was, openpyxl.formula.translate.Translator('=SUM(B1:B4)', origin='C5').translate_formula('C7') gave =SUM(B3:B6), and the Tokenizer split =ROUND(B2*C2, 2) into the function ROUND(, the operands B2 and C2, the infix operator *, a separator, a space, the number 2 and the closing parenthesis; the chapter as read presents none of these " + OX + " (" + RUN + ").",
 "ChartSequence": "A chart is assembled from cell references and added to a sheet " + S + ".",
 "ChartRecipe": "The chapter's five steps are a Reference, a Series, a chart object, appending the series and add_chart; for column A holding 1 to 100 squares, BarChart with title My Chart and Series(ref_obj, title='First series') saved a workbook with the parts xl/charts/chart1.xml and xl/drawings/drawing1.xml, the chart part contained the title and the series title, and a reloaded sheet held 1 chart; BarChart, LineChart, ScatterChart and PieChart all exist, the default chart size is 15 by 7.5, and the chart's look on screen was not viewed; practice question 18 is answered by Reference, Series, BarChart, append and add_chart, and the documentation shows the shorter add_data " + S + " " + OX + " (" + RUN + ").",
 "ReferenceObject": "Reference(sheet, 2, 3, 4, 5) printed as the range B3 to D5 of the sheet, with min_col 2, min_row 3, max_col 4 and max_row 5, and the documented signature is worksheet, min_col, min_row, max_col, max_row; the chapter says five arguments and lists three and says the first integer is the row, which is wrong, while its example Reference(sheet, 1, 1, 1, 10) is column 1, rows 1 to 10 and the saved chart names A1 to A10 " + S + " " + OX + " (" + RUN + ").",
 "BeyondTheChapter": "Large files, file-format limits, dates and the two practice programs go beyond the chapter's text " + S + " " + OX + ".",
 "LargeDataSources": "Two optimised modes handle files too large for memory " + OX + ".",
 "ReadOnlyMode": "load_workbook(..., read_only=True) gave a ReadOnlyWorksheet whose rows are ReadOnlyCell objects, calculate_dimension() returned A1:C7, iter_cols raised AttributeError, saving raised TypeError with the text Workbook is read-only, and the documentation says the workbook is loaded lazily and must be closed with close() " + OX + " (" + RUN + ").",
 "WriteOnlyMode": "Workbook(write_only=True) had no sheets (sheetnames was []), create_sheet() and append([1, 2, 3]) worked, ws['A1'] raised TypeError because a write-only sheet cannot be indexed, and a second save raised FileNotFoundError, while the documentation says a write-only workbook can be saved only once " + OX + " (" + RUN + ").",
 "FormatDetails": "The module reads the xlsx family, warns of XML attacks, has a release history and stores dates as numbers " + OX + ".",
 "OldFormatRefusal": "An old .xls file raised InvalidFileException with the text openpyxl does not support the old .xls file format, please use xlrd to read this file, or convert it to the more recent .xlsx file format., a text file named .xlsx raised BadZipFile with the text File is not a zip file, and a missing file raised FileNotFoundError; the documentation says openpyxl reads and writes xlsx, xlsm, xltx and xltm files " + OX + " " + PSF + " (" + RUN + ").",
 "XmlSafety": "The documentation's home page says that by default openpyxl does not guard against quadratic blowup or billion laughs XML attacks and that installing defusedxml guards against them; neither defusedxml nor lxml was installed in the run, and the protection was not tested " + OX + ".",
 "LibraryStatus": "The Python Package Index lists openpyxl 3.1.5 uploaded on 2024-06-28 as the newest release, with Requires-Python 3.8 or later and classifiers up to Python 3.11, and also a beta 3.2.0b1 uploaded on 2022-05-19; the documentation pages were headed 3.1.3 and generated on 2024-05-29; the chapter says to install it with pip, as Appendix A explains, and it was installed with uv into a scratch folder; every operation executed ran under Python 3.14.4 with warnings turned into errors, apart from the title-length warning the script provoked " + S + " " + PPI + " " + PSF + " (" + RUN + ").",
 "DateSerials": "The documentation says a date can be stored as an ISO 8601 string or as a number, that the 1900 date system counts 1900 as a leap year by mistake, that the 1904 system is chosen with wb.epoch, and that no timezone can be stored; in the run wb.epoch was 1899-12-30, iso_dates was False, to_excel gave 49404.565300925926 for 2035-04-05 13:34:02 and 61.0 for 1900-03-01, from_excel(1.5) gave 1900-01-01 12:00 where the plain epoch sum gives 1899-12-31 12:00, and date(1900, 2, 29) raises ValueError " + OX + " " + PSF + " (" + RUN + ").",
 "PracticePrograms": "The chapter ends with 18 practice questions and two programs to write " + S + ".",
 "MultiplicationTable": "A solution written for this study, called as a function with 6 because the command line was not used, gave a sheet of 7 rows and 7 columns with G7 equal to 36, D5 equal to 12, A1 empty, B1 and A4 in bold and C3 not in bold; the book's Figure 14-10 was not viewed " + S + " (" + RUN + ").",
 "BlankRowInserter": "A solution written for this study that copies rows before N unchanged and writes the later rows M rows lower turned the rows item1 to item5 into item1, item2, two empty rows, item3, item4, item5 for N of 3 and M of 2, and the sheet method insert_rows(3, 2) gave the same values; the command-line form was not run, and the figures were not viewed " + S + " " + OX + " (" + RUN + ").",
}
BEH = [
 ["a zip archive starts with PK and a text file is refused", "import io, zipfile\nb = io.BytesIO()\nwith zipfile.ZipFile(b, 'w') as z:\n    z.writestr('xl/workbook.xml', '<workbook/>')\nprint(b.getvalue()[:2], zipfile.ZipFile(b).namelist())\ntry:\n    zipfile.ZipFile(io.BytesIO(b'a,b'))\nexcept zipfile.BadZipFile as e:\n    print(type(e).__name__ + ': ' + str(e))", "b'PK' ['xl/workbook.xml']\nBadZipFile: File is not a zip file"],
 ["column letters and numbers round trip over all 18278 names", "def letter(n):\n    s = ''\n    while n:\n        n, r = divmod(n - 1, 26)\n        s = chr(65 + r) + s\n    return s\ndef number(col):\n    n = 0\n    for ch in col:\n        n = n * 26 + ord(ch) - 64\n    return n\nprint(all(number(letter(n)) == n for n in range(1, 18279)), letter(18278), letter(16384), letter(14), number('M'))", "True ZZZ XFD N 13"],
 ["setdefault keeps the first value and its absence raises KeyError", "d = {}\ntry:\n    d['AK']['Anchorage'] = 1\nexcept KeyError as e:\n    print(type(e).__name__ + ': ' + str(e))\nd.setdefault('AK', {})\nd.setdefault('AK', {'other': 1})\nd['AK'].setdefault('Anchorage', {'tracts': 0, 'pop': 0})\nd['AK']['Anchorage']['tracts'] += 1\nd['AK']['Anchorage']['pop'] += int('5000')\nprint(d)", "KeyError: 'AK'\n{'AK': {'Anchorage': {'tracts': 1, 'pop': 5000}}}"],
 ["pformat sorts keys unless told not to", "import pprint\nprint(pprint.pformat({'b': 1, 'a': 2}))\nprint(pprint.pformat({'b': 1, 'a': 2}, sort_dicts=False))", "{'a': 2, 'b': 1}\n{'b': 1, 'a': 2}"],
 ["a generated module written to a folder can be imported", "import importlib, pprint, sys, tempfile, os\nwith tempfile.TemporaryDirectory() as d:\n    with open(os.path.join(d, 'census2010.py'), 'w') as f:\n        f.write('allData = ' + pprint.pformat({'AK': {'Anchorage': {'pop': 9020, 'tracts': 2}}}))\n    sys.path.insert(0, d)\n    m = importlib.import_module('census2010')\n    print(m.allData['AK']['Anchorage'])", "{'pop': 9020, 'tracts': 2}"],
 ["29 February 1900 is not a Python date and the plain epoch is right from serial 61", "import datetime\ntry:\n    datetime.date(1900, 2, 29)\nexcept ValueError as e:\n    print(type(e).__name__ + ': ' + str(e))\nepoch = datetime.datetime(1899, 12, 30)\nprint(epoch + datetime.timedelta(days=61), epoch + datetime.timedelta(days=1.5))", "ValueError: day 29 must be in range 1..28 for month 2 in year 1900\n1900-03-01 00:00:00 1899-12-31 12:00:00"],
 ["a timezone has to be removed before a date is stored", "import datetime\ndt = datetime.datetime(2035, 1, 1, 12, tzinfo=datetime.timezone.utc)\nprint(dt.tzinfo is None, dt.replace(tzinfo=None), dt.replace(tzinfo=None).tzinfo)", "False 2035-01-01 12:00:00 None"],
 ["the price update changes a copy and keeps the original rows", "rows = [['Celery', 1.9], ['Potatoes', 0.86], ['Lemon', 1.1]]\nPRICE_UPDATES = {'Garlic': 3.07, 'Celery': 1.19, 'Lemon': 1.27}\nupdated = [list(r) for r in rows]\nfor row_num in range(len(updated)):\n    if updated[row_num][0] in PRICE_UPDATES:\n        updated[row_num][1] = PRICE_UPDATES[updated[row_num][0]]\nprint(rows)\nprint(updated)\nprint('Lemons' in PRICE_UPDATES)", "[['Celery', 1.9], ['Potatoes', 0.86], ['Lemon', 1.1]]\n[['Celery', 1.19], ['Potatoes', 0.86], ['Lemon', 1.27]]\nFalse"],
 ["frozen rows and columns follow from the coordinate", "import re\ndef frozen(cell):\n    col, row = re.fullmatch(r'([A-Z]+)(\\d+)', cell).groups()\n    return int(row) - 1, ord(col) - 65\nfor c in ('A2', 'B1', 'C1', 'C2', 'A1'):\n    r, k = frozen(c)\n    print(c, 'rows frozen:', r, 'columns frozen:', k)", "A2 rows frozen: 1 columns frozen: 0\nB1 rows frozen: 0 columns frozen: 1\nC1 rows frozen: 0 columns frozen: 2\nC2 rows frozen: 1 columns frozen: 2\nA1 rows frozen: 0 columns frozen: 0"],
 ["multiplication table as a grid with labels", "n = 6\ngrid = [[None] + list(range(1, n + 1))] + [[r] + [r * c for c in range(1, n + 1)] for r in range(1, n + 1)]\nprint(len(grid), len(grid[0]), grid[6][6], grid[4][3], grid[0][0])", "7 7 36 12 None"],
 ["blank rows inserted at row 3 move the later rows down", "rows = ['item1', 'item2', 'item3', 'item4', 'item5']\nN, M = 3, 2\nnew = {}\nfor r, v in enumerate(rows, 1):\n    new[r if r < N else r + M] = v\nprint([new.get(r) for r in range(1, len(rows) + M + 1)])", "['item1', 'item2', None, None, 'item3', 'item4', 'item5']"],
 ["an Element is tested with is not None and a formula is kept as text", "import xml.etree.ElementTree as ET\nc = ET.fromstring('<c r=\"A3\"><f>SUM(A1:A2)</f></c>')\nprint(c.find('f') is not None, c.find('v') is None, '=' + c.find('f').text)", "True True =SUM(A1:A2)"],
]
