"""SEN0414 chapter 7, corpus text A (version 1.0.0): the branches 'The dictionary data type', 'Keys and hashing' and 'Reading and changing pairs'.
Every output, error message and number quoted below is in CHECKS, RAISES or the leaf's own input-output example and is executed by
sen0414_ch07_corpus_v1_0_0.py. The citation tokens ([SW] and the others) are resolved there."""
__version__ = "1.0.0"
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sen0414_ch07_corpus_base_v1_0_0 import *

# ============================================================ The dictionary data type
RAW += [
 ("DictionaryModel", "The dictionary data type", 1, None, None, [
  (W, "The dictionary data type is Python's built-in way of storing many values so that each one is found by a name of its own, called a key, and not by a position. Chapter 7 of the third edition opens with the observation that a dictionary is, like a list, a mutable collection of many values, but that the indexes of a dictionary can be of many different data types and not only integers [SW]. This branch collects the ideas that define the type: what a pair is, how a dictionary is written and built, and how it differs from the list that the previous chapter taught."),
  (Y, "Most data in real programs is a set of facts about one thing: a cat has a size, a colour and an age, a friend has a birthday, a guest brings apples and cups. A list can hold such facts only if the programmer remembers that position 0 means the size and position 2 the age. A dictionary lets the code say 'color' and be understood, which is why the chapter says that a dictionary stores several pieces of data about the same thing in a single variable [SW]. The type is also the foundation of everything else in the chapter, because counting, grouping, nesting and modelling a chessboard are all built from the operations of this branch."),
  (E, "Dictionaries are met in every Python program, including the ones a learner did not write: the keyword arguments of a function call, the attributes of an object, the settings read from a file and the JSON text that web services exchange all become dictionaries. The branch comes first in the chapter's concept tree because the later branches assume a reader who can write a dictionary, read one pair from it and explain why a missing key is an error."),
  (H, "The branch has two parts. Pairs and mappings describes the type itself: the pair, the curly-bracket notation and the ways of constructing a dictionary. Dictionaries and lists compared takes the contrast the chapter draws between the two types: keys instead of indexes, equality that ignores order, the insertion order that current Python guarantees, and the fact that a dictionary is a mapping and not a sequence."),
 ], None),
 ("PairsAndMappings", "Pairs and mappings", 2, "DictionaryModel", None, [
  (W, "Pairs and mappings is the part of the branch that says what a dictionary is made of and how one is written. A dictionary is a collection of key-value pairs, and Python calls any object that joins keys to values a mapping; the dictionary is the one standard mapping type [PSF]."),
  (Y, "The vocabulary matters because every later sentence of the chapter uses it. A reader who confuses a key with a value, or a pair with a key, will misread the error messages that follow, such as KeyError, and will not know which half of a pair a loop variable holds."),
  (H, "Three concepts follow. The dictionary itself is the type and its notation. The key-value pair is the unit it is built from. The dict constructor shows the other ways of making a dictionary besides curly brackets, from keyword arguments, from pairs and from two parallel lists."),
 ], None),
 ("DictionaryType", "Dictionary", 3, "PairsAndMappings", ("my_cat = {'size': 'fat', 'color': 'gray', 'age': 17}", "A dictionary is a mutable collection of key-value pairs written between curly brackets; a key selects its value the way an index selects an item of a list, and each key occurs only once.", ("(lambda my_cat: (my_cat['size'], 'My cat has ' + my_cat['color'] + ' fur.', len(my_cat), type({}).__name__, type({'a'}).__name__))({'size': 'fat', 'color': 'gray', 'age': 17})", "('fat', 'My cat has gray fur.', 3, 'dict', 'set')")), [
  (W, "A dictionary is a built-in Python type that holds a collection of pairs, each pair joining a key to a value. It is written between curly brackets, as in my_cat = {'size': 'fat', 'color': 'gray', 'age': 17}, where 'size', 'color' and 'age' are the keys and 'fat', 'gray' and 17 are the values. The chapter introduces it as a mutable collection of many values; mutable means that the dictionary can be changed after it is created, by adding, replacing and removing pairs, without making a new dictionary [SW]. The key in square brackets finds the value, so my_cat['size'] is 'fat'."),
  (Y, "The point of a dictionary is that data about one thing can live in one variable under names that explain themselves. The chapter observes that the my_cat variable holds three different strings that describe the cat, that it can be passed as an argument or returned from a function, and that this saves creating three separate variables [SW]. The keys document the data: a reader who sees 'color' understands, whereas a list would show only a gray string at position 1."),
  (E, "Dictionaries are the commonest container in Python programs after the list. The empty dictionary {} is a usual starting point, and the characterCount program of this chapter begins with count = {} and fills it. One trap belongs here: a pair of empty curly brackets is an empty dictionary, and the empty set has no literal of its own and is written set(); braces that hold values without colons, such as {'a'}, make a set [PSF]."),
  (H, "Python reads the pairs between the brackets from left to right, stores them and binds the result to the variable. A lookup my_cat['color'] uses the key to find 'gray', and the result can be joined with other strings, as in 'My cat has ' + my_cat['color'] + ' fur.', which gives 'My cat has gray fur.'. The built-in len counts the pairs, so len(my_cat) is 3. Each key occurs once: a second pair with the same key replaces the first value instead of adding another pair, which a later concept shows."),
  (K, "A key must match exactly. 'Color' and 'color' are different keys, so my_cat['Color'] is an error even though the dictionary has a key that a human would call the same. The values may be of any type, including lists and other dictionaries, but the keys obey the rules of the next branch, and a learner who forgets them meets an error message about hashing."),
 ]),
 ("KeyValuePair", "Key-value pair", 3, "PairsAndMappings", ("the pair 'color': 'red'", "A key-value pair is one key together with the value it stands for; it is the unit a dictionary is built from, and the items view hands it out as a tuple of two.", ("(list({'color': 'red', 'age': 42}.items()), len({'color': 'red', 'age': 42}))", "([('color', 'red'), ('age', 42)], 2)")), [
  (W, "A key-value pair is a key joined to the value that it stands for. The chapter defines it in one sentence: the indexes of a dictionary are called keys, and a key with its associated value is called a key-value pair [SW]. In the dictionary {'color': 'red', 'age': 42} there are two pairs, 'color' with 'red' and 'age' with 42, and a dictionary is exactly the collection of its pairs."),
  (Y, "Thinking in pairs explains the operations of the whole chapter. Adding a pair, replacing the value of a pair, deleting a pair and looping over the pairs are four different actions, and each name in the chapter's method list, keys, values and items, says which part of the pair it hands back. The idea also explains why a dictionary can hold the same value twice but never the same key twice."),
  (E, "The pair appears in the notation of the language, in the literal {'color': 'red'}, and in the output of the items method, where each pair is printed as a tuple in round brackets, ('color', 'red'). It appears in the real world in every table of labelled facts: a phone book pairs a name with a number, a dictionary of words pairs a word with its meaning, and a coat check pairs a ticket with a coat."),
  (H, "Python stores a pair so that the key can be found again quickly. It does not search the pairs one by one; the key is turned into a number by a rule that a later concept explains, and that number tells Python where the pair is kept. The method items hands the pairs back as tuples whose first member is the key and whose second is the value, which is why a loop can unpack them into two variables."),
  (K, "The key and the value are not symmetrical. A value is found from its key, but a key cannot be found from its value except by looking at every pair, and two pairs may have equal values but never equal keys. The test 'red' in spam asks about keys and not about values, which the membership concept explains."),
 ]),
 ("DictionaryConstructors", "The dict constructor", 3, "PairsAndMappings", ("dict(one=1, two=2) and dict(zip(keys, values))", "The dict constructor builds a dictionary from keyword arguments, from pairs, from another mapping or from two parallel lists joined by zip, and when a key occurs twice the last value wins.", ("(dict([('two', 2), ('one', 1)]) == dict(one=1, two=2) == dict(zip(['one', 'two'], [1, 2])), dict([('k', 1), ('k', 2)]))", "(True, {'k': 2})")), [
  (W, "The dict constructor is the function dict(), which builds a dictionary without curly brackets. The documentation lists the forms: keyword arguments, as in dict(one=1, two=2); a list of pairs, as in dict([('two', 2), ('one', 1)]); another dictionary; and the result of zip over a list of keys and a list of values, as in dict(zip(['one', 'two'], [1, 2])). All of them give a dictionary equal to {'one': 1, 'two': 2} [PSF]."),
  (Y, "Curly brackets work when the pairs are written in the program, but real programs often have keys in one list and values in another, or pairs arriving from a file or a database. The constructor turns those into a dictionary in one expression. It also makes a copy of an existing dictionary, which the chapter needs when the chessboard program resets the board."),
  (E, "The keyword form is common when the keys are fixed names, such as dict(name='Zophie', age=7). The zip form is common when the columns of a table have been read into separate lists. The form with a list of pairs is the one produced by another dictionary's items method, so dict(d.items()) rebuilds a dictionary from its own pairs."),
  (H, "Python walks over the pairs in the order they are given and inserts each one, so when the same key occurs twice the later value replaces the earlier one: dict([('k', 1), ('k', 2)]) is {'k': 2}. The keyword form works only for keys that are valid Python names, because the key is written as an argument name; dict(my key=1) is a syntax error. Keys of any other kind need the other forms."),
  (K, "The constructor and the literal are different spellings of the same type, not different types, so dict(one=1, two=2) == {'one': 1, 'two': 2} is True. Do not expect the constructor to complain about a repeated key; it quietly keeps the last value, which can hide a mistake in the data."),
 ]),
 ("ListContrast", "Dictionaries and lists compared", 2, "DictionaryModel", None, [
  (W, "Dictionaries and lists compared is the chapter's own subsection, and its subject is what changes when the index of a collection may be any suitable value instead of a counting number. The chapter lists the contrasts it wants remembered: keys instead of indexes, no first item, equality that does not care how the pairs were entered, and no slicing [SW]."),
  (Y, "Learners arrive at dictionaries knowing lists, and every habit from lists that does not carry over is a source of mistakes: counting from zero, asking for item 0, slicing, comparing for equality by position. Naming the differences once, with an executed example for each, removes the guesswork."),
  (H, "Four concepts follow. The first shows that a key is not an index. The second shows that two dictionaries are equal whatever the order of their pairs. The third corrects the chapter's statement that dictionaries are unordered, because current Python keeps the order of insertion. The fourth explains why a dictionary cannot be sliced."),
 ], None),
 ("KeysNotIndexes", "Keys, not indexes", 3, "ListContrast", ("spam[0] with spam = {12345: 'Luggage Combination', 42: 'The Answer'}", "A dictionary has keys and not positions: spam[0] looks for a key equal to 0 and raises KeyError when there is none, even though the dictionary holds two pairs.", ("(lambda spam: (spam[12345], spam[42], 0 in spam, len(spam)))({12345: 'Luggage Combination', 42: 'The Answer'})", "('Luggage Combination', 'The Answer', False, 2)")), [
  (W, "A dictionary has keys and not indexes. The chapter makes the point with a dictionary whose keys are the integers 12345 and 42: spam[12345] is 'Luggage Combination' and spam[42] is 'The Answer', but spam[0] raises KeyError: 0, because the dictionary has no index 0 through 41 like a list would [SW]. The integers are keys like any other, chosen by the programmer, and they do not have to start at 0 or be consecutive."),
  (Y, "The distinction prevents the commonest mistake of a learner who comes from lists: assuming that the first pair added is item 0. With a list the position is a property of the collection; with a dictionary the key is a property of the data. That is also why a dictionary is the right tool when the identifiers in the data are not a tidy run of numbers, such as a locker combination, a student number or a product code."),
  (E, "Integer keys appear whenever real identifiers are used as keys: employee numbers, years, port numbers, or the ASCII code of a character. In every such dictionary an integer inside the square brackets is a request to find that key, never to count to that position."),
  (H, "The square brackets are the same in both types, but the lookup differs. A list checks that the integer is inside the range of its length and fetches by position; a dictionary turns the key into a number, finds the place that number points to and compares the key it finds there with the key asked for. If no equal key is there, Python raises KeyError with the key as its message, which for spam[0] reads KeyError: 0."),
  (K, "A dictionary with integer keys is not a list that happens to have gaps. Looping over it, sorting it and slicing it all behave differently, and the number of pairs says nothing about which integers are valid keys. The test 0 in spam asks whether 0 is a key, and here it is False although len(spam) is 2."),
 ]),
 ("OrderInsensitiveEquality", "Equality ignores order", 3, "ListContrast", ("eggs == ham", "Two dictionaries are equal when they hold the same pairs, whatever the order in which the pairs were entered, where two lists are equal only when their items are in the same order.", ("(lambda spam, bacon, eggs, ham: (spam == bacon, eggs == ham))(['cats', 'dogs', 'moose'], ['dogs', 'moose', 'cats'], {'name': 'Zophie', 'species': 'cat', 'age': '8'}, {'species': 'cat', 'age': '8', 'name': 'Zophie'})", "(False, True)")), [
  (W, "Two dictionaries are equal when they contain the same keys and the same value for each key, however the pairs were entered. The chapter shows it by comparing two lists with the same items in different orders, which are not equal, and two dictionaries with the same three pairs in different orders, which are equal: eggs == ham is True [SW]. For lists the order is part of the value; for dictionaries it is not."),
  (Y, "The rule lets a program compare two records without first putting their pairs in a fixed order. A test that builds a dictionary in any order and compares it with the expected dictionary will pass when the content is right, and a program that reads the same facts from two files that list the fields differently can still decide whether the two records agree."),
  (E, "The comparison is used in tests, in checks that a copy matches its original, and in programs that merge data from several sources. The practice programs of the chapter use it implicitly: a board is the same board whichever order its pieces were placed in."),
  (H, "Python compares the two dictionaries by size first and then looks up each key of one in the other and compares the values it finds, so the order in which the pairs happen to be stored never enters the comparison. The result for the book's example is True. The order of the pairs is still there, and a loop will show it, but it does not take part in ==."),
  (K, "Equal dictionaries may print their pairs in different orders, and list(eggs) is not equal to list(ham) here because the lists of keys keep the two orders. The relational operators work differently again: a dictionary cannot be ordered, so {'a': 1} < {'a': 2} raises TypeError."),
 ]),
 ("InsertionOrder", "Insertion order", 3, "ListContrast", ("list(d) after replacing, deleting and re-adding keys", "Since Python 3.7 a dictionary remembers the order in which its keys were first inserted, and every loop, list and display follows that order; replacing a value keeps the position of its key and a key added after a deletion goes to the end.", ("(lambda d: (d.__setitem__('one', 42), d.__delitem__('two'), d.__setitem__('two', None), list(d))[3])({'one': 1, 'two': 2, 'three': 3, 'four': 4})", "['one', 'three', 'four', 'two']")), [
  (W, "A dictionary remembers the order in which its keys were first inserted, and every operation that goes through the keys follows that order. The documentation states it in the dictionary section: dictionaries preserve insertion order, updating a key does not affect the order, and keys added after a deletion are inserted at the end; since Python 3.7 this is guaranteed by the language, where in CPython 3.6 it was an implementation detail [PSF]. The chapter, written for the older reading, says that the items of a dictionary are unordered and that there is no first item [SW]."),
  (Y, "The difference matters because the sentence in the book is no longer true of the interpreter the course teaches. Programs can now rely on the order in which a dictionary was filled: a loop over the pairs lists them in insertion order, a dictionary built from the lines of a file keeps the lines in file order, and output that is printed from a dictionary is the same on every run. The chapter's practice programs, for example, print their inventories in this order."),
  (E, "Insertion order is the reason keyword arguments can be collected in the order the caller wrote them [PEP468], the reason json.dumps writes the fields of an object in the order they were added, and the reason the display of a dictionary looks the way its author typed it. It is met whenever a dictionary is printed, looped over or converted with list()."),
  (H, "The documentation's own example shows the three rules. After d = {'one': 1, 'two': 2, 'three': 3, 'four': 4}, assigning d['one'] = 42 changes the value but leaves the key first; deleting 'two' and assigning it again moves it to the end, so list(d) is ['one', 'three', 'four', 'two']. Python achieves this by storing the pairs in an array in the order they arrive and keeping a separate index that finds them by key."),
  (K, "Insertion order is not sorted order and is not part of equality: two dictionaries with the same pairs in different insertion orders are equal. Do not rely on an order when the dictionary is built from a set or from unordered input, and call sorted() when the output must be alphabetical. Ordering means order of arrival, nothing more."),
 ]),
 ("MappingNotSequence", "A mapping is not a sequence", 3, "ListContrast", ("d[0:2]", "A dictionary is a mapping and not a sequence: its keys are not positions, so it cannot be sliced, and the subscript d[0:2] is looked up as a key and raises KeyError.", ("[isinstance({}, __import__('collections.abc').abc.Sequence), isinstance({}, __import__('collections.abc').abc.Mapping), isinstance([], __import__('collections.abc').abc.Sequence)]", "[False, True, True]")), [
  (W, "A sequence is an ordered collection whose items are reached by position and can be sliced, like a list, a tuple or a string; a mapping is a collection that joins keys to values. A dictionary is a mapping. The chapter says that because a dictionary is not ordered it is not a sequence data type and cannot be sliced like a list [SW], and current Python agrees with the conclusion, although for a different reason: a dictionary is ordered by insertion, but its keys are not positions."),
  (Y, "Knowing the difference tells a learner which tools apply. Slicing, indexing by position, concatenation with plus and repetition with a star are sequence operations and are not available on a dictionary, while looking up by key, testing membership of keys and looping over pairs are mapping operations. Choosing between the two types is choosing between the two families of operations."),
  (E, "The distinction is written into the language's own classification: the collections.abc module has a class Sequence and a class Mapping, and isinstance({}, Mapping) is True while isinstance({}, Sequence) is False. It surfaces as the error that a program meets when it treats a dictionary as a list, the KeyError that d[0:2] raises."),
  (H, "The subscript d[0:2] does not mean a slice to a dictionary. Python builds a slice object, slice(0, 2, None), and looks it up as a key. Since Python 3.12 slice objects are hashable, so the lookup proceeds and finds no such key, and the error is KeyError: slice(0, 2, None); in earlier versions the slice was refused as unhashable and the error was TypeError."),
  (K, "Do not reach for a slice to take the first few pairs of a dictionary. Convert the pairs to a list first, or use itertools.islice over the items. Remember also that a dictionary supports equality but not ordering, so sorting needs sorted() with a key, and that len, in and for work on both families of collection."),
 ]),
]
CHECKS += [("{}", "{}"), ("set()", "set()"), ("type({}).__name__", "'dict'"), ("type({'a'}).__name__", "'set'"), ("type(set()).__name__", "'set'"),
           ("len({'size': 'fat', 'color': 'gray', 'age': 17})", "3"), ("{'size': 'fat', 'color': 'gray', 'age': 17}['size']", "'fat'"),
           ("'My cat has ' + {'size': 'fat', 'color': 'gray', 'age': 17}['color'] + ' fur.'", "'My cat has gray fur.'"),
           ("'Color' in {'size': 'fat', 'color': 'gray', 'age': 17}", "False"),
           ("{'color': 'red', 'age': 42}", "{'color': 'red', 'age': 42}"), ("list({'color': 'red', 'age': 42}.items())", "[('color', 'red'), ('age', 42)]"),
           ("'red' in {'color': 'red', 'age': 42}", "False"), ("'red' in {'color': 'red', 'age': 42}.values()", "True"),
           ("dict(one=1, two=2) == {'one': 1, 'two': 2}", "True"), ("dict([('two', 2), ('one', 1)]) == {'one': 1, 'two': 2}", "True"),
           ("dict(zip(['one', 'two'], [1, 2]))", "{'one': 1, 'two': 2}"), ("dict([('k', 1), ('k', 2)])", "{'k': 2}"),
           ("dict({'one': 1, 'three': 3}, two=2) == {'one': 1, 'two': 2, 'three': 3}", "True"),
           ("dict(name='Zophie', age=7)", "{'name': 'Zophie', 'age': 7}"), ("(lambda d: dict(d.items()) == d)({'a': 1, 'b': 2})", "True"),
           ("(lambda spam: spam[12345])({12345: 'Luggage Combination', 42: 'The Answer'})", "'Luggage Combination'"),
           ("(lambda spam: 0 in spam)({12345: 'Luggage Combination', 42: 'The Answer'})", "False"),
           ("['cats', 'dogs', 'moose'] == ['dogs', 'moose', 'cats']", "False"),
           ("{'name': 'Zophie', 'species': 'cat', 'age': '8'} == {'species': 'cat', 'age': '8', 'name': 'Zophie'}", "True"),
           ("list({'name': 'Zophie', 'species': 'cat', 'age': '8'}) == list({'species': 'cat', 'age': '8', 'name': 'Zophie'})", "False"),
           ("list({'one': 1, 'two': 2, 'three': 3, 'four': 4})", "['one', 'two', 'three', 'four']"),
           ("(lambda d: (d.__setitem__('one', 42), d)[1])({'one': 1, 'two': 2, 'three': 3, 'four': 4})", "{'one': 42, 'two': 2, 'three': 3, 'four': 4}"),
           ("(lambda d: (d.__setitem__('one', 42), d.__delitem__('two'), d.__setitem__('two', None), d)[3])({'one': 1, 'two': 2, 'three': 3, 'four': 4})", "{'one': 42, 'three': 3, 'four': 4, 'two': None}"),
           ("{'a': 1, 'b': 2} == {'b': 2, 'a': 1}", "True"),
           ("__import__('collections.abc').abc.Mapping.__name__", "'Mapping'"),
           ("slice(0, 2)", "slice(0, 2, None)"), ("repr(slice(0, 2))", "'slice(0, 2, None)'"),
           ("hash(slice(0, 2)) == hash(slice(0, 2))", "True"),
           ("(lambda d: (d.__setitem__(slice(0, 2), 'x'), list(d))[1])({})", "[slice(0, 2, None)]")]
RAISES += [("(lambda spam: spam[0])({12345: 'Luggage Combination', 42: 'The Answer'})", "KeyError"),
           ("{'a': 1} < {'a': 2}", "TypeError"), ("(lambda d: d[0:2])({'a': 1})", "KeyError"),
           ("compile('dict(my key=1)', 'x', 'eval')", "SyntaxError"), ("(lambda d: d['Color'])({'color': 'gray'})", "KeyError")]
CHECKS += [PROG("d = {'a': 1}\ntry:\n    d[0:2]\nexcept KeyError as e:\n    print(type(e).__name__ + ': ' + str(e))\n", "KeyError: slice(0, 2, None)\n"),
           PROG("spam = {12345: 'Luggage Combination', 42: 'The Answer'}\ntry:\n    spam[0]\nexcept KeyError as e:\n    print(type(e).__name__ + ': ' + str(e))\n", "KeyError: 0\n")]

# ============================================================ Keys and hashing
RAW += [
 ("KeyRules", "Keys and hashing", 1, None, None, [
  (W, "Keys and hashing is the branch that says which values may be used as dictionary keys and why. The rule is short: a key must be hashable. The chapter states the consequence and leaves the reason out: while many values can be keys, a list or a dictionary cannot be, because these data types are unhashable, a concept beyond the scope of the book, and a tuple should be used where a list is wanted as a key [SW]. This branch supplies the concept the book leaves out."),
  (Y, "Hashing is the idea that makes a dictionary fast, and it is the reason for the one rule a learner meets as an error message. A learner who has met the message unhashable type: 'list' once, and been told only to use a tuple, will meet it again in other disguises, in sets, in dictionary keys built from data and in classes of their own. Knowing the rule once removes the whole family of surprises."),
  (E, "The rule is applied every time a program writes a key: the square names of the chessboard, the characters of the character count, the names in the birthdays program. It is applied silently when the key is a number, a string or a tuple of those, and noisily when it is a list or a dictionary."),
  (H, "The branch has two parts. What may be a key explains hashable values, the hash value that Python computes from a key, the tuple as the standard key for compound data, and the rule that equal keys are one key. Absent keys explains the error that follows from asking for a key that is not there."),
 ], None),
 ("WhatMayBeAKey", "What may be a key", 2, "KeyRules", None, [
  (W, "What may be a key is the part of the branch that states the rule and its consequences. A key must have a hash value that never changes during its lifetime, and two keys that compare equal must have the same hash value; the data model states these properties for every hashable object, and the documentation of the dictionary type names the practical result: values containing lists, dictionaries or other mutable types, which are compared by value, may not be used as keys [PSF]."),
  (Y, "The properties explain choices that look arbitrary otherwise. They explain why a string, a number and a tuple of numbers are acceptable keys while a list is not, why 1 and 1.0 find the same pair, and why an object that can change must not be used to find a pair, since a pair filed under one hash value would be lost when the key changes."),
  (H, "Four concepts follow. Hashable keys states the rule and the error. The hash value explains the number Python computes. The tuple as a key gives the book's recommended replacement for a list. Equal keys share one slot shows the least expected consequence, that 1, 1.0 and True are one key."),
 ], None),
 ("HashableKeys", "Hashable keys", 3, "WhatMayBeAKey", ("{[1, 2]: 'x'}", "A key must be hashable: a number, a string or a tuple of hashable items can be a key, while a list or a dictionary cannot, because they can change and Python refuses to file a pair under a value that might move.", ("[isinstance(x, __import__('collections.abc').abc.Hashable) for x in ('a', 1, (1, 2), [1], {})]", "[True, True, True, False, False]")), [
  (W, "A value is hashable when Python can compute from it a number, its hash, that stays the same for as long as the value lives, and when two equal values always give the same number. Strings, numbers, Booleans and tuples of hashable items are hashable; lists, dictionaries and sets are not. The chapter puts the practical rule in one sentence: you cannot use a list or dictionary as the key in a dictionary, because these data types are unhashable, and if you need a list for a dictionary key, use a tuple instead [SW]."),
  (Y, "The rule protects the dictionary. A pair is stored at a place that depends on the hash of its key. If the key could change, as a list can by an append, its hash would change and the pair would be sitting at the wrong place, unreachable by the key that it was filed under. The data model gives exactly this reason: a key's hash value must be immutable, otherwise it would be in the wrong hash bucket [PSF]."),
  (E, "The rule is met as an error. Writing {[1, 2]: 'x'} in current Python raises TypeError with the message that a list cannot be used as a dict key, and hash([1, 2]) raises TypeError: unhashable type: 'list'. A program meets it when it builds keys from data it has read, for example when a row of a table arrives as a list and is used as a key without conversion."),
  (H, "Python asks a value for its hash with the built-in hash(). For strings, numbers and tuples this succeeds; for a list or a dictionary the answer is a TypeError. Whether a value is hashable can be asked without trying: isinstance(x, collections.abc.Hashable) is True for 'a', 1 and (1, 2) and False for [1] and {}. A class of the programmer's own that defines __eq__ and no __hash__ becomes unhashable, because Python sets its __hash__ to None [PSF]."),
  (K, "Hashable does not mean immutable in every case, and immutable does not guarantee hashable. A tuple is immutable, but a tuple that holds a list is not hashable, because hashing the tuple needs the hash of everything inside it; (1, [2]) is refused. The message differs between Python versions: the dictionary display in 3.14 says that a list cannot be used as a dict key, while hash() says unhashable type."),
 ]),
 ("HashValue", "Hash value", 3, "WhatMayBeAKey", ("hash('spam') and hash(1) == hash(1.0)", "A hash value is the whole number that Python computes from a hashable object; equal objects have equal hash values, and the number is used to decide where a key's pair is stored.", ("(hash(1) == hash(1.0) == hash(True), hash('ab') == hash('a' + 'b'), isinstance(hash('spam'), int))", "(True, True, True)")), [
  (W, "A hash value is a whole number computed from an object by the built-in hash(). It is a short fingerprint of the object: the same object always gives the same number during one run of the program, and objects that compare equal give the same number. The data model states the only required property: objects which compare equal have the same hash value [PSF]. Different objects may share a number, which is called a collision, and Python handles that case by comparing the keys themselves."),
  (Y, "The hash value is why looking up a key is fast. Instead of comparing the key with every key in the dictionary, Python computes its hash value, jumps to the place that the number points to and compares only the keys stored there. The cost of a lookup therefore does not grow with the size of the dictionary in the way a search through a list does, which is what lets the characterCount program work, as the chapter says, on strings of millions of characters [SW]."),
  (E, "The number is rarely seen, because Python uses it internally, but it can be printed. hash(1) equals hash(1.0) and equals hash(True), which is why those three values are one key. The hash of a string is salted with a random value when the interpreter starts, so hash('spam') is the same within a run and differs between runs [PSF]; the order of a dictionary does not depend on it, because insertion order is kept separately."),
  (H, "When a pair is stored, Python takes the hash of the key, reduces it to a position in its table and puts the pair there; when the key is looked up, it repeats the same computation. If the place is already taken by a different key, the collision rule moves on to another place. Equal objects must give equal hashes because otherwise the second computation would point somewhere else and the pair would not be found."),
  (K, "Do not use the number for anything but understanding. It is not a stable identifier: for strings it changes from one run to the next, so a program that stores hash('spam') in a file and reads it back later will not find a match. And do not write a __hash__ method that disagrees with __eq__, because a dictionary then loses pairs."),
 ]),
 ("TupleAsKey", "Tuple as a key", 3, "WhatMayBeAKey", ("grid = {(0, 0): 'start', (2, 3): 'goal'}", "A tuple of hashable items is hashable, so it can be a key where a list cannot; it is the book's replacement when a compound value such as a coordinate must identify a pair.", ("(lambda grid: (grid[(2, 3)], (0, 0) in grid, (1, 1) in grid))({(0, 0): 'start', (2, 3): 'goal'})", "('goal', True, False)")), [
  (W, "A tuple is an ordered, unchangeable group of values written with round brackets, such as (2, 3). Because it cannot change and its members are hashable, the tuple is hashable and can be a dictionary key. This is the replacement the chapter recommends: if a list is wanted as a key, use a tuple instead [SW]. A dictionary such as {(0, 0): 'start', (2, 3): 'goal'} identifies each pair by two numbers."),
  (Y, "Compound keys are everywhere in programs: a coordinate on a grid, a pair of a date and a place, a person's first and last name together. Without tuples a program would have to glue such parts into one string and take them apart again, which invites mistakes. A tuple keeps the parts separate and still works as a single key."),
  (E, "The chessboard of this chapter could have been keyed by (column, row) tuples instead of strings such as 'e3'; the book chose strings because they print well. Grids, maps, games and spreadsheets use tuple keys naturally, and the items method itself hands back (key, value) tuples."),
  (H, "To hash a tuple Python hashes each member and combines the results, so the tuple is hashable exactly when all its members are. Looking up (2, 3) therefore works, the tuple (1, [2]) is refused because its list member is not hashable, and the tuple (1, 2) is the same key as another tuple (1, 2) written elsewhere, because the two compare equal."),
  (K, "Remember the comma. (2, 3) is a tuple, but (2) is just the number 2 in brackets, and a one-item tuple is written (2,). Do not put a list inside a tuple that is meant to be a key, and remember that a tuple key cannot be changed in place: to move a point, build a new key and a new pair."),
 ]),
 ("EqualKeysShareASlot", "Equal keys share one slot", 3, "WhatMayBeAKey", ("{1: 'a', 1.0: 'b', True: 'c'}", "Keys that compare equal and have the same hash are one key, so 1, 1.0 and True name a single pair, which keeps the first key object and takes the last value.", ("{1: 'a', 1.0: 'b', True: 'c'}", "{1: 'c'}")), [
  (W, "Keys that compare equal and have the same hash value are the same key. The documentation says it plainly: values that compare equal, such as 1, 1.0 and True, can be used interchangeably to index the same dictionary entry [PSF]. A dictionary written as {1: 'a', 1.0: 'b', True: 'c'} therefore has one pair, and its value is the last one assigned, 'c'."),
  (Y, "This follows from the hashing rule and is the first place where it has a visible effect. A learner who counts values with a dictionary keyed by numbers will find that the integer 1 and the float 1.0 are counted together, and that a Boolean can silently merge with the integers 0 and 1. Knowing why avoids hunting for a bug that is really a feature of equality."),
  (E, "The effect appears when a program mixes types in one dictionary: counts keyed by values read from different sources, results of calculations that give 2.0 where another gives 2, a flag stored as True beside a column that holds 1. It never appears with strings, because a string never equals a number."),
  (H, "When Python stores {1: 'a', 1.0: 'b', True: 'c'}, it inserts 1 with 'a'; then 1.0 has the same hash and compares equal to 1, so the existing pair is updated to 'b' instead of a second one being added; then True does the same, leaving 'c'. The key object that stays is the first one, the integer 1, so next(iter(d)) is an int."),
  (K, "Do not treat the type of a key as part of its identity. If the distinction between 1 and True matters, store one of them as a string, or use a tuple that includes a tag, such as ('flag', True). Note also that nan, the not-a-number float, does not equal itself, so it behaves unlike any other key."),
 ]),
 ("AbsentKeys", "Absent keys", 2, "KeyRules", None, [
  (W, "Absent keys is the part of the branch that deals with a key that is not in the dictionary. The error that Python raises for it is KeyError, and the chapter compares it to the IndexError of a list: trying to access a key that does not exist results in a KeyError error message, much like a list's out-of-range IndexError [SW]."),
  (Y, "The error is the one a learner will meet most often with dictionaries, and its message is the key itself, which makes the cause easy to find once the message is read. The three tools that avoid the error, the in test, the get method and the setdefault method, are the next branch's first part."),
  (H, "One concept follows, the KeyError itself, with the chapter's own examples."),
 ], None),
 ("KeyErrorOnMissing", "KeyError", 3, "AbsentKeys", ("spam['color'] with spam = {'name': 'Zophie', 'age': 7}", "KeyError is the exception raised when a key is not in the dictionary; its message is the missing key as Python would write it, so the cause can be read off the last line of the traceback.", ("(lambda spam: [k in spam for k in ('name', 'color')])({'name': 'Zophie', 'age': 7})", "[True, False]")), [
  (W, "KeyError is the exception that a lookup raises when the key asked for is not in the dictionary. For spam = {'name': 'Zophie', 'age': 7}, the expression spam['color'] stops the program with a traceback that ends in KeyError: 'color' [SW]. An exception is a signal that something went wrong, which the program may catch with a try and except statement or leave to end the program; the error-handling chapter that precedes this one explains it."),
  (Y, "The message is the useful part. The text after KeyError is the key that was missing, written as Python would write it, so a quoted string shows as 'color' and an integer shows as 0. A learner who reads it knows at once whether the key was misspelled, in the wrong case or simply never added. The same message names the missing item in the chapter's picnic example, where picnic_items['eggs'] ends in KeyError: 'eggs' [SW]."),
  (E, "The error is met after typing mistakes in keys, after reading data whose fields differ from what the program expects, and after deleting a key and still using it. Programs that must keep running catch it with try and except KeyError, or avoid it with the in test, the get method or the setdefault method."),
  (H, "The lookup spam['color'] computes the hash of 'color', finds the place it points to, finds nothing equal to 'color' there and raises KeyError with the key as its single argument, so e.args is ('color',) and repr(e) is KeyError('color'). The test 'color' in spam performs the same search and answers True or False without raising, which is why testing first is the book's remedy [SW]."),
  (K, "KeyError says that the key was not found, and nothing else; it does not say what the nearest key is. A KeyError inside a loop does not tell which pass failed unless the program prints the key. Do not catch KeyError so broadly that a real bug in the program is hidden behind a quiet default."),
 ]),
]
CHECKS += [("[isinstance(x, __import__('collections.abc').abc.Hashable) for x in ('a', 1, 1.0, True, (1, 2), (1, [2]), [1], {}, {1})]", "[True, True, True, True, True, True, False, False, False]"),
           ("isinstance((1, [2]), __import__('collections.abc').abc.Hashable)", "True"),
           ("hash(1) == hash(1.0) == hash(True)", "True"), ("hash('ab') == hash('a' + 'b')", "True"), ("isinstance(hash('spam'), int)", "True"),
           ("hash((2, 3)) == hash((2, 3))", "True"), ("hash((1, 2)) == hash((2, 1))", "False"),
           ("(lambda grid: grid[(2, 3)])({(0, 0): 'start', (2, 3): 'goal'})", "'goal'"), ("type((2)).__name__", "'int'"), ("type((2,)).__name__", "'tuple'"),
           ("{1: 'a', 1.0: 'b', True: 'c'}", "{1: 'c'}"), ("type(next(iter({1: 'a', 1.0: 'b', True: 'c'}))).__name__", "'int'"),
           ("len({1: 'a', 1.0: 'b', True: 'c'})", "1"), ("float('nan') == float('nan')", "False"),
           ("(lambda spam: [k in spam for k in ('name', 'color')])({'name': 'Zophie', 'age': 7})", "[True, False]"),
           ("(lambda spam: (lambda e: (e.args, repr(e)))(__import__('builtins').KeyError('color')))({})", "(('color',), \"KeyError('color')\")"),
           ("(lambda c: (c['x'] if 'x' in c else 'absent'))({})", "'absent'"),
           ("len({__import__('subprocess').run([__import__('sys').executable, '-c', 'print(hash(\"spam\"))'], capture_output=True, text=True).stdout for _ in range(3)}) > 1", "True"),
           ("issubclass(KeyError, LookupError) and issubclass(IndexError, LookupError)", "True")]
RAISES += [("{[1, 2]: 'x'}", "TypeError"), ("{{}: 1}", "TypeError"), ("hash([1, 2])", "TypeError"), ("hash((1, [2]))", "TypeError"), ("{(1, [2]): 'x'}", "TypeError"),
           ("(lambda spam: spam['color'])({'name': 'Zophie', 'age': 7})", "KeyError"), ("(lambda picnic_items: picnic_items['eggs'])({'apples': 5, 'cups': 2})", "KeyError"),
           ("['a', 'b'][5]", "IndexError")]
CHECKS += [PROG("try:\n    {[1, 2]: 'x'}\nexcept TypeError as e:\n    print(e)\ntry:\n    hash([1, 2])\nexcept TypeError as e:\n    print(e)\n", "cannot use 'list' as a dict key (unhashable type: 'list')\nunhashable type: 'list'\n"),
           PROG("class P:\n    def __init__(self, v): self.v = v\n    def __eq__(self, o): return self.v == o.v\nprint(P.__hash__)\ntry:\n    {P(1): 'x'}\nexcept TypeError as e:\n    print(e)\n", "None\ncannot use 'P' as a dict key (unhashable type: 'P')\n"),
           PROG("spam = {'name': 'Zophie', 'age': 7}\ntry:\n    spam['color']\nexcept KeyError as e:\n    print(type(e).__name__ + ': ' + str(e))\n", "KeyError: 'color'\n"),
           PROG("picnic_items = {'apples': 5, 'cups': 2}\ntry:\n    'I am bringing ' + str(picnic_items['eggs']) + ' eggs.'\nexcept KeyError as e:\n    print(type(e).__name__ + ': ' + str(e))\n", "KeyError: 'eggs'\n")]

# ============================================================ Reading and changing pairs
RAW += [
 ("ReadingAndChanging", "Reading and changing pairs", 1, None, None, [
  (W, "Reading and changing pairs is the branch of the operations a program performs on a dictionary that already exists: looking a key up safely, adding a pair, replacing a value, removing a pair and combining dictionaries. The chapter teaches the first group in two subsections, Checking Whether a Key Exists and Setting Default Values, and the second group by example in its birthdays program and in the chessboard commands [SW]."),
  (Y, "Almost every program that uses a dictionary does these five things and little else. The difference between a program that crashes on unexpected data and one that does not is usually the choice among them: a subscript that raises, a get that returns a fallback, a setdefault that fills the gap, a pop that removes and reports. The chapter's own shortcut question, number 7 of the practice questions, asks the learner to pick the right one."),
  (E, "The operations are used in the first program of the chapter, birthdays.py, which reads a pair when the name is known and adds a pair when it is not, and again in the chessboard simulator, whose commands move, remove and set are a replacement, a deletion and an assignment of a pair."),
  (H, "The branch has three parts. Reading a pair covers the membership test, get and setdefault. Adding, replacing and removing covers assignment, del, pop, update with the merge operators, and fromkeys. A first program ties the reading and adding together in the birthdays program."),
 ], None),
 ("Reading", "Reading a pair", 2, "ReadingAndChanging", None, [
  (W, "Reading a pair is the part of the branch that asks what a dictionary holds without risking an error. There are three ways: the in test asks whether a key is present, the get method returns the value or a fallback, and the setdefault method returns the value and makes sure that a value is stored."),
  (Y, "Each of the three answers a different need. Asking whether a key is present is needed when the program branches on the answer. Wanting a value or a default is the common case of counting and reporting. Wanting a value that must exist afterwards is the common case of building up a collection. A learner who knows which need is at hand picks the matching tool and writes less code."),
  (H, "The three concepts follow in that order: the membership test on keys, the get method and the setdefault method. The birthdays program and the characterCount program show them at work in complete programs."),
 ], None),
 ("MembershipOnKeys", "Membership test on keys", 3, "Reading", ("'color' in spam", "The in and not in operators applied to a dictionary ask about its keys; 'color' in spam is the same question as 'color' in spam.keys(), and the values have a separate test, 'red' in spam.values().", ("(lambda spam: ('color' in spam, 'color' in spam.keys(), 'red' in spam, 'red' in spam.values(), 'age' not in spam.keys()))({'color': 'red', 'age': 42})", "(True, True, False, True, False)")), [
  (W, "The in and not in operators, applied to a dictionary, ask whether a key is present. The chapter says that in and not in with the dictionary value itself is equivalent to using them with the keys() method, so 'color' in spam and 'color' in spam.keys() both ask about keys [SW]. To ask about values, the operators are applied to the values() method: 'red' in spam.values() is True when some pair holds 'red'."),
  (Y, "The test is how a program avoids KeyError: it checks first and acts on the answer. The chapter's birthdays program is built around it, deciding with name in birthdays whether to print a known birthday or to ask for a new one [SW]. The same test appears in the chessboard's printing function, which asks whether x + y is a key of the board before looking the piece up."),
  (E, "Membership is used in conditions, in assertions about data, and in the validators of the practice programs. It is used in the two forms the chapter shows, with the dictionary itself and with a view. The form without a view is the one recommended in practice, because it is shorter and says exactly what it means."),
  (H, "For a dictionary, key in d computes the hash of the key, looks at the place it points to and answers True when an equal key is there; it never raises KeyError. For a view of the values, there is no hash to use, so Python compares the value against the values one after another until it finds one that is equal or runs out. The first test is a direct lookup and the second is a search."),
  (K, "The most common slip is to test for a value with the plain operator: 'red' in spam is False in the chapter's example, because red is a value and not a key. The reverse slip is to test a key against the values. Equal values may repeat, so 'red' in spam.values() says that at least one pair holds red, not which one."),
 ]),
 ("GetMethod", "The get method", 3, "Reading", ("picnic_items.get('eggs', 0)", "The get method takes a key and a fallback value and returns the value of the key, or the fallback when the key is absent, without raising and without changing the dictionary.", ("(lambda picnic_items: (picnic_items.get('cups', 0), picnic_items.get('eggs', 0), picnic_items.get('eggs'), 'eggs' in picnic_items))({'apples': 5, 'cups': 2})", "(2, 0, None, False)")), [
  (W, "The get method looks up a key and returns its value, or a fallback value when the key is absent. The chapter describes it as taking two arguments, the key of the value to retrieve and a fallback value to return if that key does not exist [SW]. With picnic_items = {'apples': 5, 'cups': 2}, picnic_items.get('cups', 0) is 2 and picnic_items.get('eggs', 0) is 0, where picnic_items['eggs'] would have raised KeyError."),
  (Y, "Get removes the need for a test before the lookup. The chapter notes that checking for the existence of a key before accessing it prevents a program from crashing, and that checking by hand is tedious [SW]. A single call both tests and reads, so the programs that total, report or display values stay short and keep running on incomplete data."),
  (E, "The picnic program of the chapter uses get inside total_brought: v.get(item, 0) adds the quantity when the guest brings the item and zero when not. Get is used for configuration settings with defaults, for optional fields of a record, and for counting before the Counter class is known."),
  (H, "Get does the same search as the subscript. If the key is found it returns the stored value; if not, it returns the second argument, which is None when the second argument is left out, so the method never raises KeyError [PSF]. It does not store the fallback, so after picnic_items.get('eggs', 0) the key 'eggs' is still absent."),
  (K, "A fallback is not a promise that the data is right. A missing key that should have been there is silently turned into a zero or a None, and the program carries on with a wrong total. Use the subscript when absence is a real error and get when absence is a normal case. And remember that get does not add the key: counting needs setdefault or an assignment."),
 ]),
 ("SetdefaultMethod", "The setdefault method", 3, "Reading", ("spam.setdefault('color', 'black')", "The setdefault method stores a default value under a key only if the key is not yet there, and in every case returns the value now stored.", ("(lambda spam: (spam.setdefault('color', 'black'), spam.setdefault('color', 'white'), spam))({'name': 'Pooka', 'age': 5})", "('black', 'black', {'name': 'Pooka', 'age': 5, 'color': 'black'})")), [
  (W, "The setdefault method sets a key only if it does not already have a value, and hands back whatever is stored afterwards. The chapter explains the arguments: the first is the key to check for, and the second is the value to set at that key if the key does not exist; if the key does exist, the method returns the key's value [SW]. For spam = {'name': 'Pooka', 'age': 5}, the first call spam.setdefault('color', 'black') adds the pair and returns 'black', and the second call with 'white' changes nothing and again returns 'black'."),
  (Y, "Setdefault is the one-line form of a pattern that every beginner writes in three lines: if the key is not in the dictionary, assign a starting value; then use the key. The chapter shows the three-line version first and calls the method a nice shortcut to ensure that a key exists [SW]. Its value is that code after the call may assume the key is there, as the characterCount program does when it adds one to a count that might not exist yet."),
  (E, "Setdefault is used to start a counter at zero, to start a list for a group, and to fill in optional settings without overwriting the ones the user chose. In characterCount.py it appears as count.setdefault(character, 0) inside the loop; in grouping programs it appears as groups.setdefault(key, []).append(value)."),
  (H, "The method searches for the key once. If it finds the key, it returns the stored value and does nothing else. If not, it inserts the key with the default and returns the default. The method can change the dictionary, which is the difference from get: after spam.setdefault('color', 'black') the dictionary has three pairs, and it is the returned value, not the dictionary, that the expression is worth."),
  (K, "The default value is built every time the call is written, even when the key exists and the new value is discarded. With a list as a default, setdefault(key, []) creates an empty list on every call and throws away all but the first; for a large loop, a defaultdict is cheaper. Do not expect setdefault to replace an existing value; for that, assign."),
 ]),
 ("Changing", "Adding, replacing and removing", 2, "ReadingAndChanging", None, [
  (W, "Adding, replacing and removing is the part of the branch that changes a dictionary. A dictionary is mutable, so it can be changed in place: a new key adds a pair, an existing key has its value replaced, and a pair can be deleted by key, either with the del statement or with the pop method, which also reports the value it removed."),
  (Y, "Changing data is what makes a dictionary a model of something that moves. The chessboard simulator models a game by exactly three of these operations, and the inventory exercises of the chapter's end model a player's possessions by adding and counting. The same operations underlie every program that keeps state."),
  (H, "Five concepts follow. Adding or replacing a pair by assignment. The del statement. The pop method. The update method and the merge operators that came with Python 3.9. The fromkeys method, which builds a dictionary from a list of keys."),
 ], None),
 ("AddOrReplacePair", "Adding or replacing a pair", 3, "Changing", ("birthdays[name] = bday", "Assigning to a key with square brackets adds a pair when the key is new and replaces the value when the key exists; a new key goes at the end, and a replaced key keeps its place.", ("(lambda d: (d.__setitem__('Eve', 'Dec 5'), d.__setitem__('Bob', 'Dec 13'), list(d.items()), len(d))[2:])({'Alice': 'Apr 1', 'Bob': 'Dec 12'})", "([('Alice', 'Apr 1'), ('Bob', 'Dec 13'), ('Eve', 'Dec 5')], 3)")), [
  (W, "Assignment with square brackets, d[key] = value, writes a pair. If the key is new, the pair is added; if the key already exists, its value is replaced. The birthdays program uses it in its last branch: when a name is unknown, it asks for the birthday and stores it with birthdays[name] = bday, after which the same name is found [SW]. The chessboard's set command is the same operation, main_board[response[1]] = response[2]."),
  (Y, "One statement serves two purposes, which keeps programs short, but the program must know which of the two it intends. For a database of birthdays the difference is the difference between adding a friend and correcting a date. The pair that is added is also visible to every other name that refers to the same dictionary, since the dictionary is changed in place."),
  (E, "Assignment of pairs is the most frequent change made to a dictionary: filling a record field by field, recording a result for each name, updating a count. It is also how the program of the chapter remembers new data, although, as the chapter says, all the data entered in this program is forgotten when the program terminates, and saving it to a file is the subject of a later chapter [SW]."),
  (H, "Python looks for the key. When it is absent, a new pair is appended at the end of the order; when it is present, only the value is replaced, and the key keeps its original position. With birthdays of Alice and Bob, assigning Eve puts her third, and assigning Bob again changes his date without moving him; the dictionary then has three pairs."),
  (K, "A typing mistake in a key does not raise an error on assignment; it quietly adds a new pair under the misspelt key and leaves the right one untouched. A program that sets d['colour'] when it meant d['color'] will later read the old value. Print the dictionary or use a TypedDict when a record has fixed keys."),
 ]),
 ("DeletePair", "The del statement", 3, "Changing", ("del main_board[response[1]]", "The del statement removes a key and its value from a dictionary, and raises KeyError when the key is not there; the chessboard's remove command and the second half of its move command are del statements.", ("(lambda main_board: (main_board.__setitem__('e4', main_board['e2']), main_board.__delitem__('e2'), sorted(main_board))[2])({'e2': 'wP', 'e1': 'wK'})", "['e1', 'e4']")), [
  (W, "The del statement removes a pair from a dictionary by its key. In the chessboard simulator, the remove command is del main_board[response[1]], which makes a piece disappear from the board by deleting the pair at its square [SW]. The statement raises KeyError when the key is not present, so deleting the same square twice fails the second time."),
  (Y, "Deleting is half of every move in the chessboard model. The book moves a piece by first copying the piece from the old square to the new key and then deleting the old key, which has the effect of making it seem like the piece has moved [SW]. Because an empty square is represented by an absent key, removing the pair is exactly the same thing as emptying the square, which is why the model needs no special value for emptiness."),
  (E, "The del statement is used for removing a record, for clearing a flag, for forgetting a cached value. It is a statement and not an expression: it can stand on a line of its own but cannot be part of a larger expression, and it gives no value back. When the removed value is wanted, the pop method is the tool."),
  (H, "Python looks up the key and, if it finds it, removes the pair, leaving the order of the others unchanged. In the move command the order of the two steps matters: the piece is copied to the new key first, main_board[response[2]] = main_board[response[1]], and only then is the old key deleted. After moving e2 to e4 in a small board, the sorted keys are 'e1' and 'e4', and 'e2' no longer exists."),
  (K, "Deleting a key that is not present raises KeyError, so a program that deletes on request should test first or use pop with a default. Do not delete keys from a dictionary while looping over it, since that changes its size during iteration; collect the keys in a list first. And note that del removes only the pair, not the value object, which lives on if another name refers to it."),
 ]),
 ("PopMethod", "The pop method", 3, "Changing", ("d.pop('e2', None)", "The pop method removes a key and returns its value; with a second argument it returns that default instead of raising KeyError when the key is absent, and popitem removes and returns the most recently added pair.", ("(lambda d: (d.pop('e2'), d.pop('e2', None), d.popitem(), d))({'a1': 'wR', 'e2': 'wP', 'h8': 'bR'})", "('wP', None, ('h8', 'bR'), {'a1': 'wR'})")), [
  (W, "The pop method removes a key from a dictionary and returns the value it held. The documentation defines it: if the key is in the dictionary, remove it and return its value, else return the default; if the default is not given and the key is not present, a KeyError is raised [PSF]. Its relative popitem removes and returns a pair, the most recently added one, in last-in first-out order, and raises KeyError when the dictionary is empty."),
  (Y, "Pop combines a read and a delete in one step, so the program cannot read a value and then forget to remove it, nor remove it and lose it. With a default it also removes the risk that del has: d.pop(key, None) deletes the pair if there is one and does nothing otherwise. The chessboard's move command could be written as main_board[new] = main_board.pop(old), a single line."),
  (E, "Pop is used for taking an item from a collection of pending work, for removing a setting after it has been read, and for undoing the last change when it is used through popitem. In the chessboard model it is the natural form of a capture."),
  (H, "Python finds the key, takes the value out of the table, removes the pair and returns the value. Called with a missing key and a default, it returns the default and leaves the dictionary as it was. On {'a1': 'wR', 'e2': 'wP', 'h8': 'bR'}, pop('e2') returns 'wP', a second pop('e2', None) returns None, and popitem() then returns ('h8', 'bR') because that was the last pair added."),
  (K, "The last-in first-out order of popitem has been guaranteed only since Python 3.7; before that an arbitrary pair was returned. Do not use pop to read a value that must stay in the dictionary. And do not forget that pop with one argument raises KeyError for a missing key, exactly as the subscript does."),
 ]),
 ("UpdateAndMerge", "update and the merge operators", 3, "Changing", ("defaults | overrides", "The update method copies the pairs of another mapping into a dictionary, and since Python 3.9 the operator | builds a new merged dictionary and |= updates in place; in every case the right-hand values win where the keys clash.", ("(lambda defaults, overrides: (defaults | overrides, {**defaults, **overrides}, defaults))({'x': 1, 'y': 2}, {'y': 20})", "({'x': 1, 'y': 20}, {'x': 1, 'y': 20}, {'x': 1, 'y': 2})")), [
  (W, "To update a dictionary is to copy the pairs of another mapping, or of a list of pairs, into it, overwriting any key that already exists. The documentation gives the update method for the change in place, and the operators d | other and d |= other, added in Python 3.9 by PEP 584, for the merge: | creates a new dictionary containing the keys and values of both, and |= updates the left dictionary; in both, the values of the right-hand operand take priority when the keys are shared [PSF] [PEP584]."),
  (Y, "Merging is how defaults and overrides are combined, how records from two sources are joined, and how a program builds one dictionary out of several without a loop. The older spelling {**a, **b}, which unpacks both dictionaries into a new display, does the same job, and PEP 448 added it in Python 3.5 [PEP448]. The new operators give the idea a name that reads like arithmetic."),
  (E, "Update is used to load settings over defaults, to add a batch of results to a running total of results, and to copy a template's fields into a new record. The chapter itself does not teach it; its programs add pairs one at a time with square brackets, which is the same effect on a smaller scale."),
  (H, "With defaults = {'x': 1, 'y': 2} and overrides = {'y': 20}, defaults | overrides is {'x': 1, 'y': 20}, a new dictionary, and defaults is unchanged; defaults |= overrides would change defaults itself. Python walks the right-hand pairs in order and stores each one, so a clashing key takes the right-hand value and stays at its original position."),
  (K, "The merge is shallow: when the values are themselves dictionaries, the inner dictionaries are not merged, only replaced. The operator | needs dictionaries on both sides, whereas update and |= also accept a list of pairs. And the update method returns None, so writing d = d.update(other) throws the dictionary away."),
 ]),
 ("FromkeysMethod", "The fromkeys method", 3, "Changing", ("dict.fromkeys('abc', 0)", "The class method dict.fromkeys builds a dictionary whose keys are the items of an iterable, all with one starting value; with a mutable value such as a list, every key shares that one object.", ("(dict.fromkeys('abc', 0), (lambda d: d['a'] is d['b'])(dict.fromkeys('ab', [])))", "({'a': 0, 'b': 0, 'c': 0}, True)")), [
  (W, "The fromkeys method creates a new dictionary from an iterable of keys and one value. dict.fromkeys('abc', 0) takes the characters of the string as keys and gives each the value 0, so the result is {'a': 0, 'b': 0, 'c': 0}. The documentation notes that fromkeys is a class method that returns a new dictionary, that the value defaults to None, and that all the values refer to just a single instance [PSF]."),
  (Y, "It is the quick way to make a table of counters, a set of flags or a checklist of keys that all start in the same state. A program that must begin with a known list of keys, such as the five kinds of chess piece, can build the dictionary in one expression instead of a loop of assignments."),
  (E, "Typical uses are a counter dictionary initialised to zero, a membership table where the values do not matter, and a way of removing duplicates while keeping order: list(dict.fromkeys(items)) keeps the first occurrence of every item, because keys are unique and ordered by insertion."),
  (H, "Python creates an empty dictionary and, for every item of the iterable, inserts that item as a key with the same value object. For a number or a string that is harmless, because the object cannot change. For a list it is a trap: dict.fromkeys('ab', []) gives both keys the very same list, so d['a'] is d['b'] is True, and appending to one appends to both."),
  (K, "The documentation's own advice for distinct mutable values is a dictionary comprehension: {k: [] for k in 'ab'} builds a new list for every key. Remember also that fromkeys is called on the dict class and not on an existing dictionary, and that it never changes a dictionary in place."),
 ]),
 ("FirstProgram", "A first program", 2, "ReadingAndChanging", None, [
  (W, "A first program is the chapter's first complete use of a dictionary: birthdays.py, a small database of friends' birthdays held in memory. It is placed after the single operations because it combines three of them, a test with in, a lookup with square brackets and an assignment that adds a pair."),
  (Y, "A complete program shows what the separate operations are for. The learner sees a dictionary used as a lookup table whose content changes while the program runs, and sees the honest limit of the design: the data is forgotten when the program ends."),
  (H, "One concept follows, the birthdays program, executed with the book's own sequence of inputs."),
 ], None),
 ("BirthdayLookup", "The birthdays program", 3, "FirstProgram", ("birthdays.py", "The birthdays program keeps names as keys and birthdays as values in a dictionary, looks a typed name up with in and square brackets, and adds a pair for an unknown name.", ("(lambda birthdays, name: birthdays[name] + ' is the birthday of ' + name if name in birthdays else 'I do not have birthday information for ' + name)({'Alice': 'Apr 1', 'Bob': 'Dec 12', 'Carol': 'Mar 4'}, 'Alice')", "'Apr 1 is the birthday of Alice'")), [
  (W, "The birthdays program stores the birthdays of friends in a dictionary whose keys are names and whose values are dates: {'Alice': 'Apr 1', 'Bob': 'Dec 12', 'Carol': 'Mar 4'}. It asks for a name in a loop that ends on a blank answer; a known name prints its birthday, and an unknown name leads to a question and a new pair [SW]. It is the chapter's first example of a dictionary that changes while a program runs."),
  (Y, "The program shows the three operations of the branch at work in a handful of lines. The test name in birthdays decides between lookup and addition; birthdays[name] reads a value; birthdays[name] = bday writes one. Without a dictionary the same program would need a list of names, a list of dates and a search to link them, and would be longer and slower."),
  (E, "The pattern is the pattern of every lookup table: a phone book, a price list, a glossary, a login table. The program as printed runs in the console with the sequence of inputs Alice, Eve, Dec 5, Eve and a blank line, and its output is the transcript printed in the book: the known birthday of Alice, the question about Eve, the confirmation, and then Eve's new birthday found in the dictionary."),
  (H, "The program starts with the dictionary and loops forever until the blank answer ends it with break. Each pass prints the prompt, reads a name, and branches on name in birthdays. In the first branch it prints birthdays[name] joined with the text; in the second it prints two messages, reads bday with input and stores it. Since the same dictionary object lives through the whole loop, the second request for Eve finds the pair that was added in the first."),
  (K, "All the data entered is forgotten when the program ends, as the chapter says, because the dictionary lives only in memory [SW]. The names are case sensitive, so alice is not Alice and starts a new pair. A real program would also strip spaces from the typed name before using it as a key."),
 ]),
]
CHECKS += [("(lambda spam: ('color' in spam, 'color' in spam.keys()))({'color': 'red', 'age': 42})", "(True, True)"),
           ("(lambda spam: 'red' in spam)({'color': 'red', 'age': 42})", "False"),
           ("(lambda picnic_items: 'I am bringing ' + str(picnic_items.get('cups', 0)) + ' cups.')({'apples': 5, 'cups': 2})", "'I am bringing 2 cups.'"),
           ("(lambda picnic_items: 'I am bringing ' + str(picnic_items.get('eggs', 0)) + ' eggs.')({'apples': 5, 'cups': 2})", "'I am bringing 0 eggs.'"),
           ("(lambda picnic_items: (picnic_items.get('eggs'), len(picnic_items)))({'apples': 5, 'cups': 2})", "(None, 2)"),
           ("(lambda spam: (spam.setdefault('color', 'black'), spam))({'name': 'Pooka', 'age': 5})", "('black', {'name': 'Pooka', 'age': 5, 'color': 'black'})"),
           ("(lambda spam: (spam.setdefault('color', 'black'), spam.setdefault('color', 'white'), spam))({'name': 'Pooka', 'age': 5})", "('black', 'black', {'name': 'Pooka', 'age': 5, 'color': 'black'})"),
           ("(lambda spam: (len(spam), spam.setdefault('color', 'black'), len(spam)))({'name': 'Pooka', 'age': 5})", "(2, 'black', 3)"),
           ("(lambda b: (b.__setitem__('e4', b['e2']), b.__delitem__('e2'), b)[2])({'e2': 'wP', 'e1': 'wK'})", "{'e1': 'wK', 'e4': 'wP'}"),
           ("(lambda d: (d.pop('e2'), d.pop('e2', None), d.popitem(), d))({'a1': 'wR', 'e2': 'wP', 'h8': 'bR'})", "('wP', None, ('h8', 'bR'), {'a1': 'wR'})"),
           ("(lambda b: (b.__setitem__('e4', b.pop('e2')), b)[1])({'e2': 'wP', 'e1': 'wK'})", "{'e1': 'wK', 'e4': 'wP'}"),
           ("(lambda a, b: (a | b, a))({'x': 1, 'y': 2}, {'y': 20})", "({'x': 1, 'y': 20}, {'x': 1, 'y': 2})"),
           ("(lambda a, b: ({**a, **b} == a | b))({'x': 1, 'y': 2}, {'y': 20})", "True"),
           ("(lambda a: (a.__ior__([('b', 2)]) is a, a))({'a': 1})", "(True, {'a': 1, 'b': 2})"),
           ("(lambda d: (d.update({'x': 1}, y=2), d)[1])({})", "{'x': 1, 'y': 2}"), ("(lambda d: d.update({'x': 1}))({})", "None"),
           ("(lambda a, b: (a | b, {'k': {'a': 1}} | {'k': {'b': 2}}))({}, {})", "({}, {'k': {'b': 2}})"),
           ("dict.fromkeys('abc', 0)", "{'a': 0, 'b': 0, 'c': 0}"), ("dict.fromkeys('ab')", "{'a': None, 'b': None}"),
           ("(lambda d: d['a'] is d['b'])(dict.fromkeys('ab', []))", "True"),
           ("(lambda d: (d['a'].append(1), d)[1])(dict.fromkeys('ab', []))", "{'a': [1], 'b': [1]}"),
           ("{k: [] for k in 'ab'}", "{'a': [], 'b': []}"), ("(lambda d: d['a'] is d['b'])({k: [] for k in 'ab'})", "False"),
           ("list(dict.fromkeys(['b', 'a', 'b', 'c', 'a']))", "['b', 'a', 'c']"),
           ("(lambda d: (d.__setitem__('Eve', 'Dec 5'), d.__setitem__('Bob', 'Dec 13'), list(d), len(d))[2:])({'Alice': 'Apr 1', 'Bob': 'Dec 12'})", "(['Alice', 'Bob', 'Eve'], 3)"),
           ("(lambda d: (d.setdefault('k', []).append(1), d.setdefault('k', []).append(2), d)[2])({})", "{'k': [1, 2]}"),
           PROG(BIRTHDAYS, BIRTHDAYS_OUT, inp=BIRTHDAYS_INPUT)]
RAISES += [("(lambda d: d.__delitem__('zz'))({'a': 1})", "KeyError"), ("(lambda d: d.pop('x'))({})", "KeyError"), ("{}.popitem()", "KeyError"),
           ("{'a': 1} | [('b', 2)]", "TypeError"), ("(lambda d: d.__delitem__('e2'))({'e1': 'wK'})", "KeyError")]
CHECKS += [PROG("d = {}\ntry:\n    del d['zz']\nexcept KeyError as e:\n    print(type(e).__name__ + ': ' + str(e))\ntry:\n    d.popitem()\nexcept KeyError as e:\n    print(type(e).__name__ + ': ' + str(e))\n", "KeyError: 'zz'\nKeyError: 'popitem(): dictionary is empty'\n")]
