#!/usr/bin/env python3
"""SEN0414 chapter 6 (Lists) - corpus text, part B, version 1.0.0: the branch 'Searching and ordering'.

Same contract as part A: connected prose, citation tokens resolved by the corpus, and every number, output and error message
quoted in a paragraph listed in CHECKS or RAISES (executed by sen0414_ch06_corpus_v1_0_0.py under python3.14 and 3.13).
"""
__version__ = "1.0.0"
from sen0414_ch06_helpers_v1_0_0 import W, Y, E, H, K, C, PROG, VPROG

RAW = []
CHECKS = []
RAISES = []

RAW += [
 ("SearchingOrdering", "Searching and ordering", 1, None, None, [
  (W, "Once a list holds many items, a program needs to ask questions of it and to arrange it: is this value in the list, where is it, which item comes first. This branch explains the methods that answer such questions and put the items in order. It starts with what a method is, then covers the in and not in operators, the index method and the short-circuiting of the Boolean operators that lets a program test before it reads, and it ends with sorting and reversing [SW]."),
  (Y, "Searching and ordering are the two services that people ask of a collection more than any other. A phone book is useful because a name can be found and because the names are in order. The same two services make a list of results, names or readings usable by a program, and the chapter's rule about which of these operations change the list and which give a new value is a rule the rest of the course relies on."),
  (E, "The operators and methods of this branch appear in programs that check input against a list of allowed words, in programs that look up the position of a record, and in programs that sort the lines of a report. The sorted lists of file names that the file chapters return, and the ordered rows that the spreadsheet chapters write, come from the same operations [PSF]."),
  (H, "The branch has three groups. The first explains what a method is and why a method belongs to one data type. The second, searching, explains in, not in, index and the short-circuit rule. The third, ordering, explains sort with its key and reverse arguments, reverse, and the built-in function sorted that returns a new list and leaves the original alone."),
 ], None),
 ("Methods", "Calling methods", 2, "SearchingOrdering", None, [
  (W, "A method is the same thing as a function, except that it is called on a value [SW]. This group has one concept, the list method, which is the form in which almost every operation of this branch and of the previous one is written: the value, a period, the name and the arguments."),
  (Y, "Methods are how the data types of Python carry their own operations. A learner who understands that spam.index('hello') is a function that is tied to the list in spam can read every later method, of strings, of dictionaries and of files, in the same way."),
  (H, "The concept shows the call, explains the idea of a function that is always associated with a value, and shows the error that follows when a method is called on a value of the wrong type."),
 ], None),
 ("Method", "Method", 3, "Methods", ("spam.index('hello')", "A method is a function that is called on a value, written value.name(arguments); each data type has its own methods, and calling a list method on a string raises an AttributeError.", ("['hello', 'hi'].index('hello')", "0")), [
  (W, "A method is the same thing as a function, except it is called on a value. A list stored in spam is searched with the index method by writing spam.index('hello'): the method part comes after the value, separated by a period [SW]. Each data type has its own set of methods, and the list type has several for finding, adding, removing and otherwise manipulating the values in a list. The chapter asks the reader to think of a method as a function that is always associated with a value; the function would hypothetically be index(spam, 'hello'), but since index is a list method and not a function in general, it is written after the value."),
  (Y, "The notation tells the reader at a glance which value an operation works on, and it keeps the operations of a type together. A programmer who wants to know what can be done with a list asks the list: the documentation lists the methods of the mutable sequence types in one place, and the built-in function dir shows the names [PSF]. Because the method belongs to the value, the same word can mean different things for different types, as index does for a list and for a string."),
  (E, "In the executed examples ['hello', 'hi'].index('hello') is 0. Methods belong to a single data type: the methods append and insert are list methods and can be called on list values only, not on strings or integers. The expression 'hello'.append('world') raises an AttributeError whose message is 'str' object has no attribute 'append', and the integer 42 raises the message 'int' object has no attribute 'insert' when insert is called on it [SW]."),
  (H, "When Python meets spam.index('hello') it evaluates spam, looks for the name index in the type of that value, and calls what it finds with the value as the first argument and the other arguments after it. This is why the hypothetical function index(spam, 'hello') of the chapter is a faithful picture: the method call and the function call do the same work, and the type of the value decides which function is found. If the type has no such name, the lookup fails with an AttributeError."),
  (K, "Two slips belong here. The first is to call a list method on something that is not a list, usually because an earlier step returned a string or None; the AttributeError names the type, and the type in the message is the first clue. The second is to leave out the parentheses: spam.append is a bound method object and not a call, and nothing is appended. The chapter on functions explains the parentheses; here it is enough to check that every method call has them."),
 ]),
 ("Searching", "Searching a list", 2, "SearchingOrdering", None, [
  (W, "Searching a list means asking where a value is or whether it is there. The group has three concepts: the in and not in operators that answer yes or no, the index method that answers with a position, and the short-circuiting of and and or that lets a program ask a question about an item only when the item exists. The chapter teaches in, not in and index, and then short-circuiting [SW]."),
  (Y, "A list that cannot be searched is only a pile. Almost every program that checks a user's input, looks up a record or avoids a duplicate begins with one of these questions. They also teach, in the order of the group, how Python reports a failed search: in answers with False, and index answers with an error."),
  (H, "The first concept explains in and not in with the pet-name program. The second explains index and its first-match rule, and the third explains how len(spam) > 0 and spam[0] == 'cat' stays safe on an empty list."),
 ], None),
 ("Membership", "in and not in operators", 3, "Searching", ("'howdy' in ['hello', 'hi', 'howdy', 'heyas']", "The in operator gives True if a value equals an item of the list and False otherwise, and not in gives the opposite.", ("'howdy' in ['hello', 'hi', 'howdy', 'heyas']", "True")), [
  (W, "You can determine whether a value is or is not in a list with the in and not in operators. Like other operators they occur in expressions and connect two values: a value to look for and the list where it may be found. The expression evaluates to a Boolean value [SW]. With spam holding ['hello', 'hi', 'howdy', 'heyas'], 'howdy' in spam is True, 'cat' in spam is False, 'howdy' not in spam is False and 'cat' not in spam is True. The documentation says that x in s is True if an item of s is equal to x, and False otherwise [PSF]."),
  (Y, "A yes or no question about a collection is the commonest test in a program, and the operator reads like the English sentence. It also replaces a loop: without in, a program would walk the list item by item and compare each with the value, and with in the walk is done inside Python. The same operator works on strings, on tuples, on ranges and, in the next chapter, on dictionaries, so it is one of the most widely reused ideas of the course."),
  (E, "The chapter's program myPets.py keeps my_pets = ['Zophie', 'Pooka', 'Fat-tail'], asks for a pet name with input, and prints I do not have a pet named Footfoot when the name is not in the list, and the name followed by is my pet when it is. In the executed run, the entry Footfoot gives exactly the first message. The test is by equality, not by identity: 1 in [1.0] is True because 1 == 1.0. On strings the same operator tests for a substring, so 'ab' in 'cabd' is True although 'ab' in ['cabd'] is False."),
  (H, "Python compares the value with the items from the first to the last, using ==, and stops at the first match. The time it takes therefore grows with the length of the list, and a membership test on a long list that is made again and again in a loop is a known source of slow programs; the data structures of a later chapter answer the question in constant time. The result is always a Boolean, so the operator can be used directly in an if statement."),
  (K, "Keep in mind that the not in operator is distinct from the Boolean not operator [SW]. The expression not x in spam is read as not (x in spam) and gives the same answer as x not in spam, but the second form reads as one test and is the one programmers write. A second slip is to test a list with a value of another type, for example the string '3' against a list of integers, which is simply False and raises no error, so a surprising False should be checked for a type mismatch before the list is doubted."),
 ]),
 ("IndexMethod", "index method", 3, "Searching", ("spam.index('Pooka')", "The index method returns the index of the first item equal to the value and raises a ValueError if there is none.", ("['Zophie', 'Pooka', 'Fat-tail', 'Pooka'].index('Pooka')", "1")), [
  (W, "List values have an index method that can be passed a value. If that value exists in the list, the method returns the index of the value; if it is not in the list, Python produces a ValueError [SW]. With spam holding ['hello', 'hi', 'howdy', 'heyas'], spam.index('hello') is 0 and spam.index('heyas') is 3. When the list contains duplicates of the value, the method returns the index of its first appearance: for ['Zophie', 'Pooka', 'Fat-tail', 'Pooka'] it returns 1 for 'Pooka' and not 3."),
  (Y, "The operator in says that a value is there, and the method index says where. The position is what a program needs in order to replace the item, to delete it with del or to look at its neighbours. The two together make the usual search idiom: ask with in, and only then ask with index, so that the failure case is handled before it can raise an error."),
  (E, "In the executed examples the index of 'hello' is 0, the index of 'heyas' is 3 and the first 'Pooka' is at 1. The method accepts a start and an end as optional arguments, so ['a', 'b', 'a'].index('a', 1) is 2: the search starts at position 1 and finds the second 'a'. Searching for a value that is absent, as with spam.index('howdy howdy howdy'), raises a ValueError. Under Python 3.14 the message is list.index(x): x not in list, whereas Python 3.12 and 3.13, like the printed chapter, give the older wording 'howdy howdy howdy' is not in list."),
  (H, "The method compares the value with the items from the start position onward, using ==, and returns the position of the first one that matches; if it reaches the end it raises the error. Like in, it takes time proportional to the length of the list. It returns a number, so the answer can be used as an index at once, which is the reason the method raises an error rather than returning a special value: a returned -1 would be a valid index that means the last item [PSF]."),
  (K, "The error is the point of the method and must be planned for. A program that calls index on a value that may be missing should test with in first, or catch the ValueError with try and except, which the later chapter on errors explains. Do not forget the first-match rule: a list with duplicates has several positions for the same value, and index gives only the first. To find all of them, loop with enumerate, which is explained in the branch on loops."),
 ]),
 ("ShortCircuit", "Short-circuiting", 3, "Searching", ("len(spam) > 0 and spam[0] == 'cat'", "The operators and and or stop as soon as the left operand decides the result and do not evaluate the right operand, so a test on the left can guard an expression on the right.", ("(lambda spam: len(spam) > 0 and spam[0] == 'cat')([])", "False")), [
  (W, "Boolean operators have a subtle behaviour that is easy to miss. If either value combined by and is False the whole expression is False, and if either value combined by or is True the whole expression is True. For the expression False and spam it does not matter whether spam is True or False, because the answer is already False; Python uses this fact to skip the right-hand side altogether. This shortcut is called short-circuiting [SW]. The reference states the rule exactly: x and y evaluates x first and, if x is false, returns it, otherwise evaluates y [PSF]."),
  (Y, "Short-circuiting is more than a speed-up, and the chapter shows why on a list. A program that reads the first item of a list that may be empty would fail with an IndexError. Putting the question whether the list has any items on the left of an and makes the right side run only when it is safe. The pattern guard and then use is one of the most common in real programs, and it turns a crash into a quiet False."),
  (E, "The chapter's first version reads spam[0] == 'cat' directly, and for spam = ['cat', 'dog'] it prints A cat is the first item. For the empty list the same line raises an IndexError, and the corrected condition len(spam) > 0 and spam[0] == 'cat' evaluates to False and so prints The first item is not a cat. In the executed examples the guarded condition gives False for [] and True for ['cat', 'dog'], and the expression True or [][0] is True without any error, since or also stops early."),
  (H, "For and, Python evaluates the left operand and, if it is false, returns that operand without looking at the right one; if it is true, the result is the right operand. For or the rule is mirrored: a true left operand is returned and the right is skipped. The operators return one of their operands, not necessarily True or False, so [] and 5 is [] and [] or 5 is 5. The empty list counts as false, as do the empty string and zero, which is why many programmers write if spam: where the chapter writes if len(spam) > 0."),
  (K, "The order of the operands matters, and the guard must come first: spam[0] == 'cat' and len(spam) > 0 still raises the error. A second trap is to put an expression with a side effect, such as a call that changes a list, on the right of and or or and to forget that it may never run. Keep the right operand free of side effects, or use an if statement when the order of actions matters."),
 ]),
 ("Ordering", "Ordering a list", 2, "SearchingOrdering", None, [
  (W, "Ordering a list means putting its items in a sequence by comparison: numbers from small to large, strings from first to last in the dictionary. The group has four concepts: the sort method, its key and reverse arguments, the reverse method, and the function sorted that gives a new ordered list. The chapter teaches sort and reverse [SW], and the documentation adds the function sorted [PSF]."),
  (Y, "Sorted data is easier for people to read and for programs to search, to merge and to compare. The group also brings the first clear case in the course of a design choice that runs through Python: a method that changes a list in place returns None, while a function that makes a new list returns it."),
  (H, "The first concept explains sort and its three cautions: it works in place, it cannot compare numbers with strings, and it orders strings by their character codes. The second explains key and reverse, the third reverse, and the fourth sorted."),
 ], None),
 ("SortMethod", "sort method", 3, "Ordering", ("spam.sort()", "The sort method orders the items of the list in place, from small to large, and returns None; it cannot compare numbers with strings and orders strings by character code.", ("(s := [2, 5, 3.14, 1, -7], s.sort(), s)[2]", "[-7, 1, 2, 3.14, 5]")), [
  (W, "You can sort lists of number values or lists of strings with the sort method. It returns the numbers in numerical order and the strings in alphabetical order; with spam holding [2, 5, 3.14, 1, -7], the call spam.sort() leaves [-7, 1, 2, 3.14, 5], and with ['Ants', 'Cats', 'Dogs', 'Badgers', 'Elephants'] it leaves ['Ants', 'Badgers', 'Cats', 'Dogs', 'Elephants'] [SW]. The documentation adds that the method modifies the sequence in place for economy of space when sorting a large sequence, and that it returns None to remind the reader that it works by side effect [PSF]."),
  (Y, "The chapter lists three things to note about sort, and each of them is a lesson about the language. The method works in place, so it teaches the difference between changing a list and making one. It needs items that can be compared, so it teaches that Python does not guess. And it orders strings by character code, so it teaches that a computer's idea of alphabetical order is not a person's. A student who understands these three points will not be surprised by most sorting problems."),
  (E, "In the executed examples, spam = spam.sort() leaves spam equal to None, because sort returns None after it has sorted the old list, and the sorted list is lost. A list that mixes numbers and strings, [1, 3, 2, 4, 'Alice', 'Bob'], raises a TypeError, because Python does not know how to compare them; the message is '<' not supported between instances of 'str' and 'int'. Strings are ordered by character code, so ['Alice', 'ants', 'Bob', 'badgers', 'Carol', 'cats'] becomes ['Alice', 'Bob', 'Carol', 'ants', 'badgers', 'cats'], with every capital letter before every lower-case letter."),
  (H, "The method uses the algorithm called Timsort, which finds runs of items that are already ordered and merges them, and which the documentation describes as stable: items that compare equal keep their original order [PSF]. Python compares two items with the less-than operator, so any items that support it can be sorted, which is why numbers and strings work and why a number and a string do not. The comparison of strings goes character by character by code point, and the code of Z is lower than that of a."),
  (K, "Never write spam = spam.sort(): the list is sorted, then the name is rebound to the None that the method returned, and the data is lost. If a sorted copy is wanted and the original must stay as it is, use the function sorted, described below. If the order of strings must ignore the case, pass key=str.lower, which the next concept explains."),
 ]),
 ("SortKeyReverse", "key and reverse arguments", 3, "Ordering", ("spam.sort(key=str.lower)", "The keyword arguments reverse and key change how sort and sorted compare: reverse=True gives descending order and key names a function applied to each item before the comparison.", ("sorted(['a', 'z', 'A', 'Z'], key=str.lower)", "['a', 'A', 'z', 'Z']")), [
  (W, "The sort method takes two keyword-only arguments. Passing True as the reverse argument sorts the values in reverse order: after spam.sort() the call spam.sort(reverse=True) leaves ['Elephants', 'Dogs', 'Cats', 'Badgers', 'Ants'] [SW]. If the values should be sorted in regular alphabetical order, the chapter passes str.lower as the key argument, so ['a', 'z', 'A', 'Z'] becomes ['a', 'A', 'z', 'Z']. This argument causes sort to treat all the items in the list as if they were lowercase without actually changing the values in the list."),
  (Y, "The key argument turns sorting from one fixed rule into any rule the programmer can write as a function of one item. Sorting words by length, files by size or records by a field are all the same call with a different key. The documentation notes that the key function is called once for each item and that the results, not the items, are compared, which makes the call fast even for complex rules [PSF]."),
  (E, "In the executed examples sorted([2, 5, 3.14, 1, -7], reverse=True) is [5, 3.14, 2, 1, -7]. Sorting ['banana', 'Apple', 'cherry'] with key=str.lower gives ['Apple', 'banana', 'cherry'], and sorting ['bb', 'aa', 'c', 'dd'] with key=len gives ['c', 'bb', 'aa', 'dd']; here 'bb', 'aa' and 'dd' have the same key and keep their original order, because the sort is stable. The same two keywords exist for the function sorted."),
  (H, "Python computes the key of each item once, keeps the pairs of key and item, orders the pairs by the keys and returns the items. The original values are never changed, which is why the chapter says that the list is not really turned to lower case. With reverse=True the result is as if the list had been sorted and then reversed, except that equal items keep their original order, so reverse=True and the reverse method are not interchangeable on lists with equal keys."),
  (K, "The argument is the function itself, not a call of it: key=str.lower, not key=str.lower(). Both arguments must be written with their names, as key=... and reverse=..., because they are keyword-only. A key function must return values that can be compared with each other; a key that returns numbers for some items and strings for others raises the same TypeError as a mixed list."),
 ]),
 ("ReverseMethod", "reverse method", 3, "Ordering", ("spam.reverse()", "The reverse method turns the order of the items around in place and returns None; the slice with step -1 gives a reversed copy and leaves the list unchanged.", ("(s := ['cat', 'dog', 'moose'], s.reverse(), s)[2]", "['moose', 'dog', 'cat']")), [
  (W, "If you need to quickly reverse the order of the items in a list, you call the reverse list method. With spam holding ['cat', 'dog', 'moose'], the call spam.reverse() leaves ['moose', 'dog', 'cat'] [SW]. Like the sort method, reverse does not return a list, which is why the chapter writes spam.reverse() and not spam = spam.reverse(). The documentation says the method reverses the items of the sequence in place for economy of space [PSF]."),
  (Y, "Reversal is not sorting: it makes no comparison and so it works on any items, even on a list that mixes numbers and strings. It is used to turn a list that was built from the end back into reading order, to read a log from the newest entry, and to compare a sequence with its mirror image, as in a test for a palindrome."),
  (E, "In the executed examples spam.reverse() on ['cat', 'dog', 'moose'] gives ['moose', 'dog', 'cat'] and returns None. A list of mixed types, [1, 'a', None], is reversed to [None, 'a', 1] without any error. The slice with step -1 gives the same order as a new list: [1, 2, 3][::-1] is [3, 2, 1], and the built-in reversed gives an iterator that list turns into the list ['b', 'a']."),
  (H, "The method swaps the first item with the last, the second with the one before the last, and so on, until the middle is reached, and it needs no extra list. The time grows with the length of the list. Because it changes the list in place, every name that refers to the same list sees the new order."),
  (K, "The two common slips are the same as for sort: reading its result, which is None, and forgetting that it changes the original. A program that must keep the original order should reverse a copy, or take the slice [::-1], or use reversed in a for loop."),
 ]),
 ("SortedFunction", "sorted function", 3, "Ordering", ("sorted(spam)", "The built-in function sorted returns a new ordered list from any iterable and leaves the original unchanged; it takes the same key and reverse arguments as the sort method.", ("(lambda s: (sorted(s), s))([3, 1, 2])", "([1, 2, 3], [3, 1, 2])")), [
  (W, "The built-in function sorted returns a new list containing all the items of an iterable in ascending order, and leaves the original unchanged [PSF]. It takes the same key and reverse arguments as the sort method. Where spam.sort() changes spam and returns None, sorted(spam) returns the ordered list and spam keeps its order. The chapter teaches the method; the function is the tool for the cases in which the original must survive."),
  (Y, "The pair of a method that works in place and a function that returns a new list shows a design rule that Python follows widely: an operation either changes its object and returns None, or leaves the object alone and returns a new value, and it does not do both. Knowing the rule lets a programmer predict what a call will do without looking it up, and it explains why chaining calls on a list, as in spam.sort().reverse(), fails."),
  (E, "In the executed examples sorted([3, 1, 2]) is [1, 2, 3] while the list itself remains [3, 1, 2]. The function accepts any iterable, so sorted('banana') is ['a', 'a', 'a', 'b', 'n', 'n'], and a tuple or a set gives a list as well. With reverse=True the result is in descending order: sorted([3, 1, 2], reverse=True) is [3, 2, 1]. Because the result is a new list, it can be passed straight to another function, as in len(sorted(spam))."),
  (H, "The function makes a list from the iterable, sorts that list in place with the same algorithm as the method, and returns it. The first step is the copy, which is why it costs a little more memory than the method. The sort is stable, and the key function is called once per item, just as for the method."),
  (K, "Use the method when the list is no longer needed in its old order and when it is large, and the function when the original order matters or when the data is not a list. The result is always a list, even for a string or a tuple, so code that expected a string back must join the characters again."),
 ]),
]

CHECKS += [("['hello', 'hi'].index('hello')", "0"),
           PROG("for v in ['hello']:\n    try:\n        v.append('world')\n    except AttributeError as e:\n        print(e)\ntry:\n    (42).insert(1, 'world')\nexcept AttributeError as e:\n    print(e)\n", "'str' object has no attribute 'append'\n'int' object has no attribute 'insert'\n"),
           ("callable(['a'].append)", "True"),
           ("(lambda spam: ('howdy' in spam, 'cat' in spam, 'howdy' not in spam, 'cat' not in spam))(['hello', 'hi', 'howdy', 'heyas'])", "(True, False, False, True)"),
           ("(1 in [1.0], 'ab' in 'cabd', 'ab' in ['cabd'])", "(True, True, False)"),
           ("'3' in [1, 2, 3]", "False"),
           ("(lambda x, s: (not x in s, x not in s))(5, [1, 2])", "(True, True)"), ("ord('Z') < ord('a')", "True"),
           PROG("my_pets = ['Zophie', 'Pooka', 'Fat-tail']\nprint('Enter a pet name:')\nname = input()\nif name not in my_pets:\n    print('I do not have a pet named ' + name)\nelse:\n    print(name + ' is my pet.')\n", "Enter a pet name:\nI do not have a pet named Footfoot\n", inp="Footfoot\n"),
           PROG("my_pets = ['Zophie', 'Pooka', 'Fat-tail']\nprint('Enter a pet name:')\nname = input()\nif name not in my_pets:\n    print('I do not have a pet named ' + name)\nelse:\n    print(name + ' is my pet.')\n", "Enter a pet name:\nPooka is my pet.\n", inp="Pooka\n"),
           ("(lambda spam: (spam.index('hello'), spam.index('heyas')))(['hello', 'hi', 'howdy', 'heyas'])", "(0, 3)"),
           ("['Zophie', 'Pooka', 'Fat-tail', 'Pooka'].index('Pooka')", "1"), ("['a', 'b', 'a'].index('a', 1)", "2"),
           VPROG("try:\n    ['hello', 'hi', 'howdy', 'heyas'].index('howdy howdy howdy')\nexcept ValueError as e:\n    print(e)\n", "list.index(x): x not in list\n", "'howdy howdy howdy' is not in list\n"),
           PROG("spam = ['cat', 'dog']\nif spam[0] == 'cat':\n    print('A cat is the first item.')\nelse:\n    print('The first item is not a cat.')\n", "A cat is the first item.\n"),
           PROG("spam = []\nif len(spam) > 0 and spam[0] == 'cat':\n    print('A cat is the first item.')\nelse:\n    print('The first item is not a cat.')\n", "The first item is not a cat.\n"),
           ("(lambda f: (f([]), f(['cat', 'dog'])))(lambda spam: len(spam) > 0 and spam[0] == 'cat')", "(False, True)"),
           ("True or [][0]", "True"), ("([] and 5, [] or 5, [1] and 5)", "([], 5, 5)"),
           ("(bool([]), bool(''), bool(0), bool([0]))", "(False, False, False, True)"),
           ("(s := [2, 5, 3.14, 1, -7], s.sort(), s)[2]", "[-7, 1, 2, 3.14, 5]"),
           ("(s := ['Ants', 'Cats', 'Dogs', 'Badgers', 'Elephants'], s.sort(), s)[2]", "['Ants', 'Badgers', 'Cats', 'Dogs', 'Elephants']"),
           ("(s := [3, 1, 2], s := s.sort(), s)[2]", "None"), ("[3, 1, 2].sort()", "None"),
           ("(s := ['Alice', 'ants', 'Bob', 'badgers', 'Carol', 'cats'], s.sort(), s)[2]", "['Alice', 'Bob', 'Carol', 'ants', 'badgers', 'cats']"),
           PROG("try:\n    [1, 3, 2, 4, 'Alice', 'Bob'].sort()\nexcept TypeError as e:\n    print(e)\n", "'<' not supported between instances of 'str' and 'int'\n"),
           ("(s := ['Ants', 'Cats', 'Dogs', 'Badgers', 'Elephants'], s.sort(), s.sort(reverse=True), s)[3]", "['Elephants', 'Dogs', 'Cats', 'Badgers', 'Ants']"),
           ("(s := ['a', 'z', 'A', 'Z'], s.sort(key=str.lower), s)[2]", "['a', 'A', 'z', 'Z']"),
           ("sorted(['a', 'z', 'A', 'Z'], key=str.lower)", "['a', 'A', 'z', 'Z']"), ("sorted(['a', 'z', 'A', 'Z'])", "['A', 'Z', 'a', 'z']"),
           ("sorted([2, 5, 3.14, 1, -7], reverse=True)", "[5, 3.14, 2, 1, -7]"),
           ("sorted(['banana', 'Apple', 'cherry'], key=str.lower)", "['Apple', 'banana', 'cherry']"), ("sorted(['bb', 'aa', 'c', 'dd'], key=len)", "['c', 'bb', 'aa', 'dd']"),
           ("(s := ['cat', 'dog', 'moose'], s.reverse(), s)[2]", "['moose', 'dog', 'cat']"), ("['cat'].reverse()", "None"),
           ("(s := [1, 'a', None], s.reverse(), s)[2]", "[None, 'a', 1]"), ("[1, 2, 3][::-1]", "[3, 2, 1]"), ("list(reversed(['a', 'b']))", "['b', 'a']"),
           ("(lambda s: (sorted(s), s))([3, 1, 2])", "([1, 2, 3], [3, 1, 2])"), ("sorted('banana')", "['a', 'a', 'a', 'b', 'n', 'n']"),
           ("sorted([3, 1, 2], reverse=True)", "[3, 2, 1]"), ("len(sorted([3, 1, 2]))", "3"),
           ("(s := [3, 1, 2], isinstance(s.sort(), list))[1]", "False")]
RAISES += [("'hello'.append('world')", "AttributeError"), ("(42).insert(1, 'world')", "AttributeError"),
           ("['hello', 'hi', 'howdy', 'heyas'].index('howdy howdy howdy')", "ValueError"), ("(lambda spam: spam[0] == 'cat')([])", "IndexError"),
           ("(lambda spam: spam[0] == 'cat' and len(spam) > 0)([])", "IndexError"),
           ("[1, 3, 2, 4, 'Alice', 'Bob'].sort()", "TypeError"), ("[3, 1, 2].sort().reverse()", "AttributeError"), ("sorted([1, 'a'])", "TypeError")]
