"""Chapter 24 content for the RDODI build: sources, findings, taxonomy and section bodies.
The book's chapter was read on automatetheboringstuff.com on 2026-10-01 (HTML fetched with curl through the session proxy, because the
WebFetch tool's permission request was not answered; converted to text and read in full), and checked against the book's own chapter
ontology (7 sections, 7 practice questions). The third-party packages were read from the files PyPI serves, stored beside the page inputs
in 08-tooling/ch24-page/sources/: pyttsx3 2.99 (wheel, uploaded 2025-07-08), openai-whisper 20250625 (sdist, uploaded 2025-06-26) and
yt-dlp 2026.8.19 (wheel, uploaded 2026-08-19, executed only in a scratch environment; its probe script and recorded output are stored).
The Python documentation was read live on docs.python.org (the pages say 3.14.8); every behaviour stated here was executed under
Python 3.14.4. Nothing that needs a sound card, a speech model, the network or a real video site was run: those statements are
marked as read, not executed. A claim not in this file was not made."""
__version__ = "1.0.0"
import os
CH = 24
DATE = "2026-10-01"
PYVER = "3.14.4"
TITLE = "Text-to-speech and speech recognition engines for an advanced course: chapter 24 of the 3rd edition and today's packages"
QUESTION = "What does chapter 24 of the 3rd edition teach about speech from text with pyttsx3, text from speech with Whisper, subtitle files and downloading with yt-dlp, which of its statements still hold for the current releases of those packages and for Python 3.14.4, what could be executed offline here, and what must an advanced course add?"
CQS = ("Which parts of the chapter's speech programs run without a sound card, a speech model, a download or a network, and which cannot?",
       "Where do the chapter's statements about file formats, model names and package behaviour differ from the current package sources, and on what source?")
PUBS = [
 ("P01","Automate the Boring Stuff with Python, 3rd edition - Chapter 24, Text-to-Speech and Speech Recognition Engines (Al Sweigart, No Starch Press, 2025)","https://automatetheboringstuff.com/3e/chapter24.html",True),
 ("P02","The Python Standard Library, wave - Read and write WAV files (Python documentation, read live)","https://docs.python.org/3/library/wave.html",False),
 ("P03","The Python Standard Library, pathlib - Object-oriented filesystem paths, glob and match (Python documentation, read live)","https://docs.python.org/3/library/pathlib.html",False),
 ("P04","The Python Standard Library, json - JSON encoder and decoder (Python documentation, read live)","https://docs.python.org/3/library/json.html",False),
 ("P05","The Python Standard Library, io - Core tools for working with streams (Python documentation, read live)","https://docs.python.org/3/library/io.html",False),
 ("P06","The Python Standard Library, Built-in Types - printf-style string formatting with a mapping (Python documentation, read live)","https://docs.python.org/3/library/stdtypes.html",False),
 ("P07","The Python Standard Library, tempfile - Generate temporary files and directories (Python documentation, read live)","https://docs.python.org/3/library/tempfile.html",False),
 ("P08","What's New In Python 3.13 - the modules removed by PEP 594 (Python documentation, read live)","https://docs.python.org/3/whatsnew/3.13.html",False),
 ("P09","PEP 594 - Removing dead batteries from the standard library (Python Enhancement Proposals)","https://peps.python.org/pep-0594/",False),
 ("P10","The Python Standard Library, subprocess - Subprocess management (Python documentation, read live)","https://docs.python.org/3/library/subprocess.html",False),
 ("P11","The Python Standard Library, struct - Interpret bytes as packed binary data (Python documentation, read live)","https://docs.python.org/3/library/struct.html",False),
 ("P12","pyttsx3 2.99 wheel, the package source read and executed with its dummy driver (Natesh M Bhat, uploaded 2025-07-08, MPL-2.0)","https://files.pythonhosted.org/packages/84/14/9fb5842581f0419b5eb85f8c26c1c0c0f4cf6b4d5be638ae3157316a2650/pyttsx3-2.99-py3-none-any.whl",False),
 ("P13","pyttsx3 on the Python Package Index, release metadata (JSON interface: version 2.99, upload date, dependencies)","https://pypi.org/pypi/pyttsx3/json",False),
 ("P14","pyttsx3 documentation on Read the Docs (describes version 2.6, rendered 2021-07-14)","https://pyttsx3.readthedocs.io/en/latest/",False),
 ("P15","openai-whisper 20250625 source distribution, the package source, README and licence read (OpenAI, uploaded 2025-06-26, MIT)","https://files.pythonhosted.org/packages/35/8e/d36f8880bcf18ec026a55807d02fe4c7357da9f25aebd92f85178000c0dc/openai_whisper-20250625.tar.gz",False),
 ("P16","openai-whisper on the Python Package Index, project page","https://pypi.org/project/openai-whisper/",False),
 ("P17","yt-dlp 2026.8.19 wheel, the package source read and run offline in a scratch environment (uploaded 2026-08-19, Unlicense)","https://files.pythonhosted.org/packages/69/b2/8cd1613f56eed7ceb64fbd4df3f1c01246bfb098e6f398228bafda22b80b/yt_dlp-2026.8.19-py3-none-any.whl",False),
 ("P18","yt-dlp on the Python Package Index, project page","https://pypi.org/project/yt-dlp/",False),
 ("P19","WebVTT: The Web Video Text Tracks Format (W3C Candidate Recommendation Draft, 20 May 2026)","https://www.w3.org/TR/webvtt1/",False),
 ("P20","SubRip - the .srt subtitle file format (Wikipedia)","https://en.wikipedia.org/wiki/SubRip",False),
]
CONCEPTS = [("Section",x) for x in ("Text-to-Speech Engine","Speech Recognition","Creating Subtitle Files","Downloading Videos from Websites","Summary","Practice Questions","Practice Programs")] + \
 [("Method",x) for x in ("pyttsx3.init","say","runAndWait","setProperty","getProperty","save_to_file","whisper.load_model","transcribe","yt_dlp.YoutubeDL")] + \
 [("Concept",x) for x in ("Speech from text","Voice settings","Text from speech")]
FINDINGS = [
 ("F1","Background","Chapter 24 of the 3rd edition, Text-to-Speech and Speech Recognition Engines, teaches three third-party packages: pyttsx3, which speaks text through the speech engine of the operating system (SAPI5 on Windows, NSSpeechSynthesizer on macOS, eSpeak on Linux) with say(), runAndWait(), getProperty() and setProperty() for rate, volume and voice, and save_to_file() for a WAV file; Whisper, installed as openai-whisper, which loads a model named tiny, base, small, medium or large-v3 with load_model(), transcribes an audio file with transcribe() into a dictionary whose 'text' key holds the words, and writes SRT, VTT, TSV, TXT or JSON files through get_writer(); and yt-dlp, which downloads a video or only its audio or metadata; it closes with seven practice questions and three practice programs: a spoken guess-the-number game, the song 99 Bottles of Beer, and a YouTube transcriber.",["P01"]),
 ("F2","Comparative analysis","The behaviour of pyttsx3 that the chapter describes reproduces where it can be run without a sound card: with the package's dummy driver under Python 3.14.4, say() returns at once and only queues the text, the events started-utterance and finished-utterance come only after runAndWait(), setProperty('rate', 300) takes effect only when the queue is run, getProperty('volume') and getProperty('rate') give 1.0 and 200, getProperty('voices') is a list of Voice objects that print as <pyttsx3.voice.Voice object at 0x...>, and a Voice made without gender, age and languages holds None, None and an empty list, as the chapter says; the default init() on this machine raises RuntimeError saying that eSpeak or eSpeak-ng is probably not installed, which is why the chapter tells Linux readers to install espeak; no speech was heard and no real voice was listed, because the machine has no engine and no sound card.",["P01","P12"]),
 ("F3","Comparative analysis","The chapter's statement that pyttsx3 can save .wav files only holds for two of its three engines and not for the third: the eSpeak driver of version 2.99 writes the file with the standard wave module as mono, 16-bit, 22,050 Hz, the SAPI5 driver writes through a SAPI file stream, and the macOS driver carries the comment that Apple writes .aiff, not .wav; the standard-library modules for AIFF (aifc), audioop, sunau, chunk and sndhdr were removed in Python 3.13 by PEP 594 and are absent under 3.14.4, while wave remains, so a WAV file can be read with the standard library and an AIFF file cannot.",["P01","P02","P08","P09","P12"]),
 ("F4","Comparative analysis","The chapter's account of Whisper holds with additions the chapter leaves out: release 20250625 accepts fourteen model names, not five, among them the .en models, large-v1, large-v2, large, and turbo with large-v3-turbo, and its command line uses turbo as the default model where the chapter recommends base; the five names the chapter gives are all valid; Whisper decodes every audio file by starting the ffmpeg command-line program for 16 kHz mono samples, so ffmpeg must be installed, which the chapter does not say; the memory column of the chapter's Table 24-1 (1, 1, 2, 5 and 10 GB) equals the required-VRAM column of the package's README; the runtimes of the table were measured by the author on his laptop and were not reproduced, since no model can be downloaded and run here, and the only numbers computed from them are ratios, such as the 'large-v3' model taking 12.8 times as long as 'base' on the 15-minute sample; the package lists Python 3.8 to 3.13 and was not installed or run here under Python 3.14.4.",["P01","P15","P16"]),
 ("F5","Comparative analysis","The chapter's sample subtitle files reproduce when Whisper's own writer source is executed: the SRT file numbers each block from 1, always shows hours and uses a comma before the milliseconds (00:00:05,640), the VTT file starts with the line WEBVTT and shows hours only when they are not zero (00:05.640), the TSV file has the header line start, end and text with times as integer milliseconds (5640), and the TXT file has one stripped segment per line; the writer replaces --> inside a segment's text by ->, names the output file after the audio file without its folder or extension (talks/hello.wav gives hello.srt), and raises KeyError for a format it does not know; the W3C WebVTT text confirms that hours may be omitted when zero, and the description of SubRip confirms the comma.",["P01","P15","P19","P20"]),
 ("F6","Comparative analysis","The chapter's language option holds and is wider than the chapter says: get_tokenizer lower-cases the name, so language='English' is accepted, the package knows 100 languages, and the chapter's statement that the engines work with most widely spoken languages is consistent with that list; the dictionary returned by transcribe() has exactly the keys text, segments and language, and each segment carries start, end and text, which is what the subtitle writers read; with word timestamps requested, each segment also carries a list of words, and the writers can then break subtitles by a number of words per line or by a line width and a line count, options the chapter does not cover.",["P01","P15"]),
 ("F7","Comparative analysis","The chapter's yt-dlp code is consistent with the package, checked offline in a scratch environment with yt-dlp 2026.8.19 under Python 3.14.4 without any download: the template 'downloaded_content.%(ext)s' gives downloaded_content.m4a, the post-processor FFmpegExtractAudio exists and needs ffmpeg, and sanitize_info() exists; but the chapter's prose names ydl.sanitize(), which the package does not have, the download() method also accepts a single address instead of a list because it wraps it, extract_info() downloads by default unless skip_download is set as the chapter does, and a title is not stripped of its forbidden characters as the chapter says but has them replaced by look-alike characters such as a full-width question mark and colon; no video was fetched, because the session has no route to the video sites.",["P01","P17","P18"]),
 ("F8","Contemporary developments","Current practice adds what the chapter does not show: pyttsx3 2.99 has a module-level speak() that calls init(), say() and runAndWait(), a dummy driver that lets programs be tested without a voice, callbacks registered with connect() for the events started-utterance, started-word, finished-utterance and error, and say() returns an error message instead of queuing an empty string; its Read the Docs page still describes version 2.6 from 2021; programs that speak or transcribe are best written so that the engine is passed in, as the practice programs here do with recording stand-ins, and every result of Whisper needs human review, as the chapter says.",["P01","P12","P13","P14"]),
 ("F9","Conclusion","For an advanced course, chapter 24 is best taught as glue code around three engines that cannot all run in a classroom: what runs offline is the standard-library part (wave files, subtitle formats, file names, JSON, glob, arithmetic on the book's table) and the package logic that has a dummy mode (pyttsx3's queue, properties and events), and what needs a voice, a model, ffmpeg or a network (speaking, saving with a real engine, load_model, transcribe, yt-dlp downloads) is read and not executed; the chapter's printed behaviour holds, and the course should add the AIFF case and the removed audio modules, the fourteen Whisper model names and the turbo default, the ffmpeg requirement, the word-level subtitle options, yt-dlp's look-alike file names, and the testing of speech code with injected engines.",["P01","P08","P12","P15","P17"]),
]
# (top, mid, leaf, exemplar, definition, io-or-None)
TAX = [
 ("SpeechSynthesis","EngineSetup","SynthesisPackage","import pyttsx3","pyttsx3 is a third-party package, installed with pip install pyttsx3, that does not synthesise the voice itself but drives the speech engine that the operating system already has; its name is py for Python, tts for text-to-speech, x for extended and 3 for Python 3.",None),
 ("SpeechSynthesis","EngineSetup","PlatformEngines","pyttsx3.init('dummy')","The engine behind pyttsx3 depends on the platform: SAPI5 on Windows, NSSpeechSynthesizer on macOS and eSpeak on Linux; the package lists the engines per platform with the first as the default, and also ships a dummy driver that speaks nothing and is meant for tests.",("{'win32': 'sapi5', 'darwin': 'nsss'}.get('linux', 'espeak')","'espeak'")),
 ("SpeechSynthesis","EngineSetup","InitFunction","engine = pyttsx3.init()","pyttsx3.init() returns an Engine object for a named driver or the platform default and returns the same object again for the same driver while it is alive; when the driver cannot start, as with eSpeak missing on Linux, it raises RuntimeError.",None),
 ("SpeechSynthesis","Speaking","SayMethod","engine.say('Hello.')","say() adds a text to the engine's queue and returns at once; it does not speak, and it returns an error message instead of queuing when the text is empty or only spaces.",None),
 ("SpeechSynthesis","Speaking","RunAndWait","engine.runAndWait()","runAndWait() starts the engine, works through everything queued so far and blocks until the last utterance is finished; without it nothing queued by say(), setProperty() or save_to_file() takes effect.",None),
 ("SpeechSynthesis","Speaking","EngineEvents","engine.connect('finished-utterance', callback)","connect() registers a callback for one of the engine's events: started-utterance, started-word, finished-utterance or error; the callbacks run during runAndWait(), and each receives the name given to say().",None),
 ("SpeechSynthesis","Speaking","SpeakShortcut","pyttsx3.speak('Hello.')","Version 2.99 has a module-level speak(text) that gets the engine with init(), queues the text with say() and calls runAndWait(), which the chapter does not show.",None),
 ("SpeechSynthesis","VoiceSettings","GetProperty","engine.getProperty('rate')","getProperty() reads a setting by name: 'rate' is words per minute, 'volume' a float from 0.0 to 1.0, 'voice' the current voice and 'voices' the plural list of all Voice objects; an unknown name raises KeyError.",None),
 ("SpeechSynthesis","VoiceSettings","SetProperty","engine.setProperty('rate', 300)","setProperty() queues a change of 'rate', 'volume' or 'voice'; the singular 'voice' takes the id of a Voice, and like speech the change is applied only when runAndWait() runs the queue.",None),
 ("SpeechSynthesis","VoiceSettings","SpeechRate","60 / 200","The rate is the speaking speed in words per minute and starts at 200, so at the default each word takes on average 60 / 200 of a second.",("60 / 200","0.3")),
 ("SpeechSynthesis","VoiceSettings","VoiceObjects","engine.getProperty('voices')","A Voice object has the attributes id, name, languages, gender and age; gender and age are None and languages is an empty list when the operating system does not say, and a list of Voice objects prints as <pyttsx3.voice.Voice object at 0x...> because the class defines no repr.",None),
 ("SpeechSynthesis","SavedAudio","SaveToFile","engine.save_to_file('Hello.', 'hello.wav')","save_to_file() queues speech to be written to a file instead of the speakers, and like say() it needs runAndWait() before the file exists; the chapter says that only .wav is possible, which is true of the eSpeak and SAPI5 drivers and not of the macOS driver, which writes .aiff.",None),
 ("SpeechSynthesis","SavedAudio","WavContainer","wave.open('hello.wav', 'rb')","A WAV file is a RIFF container holding a format header and raw samples; the standard wave module reads and writes it, and the eSpeak driver of pyttsx3 writes mono, 2-byte samples at 22,050 frames per second, so one second of silence is 44 header bytes plus 44,100 data bytes.",("(lambda io, wave: (lambda b: (lambda w: (w.setnchannels(1), w.setsampwidth(2), w.setframerate(22050), w.writeframes(bytes(44100)), w.close(), (b.getvalue()[:4], b.getvalue()[8:12], len(b.getvalue())))[-1])(wave.open(b, 'wb')))(io.BytesIO()))(__import__('io'), __import__('wave'))","(b'RIFF', b'WAVE', 44144)")),
 ("SpeechSynthesis","SavedAudio","SpeechDuration","1800 / 200","The length of speech follows from the word count and the rate: 1,800 words at 200 words per minute take 9 minutes, which agrees in size with the 10-minute file that the chapter reports for its laptop.",("1800 / 200","9.0")),
 ("SpeechSynthesis","SavedAudio","RemovedAudioModules","import wave","Python 3.13 removed aifc, audioop, sunau, chunk and sndhdr from the standard library under PEP 594 and kept wave; under 3.14.4 only wave can still be imported, so AIFF files, which the macOS driver of pyttsx3 writes, need a third-party reader.",None),
 ("SpeechRecognition","WhisperModels","WhisperPackage","pip install openai-whisper","Whisper is installed as openai-whisper, because the package called whisper on PyPI is something else; it depends on PyTorch and other large packages and needs the ffmpeg program on the path, which the chapter does not mention; this was read and not installed here.",None),
 ("SpeechRecognition","WhisperModels","LoadModel","model = whisper.load_model('base')","load_model(name) returns a model object; release 20250625 accepts fourteen names, among them the chapter's tiny, base, small, medium and large-v3, the .en models for English only, large-v1, large-v2, large, and turbo; the first call downloads the model file.",None),
 ("SpeechRecognition","WhisperModels","ModelSizes","whisper.load_model('large-v3')","Larger models are slower and more accurate: on the chapter's 15-minute sample the author's laptop needed 2 minutes 34 seconds for base and 32 minutes 58 seconds for large-v3, about 12.8 times as long; these times are the book's own measurements, not reproduced here.",("round((32 * 60 + 58) / (2 * 60 + 34), 1)","12.8")),
 ("SpeechRecognition","WhisperModels","GraphicsProcessor","whisper.load_model('base', device='cuda')","By default Whisper computes on the CPU; with an NVIDIA card and the matching PyTorch the device argument 'cuda' moves the model to the graphics processor and speeds transcription up; this was read and not run here.",None),
 ("SpeechRecognition","Transcription","TranscribeMethod","result = model.transcribe('hello.wav')","transcribe(path) decodes the audio or video file and returns a dictionary; it can take seconds or hours depending on the model and the length, and it accepts a language argument; it was read and not run here.",None),
 ("SpeechRecognition","Transcription","ResultDictionary","result['text']","The dictionary returned by transcribe() has the keys text, segments and language; the 'text' value is the whole transcription and every entry of 'segments' has start and end in seconds and its own text.",("{'text': ' Hello. How are you doing?', 'segments': [{'start': 0.0, 'end': 2.5, 'text': ' Hello. How are you doing?'}], 'language': 'en'}['text'].strip()","'Hello. How are you doing?'")),
 ("SpeechRecognition","Transcription","LanguageOption","model.transcribe('hello.wav', language='English')","Without a language argument Whisper detects the language from the first 30 seconds; with one it skips that step, and the name may be a code such as 'en' or a name such as 'English', which is lower-cased; the package knows 100 languages.",None),
 ("SpeechRecognition","Transcription","AudioDecoding","ffmpeg -i hello.wav -f s16le -ac 1 -ar 16000 -","Whisper does not read the file itself: it starts ffmpeg to convert any audio or video file to 16,000 samples per second of mono 16-bit sound, and it processes that sound in 30-second chunks of 480,000 samples.",("30 * 16000","480000")),
 ("SpeechRecognition","Transcription","HumanReview","print(result['text'])","All models make errors, including in punctuation and capital letters, so the chapter asks that a person review every transcription and suggests trying a larger model when there are many errors.",None),
 ("SpeechRecognition","SubtitleFiles","SrtFormat","00:00:00,000 --> 00:00:05,640","A SubRip file holds numbered blocks separated by a blank line, each with a start and end time as hours:minutes:seconds,milliseconds with a comma and then the text; Whisper's SRT writer always writes the hours.",("(lambda ms: '%02d:%02d:%02d,%03d' % (ms // 3600000, ms % 3600000 // 60000, ms % 60000 // 1000, ms % 1000))(round(5.64 * 1000))","'00:00:05,640'")),
 ("SpeechRecognition","SubtitleFiles","VttFormat","00:05.640","A WebVTT file starts with the line WEBVTT and writes times with a full stop before the milliseconds; the hours may be left out when they are zero, which is how Whisper writes them.",("(lambda ms: '%02d:%02d.%03d' % (ms % 3600000 // 60000, ms % 60000 // 1000, ms % 1000))(round(5.64 * 1000))","'00:05.640'")),
 ("SpeechRecognition","SubtitleFiles","TsvFormat","start end text","Whisper's TSV file is not an official subtitle format: it has the header line start, end and text separated by tabs and then one line per segment with the times as integer milliseconds, which any program with the csv module can read.",("(round(1000 * 5.64), round(1000 * 14.96))","(5640, 14960)")),
 ("SpeechRecognition","SubtitleFiles","TxtAndJsonFormats","get_writer('json', '.')","The TXT writer writes one stripped segment text per line and the JSON writer dumps the whole result dictionary with json.dump; the chapter lists both names in the get_writer() argument.",("__import__('json').dumps({'start': 0, 'end': 1.5, 'text': ' a'})","'{\"start\": 0, \"end\": 1.5, \"text\": \" a\"}'")),
 ("SpeechRecognition","SubtitleFiles","GetWriter","whisper.utils.get_writer('srt', '.')","get_writer(format, folder) returns a writer function, and calling it with the result and an audio file name writes folder/name.format, where the name is the audio file's name without its folder and extension; an unknown format raises KeyError.",("__import__('os').path.splitext(__import__('os').path.basename('talks/hello.wav'))[0] + '.srt'","'hello.srt'")),
 ("SpeechRecognition","SubtitleFiles","WordTimestamps","write_function(result, 'audio', {'max_words_per_line': 2})","When the transcription was made with word timestamps, every segment also holds a list of words with their own times, and the writer can then start a new subtitle after a number of words or a line width; the chapter does not cover these options.",None),
 ("VideoDownload","Downloading","YtDlpPackage","import yt_dlp","yt-dlp is a third-party package that downloads from YouTube and many other video sites; it is installed with pip, changes often as the sites change, and the chapter's first advice for an error is to install the latest version; it was run here only offline, in a scratch environment.",None),
 ("VideoDownload","Downloading","DownloadCall","ydl.download([video_url])","download() is called with a list of addresses inside a with yt_dlp.YoutubeDL() block; current yt-dlp also accepts one address, wrapping it in a list itself; the download needs a network and was not run.",None),
 ("VideoDownload","Downloading","DownloadOptions","yt_dlp.YoutubeDL({'quiet': True})","The dictionary given to YoutubeDL holds options such as quiet and no_warnings to silence the output, outtmpl for the file name, format for the choice of stream, postprocessors for steps after the download, and skip_download to fetch only information.",None),
 ("VideoDownload","Downloading","OutputTemplate","'outtmpl': 'downloaded_content.%(ext)s'","The outtmpl option is an output template: the text is filled in with printf-style named fields, so %(ext)s becomes the real file extension and the script can know the file's stem in advance; without it the name is built from the video's title and id.",("'downloaded_content.%(ext)s' % {'ext': 'm4a'}","'downloaded_content.m4a'")),
 ("VideoDownload","Downloading","AudioExtraction","'format': 'm4a/bestaudio/best'","The format option lists choices separated by slashes, tried from left to right, and the FFmpegExtractAudio post-processor then extracts the sound with ffmpeg into the preferred codec; it needs ffmpeg installed and a network, and was not run.",("'m4a/bestaudio/best'.split('/')","['m4a', 'bestaudio', 'best']")),
 ("VideoDownload","Metadata","FindDownloadedFile","Path().glob('downloaded_content.*')","Because the extension can vary, the script finds the file with a glob pattern: Path().glob('downloaded_content.*') yields every file in the current folder whose name is downloaded_content followed by any extension, and the chapter takes the first.",("(__import__('pathlib').PurePath('downloaded_content.m4a').match('downloaded_content.*'), __import__('pathlib').PurePath('notes.txt').match('downloaded_content.*'))","(True, False)")),
 ("VideoDownload","Metadata","MetadataOnly","ydl.extract_info(video_url)","With skip_download set, extract_info() returns a dictionary of facts about the video, such as title and duration; sanitize_info() turns that dictionary into something JSON can store, and the chapter writes it to metadata.json with json.dumps and encoding utf-8.",("__import__('json').loads(__import__('json').dumps({'title': 'T', 'duration': 60}))['duration']","60")),
 ("VideoDownload","Metadata","FilenameCleaning","yt_dlp.YoutubeDL({}).prepare_filename(info)","The chapter says characters not allowed in filenames are excluded from a title-based name; yt-dlp 2026.8.19 instead replaces them with look-alike characters, so 'What: is? this/that' becomes a name with a full-width colon, a full-width question mark and a division-like slash, followed by the id in square brackets.",None),
 ("VideoDownload","Metadata","DownloadFailures","pip install --upgrade yt-dlp","A site may refuse a download because of age or login rules, location or protection against scripts; the chapter's first step is to update yt-dlp, which follows the sites' changes, and a script should treat a failed download as a normal outcome.",None),
 ("PracticeWork","Questions","PracticeQuestions","Practice questions 1 to 7","The seven practice questions ask: how to make pyttsx3 speak faster (raise the 'rate' property), which format it saves (WAV, with the exceptions above), whether pyttsx3 and Whisper need online services (no, apart from Whisper's first model download), whether they support other languages (yes), which model is the default (the chapter recommends base but does not call it a default, while the command line of release 20250625 uses turbo), which two subtitle formats are common (SRT and VTT), and whether yt-dlp works on other sites than YouTube (yes).",None),
 ("PracticeWork","Programs","GuessWithVoice","speak('Your guess, 42, is too low.')","The first practice program replaces print() in the guess-the-number game by a function speak() that prints the text and also says it, and makes the hints name the guess, such as Your guess, 42, is too low.",("(lambda guess, secret: 'Your guess, %d, is too %s.' % (guess, 'low' if guess < secret else 'high'))(42, 50)","'Your guess, 42, is too low.'")),
 ("PracticeWork","Programs","BottlesSong","'%d bottle%s' % (n, ...)","The second practice program speaks 99 Bottles of Beer, each verse one bottle fewer, down to the line No more bottles of beer on the wall; starting at 2 or 3 makes testing easier, and the word bottle needs its singular form for one bottle.",("[('1 bottle' if n == 1 else '%d bottles' % n) for n in (2, 1, 0)]","['2 bottles', '1 bottle', '0 bottles']")),
 ("PracticeWork","Programs","TranscriberGlue","transcribe_all(urls, download, transcribe, write)","The third practice program glues yt-dlp and Whisper: for each address it downloads the audio, transcribes it and writes an SRT file; passing the three steps in as functions lets the loop be tested offline with stand-ins, while the real steps need a network and a model.",None),
]
ERRORS = []
CLAIMS = [
 ("(1800 / 200, 60 / 200)", "(9.0, 0.3)"),
 ("(round(900 / (2 * 60 + 34), 2), round(900 / (32 * 60 + 58), 2))", "(5.84, 0.46)"),
 ("[(n, round(900 / (m * 60 + s), 2)) for n, m, s in (('tiny', 1, 20), ('base', 2, 34), ('small', 6, 37), ('medium', 20, 17), ('large-v3', 32, 58))]", "[('tiny', 11.25), ('base', 5.84), ('small', 2.27), ('medium', 0.74), ('large-v3', 0.46)]"),
 ("[round(1000 * s) for s in (0, 5.64, 14.96)]", "[0, 5640, 14960]"),
]
S = "(Sweigart, 2025)"; PSF = "(Python Software Foundation, 2026)"; OA = "(OpenAI, 2025)"; NB = "(Bhat, 2025)"; WC = "(W3C, 2026)"; PPI = "(Python Package Index, 2026)"; PEP = "(Heimes and Cannon, 2019)"
BODY = {
 "SpeechSynthesis": "Text-to-speech in the chapter is the pyttsx3 package: it starts an engine, queues text, changes rate, volume and voice, and can save the speech to a file " + S + " " + NB + ".",
 "SpeechRecognition": "Speech recognition in the chapter is the Whisper package: it loads a trained model, turns an audio file into text with timings, and can write the result as subtitle files " + S + " " + OA + ".",
 "VideoDownload": "The chapter uses the yt-dlp package to fetch the audio or the facts of an online video so that Whisper has a file to transcribe " + S + " " + PPI + ".",
 "PracticeWork": "The chapter closes with seven practice questions and three practice programs " + S + ".",
 "EngineSetup": "pyttsx3 does not synthesise the voice itself; it drives the speech engine that the operating system already has, and starting it is one function call " + S + " " + NB + ".",
 "Speaking": "Speech is a queue: say() adds to it and runAndWait() runs it " + S + " " + NB + ".",
 "VoiceSettings": "Rate, volume and voice are read with getProperty() and changed with setProperty() " + S + " " + NB + ".",
 "SavedAudio": "Speech can go to a file instead of the speakers, and the file can be read back with the standard library if it is a WAV file " + S + " " + PSF + ".",
 "WhisperModels": "Whisper runs a trained model on the computer; the model's name sets the balance between speed and accuracy " + S + " " + OA + ".",
 "Transcription": "transcribe() turns an audio file into a dictionary of text and timed segments " + S + " " + OA + ".",
 "SubtitleFiles": "The timed segments of a transcription can be written as subtitle files in several formats " + S + " " + OA + ".",
 "Downloading": "yt-dlp downloads a video or only its sound, steered by a dictionary of options " + S + " " + PPI + ".",
 "Metadata": "After a download the script must find the file, and it can ask for the video's facts without downloading " + S + " " + PPI + ".",
 "Questions": "The practice questions test the chapter's facts about the three packages " + S + ".",
 "Programs": "The practice programs put the packages to use in a game, a song and a transcriber " + S + ".",
 "SynthesisPackage": "pyttsx3 is installed with pip install pyttsx3; on Linux the speech engine eSpeak may need to be installed first with sudo apt install espeak, and the name means py for Python, tts for text-to-speech, x for extended and 3 for Python 3 " + S + "; release 2.99 was uploaded on 2025-07-08 and depends on comtypes, pypiwin32 and pywin32 only on Windows and on pyobjc only on macOS " + NB + ". The package source was read and executed with its dummy driver; no real voice was run.",
 "PlatformEngines": "The chapter names SAPI5 for Windows, NSSpeechSynthesizer for macOS and eSpeak for Linux " + S + "; the package source holds a table of engines per platform, win32 giving sapi5 first, darwin giving nsss first and every other platform giving espeak, which was executed by setting sys.platform in a test, and it ships a dummy driver that speaks nothing " + NB + ".",
 "InitFunction": "pyttsx3.init() returns an Engine object " + S + "; with the dummy driver a second call returns the very same object, and its repr is pyttsx3.engine.Engine('dummy', debug=False); the default init() on this machine, where eSpeak is not installed, raised RuntimeError with the text This means you probably do not have eSpeak or eSpeak-ng installed! " + NB + ".",
 "SayMethod": "say() takes the text to speak, and the speaking does not begin until runAndWait() is called " + S + "; with the dummy driver say('Hello. How are you doing?', 'greeting') returned None and the list of events was still empty, and say('') and say(None) returned the text Argument value can't be None or empty instead of queuing " + NB + ".",
 "RunAndWait": "runAndWait() blocks until the computer has finished speaking the whole string " + S + "; with the dummy driver the events started greeting and finished greeting True appeared only after the call, and the dummy driver cannot run the loop a second time in one process, which the real drivers can, so each executed example used it once " + NB + ".",
 "EngineEvents": "The chapter does not mention events; the package lets a program register callbacks with connect() for started-utterance, started-word, finished-utterance and error " + NB + ", and the executed example received the two utterance events in order and the word events with their start position and length.",
 "SpeakShortcut": "The chapter calls init(), say() and runAndWait() one after the other " + S + "; version 2.99 also has speak(text), whose source is exactly those three lines " + NB + ".",
 "GetProperty": "getProperty('volume') gives 1.0 and getProperty('rate') gives 200 in the chapter, and the strings 'rate', 'volume' and 'voices' read the settings " + S + "; with the dummy driver the same two calls gave 1.0 and 200, 'voices' gave three Voice objects, and the unknown name 'tempo' raised KeyError with the text unknown property tempo " + NB + ".",
 "SetProperty": "setProperty('rate', 300) and setProperty('volume', 0.5) change the settings, and the voice is set with the singular 'voice' and the id of a Voice object " + S + "; with the dummy driver the rate still read 200 and the volume 1.0 right after the calls and read 300 and 0.5 only after runAndWait() " + NB + ".",
 "SpeechRate": "The chapter says the voice speaks at 200 words per minute by default " + S + "; the eSpeak driver of version 2.99 sets the rate 200 and the volume 1.0 when it starts " + NB + ", and 60 divided by 200 is 0.3, the seconds per word, which was computed.",
 "VoiceObjects": "The chapter describes the name, gender, age and languages of a Voice and the printed form <pyttsx3.voice.Voice object at 0x...> " + S + "; a Voice made with only an id held None for name, gender and age and [] for languages, and the printed list of the dummy driver's voices began with [<pyttsx3.voice.Voice object at 0x " + NB + ".",
 "SaveToFile": "save_to_file() needs runAndWait() before the file exists, and the chapter says that pyttsx3 can save .wav files only and not .mp3 or another format " + S + "; the source of version 2.99 writes WAV in the eSpeak driver with the wave module, writes through a SAPI file stream in the SAPI5 driver, and says in the macOS driver that Apple writes .aiff, not .wav " + NB + ". No file was saved by a real engine here, and the dummy driver has no save_to_file.",
 "WavContainer": "A WAV file written with the standard wave module as one channel, 2-byte samples and 22,050 frames per second, the parameters of the eSpeak driver, began with RIFF and WAVE, and one second was 44,144 bytes long and read back as 22,050 frames, 1.0 second " + PSF + " " + NB + ". This is a file made by this example and not one made by pyttsx3.",
 "SpeechDuration": "The chapter reports that a string of 1,800 words became a 10-minute audio file in about two seconds on the author's computer " + S + "; 1,800 words at the default 200 words per minute is 9.0 minutes, computed, which is of the same size; the time of two seconds was not reproduced.",
 "RemovedAudioModules": "Python 3.13 removed aifc, audioop, sunau, chunk and sndhdr, and find_spec found none of them under 3.14.4 while it found wave " + PEP + " " + PSF + "; the macOS driver of pyttsx3 writes AIFF, so reading such a file needs a third-party package.",
 "WhisperPackage": "The chapter says to install Whisper with pip install openai-whisper, that the package called whisper on PyPI is something else, and that the download is large " + S + "; the package lists PyTorch, numba, numpy and tiktoken as requirements, names Python 3.8 to 3.13 in its classifiers, and needs the command-line tool ffmpeg, which the chapter does not mention " + OA + ". It was read from the source distribution and not installed here, so Whisper was not run under Python 3.14.4.",
 "LoadModel": "load_model() takes one of the names 'tiny', 'base', 'small', 'medium' or 'large-v3' in the chapter " + S + "; the source of release 20250625 holds fourteen names, the five of the chapter among them and also tiny.en, base.en, small.en, medium.en, large-v1, large-v2, large, large-v3-turbo and turbo, where large is the same file as large-v3 and turbo the same as large-v3-turbo " + OA + ".",
 "ModelSizes": "Table 24-1 gives file sizes of 74MB to 3GB, memory of 1GB to 10GB and the author's runtimes, and the author finds base suitable for 99 percent of purposes " + S + "; its memory column equals the required-VRAM column of the package's README, and the 15-minute sample of 900 seconds gives 11.25, 5.84, 2.27, 0.74 and 0.46 seconds of audio per second of computing for tiny, base, small, medium and large-v3, all computed from the table, while large-v3 took about 12.8 times as long as base " + OA + ".",
 "GraphicsProcessor": "The chapter says that Whisper uses the CPU by default and that device='cuda' uses an NVIDIA graphics processor " + S + "; the command line of release 20250625 chooses cuda when PyTorch reports it and the CPU otherwise " + OA + ". No graphics processor was used here.",
 "TranscribeMethod": "transcribe() is called on the model with the audio file's name, and the chapter says that Whisper accepts any audio or video file and converts it itself " + S + "; it was read and not run here, since no model can be downloaded.",
 "ResultDictionary": "The 'text' key holds the transcription " + S + "; in the source of release 20250625 transcribe() ends by returning a dict with the keys text, segments and language, which was found by parsing that function's code " + OA + ". The dictionary in the executed example was written by hand in that shape and was not produced by Whisper.",
 "LanguageOption": "The chapter passes language='English' and says that Whisper detects the language by itself otherwise " + S + "; get_tokenizer lower-cases the name and looks it up among 100 language names and codes, so 'English' becomes en, which was found by parsing the stored source " + OA + ".",
 "AudioDecoding": "The chapter says that Whisper converts any file to the format it requires " + S + "; in release 20250625 that conversion is a call of ffmpeg with the options -f s16le -ac 1 and -ar 16000 (SAMPLE_RATE 16000), documented in the source as Requires the ffmpeg CLI in PATH, and a chunk is 30 seconds of 480,000 samples, which was read from the source by parsing it " + OA + " " + PSF + ".",
 "HumanReview": "The chapter says that all models produce errors, that Whisper is pretty good but never perfect at punctuation and capitals, and that the output should always be reviewed by a person " + S + ".",
 "SrtFormat": "The chapter's SRT sample shows block numbers, 00:00:00,000 --> 00:00:05,640 and the text " + S + "; Whisper's SRT writer, executed from the stored source, wrote 1 then 00:00:00,000 --> 00:00:05,640 then the text and a blank line, then 2 and 00:00:05,640 --> 00:00:14,960, and a formula written here gave the same as Whisper's format_timestamp for ten test times " + OA + " " + PPI + ".",
 "VttFormat": "The chapter's VTT sample starts with WEBVTT and shows 00:00.000 --> 00:05.640 " + S + "; the executed writer wrote WEBVTT, a blank line and the same lines, and wrote 01:01:01.500 for 3,661.5 seconds, so hours appear only when they are not zero, as the W3C text allows " + WC + " " + OA + ".",
 "TsvFormat": "The chapter's TSV sample has the header start, end, text and times such as 0 and 5640 " + S + "; the executed writer wrote the header with tabs and the integer milliseconds 0, 5640 and 14960 " + OA + ".",
 "TxtAndJsonFormats": "The chapter names the formats 'txt' and 'json' for get_writer() " + S + "; the executed TXT writer wrote the two stripped segment texts on two lines, and the JSON writer wrote the whole dictionary with json.dump, keeping the leading space of a segment's text " + OA + " " + PSF + ".",
 "GetWriter": "The chapter calls get_writer('srt', '.') and then write_function(result, 'audio') and gets audio.srt " + S + "; the executed writer named the file after the audio file's basename without extension, so talks/hello.wav gave hello.srt, replaced --> inside a segment's text by ->, and get_writer('pdf', '.') raised KeyError " + OA + ".",
 "WordTimestamps": "The chapter does not cover word timestamps; in the executed example a result with a list of words in its segment gave one subtitle by default, three subtitles of two, two and one words with max_words_per_line 2, and two subtitles with max_line_width 10 and max_line_count 2 " + OA + ". The words and times were written by hand and were not produced by Whisper.",
 "YtDlpPackage": "The chapter installs yt-dlp as described in its Appendix A and says that the first step for an error is to install the latest version " + S + "; release 2026.8.19 was uploaded on 2026-08-19 and needs Python 3.10 or later " + PPI + ". It was run only offline in a scratch environment, by a stored probe script with its recorded output; no video site was contacted.",
 "DownloadCall": "The chapter says that download() expects a list, which is why the address is put in a list " + S + "; the source of yt-dlp 2026.8.19 wraps a single address itself and comments that passing one address is a common mistake " + PPI + ". The download itself needs a network and was not run.",
 "DownloadOptions": "The chapter's dictionary holds quiet, no_warnings, outtmpl, format, postprocessors and skip_download " + S + "; the options object was built offline in the scratch environment without error and kept the post-processor FFmpegExtractAudio " + PPI + ".",
 "OutputTemplate": "The chapter sets 'outtmpl': 'downloaded_content.%(ext)s' and says that the name would otherwise be based on the video's title " + S + "; the template is filled in with printf-style named fields, and 'downloaded_content.%(ext)s' % {'ext': 'm4a'} gave downloaded_content.m4a, while yt-dlp's prepare_filename gave the same name for a dictionary with ext m4a and gave a name built from title and id in square brackets under the default template " + PSF + " " + PPI + ".",
 "AudioExtraction": "The chapter asks for the format 'm4a/bestaudio/best' and the post-processor FFmpegExtractAudio with the codec m4a " + S + "; the post-processor class exists in the package, which was checked offline, but extracting sound runs ffmpeg on a downloaded file, so it was not run " + PPI + ".",
 "FindDownloadedFile": "The chapter finds the file with Path().glob('downloaded_content.*') and takes the first match " + S + "; in a temporary folder holding downloaded_content.m4a, notes.txt and downloaded_content_old.mp3 the glob matched exactly one file and str() of it was downloaded_content.m4a " + PSF + ".",
 "MetadataOnly": "The chapter sets skip_download, calls extract_info() and sanitize_info() and writes metadata.json with encoding utf-8 " + S + "; a dictionary written with json.dumps in that way read back equal, and sanitize_info() exists in the package, turned a function in the dictionary into text and made json.dumps work, while extract_info() would need a network " + PPI + " " + PSF + ".",
 "FilenameCleaning": "The chapter says the title-based filename excludes characters not allowed in filenames " + S + "; for the title What: is? this/that yt-dlp 2026.8.19 gave a name with a full-width colon, a full-width question mark and a division-like slash followed by [abc].mp4, so the characters are replaced and not excluded " + PPI + ". The chapter's prose also names ydl.sanitize(), which the package does not have; its code uses sanitize_info().",
 "DownloadFailures": "The chapter lists age or login requirements, geographic restrictions and anti-scraping measures as reasons for a refusal and says to install the latest yt-dlp first " + S + "; an attempt in the scratch environment to download a placeholder address that cannot exist raised DownloadError, which shows that a failed download is an exception a script must expect " + PPI + ".",
 "PracticeQuestions": "The answers to the seven questions are the chapter's own " + S + ": faster speech by a higher 'rate'; WAV; no online service except Whisper's first model download; yes, other languages; the chapter recommends base and does not call it a default, while the command line of release 20250625 defaults to turbo " + OA + "; SRT and VTT; yes, other sites.",
 "GuessWithVoice": "The practice program replaces every print() by speak() and says the guess in the hint " + S + "; a solution with a recording stand-in for the engine printed and recorded the four lines I am thinking of a number between 1 and 20., Your guess, 10, is too low., Your guess, 18, is too high. and Good job! You guessed my number in 3 guesses!, and the recorded list equalled the printed lines. The stand-in is not pyttsx3.",
 "BottlesSong": "The practice program sings the lyrics from 99 and suggests starting at 2 or 3 " + S + "; a solution started at 3 printed three verses in which 2 bottles, 1 bottle and finally No more bottles of beer on the wall follow, with the singular for one bottle. The lyrics were printed and not spoken.",
 "TranscriberGlue": "The practice program combines yt-dlp and Whisper to make SRT files from a list of addresses " + S + "; a loop that takes the download, transcribe and write steps as functions ran with stand-ins and returned one SRT text per address. The stand-ins are not yt-dlp or Whisper, and the real pipeline was not run.",
}
# Behaviours stated in prose, executed. Paths to the stored package sources are filled in when this module is loaded.
_SRC = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ch24-page", "sources") + os.sep
_FILL = {"@WHEEL@": _SRC + "sen0414_ch24_pyttsx3_2_99_wheel_v1_0_0.whl", "@UTILS@": _SRC + "sen0414_ch24_whisper_utils_20250625_v1_0_0.py",
         "@INIT@": _SRC + "sen0414_ch24_whisper_init_20250625_v1_0_0.txt", "@TOK@": _SRC + "sen0414_ch24_whisper_tokenizer_20250625_v1_0_0.txt",
         "@AUD@": _SRC + "sen0414_ch24_whisper_audio_20250625_v1_0_0.txt", "@TRN@": _SRC + "sen0414_ch24_whisper_transcribe_20250625_v1_0_0.txt",
         "@README@": _SRC + "sen0414_ch24_whisper_README_20250625_v1_0_0.txt"}
def _fill(code):
    for k, v in _FILL.items():
        code = code.replace(k, v)
    return code
BEH = [
 ['default init() without an installed eSpeak', "import sys\nsys.path.insert(0, '@WHEEL@')\nimport pyttsx3\ntry:\n    pyttsx3.init()\nexcept RuntimeError as e:\n    print(type(e).__name__ + ': ' + str(e))\n", 'RuntimeError: This means you probably do not have eSpeak or eSpeak-ng installed!'],
 ['say() only queues; speech starts in runAndWait() (dummy driver)', "import sys\nsys.path.insert(0, '@WHEEL@')\nimport pyttsx3\nengine = pyttsx3.init('dummy')\nevents = []\nengine.connect('started-utterance', lambda name: events.append('started ' + str(name)))\nengine.connect('finished-utterance', lambda name, completed: events.append('finished %s %s' % (name, completed)))\nprint(engine.say('Hello. How are you doing?', 'greeting'))\nprint(events)\nengine.runAndWait()\nprint(events)\nprint(pyttsx3.init('dummy') is engine, repr(engine))\n", "None\n[]\n['started greeting', 'finished greeting True']\nTrue pyttsx3.engine.Engine('dummy', debug=False)"],
 ['getProperty, setProperty and the plural voices (dummy driver)', "import sys\nsys.path.insert(0, '@WHEEL@')\nimport pyttsx3\nengine = pyttsx3.init('dummy')\nprint(engine.getProperty('volume'), engine.getProperty('rate'))\nvoices = engine.getProperty('voices')\nprint(len(voices), [v.name for v in voices])\nprint(repr(voices).startswith('[<pyttsx3.voice.Voice object at 0x'))\nengine.setProperty('rate', 300)\nengine.setProperty('volume', 0.5)\nprint(engine.getProperty('rate'), engine.getProperty('volume'))\nengine.say('The quick brown fox jumps over the yellow lazy dog.')\nengine.runAndWait()\nprint(engine.getProperty('rate'), engine.getProperty('volume'))\ntry:\n    engine.getProperty('tempo')\nexcept KeyError as e:\n    print('KeyError', e)\n", "1.0 200\n3 ['John Doe', 'Jane Doe', 'Jimmy Doe']\nTrue\n200 1.0\n300 0.5\nKeyError 'unknown property tempo'"],
 ['an empty string is refused by say(), and Voice fields default to None and an empty list', "import sys\nsys.path.insert(0, '@WHEEL@')\nimport pyttsx3\nfrom pyttsx3.voice import Voice\nengine = pyttsx3.init('dummy')\nprint(engine.say(''), engine.say('   '), engine.say(None))\nv = Voice('some.id')\nprint(v.id, v.name, v.gender, v.age, v.languages)\n", "Argument value can't be None or empty Argument value can't be None or empty Argument value can't be None or empty\nsome.id None None None []"],
 ['which engine each platform uses', "import sys\nsys.path.insert(0, '@WHEEL@')\nimport pyttsx3.engine as e\nfor p in ('win32', 'darwin', 'linux'):\n    sys.platform = p\n    print(p, e.engines_by_sys_platform(), e.default_engine_by_sys_platform())\n", "win32 ('sapi5', 'espeak') sapi5\ndarwin ('nsss', 'espeak', 'avspeech') nsss\nlinux ('espeak',) espeak"],
 ['pyttsx3 2.99 has a speak() shortcut that the chapter does not show', "import sys, inspect\nsys.path.insert(0, '@WHEEL@')\nimport pyttsx3\nprint(hasattr(pyttsx3, 'speak'))\nprint([line.strip() for line in inspect.getsource(pyttsx3.speak).splitlines()[1:]])\n", "True\n['engine = init()', 'engine.say(text)', 'engine.runAndWait()']"],
 ["a WAV file with the parameters of pyttsx3's eSpeak driver, written and read with the wave module", "import io, math, struct, wave\nrate = 22050\nframes = b''.join(struct.pack('<h', int(12000 * math.sin(2 * math.pi * 440 * i / rate))) for i in range(rate))\nbuf = io.BytesIO()\nwith wave.open(buf, 'wb') as w:\n    w.setnchannels(1)\n    w.setsampwidth(2)\n    w.setframerate(rate)\n    w.writeframes(frames)\ndata = buf.getvalue()\nprint(len(data), data[:4], data[8:12])\nwith wave.open(io.BytesIO(data), 'rb') as r:\n    print(r.getnchannels(), r.getsampwidth(), r.getframerate(), r.getnframes(), r.getnframes() / r.getframerate())\n", "44144 b'RIFF' b'WAVE'\n1 2 22050 22050 1.0"],
 ['the removed audio modules and the surviving wave module', "import importlib.util\nprint({m: importlib.util.find_spec(m) is not None for m in ('aifc', 'audioop', 'sunau', 'chunk', 'sndhdr', 'wave')})\n", "{'aifc': False, 'audioop': False, 'sunau': False, 'chunk': False, 'sndhdr': False, 'wave': True}"],
 ["Whisper's own subtitle writers, loaded from the stored source file, write every format", "import importlib.util, os, tempfile\nspec = importlib.util.spec_from_file_location('whisper_utils', '@UTILS@')\nwu = importlib.util.module_from_spec(spec); spec.loader.exec_module(wu)\nresult = {'text': ' Dinosaurs are a diverse group of reptiles of the clade dinosauria. They first appeared during the triassic period.',\n          'segments': [{'start': 0.0, 'end': 5.64, 'text': ' Dinosaurs are a diverse group of reptiles of the clade dinosauria. They first'},\n                       {'start': 5.64, 'end': 14.96, 'text': ' appeared during the triassic period.'}], 'language': 'en'}\nwith tempfile.TemporaryDirectory() as d:\n    for fmt in ('srt', 'vtt', 'tsv', 'txt'):\n        wu.get_writer(fmt, d)(result, 'audio')\n    for name in sorted(os.listdir(d)):\n        print('--', name)\n        print(repr(open(os.path.join(d, name), encoding='utf-8').read()))\n", "-- audio.srt\n'1\\n00:00:00,000 --> 00:00:05,640\\nDinosaurs are a diverse group of reptiles of the clade dinosauria. They first\\n\\n2\\n00:00:05,640 --> 00:00:14,960\\nappeared during the triassic period.\\n\\n'\n-- audio.tsv\n'start\\tend\\ttext\\n0\\t5640\\tDinosaurs are a diverse group of reptiles of the clade dinosauria. They first\\n5640\\t14960\\tappeared during the triassic period.\\n'\n-- audio.txt\n'Dinosaurs are a diverse group of reptiles of the clade dinosauria. They first\\nappeared during the triassic period.\\n'\n-- audio.vtt\n'WEBVTT\\n\\n00:00.000 --> 00:05.640\\nDinosaurs are a diverse group of reptiles of the clade dinosauria. They first\\n\\n00:05.640 --> 00:14.960\\nappeared during the triassic period.\\n\\n'"],
 ['get_writer names the file after the audio file, and a format it does not know raises KeyError', "import importlib.util, os, tempfile\nspec = importlib.util.spec_from_file_location('whisper_utils', '@UTILS@')\nwu = importlib.util.module_from_spec(spec); spec.loader.exec_module(wu)\nresult = {'text': 'a --> b', 'segments': [{'start': 0, 'end': 1.5, 'text': ' a --> b'}]}\nwith tempfile.TemporaryDirectory() as d:\n    wu.get_writer('srt', d)(result, 'talks/hello.wav')\n    wu.get_writer('json', d)(result, 'audio')\n    print(sorted(os.listdir(d)))\n    print(repr(open(os.path.join(d, 'hello.srt'), encoding='utf-8').read()))\n    print(open(os.path.join(d, 'audio.json'), encoding='utf-8').read())\ntry:\n    wu.get_writer('pdf', '.')\nexcept KeyError as e:\n    print('KeyError', e)\nprint(wu.format_timestamp(5.64, True, ','), wu.format_timestamp(5.64), wu.format_timestamp(3661.5), wu.format_timestamp(3661.5, True, ','))\n", '[\'audio.json\', \'hello.srt\']\n\'1\\n00:00:00,000 --> 00:00:01,500\\na -> b\\n\\n\'\n{"text": "a --> b", "segments": [{"start": 0, "end": 1.5, "text": " a --> b"}]}\nKeyError \'pdf\'\n00:00:05,640 00:05.640 01:01:01.500 01:01:01,500'],
 ["my own timestamp formulas equal Whisper's format_timestamp", "import importlib.util\nspec = importlib.util.spec_from_file_location('whisper_utils', '@UTILS@')\nwu = importlib.util.module_from_spec(spec); spec.loader.exec_module(wu)\ndef srt(seconds):\n    ms = round(seconds * 1000.0)\n    return '%02d:%02d:%02d,%03d' % (ms // 3600000, ms % 3600000 // 60000, ms % 60000 // 1000, ms % 1000)\ndef vtt(seconds):\n    ms = round(seconds * 1000.0)\n    h = '%02d:' % (ms // 3600000) if ms >= 3600000 else ''\n    return '%s%02d:%02d.%03d' % (h, ms % 3600000 // 60000, ms % 60000 // 1000, ms % 1000)\nsamples = [0, 0.001, 5.64, 14.96, 59.9996, 61.5, 3599.999, 3600, 3661.5, 86399.123]\nprint(all(srt(s) == wu.format_timestamp(s, True, ',') for s in samples), all(vtt(s) == wu.format_timestamp(s) for s in samples))\nprint(srt(5.64), vtt(5.64), vtt(3661.5), srt(86399.123))\n", 'True True\n00:00:05,640 00:05.640 01:01:01.500 23:59:59,123'],
 ['word timestamps let the writer break subtitles by word count or by line width, options the chapter does not cover', "import importlib.util, os, tempfile\nspec = importlib.util.spec_from_file_location('whisper_utils', '@UTILS@')\nwu = importlib.util.module_from_spec(spec); spec.loader.exec_module(wu)\nwords = [(' one', 0.0, 0.5), (' two', 0.5, 1.0), (' three', 1.0, 1.6), (' four', 1.6, 2.0), (' five', 2.0, 2.4)]\nresult = {'text': ' one two three four five', 'segments': [{'start': 0.0, 'end': 2.4, 'text': ' one two three four five',\n          'words': [{'word': w, 'start': s, 'end': e} for w, s, e in words]}]}\nfor options in ({}, {'max_words_per_line': 2}, {'max_line_width': 10, 'max_line_count': 2}):\n    with tempfile.TemporaryDirectory() as d:\n        wu.get_writer('srt', d)(result, 'audio', options)\n        print(options, repr(open(os.path.join(d, 'audio.srt'), encoding='utf-8').read()))\n", "{} '1\\n00:00:00,000 --> 00:00:02,400\\none two three four five\\n\\n'\n{'max_words_per_line': 2} '1\\n00:00:00,000 --> 00:00:01,000\\none two\\n\\n2\\n00:00:01,000 --> 00:00:02,000\\nthree four\\n\\n3\\n00:00:02,000 --> 00:00:02,400\\nfive\\n\\n'\n{'max_line_width': 10, 'max_line_count': 2} '1\\n00:00:00,000 --> 00:00:02,000\\none two\\nthree four\\n\\n2\\n00:00:02,000 --> 00:00:02,400\\nfive\\n\\n'"],
 ['the model names Whisper 20250625 accepts, and the default of its command line', 'import ast, re\nsrc = open(\'@INIT@\', encoding=\'utf-8\').read()\nmodels = None\nfor node in ast.parse(src).body:\n    if isinstance(node, ast.Assign) and getattr(node.targets[0], \'id\', \'\') == \'_MODELS\':\n        models = ast.literal_eval(node.value)\nprint(len(models), list(models))\nprint([m in models for m in (\'tiny\', \'base\', \'small\', \'medium\', \'large-v3\')])\nprint(models[\'large\'] == models[\'large-v3\'], models[\'turbo\'] == models[\'large-v3-turbo\'])\nprint(re.findall(r\'"--model", default="(\\w+)"\', open(\'@TRN@\', encoding=\'utf-8\').read()))\n', "14 ['tiny.en', 'tiny', 'base.en', 'base', 'small.en', 'small', 'medium.en', 'medium', 'large-v1', 'large-v2', 'large-v3', 'large', 'large-v3-turbo', 'turbo']\n[True, True, True, True, True]\nTrue True\n['turbo']"],
 ["Whisper's language names: how many, and whether the chapter's 'English' is accepted", "import ast\nsrc = open('@TOK@', encoding='utf-8').read()\ntree = ast.parse(src)\nlangs = next(ast.literal_eval(n.value) for n in tree.body if isinstance(n, ast.Assign) and getattr(n.targets[0], 'id', '') == 'LANGUAGES')\nprint(len(langs), langs['en'], langs['tr'])\nnames = {v: k for k, v in langs.items()}\nprint('English'.lower() in names, names['english'])\nprint('get_tokenizer lowercases the name:', 'language = language.lower()' in src)\n", '100 english turkish\nTrue en\nget_tokenizer lowercases the name: True'],
 ['what Whisper does to the audio file: it calls ffmpeg for 16 kHz mono samples, and transcribe() returns text, segments and language', 'import ast, re\nsrc = open(\'@AUD@\', encoding=\'utf-8\').read()\nprint(re.findall(r\'^SAMPLE_RATE = (\\d+)\', src, re.M), \'"ffmpeg"\' in src, \'"-ar"\' in src, \'"-ac", "1"\' in src, \'Requires the ffmpeg CLI in PATH\' in src)\ntsrc = open(\'@TRN@\', encoding=\'utf-8\').read()\ntree = ast.parse(tsrc)\nfn = next(n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name == \'transcribe\')\nret = [n for n in ast.walk(fn) if isinstance(n, ast.Return) and isinstance(n.value, ast.Call) and getattr(n.value.func, \'id\', \'\') == \'dict\'][-1]\nprint([k.arg for k in ret.value.keywords])\n', "['16000'] True True True True\n['text', 'segments', 'language']"],
 ['the output template of the chapter and glob find the downloaded file', "import os, tempfile\nfrom pathlib import Path\nprint('downloaded_content.%(ext)s' % {'ext': 'm4a'})\nwith tempfile.TemporaryDirectory() as d:\n    os.chdir(d)\n    for name in ('downloaded_content.m4a', 'notes.txt', 'downloaded_content_old.mp3'):\n        Path(name).write_text('x')\n    matching_filenames = list(Path().glob('downloaded_content.*'))\n    downloaded_filename = str(matching_filenames[0])\n    print(len(matching_filenames), repr(downloaded_filename))\n    os.chdir('/')\n", "downloaded_content.m4a\n1 'downloaded_content.m4a'"],
 ['the metadata file of the chapter: JSON written with encoding utf-8 and read back', "import json, os, tempfile\ninfo = {'title': 'Beyond the Basic Stuff with Python - Al Sweigart - Part 1', 'duration': 3600, 'id': 'kSrnLbioN6w'}\nwith tempfile.TemporaryDirectory() as d:\n    path = os.path.join(d, 'metadata.json')\n    with open(path, 'w', encoding='utf-8') as json_file:\n        json_file.write(json.dumps(info))\n    back = json.load(open(path, encoding='utf-8'))\nprint(back == info, sorted(back), back['title'])\n", "True ['duration', 'id', 'title'] Beyond the Basic Stuff with Python - Al Sweigart - Part 1"],
 ['hello_tts.py of the chapter with a recording stand-in for the engine and a scripted answer', "import io, sys\nclass Recorder:\n    def __init__(self): self.said = []; self.pending = []\n    def say(self, text): self.pending.append(text)\n    def runAndWait(self): self.said += self.pending; self.pending = []\nengine = Recorder()\nsys.stdin = io.StringIO('great\\n')\nengine.say('Hello. How are you doing?')\nengine.runAndWait()\nfeeling = input('>')\nengine.say('Yes. I am feeling ' + feeling + ' as well.')\nengine.runAndWait()\nprint(engine.said)\n", ">['Hello. How are you doing?', 'Yes. I am feeling great as well.']"],
 ['practice program: voice for guess the number, with a recording stand-in for the engine', "class Recorder:\n    def __init__(self): self.said = []\n    def say(self, text): self.said.append(text)\n    def runAndWait(self): pass\nengine = Recorder()\ndef speak(text):\n    print(text)\n    engine.say(text)\n    engine.runAndWait()\ndef play(secret, guesses):\n    speak('I am thinking of a number between 1 and 20.')\n    for n, guess in enumerate(guesses, 1):\n        if guess < secret:\n            speak('Your guess, %d, is too low.' % guess)\n        elif guess > secret:\n            speak('Your guess, %d, is too high.' % guess)\n        else:\n            speak('Good job! You guessed my number in %d guesses!' % n)\n            break\nplay(14, [10, 18, 14])\nprint(engine.said == ['I am thinking of a number between 1 and 20.', 'Your guess, 10, is too low.', 'Your guess, 18, is too high.', 'Good job! You guessed my number in 3 guesses!'])\n", 'I am thinking of a number between 1 and 20.\nYour guess, 10, is too low.\nYour guess, 18, is too high.\nGood job! You guessed my number in 3 guesses!\nTrue'],
 ['practice program: the lyrics of 99 bottles of beer, started at 3', "def verses(start):\n    lines = []\n    for n in range(start, 0, -1):\n        now = '%d bottle%s' % (n, '' if n == 1 else 's')\n        left = 'No more bottles' if n == 1 else '%d bottle%s' % (n - 1, '' if n == 2 else 's')\n        lines += [now + ' of beer on the wall,', now + ' of beer,', 'Take one down, pass it around,', left + ' of beer on the wall.', '']\n    return lines\nprint('\\n'.join(verses(3)))\n", '3 bottles of beer on the wall,\n3 bottles of beer,\nTake one down, pass it around,\n2 bottles of beer on the wall.\n\n2 bottles of beer on the wall,\n2 bottles of beer,\nTake one down, pass it around,\n1 bottle of beer on the wall.\n\n1 bottle of beer on the wall,\n1 bottle of beer,\nTake one down, pass it around,\nNo more bottles of beer on the wall.'],
 ['practice program: the YouTube transcriber as glue, with stand-ins for yt-dlp and Whisper', "def transcribe_all(urls, download, transcribe, write):\n    done = []\n    for url in urls:\n        audio = download(url)\n        result = transcribe(audio)\n        done.append(write(result, audio))\n    return done\nfake_download = lambda url: 'downloaded_' + url.rsplit('=', 1)[-1] + '.m4a'\nfake_transcribe = lambda audio: {'text': 'stand-in text for ' + audio, 'segments': [{'start': 0.0, 'end': 1.0, 'text': ' stand-in'}]}\ndef fake_write(result, audio):\n    stem = audio.rsplit('.', 1)[0]\n    return stem + '.srt: ' + '1\\n00:00:00,000 --> 00:00:01,000\\n' + result['segments'][0]['text'].strip()\nfor line in transcribe_all(['https://example.test/watch?v=aaa', 'https://example.test/watch?v=bbb'], fake_download, fake_transcribe, fake_write):\n    print(repr(line))\n", "'downloaded_aaa.srt: 1\\n00:00:00,000 --> 00:00:01,000\\nstand-in'\n'downloaded_bbb.srt: 1\\n00:00:00,000 --> 00:00:01,000\\nstand-in'"],
 ['word events of the engine carry the start position and length of each word (dummy driver)', "import sys\nsys.path.insert(0, '@WHEEL@')\nimport pyttsx3\nengine = pyttsx3.init('dummy')\nwords = []\nengine.connect('started-word', lambda name, location, length: words.append((name, location, length)))\nengine.say('Hello there friend', 'w')\nengine.runAndWait()\nprint(words)\n", "[('w', 0, 5), ('w', 6, 5), ('w', 12, 6)]"],
 ["the memory column of the chapter's Table 24-1 against the README of Whisper 20250625, and the 30-second chunk", "import re\nreadme = open('@README@', encoding='utf-8').read()\nrows = re.findall(r'^\\|\\s*(tiny|base|small|medium|large|turbo)\\s*\\|[^|]*\\|[^|]*\\|[^|]*\\|\\s*~(\\d+) GB', readme, re.M)\nprint(rows)\nbook = {'tiny': 1, 'base': 1, 'small': 2, 'medium': 5, 'large': 10}\nprint(all(book[n] == int(g) for n, g in rows if n in book))\naud = open('@AUD@', encoding='utf-8').read()\nprint(re.findall(r'^CHUNK_LENGTH = (\\d+)', aud, re.M), re.findall(r'^N_SAMPLES = (.*)$', aud, re.M))\n", "[('tiny', '1'), ('base', '1'), ('small', '2'), ('medium', '5'), ('large', '10'), ('turbo', '6')]\nTrue\n['30'] ['CHUNK_LENGTH * SAMPLE_RATE  # 480000 samples in a 30-second chunk']"],
]
BEH = [(n, _fill(c), e) for n, c, e in BEH]
