#!/usr/bin/env python3
"""SEN0414 chapter 6 (Lists) - corpus text, part C, version 1.0.0: the branches 'Looping and unpacking' and 'Sequences and references'.

Same contract as parts A and B: connected prose, citation tokens resolved by the corpus, every number, output and error message
quoted in a paragraph listed in CHECKS or RAISES (executed by sen0414_ch06_corpus_v1_0_0.py under python3.14 and 3.13).
"""
__version__ = "1.0.0"
from sen0414_ch06_helpers_v1_0_0 import W, Y, E, H, K, C, PROG, VPROG

RAW = []
CHECKS = []
RAISES = []
CP = "__import__('copy')"

# ============================================================ Looping and unpacking
RAW += [
 ("LoopsUnpacking", "Looping and unpacking", 1, None, None, [
  (W, "A list is made to be walked through, and this branch explains the ways of doing it that the chapter and the documentation teach: the for loop over the items, the loop over the indexes with range(len(...)), the enumerate function that supplies both, the list comprehension that builds a new list from an old one, and the unpacking of a list into several variables [SW]. It also states the one rule about loops that every programmer must remember, which is not to change a list while a loop is walking through it."),
  (Y, "Most of what a program does with a list is done once for each item. The choice among the forms is a choice of clarity: the loop over the items is the shortest, the loop over the indexes is needed when the position matters, enumerate says that plainly, and the comprehension says that the result is a new list. Learning them together shows that they are different views of one idea, repeating a step for every item of a sequence."),
  (E, "Every program in the later chapters that reads a file, a spreadsheet or a web page has a loop over a list in it. The Matrix screensaver at the end of this chapter loops over the indexes of its column counters, the cat-name program loops over the names it has collected, and the unpacking of a pair into two names appears in every loop over the items of a dictionary in the next chapter [PSF]."),
  (H, "The branch has two groups. The first, looping, explains the loop over indexes, enumerate, the danger of changing a list during a loop, and the list comprehension. The second, unpacking, explains the multiple assignment trick and the starred form that collects the rest."),
 ], None),
 ("Looping", "Looping over a list", 2, "LoopsUnpacking", None, [
  (W, "Technically, a for loop repeats its block once for each item in a list value [SW]. The group explains the four forms that matter in practice: the loop over the indexes, the loop that counts with enumerate, the loop that must not change its own list, and the comprehension that replaces a loop that builds a list."),
  (Y, "The forms differ in what they give the loop body: the item, the index, both, or a new list at the end. Choosing the form that gives exactly what the body needs removes the index arithmetic that is the commonest source of off-by-one errors."),
  (H, "The first concept shows how range and a list behave alike in a for loop and how range(len(supplies)) reaches every index. The second shows enumerate, the third the trap of removing items during a loop, and the fourth the list comprehension."),
 ], None),
 ("RangeLenLoop", "Loop over the indexes", 3, "Looping", ("for i in range(len(supplies)):", "Writing range(len(some_list)) in a for loop visits every index of the list from 0 to len minus 1, whatever the length, so the body can use both i and some_list[i].", ("[(i, s) for i, s in enumerate(['pens', 'staplers', 'flamethrowers', 'binders'])]", "[(0, 'pens'), (1, 'staplers'), (2, 'flamethrowers'), (3, 'binders')]")), [
  (W, "A for loop runs its block once for each item in a sequence, and the loop variable takes the items one after another. The chapter shows that for i in range(4) prints 0, 1, 2 and 3 because the value that range(4) returns is a sequence that Python considers to be similar to [0, 1, 2, 3], and that for i in [0, 1, 2, 3] gives the same output [SW]. A common technique that follows from this is to use range(len(some_list)) with a for loop to iterate over the indexes of a list."),
  (Y, "The form is handy because the code in the loop can access the index, as the variable i, and the value at that index, as supplies[i]. Best of all, range(len(supplies)) iterates through all the indexes of the list, no matter how many items it contains [SW]. It is the form to choose when the loop must change items in place, compare an item with its neighbour, or print the position, since all of these need the index."),
  (E, "The chapter's example uses supplies = ['pens', 'staplers', 'flamethrowers', 'binders'] and prints Index 0 in supplies is: pens, then the same for 1, 2 and 3. In the executed examples the indexes visited are [0, 1, 2, 3], the length of the list being 4, and the same loop on an empty list runs zero times, because range(0) is empty. The form with a neighbour compares supplies[i] with supplies[i + 1] for i in range(len(supplies) - 1); stopping one place early is what keeps the last comparison valid."),
  (H, "The call len(supplies) is evaluated once, when the loop starts, and range builds a lazy sequence of the integers from 0 up to but not including that length. Each pass binds i to the next integer and runs the body. If the body adds or removes items, the range does not change, so the loop may then reach an index that no longer exists or miss new items. A for loop over the list itself, on the other hand, follows the list as it is."),
  (K, "When the body needs only the items, loop over the list itself: for item in supplies is shorter and cannot go out of range. When it needs both, prefer enumerate, which comes next. Using range(len(...)) is correct but it is the form in which an index error is easiest to make, as in range(len(supplies) + 1), which reads one place too far and raises an IndexError at the last pass."),
 ]),
 ("EnumerateLoop", "enumerate function", 3, "Looping", ("for index, item in enumerate(supplies):", "The built-in function enumerate yields a pair of the index and the item on each pass of the loop, so the body needs no index arithmetic.", ("list(enumerate(['pens', 'staplers']))", "[(0, 'pens'), (1, 'staplers')]")), [
  (W, "Instead of the range(len(some_list)) technique, a program can call the enumerate function. On each iteration of the loop, enumerate returns two values: the index of the item in the list, and the item in the list itself [SW]. The loop for index, item in enumerate(supplies) is equivalent to the loop over range(len(supplies)) and prints Index 0 in supplies is: pens and so on. The documentation defines enumerate as returning an iterator of pairs, each made of a count and the value obtained from iterating over the sequence [PSF]."),
  (Y, "The function is useful if you need both the item and the item's index in the loop's block [SW]. It states the purpose of the loop in the first line, it removes the expression supplies[i] from the body, and it works on anything that can be looped over, not only on lists. A reader who sees enumerate knows at once that the position is used."),
  (E, "In the executed examples list(enumerate(['pens', 'staplers'])) is [(0, 'pens'), (1, 'staplers')], so each pair is a tuple of two values, which the loop header unpacks into index and item. The optional start argument changes the first number: list(enumerate(['a', 'b'], start=1)) is [(1, 'a'), (2, 'b')], which is handy for numbered lists that a person reads. The cat-name program of the chapter could print the names with their numbers in one line of the header."),
  (H, "The function does not build a list of pairs. It returns an object that produces the next pair each time the loop asks for one, so it uses no more memory for a list of a million items than for a list of ten. The pair is a tuple, and the header index, item is the multiple assignment trick of the next group, applied once on each pass."),
  (K, "The order is fixed: the index comes first and the item second, and writing for item, index in enumerate(...) swaps the meaning without any error message. The count starts at zero unless the start argument says otherwise, so a printed list for people usually needs start=1. And since enumerate gives an iterator, printing it directly shows an object description and not the pairs; wrap it in list to see them."),
 ]),
 ("MutationWhileIterating", "Changing a list during a loop", 3, "Looping", ("for x in items: items.remove(x)", "A list iterator counts positions, so removing items during a for loop moves later items into positions the loop has passed and skips them; loop over a copy or build a new list instead.", ("(lambda items: ([items.remove(x) for x in items], items)[1])(['a', 'b', 'c', 'd'])", "['b', 'd']")), [
  (W, "Code that changes a list while a for loop is walking through that same list can be tricky to get right, as the tutorial warns, and the usual advice is to loop over a copy of the collection or to create a new collection [PSF]. The behaviour has a simple cause: the loop does not remember the items, it remembers a position, and it asks the list for the item at that position on every pass."),
  (Y, "A program that removes the items that do not fit a condition is one of the commonest tasks with a list, and it is the place where beginners lose items without an error. The result looks plausible, the program does not stop, and the missing items may be noticed only much later. The rule in this concept is therefore among the most valuable of the chapter: never add or remove items of the list that the loop is reading."),
  (E, "In the executed examples, removing every item of ['a', 'b', 'c', 'd'] inside a loop over the same list leaves ['b', 'd'] and not the empty list. The loop starts at position 0 and removes 'a'; the other items move one place to the left, so 'b' is now at position 0, and the loop moves on to position 1, which holds 'c', and removes it; 'd' has moved to position 1, the next position is 2, which is past the end, and the loop stops. Removing the even numbers from [1, 2, 3, 4, 5, 6] this way happens to give the right answer, [1, 3, 5], which hides the fault."),
  (H, "The list iterator of the for statement holds a counter that starts at 0 and grows by one on every pass, and it stops when the counter equals the current length of the list. Removing an item moves every later item one place to the left and so shifts the items under the counter. Adding items at the front has the opposite effect, so that the loop meets the same item twice; adding at the end can make the loop run for ever."),
  (K, "The remedies are three. Loop over a copy: for x in items[:] reads the copy and changes the original. Build a new list instead of changing the old one, with a comprehension such as [x for x in items if keep(x)], and give it the old name. Or loop over the indexes backwards, from the last to the first, so that a removal affects only positions the loop has already passed. The first two are clearer, and the comprehension is the one the documentation prefers."),
 ]),
 ("ListComprehension", "List comprehension", 3, "Looping", ("[x**2 for x in range(10)]", "A list comprehension builds a new list in one expression from an expression, a for clause and an optional if clause, in place of a loop that appends to an empty list.", ("[x**2 for x in range(10)]", "[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]")), [
  (W, "A list comprehension is a concise way to create a list in one expression. Its brackets contain an expression followed by a for clause, then zero or more for or if clauses; the result is a new list made by evaluating the expression for each item that the clauses produce [PSF]. The expression [x**2 for x in range(10)] is the list of the squares of 0 to 9, and [x for x in range(10) if x % 2 == 0] keeps only the even numbers. The proposal that added the notation to the language in version 2.0 describes it as a way to build a list without the map, filter and lambda forms [PEP202]."),
  (Y, "The comprehension turns a pattern of four lines, creating an empty list, looping, testing and appending, into one line that says what the new list contains. It is also the answer to the previous concept: a comprehension with an if clause builds a filtered list without touching the old one. The tutorial uses it for transposing a matrix, for flattening a list of lists and for building the independent rows of a grid [PSF]."),
  (E, "In the executed examples [x**2 for x in range(10)] is [0, 1, 4, 9, 16, 25, 36, 49, 64, 81] and the filtered form gives [0, 2, 4, 6, 8]. A grid of two independent rows of three zeros is [[0] * 3 for _ in range(2)], and unlike [[0] * 3] * 2 a change to one row stays in that row. The variable of the comprehension belongs to the comprehension: it does not leak into the surrounding code, which is the difference from a for loop."),
  (H, "Python evaluates the clauses from left to right as nested loops, tests the if clauses, evaluates the expression for each pair that passes and appends the value to a new list. It does not change any list that it reads. When the clauses name more than one for, as in [(a, b) for a in 'xy' for b in (1, 2)], the first runs as the outer loop and the second as the inner loop, which gives [('x', 1), ('x', 2), ('y', 1), ('y', 2)]."),
  (K, "A comprehension that grows beyond one short line is harder to read than the loop it replaces, and the programmer should choose the clearer form. A comprehension is for building a list, not for its side effects: writing one only to call a function on each item builds a list that nobody uses. And the result is a list in memory, so a comprehension over a very large input should be a generator expression, which the later chapters explain."),
 ]),
 ("Unpacking", "Unpacking a list", 2, "LoopsUnpacking", None, [
  (W, "Unpacking assigns the items of a list to several variables in one statement. The group has two concepts: the multiple assignment trick, in which the number of names must match the number of items, and the starred form, in which one name collects whatever is left over. The chapter calls the multiple assignment trick technically tuple unpacking [SW]."),
  (Y, "Unpacking makes code shorter and more readable than separate index expressions, and it names the parts of a record at the place where they are taken apart. It is the mechanism behind the loop header of enumerate, behind swapping two variables in one line, and behind the way functions return several values."),
  (H, "The first concept explains the trick and its ValueError when the counts differ. The second explains the starred name that makes the counts agree whatever the length."),
 ], None),
 ("MultipleAssignment", "Multiple assignment trick", 3, "Unpacking", ("size, color, disposition = cat", "Assigning a list to several names assigns its items to the names from left to right; the number of names and the length of the list must be equal or Python raises a ValueError.", ("[(size, color, disposition) for size, color, disposition in [['fat', 'gray', 'loud']]][0]", "('fat', 'gray', 'loud')")), [
  (W, "The multiple assignment trick, technically called tuple unpacking, is a shortcut that lets you assign multiple variables with the values in a list in one line of code [SW]. Instead of writing size = cat[0], color = cat[1] and disposition = cat[2], the program writes size, color, disposition = cat, with cat holding ['fat', 'gray', 'loud']. The reference describes the rule: if the target list is a comma-separated list of targets, the object must be an iterable with the same number of items as there are targets, and the items are assigned from left to right [PSF]."),
  (Y, "This trick makes your code shorter and more readable than entering three separate lines of code [SW]. The names say what each item means, which index numbers cannot. It also swaps two variables without a helper: a, b = b, a evaluates the right side first, as a pair, and then assigns, so a, b = 1, 2 followed by a, b = b, a leaves a equal to 2 and b equal to 1."),
  (E, "In the executed examples size, color, disposition = ['fat', 'gray', 'loud'] gives size equal to 'fat', color equal to 'gray' and disposition equal to 'loud'. If the number of variables and the length of the list are not exactly equal, Python gives a ValueError: with four names and three items the message is not enough values to unpack (expected 4, got 3), and with two names and three items it is too many values to unpack (expected 2, got 3) in Python 3.14, where Python 3.12 and 3.13 write only (expected 2). Any iterable can be unpacked, so a, b = 'xy' gives 'x' and 'y'."),
  (H, "Python evaluates the right-hand side first, takes the iterable apart item by item, counts the items and, if the count matches, binds the names from left to right. If the count does not match, it raises the error before any name is changed. The statement works with a list on the right and with a tuple on the right, since only the count matters, and it nests: (a, b), c = [1, 2], 3 binds a, b and c."),
  (K, "The count must be exactly right, so unpacking is a good fit for data of a known shape, such as a record with fixed fields, and a poor fit for lists of unknown length. For those, use the starred form of the next concept, or an index. Do not use the trick on a list that may be empty without checking its length first, since the ValueError that it raises names counts and not the cause."),
 ]),
 ("StarredUnpacking", "Starred unpacking", 3, "Unpacking", ("first, *rest = cat", "One starred name in an unpacking collects the leftover items into a list, so the counts always agree; the starred name receives an empty list when nothing is left.", ("[(first, rest) for first, *rest in [[1, 2, 3, 4]]][0]", "(1, [2, 3, 4])")), [
  (W, "Starred unpacking allows one name in the target list to be prefixed with an asterisk, and that name collects all the items that the other names do not take, as a list. The proposal that added it to the language in version 3.0 gives first, *rest = seq as the model: the first item goes to first and the rest goes to rest [PEP3132]. The reference states that the starred name is assigned a list of the items left over [PSF]."),
  (Y, "The ordinary trick needs the number of items in advance, and the starred form removes the need. It splits a list into head and tail without slicing, takes the last item and the rest in one statement, and picks out the ends of a list of any length. The proposal motivates it by the common case of splitting a sequence into a head and the remainder [PEP3132]."),
  (E, "In the executed examples first, *rest = [1, 2, 3, 4] gives first equal to 1 and rest equal to [2, 3, 4], and *init, last = [1, 2, 3, 4] gives init equal to [1, 2, 3] and last equal to 4. The starred name may also be in the middle: a, *middle, z = [1, 2, 3, 4] gives middle equal to [2, 3]. With only two items the middle is empty: a, *m, z = [1, 2] gives m equal to []. The starred name is always a list, even when the source was a tuple or a string."),
  (H, "Python first assigns the items to the plain names before and after the starred name, which need at least that many items, and then gives the starred name a new list of whatever lies between. The starred name therefore never fails by count, but the other names still can: if there are fewer items than plain names, the ValueError is raised as before. Only one starred name is allowed in a target list, and a starred name alone must be inside a list or a tuple."),
  (K, "The starred name makes a new list, so a change to rest does not change the source. Do not confuse the starred target on the left of an assignment with the star in front of an argument or a list item on the right, as in [*a, *b], which spreads the items of two lists into one new list [PEP448]; the two share a symbol and do opposite things."),
 ]),
]

CHECKS += [("[i for i in range(4)] == [0, 1, 2, 3]", "True"), ("list(range(4))", "[0, 1, 2, 3]"),
           PROG("for i in range(4):\n    print(i)\n", "0\n1\n2\n3\n"), PROG("for i in [0, 1, 2, 3]:\n    print(i)\n", "0\n1\n2\n3\n"),
           PROG("supplies = ['pens', 'staplers', 'flamethrowers', 'binders']\nfor i in range(len(supplies)):\n    print('Index ' + str(i) + ' in supplies is: ' + supplies[i])\n", "Index 0 in supplies is: pens\nIndex 1 in supplies is: staplers\nIndex 2 in supplies is: flamethrowers\nIndex 3 in supplies is: binders\n"),
           ("list(range(len(['pens', 'staplers', 'flamethrowers', 'binders'])))", "[0, 1, 2, 3]"), ("list(range(len([])))", "[]"), ("[i for i in range(len([]))]", "[]"),
           ("(lambda s: [(s[i], s[i + 1]) for i in range(len(s) - 1)])([1, 2, 3])", "[(1, 2), (2, 3)]"),
           PROG("supplies = ['pens', 'staplers']\ntry:\n    for i in range(len(supplies) + 1):\n        print(supplies[i])\nexcept IndexError as e:\n    print(e)\n", "pens\nstaplers\nlist index out of range\n"),
           PROG("supplies = ['pens', 'staplers', 'flamethrowers', 'binders']\nfor index, item in enumerate(supplies):\n    print('Index ' + str(index) + ' in supplies is: ' + item)\n", "Index 0 in supplies is: pens\nIndex 1 in supplies is: staplers\nIndex 2 in supplies is: flamethrowers\nIndex 3 in supplies is: binders\n"),
           ("[(i, s) for i, s in enumerate(['pens', 'staplers', 'flamethrowers', 'binders'])]", "[(0, 'pens'), (1, 'staplers'), (2, 'flamethrowers'), (3, 'binders')]"),
           ("list(enumerate(['pens', 'staplers']))", "[(0, 'pens'), (1, 'staplers')]"), ("list(enumerate(['a', 'b'], start=1))", "[(1, 'a'), (2, 'b')]"),
           ("type(enumerate(['a'])).__name__", "'enumerate'"),
           ("(lambda items: ([items.remove(x) for x in items], items)[1])(['a', 'b', 'c', 'd'])", "['b', 'd']"),
           ("(lambda items: ([items.remove(x) for x in items if x % 2 == 0], items)[1])([1, 2, 3, 4, 5, 6])", "[1, 3, 5]"),
           ("(lambda items: ([items.remove(x) for x in items[:]], items)[1])(['a', 'b', 'c', 'd'])", "[]"),
           ("[x for x in ['a', 'b', 'c', 'd'] if x not in ('a', 'c')]", "['b', 'd']"),
           ("(lambda items: [items.pop(i) for i in range(len(items) - 1, -1, -1)] and items)([1, 2, 3])", "[]"),
           ("[x**2 for x in range(10)]", "[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]"), ("[x for x in range(10) if x % 2 == 0]", "[0, 2, 4, 6, 8]"),
           ("(g := [[0] * 3 for _ in range(2)], g[0].__setitem__(0, 9), g)[2]", "[[9, 0, 0], [0, 0, 0]]"),
           ("[(a, b) for a in 'xy' for b in (1, 2)]", "[('x', 1), ('x', 2), ('y', 1), ('y', 2)]"),
           ("[[row[i] for row in [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]] for i in range(4)]", "[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]"),
           ("[n for row in [[1, 2], [3]] for n in row]", "[1, 2, 3]"),
           PROG("x = 'outside'\n_ = [x for x in range(3)]\nprint(x)\n", "outside\n"),
           PROG("cat = ['fat', 'gray', 'loud']\nsize, color, disposition = cat\nprint(size, color, disposition)\n", "fat gray loud\n"),
           PROG("try:\n    cat = ['fat', 'gray', 'loud']\n    size, color, disposition, name = cat\nexcept ValueError as e:\n    print(e)\n", "not enough values to unpack (expected 4, got 3)\n"),
           VPROG("try:\n    a, b = ['fat', 'gray', 'loud']\nexcept ValueError as e:\n    print(e)\n", "too many values to unpack (expected 2, got 3)\n", "too many values to unpack (expected 2)\n"),
           PROG("a, b = 1, 2\na, b = b, a\nprint(a, b)\n", "2 1\n"), PROG("a, b = 'xy'\nprint(a, b)\n", "x y\n"), PROG("(a, b), c = [1, 2], 3\nprint(a, b, c)\n", "1 2 3\n"),
           ("[(first, rest) for first, *rest in [[1, 2, 3, 4]]][0]", "(1, [2, 3, 4])"),
           PROG("first, *rest = [1, 2, 3, 4]\nprint(first, rest)\n", "1 [2, 3, 4]\n"), PROG("*init, last = [1, 2, 3, 4]\nprint(init, last)\n", "[1, 2, 3] 4\n"),
           PROG("a, *middle, z = [1, 2, 3, 4]\nprint(a, middle, z)\n", "1 [2, 3] 4\n"), PROG("a, *m, z = [1, 2]\nprint(a, m, z)\n", "1 [] 2\n"),
           PROG("a, *rest = (1, 2, 3)\nprint(rest)\nb, *s = 'xyz'\nprint(s)\n", "[2, 3]\n['y', 'z']\n"),
           PROG("a, b, *c = [1]\n", "", stream="returncode").__class__ and ("[*[1, 2], *[3]]", "[1, 2, 3]")]
RAISES += [("(lambda a, b, c, d: 0)(*['fat', 'gray', 'loud'])", "TypeError"), ("(lambda s: s[len(s)])(['pens', 'staplers'])", "IndexError")]

# ============================================================ Sequences and references
RAW += [
 ("SequencesReferences", "Sequences and references", 1, None, None, [
  (W, "Lists are one of several sequence data types, and this branch places them among their relatives and then explains the idea behind the chapter's most surprising behaviours. It covers the sequences that work like lists (strings and ranges), the difference between values that can be changed and values that cannot, the tuple, and the references by which names refer to values, with the consequences for assignment, function arguments, repeated lists and copies [SW]."),
  (Y, "Beginners meet the same surprise in many forms: a change made through one name shows through another, a function changes the list it was given, a grid built by repetition changes all of its rows at once. All of these are one fact seen from different sides, and the chapter's summary states it as variables do not store list values directly, they store references to lists. A programmer who knows the fact can predict every one of the surprises."),
  (E, "References decide how functions behave in every later chapter: a function that is passed a list or a dictionary can change it, a function that is passed a number or a string cannot. The choice between a list and a tuple, the copying of data before it is changed, and the building of tables of independent rows all come back in the chapters on dictionaries, files and data [PSF]."),
  (H, "The branch has three groups. Sequence types explains strings and ranges as sequences, the difference between mutable and immutable types, and the tuple. References explains the name-tag picture, function arguments and the repeated list. Copying explains copy.copy and copy.deepcopy."),
 ], None),
 ("SequenceTypes", "Sequence types", 2, "SequencesReferences", None, [
  (W, "The Python sequence data types include lists, strings, range objects returned by range(), and tuples [SW]. The group explains what they have in common, why lists differ from strings and tuples in being changeable, and how the tuple is written and used."),
  (Y, "Recognising a sequence tells a programmer what can be done with a value before looking anything up: indexing, slicing, looping, len and the in operator all work. Knowing which sequences can be changed tells the programmer whether a mistake can alter data in another part of the program."),
  (H, "The first concept shows the operations a string shares with a list. The second explains mutable and immutable values with the string and the list. The third explains the tuple and the conversion functions list and tuple."),
 ], None),
 ("StringSequence", "Strings and ranges as sequences", 3, "SequenceTypes", ("name[0], name[-2], name[0:4], 'Zo' in name", "Strings and range objects are sequences like lists: they can be indexed, sliced, looped over, measured with len and searched with in and not in.", ("('Zophie'[0], 'Zophie'[-2], 'Zophie'[0:4], 'Zo' in 'Zophie')", "('Z', 'i', 'Zoph', True)")), [
  (W, "Lists are not the only data types that represent ordered sequences of values. Strings and lists are similar if you consider a string to be a list of single text characters. The Python sequence data types include lists, strings, range objects returned by range(), and tuples, and many of the things you can do with lists can also be done with strings and other sequence values [SW]. You can index them, slice them, loop over them, ask for their length with len, and test them with the in and not in operators."),
  (Y, "The common notation means that what a learner knows about lists carries over. The same square brackets, the same zero-based counting and the same half-open slices are used for text, for ranges and for tuples, and a function written for one sequence often works for the others. The documentation lists the operations that all sequence types support in one table and those that only mutable types support in another [PSF]."),
  (E, "The chapter's example uses name = 'Zophie'. The first character name[0] is 'Z', the second to last name[-2] is 'i', the slice name[0:4] is 'Zoph', 'Zo' in name is True, 'z' in name is False because the test respects the case, and 'p' not in name is False. A loop over the string prints each character in turn, with the chapter's decoration * * * Z * * * for the first. Ranges behave the same way: range(5)[2] is 2, 3 in range(5) is True and range(0, 10, 2)[1:3] is range(2, 6, 2), a smaller range and not a list."),
  (H, "What the types share is a protocol: each can report its length, give the item at an integer position, and be walked through in order. Indexing, slicing, len, in and for are written once in terms of the protocol, which is why they work on all four types. They differ in what an item is (a character, an integer, any value) and in whether they can be changed."),
  (K, "The in operator has a different meaning for strings than for lists: 'ab' in 'cabd' tests for a substring of any length, while 'ab' in ['cabd'] tests for an item equal to 'ab'. A string slice is again a string and a list slice is a list, so a program that expects a list from a string operation must convert with list(). And the characters of a string are strings of length one, so 'a' in 'abc' and 'a' == 'abc'[0] are both True."),
 ]),
 ("MutableImmutable", "Mutable and immutable values", 3, "SequenceTypes", ("name[7] = 'the'", "A list is mutable: its items can be added, removed and replaced in place; a string is immutable and an attempt to change one of its characters raises a TypeError.", ("(lambda eggs: (lambda before: (eggs.__setitem__(0, 'x'), id(eggs) == before)[1])(id(eggs)))(['A', 'B', 'C'])", "True")), [
  (W, "A list value is a mutable data type: you can add, remove or change its values. A string, however, is immutable: it cannot be changed [SW]. Trying to reassign a single character of a string, as in name[7] = 'the', raises a TypeError whose message is 'str' object does not support item assignment. The proper way to mutate a string is to build a new string from parts of the old one with slicing and concatenation: name[0:7] + 'the' + name[8:12] turns 'Zophie a cat' into 'Zophie the cat' and leaves the original untouched."),
  (Y, "The distinction decides what a function or a second name can do to a value. A value that cannot change is safe to share, and a value that can change is a shared state whoever holds it. The chapter promises that mutable and immutable types will explain the different behaviour when calling functions with mutable arguments versus immutable arguments, and the references concepts below keep the promise. Immutability is also what allows a value to be used as a key of a dictionary, which the next chapter needs."),
  (E, "The chapter's second example separates two things that look alike. After eggs = ['A', 'B', 'C'] the line eggs = ['x', 'y', 'z'] does not modify the list in eggs; a new and entirely different list replaces the old one. To modify the original list the program must use del and append, three del statements and three appends, after which eggs holds ['x', 'y', 'z'] in the same list value it started with. This is called changing the list in place. In the executed example the identity of the list is the same before and after the in-place change and different after the reassignment."),
  (H, "Assigning to a name binds the name to a value and so never changes a value. A method or an item assignment, on the other hand, acts on the value itself, if the type allows it. Strings, numbers, tuples and None are immutable, so every operation on them gives a new value; lists, dictionaries and sets are mutable. An immutable value has a hash that never changes, so hash((1, 2)) works while hash([1]) raises a TypeError with the message unhashable type: 'list'."),
  (K, "The confusion between rebinding and mutating is behind the commonest surprises of the chapter. A line such as spam = spam + [1] makes a new list and rebinds the name, so other names that referred to the old list do not see it, while spam += [1] and spam.append(1) change the list that all of them share. When in doubt, ask whether the line changes what the name refers to or what the value contains."),
 ]),
 ("TupleType", "Tuple", 3, "SequenceTypes", ("eggs = ('hello', 42, 0.5)", "A tuple is an immutable sequence written with commas, usually in parentheses; it supports indexing, slicing and len like a list but raises a TypeError on item assignment.", ("(lambda eggs: (eggs[0], eggs[1:3], len(eggs)))(('hello', 42, 0.5))", "('hello', (42, 0.5), 3)")), [
  (W, "There are only two differences between the tuple data type and the list data type. The first is that tuples are written with parentheses instead of square brackets. The second and primary one is that tuples, like strings, are immutable: you cannot modify, append or remove their values [SW]. With eggs = ('hello', 42, 0.5), eggs[0] is 'hello', eggs[1:3] is (42, 0.5) and len(eggs) is 3, but eggs[1] = 99 raises a TypeError with the message 'tuple' object does not support item assignment."),
  (Y, "A tuple tells anyone reading the code that the sequence of values is not meant to change. The chapter gives a second benefit: because tuples are immutable and their contents do not change, Python can implement optimizations that make code using tuples slightly faster than code using lists. A tuple whose items are all immutable can be used as a dictionary key, and a list cannot. The documentation describes the usual uses: tuples hold heterogeneous data, such as the pairs of enumerate, and lists hold homogeneous data [PSF]."),
  (E, "A tuple with a single value needs a trailing comma: type(('hello',)) is a tuple, while type(('hello')) is a str, because without the comma the parentheses are only grouping. The functions tuple() and list() convert between the types: tuple(['cat', 'dog', 5]) is ('cat', 'dog', 5), list(('cat', 'dog', 5)) is ['cat', 'dog', 5] and list('hello') is ['h', 'e', 'l', 'l', 'o']. Converting a tuple to a list is handy if you need a mutable version of a tuple value [SW]. The empty tuple is written ()."),
  (H, "It is the comma that makes the tuple and the parentheses only group, which is why x = 1, 2 is a tuple and why the multiple assignment trick and the return of two values from a function use tuples without writing a single parenthesis. The tuple holds references, as every container does, so it is immutable in the sense that its references cannot be replaced, not that the objects they point to cannot change."),
  (K, "A tuple that contains a list does not freeze the list. With t = ([1],) the statement t[0].append(2) changes the list and leaves t equal to ([1, 2],). The FAQ shows the odd case t[0] += [2], which raises a TypeError because the assignment back into the tuple is refused, although the list has already been extended [PSF]. And the missing comma, ('hello') for ('hello',), is the commonest slip."),
 ]),
 ("References", "Names and references", 2, "SequencesReferences", None, [
  (W, "A common metaphor is that variables are boxes that store values, but this explanation is a simplification of what Python does. A better metaphor is that variables are paper name tags attached to values with string [SW]. The group explains the consequences of the name-tag picture: assignment copies a reference, a function receives a reference, and repeating a list repeats references."),
  (Y, "With the name-tag picture, the behaviour of lists stops being strange. Two names on one list is not a bug but the meaning of assignment, and the chapter offers two rules to hold on to: variables never contain values, they contain only references to values, and the assignment operator copies only references, it never copies values."),
  (H, "The first concept explains aliasing with the spam and eggs example. The second explains function arguments, the third the repeated list, and the group after this one explains how to make a real copy."),
 ], None),
 ("Aliasing", "Aliasing", 3, "References", ("eggs = spam", "Assigning one variable to another copies the reference, not the value, so for a list both names refer to the same list and a change made through either shows through both.", ("(lambda spam: (lambda eggs: (eggs.__setitem__(1, 'Hello!'), spam, eggs is spam))(spam))([0, 1, 2, 3])[1:]", "([0, 'Hello!', 2, 3], True)")), [
  (W, "When you assign 42 to the variable spam, you are creating the 42 value in the computer's memory and storing a reference to it in the variable. When you copy the value in spam and assign it to eggs, you are copying the reference; both variables refer to the same 42 [SW]. Changing spam afterwards, with spam = 99, attaches the name tag to a new value, and eggs still refers to 42. Aliasing is the name for two or more names referring to the same value."),
  (Y, "For a number nobody notices, since the number cannot change. For a list the effect is the main thing to understand in the chapter. The line eggs = spam copies only the reference; there is still only one list, and spam and eggs both refer to it. Changing the first item through eggs changes it for spam as well. The chapter calls the code odd-looking at first sight, and it is the reason the next concepts exist [SW]."),
  (E, "In the executed examples, after spam = [0, 1, 2, 3] and eggs = spam, the assignment eggs[1] = 'Hello!' makes both spam and eggs equal to [0, 'Hello!', 2, 3], and spam is eggs is True. For the number the result differs: after spam = 42, eggs = spam and spam = 99, spam is 99 and eggs is still 42. The operator is tests whether two names refer to the same object, and the built-in function id gives the identity, which is the same for both names of an alias."),
  (H, "A variable is an entry that maps a name to an object. Assignment of the form name = expression evaluates the expression and binds the name to the resulting object; with a name on the right the object is the very one the other name has. The reference data model puts it this way: every object has an identity, a type and a value; the identity never changes, and the is operator compares identities [PSF]. The list is one object with one identity however many names it has."),
  (K, "Aliasing is useful when it is meant and harmful when it is not. If a program needs an independent list, it has to copy it, as the next group explains. When a bug shows a list that changed for no visible reason, search the program for every place where the list is assigned to another name, passed to a function or stored in another list, since any of them may hold the same list."),
 ]),
 ("ListArguments", "Lists as function arguments", 3, "References", ("def eggs(some_parameter): some_parameter.append('Hello')", "A function receives a copy of the reference, so a function that changes a list argument in place changes the caller's list, while rebinding the parameter has no effect outside.", ("(lambda eggs: (lambda spam: (eggs(spam), spam)[1])([1, 2, 3]))(lambda p: p.append('Hello'))", "[1, 2, 3, 'Hello']")), [
  (W, "References are particularly important for understanding how arguments get passed to functions. When a function is called, Python copies the reference to the arguments to the parameter variables. For mutable values like lists, this means the code in the function modifies the original value in place [SW]. In the chapter's program the function eggs appends 'Hello' to its parameter; with spam = [1, 2, 3], the call eggs(spam) leaves spam equal to [1, 2, 3, 'Hello'], although the function returns nothing."),
  (Y, "A function that changes its list argument can be useful, since it avoids copying a large list, and it is what the list methods themselves do. It can also be the cause of confusing bugs. The chapter warns that forgetting that Python handles list and dictionary variables in this way can lead to unexpected behaviour. A reader of a function should know whether it changes its arguments, and a writer should say so in its name or its documentation."),
  (E, "In the executed examples, even though spam and some_parameter contain separate references, they both refer to the same list, which is why the append inside the function affects the list after the call has returned. A function that builds a new list and returns it behaves differently: with def f(p): p = p + ['x']; return p the call f(spam) returns [1, 2, 3, 'x'] and spam is still [1, 2, 3]. A function that uses p += ['x'] changes the caller's list again, because += on a list extends it in place."),
  (H, "The parameter is a new name bound to the same object as the argument. Anything done through the object, such as append, is seen by the caller. Assignment to the parameter, as in p = something, only moves the parameter's name tag and the caller's is untouched. This is the rule that the community describes as passing the object reference; it is neither a copy of the value nor a way for the function to rebind the caller's variable."),
  (K, "To protect the caller's list, copy it at the top of the function or build a new list instead of changing the old one, and to change it on purpose, document it. A related trap is a mutable default value in the definition, such as def f(items=[]), which is created once and shared by all calls; the FAQ explains why, and the usual cure is a default of None [PSF]."),
 ]),
 ("ReplicationAliasing", "Repeating a list of lists", 3, "References", ("[[0] * 3] * 2", "Repeating a list with * repeats references to the same items, so a list of lists built this way holds several references to one inner list.", ("(lambda g: (g[0].__setitem__(0, 9), g, g[0] is g[1])[1:])([[0] * 3] * 2)", "([[9, 0, 0], [9, 0, 0]], True)")), [
  (W, "The replication operator * repeats the items of a list, but it repeats the references to them and does not copy the objects they refer to. For a list of numbers or strings this is harmless, since those cannot change. For a list whose item is itself a list, [[0] * 3] * 2, the result holds two references to one inner list. The documentation says it in so many words: copies are shallow, and the items of the list are not copied but referenced multiple times [PSF]."),
  (Y, "The case matters because the notation looks like the natural way to build a table. The Python FAQ spends a whole entry on it under the heading how do I create a multidimensional list, and it gives the cure in the same place [PSF]. A student who has met the case once will never build a grid by repeating a row, and will know the general rule behind it: a list holds references, and operators that make more references do not make more objects."),
  (E, "In the executed examples g = [[0] * 3] * 2 is [[0, 0, 0], [0, 0, 0]], and after g[0][0] = 9 the grid is [[9, 0, 0], [9, 0, 0]], since g[0] is g[1] is True. Building the rows with a comprehension, g = [[0] * 3 for _ in range(2)], evaluates [0] * 3 once for every row and so gives two separate lists; the same assignment then changes only the first row, giving [[9, 0, 0], [0, 0, 0]], and g[0] is g[1] is False. The Matrix screensaver of this chapter safely uses the replication [0] * WIDTH, since a list of integers is made of immutable items."),
  (H, "The expression [0] * 3 evaluates its left operand once, so it produces a single inner list. The outer replication copies its reference twice. A comprehension, on the other hand, evaluates the inner expression again for every pass, so each row is a new object. The same distinction explains why x = y = [] makes one list and not two, and why a list that contains itself is possible: the reference to the list can be stored inside the list."),
  (K, "Use replication for flat lists of immutable items, as in [0] * WIDTH, and a comprehension for lists of lists. If a grid behaves as if its rows were linked, test it with the is operator on two rows before debugging anything else, since that test tells at once whether the rows are the same object."),
 ]),
 ("Copying", "Copying lists", 2, "SequencesReferences", None, [
  (W, "To make a list that is independent of another, a program has to copy it. Python provides a module named copy for the purpose, with the functions copy.copy and copy.deepcopy, and the list type has its own copy method and the slice [:] that do the same as the first of them [SW]. The group explains the two kinds of copying and when to use each."),
  (Y, "Passing around references is often the handiest way to deal with lists, but if a function modifies the list passed to it, you may not want these changes in the original list [SW]. Copying is the tool that gives a function or a second variable its own list to change."),
  (H, "The first concept explains the shallow copy, which makes a new outer list that shares its items. The second explains the deep copy, which copies the inner lists as well."),
 ], None),
 ("ShallowCopy", "Shallow copy", 3, "Copying", ("cheese = copy.copy(spam)", "The function copy.copy makes a new list that holds references to the same items as the original; changing an item of the copy does not change the original, but changing a shared inner list shows through both.", ("(lambda s: (lambda c: (c.__setitem__(1, 42), s, c))(" + CP + ".copy(s)))(['A', 'B', 'C'])[1:]", "(['A', 'B', 'C'], ['A', 42, 'C'])")), [
  (W, "The function copy.copy can make a duplicate copy of a mutable value like a list. After import copy, spam = ['A', 'B', 'C'] and cheese = copy.copy(spam), the assignment cheese[1] = 42 changes the copy and leaves spam as ['A', 'B', 'C'], while cheese becomes ['A', 42, 'C']. The spam and cheese variables now refer to separate lists [SW]. The list method copy and the slice spam[:] make the same kind of copy; the documentation calls them shallow copies and says that a shallow copy constructs a new compound object and then inserts into it references to the objects found in the original [PSF]."),
  (Y, "The copy gives a function or a second variable a list it may change without affecting the first. It is the right tool when the items are immutable, such as numbers and strings, and the cheap one, since only the outer list is built. The chapter's picture is that lists do not contain values directly, they contain references to values, and the shallow copy copies the row of references and nothing behind them."),
  (E, "In the executed examples copy.copy(spam) is not spam and is equal to spam, and so are spam[:] and spam.copy(). The shallow copy of [[1], [2]] is a new outer list that holds the same two inner lists: after the copy c has c[0].append(9), the original is [[1, 9], [2]] as well, and after c.append(7) only the copy has three items. This is the limit of a shallow copy, and the reason for the next concept."),
  (H, "The function creates a new list object and fills it with the same references that the original holds, one for each item. The outer lists are therefore independent, with changes to their length, order and which items they refer to, and the inner objects are shared. For lists of immutable items this independence is complete, since an immutable item cannot be changed through either list."),
  (K, "Check the items before relying on a shallow copy. If they are all numbers, strings or tuples of those, it is enough. If any item is a list or a dictionary and the program changes it, use the deep copy. And remember that copying has a cost: copying a very large list again and again in a loop can make a program slow."),
 ]),
 ("DeepCopy", "Deep copy", 3, "Copying", ("copy.deepcopy(spam)", "The function copy.deepcopy copies the list and, recursively, the lists inside it, so nothing is shared between the original and the copy.", ("(lambda s: (lambda c: (c[0].append(9), s, c))(" + CP + ".deepcopy(s)))([[1], [2]])[1:]", "([[1], [2]], [[1, 9], [2]])")), [
  (W, "If the list you need to copy contains lists, use the copy.deepcopy function instead of copy.copy; the copy.deepcopy function will copy these inner lists as well [SW]. The documentation defines the difference: a deep copy constructs a new compound object and then, recursively, inserts copies into it of the objects found in the original [PSF]."),
  (Y, "The deep copy is the safe choice when a program must change a structure without touching the original, for example a game board that is tried out and then thrown away, or a table that a function edits. It makes the result completely independent, so a bug in the copy cannot reach the original, and this is worth its cost where the data is not large."),
  (E, "In the executed examples the deep copy of [[1], [2]] is changed with c[0].append(9), and the original stays [[1], [2]] while the copy is [[1, 9], [2]]. The deep copy of a list that contains itself works as well: the copy contains itself, not the original, because the module remembers the objects it has copied already. The copy module also copies dictionaries and instances of classes, as the later chapters use it."),
  (H, "The function walks through the structure, creates a new object for each mutable object it meets and records the correspondence in a table of memo entries, so that an object reachable by two routes is copied once and the shape of the structure is preserved. Immutable atoms such as numbers and strings are shared, since sharing them is harmless."),
  (K, "A deep copy of a large structure is slow and uses a lot of memory, and objects that hold resources such as open files cannot be copied at all. A common compromise is to copy only the levels that the program will change, for example a new outer list with a copy of each row, [row[:] for row in grid]."),
 ]),
]

CHECKS += [("('Zophie'[0], 'Zophie'[-2], 'Zophie'[0:4], 'Zo' in 'Zophie')", "('Z', 'i', 'Zoph', True)"), ("('z' in 'Zophie', 'p' not in 'Zophie')", "(False, False)"),
           PROG("name = 'Zophie'\nfor i in name:\n    print('* * * ' + i + ' * * *')\n", "* * * Z * * *\n* * * o * * *\n* * * p * * *\n* * * h * * *\n* * * i * * *\n* * * e * * *\n"),
           ("(range(5)[2], 3 in range(5), range(0, 10, 2)[1:3])", "(2, True, range(2, 6, 2))"), ("('ab' in 'cabd', 'ab' in ['cabd'])", "(True, False)"),
           ("('a' in 'abc', 'a' == 'abc'[0], type('abc'[0:2]).__name__)", "(True, True, 'str')"),
           PROG("name = 'Zophie a cat'\ntry:\n    name[7] = 'the'\nexcept TypeError as e:\n    print(e)\n", "'str' object does not support item assignment\n"),
           ("(lambda name: (name[0:7] + 'the' + name[8:12], name))('Zophie a cat')", "('Zophie the cat', 'Zophie a cat')"),
           PROG("eggs = ['A', 'B', 'C']\nbefore = id(eggs)\neggs = ['x', 'y', 'z']\nprint(id(eggs) == before)\neggs = ['A', 'B', 'C']\nbefore = id(eggs)\ndel eggs[2]\ndel eggs[1]\ndel eggs[0]\neggs.append('x')\neggs.append('y')\neggs.append('z')\nprint(eggs, id(eggs) == before)\n", "False\n['x', 'y', 'z'] True\n"),
           ("hash((1, 2)) == hash((1, 2))", "True"),
           PROG("try:\n    hash([1])\nexcept TypeError as e:\n    print(e)\n", "unhashable type: 'list'\n"),
           ("(s := [1], t := s, s := s + [2], t, s)[3:]", "([1], [1, 2])"), ("(s := [1], t := s, s.append(2), t)[3]", "[1, 2]"), ("(s := [1], t := s, s.__iadd__([2]), t)[3]", "[1, 2]"),
           ("(lambda e: (e[0], e[1:3], len(e)))(('hello', 42, 0.5))", "('hello', (42, 0.5), 3)"),
           PROG("eggs = ('hello', 42, 0.5)\ntry:\n    eggs[1] = 99\nexcept TypeError as e:\n    print(e)\n", "'tuple' object does not support item assignment\n"),
           ("(type(('hello',)).__name__, type(('hello')).__name__, type(()).__name__)", "('tuple', 'str', 'tuple')"),
           ("(tuple(['cat', 'dog', 5]), list(('cat', 'dog', 5)), list('hello'))", "(('cat', 'dog', 5), ['cat', 'dog', 5], ['h', 'e', 'l', 'l', 'o'])"),
           ("(lambda: (x := 1, 2))()", "(1, 2)"),
           ("(t := ([1],), t[0].append(2), t)[2]", "([1, 2],)"),
           PROG("t = ([1],)\ntry:\n    t[0] += [2]\nexcept TypeError as e:\n    print(e)\nprint(t)\n", "'tuple' object does not support item assignment\n([1, 2],)\n"),
           PROG("spam = 42\neggs = spam\nspam = 99\nprint(spam, eggs)\n", "99 42\n"),
           PROG("spam = [0, 1, 2, 3]\neggs = spam\neggs[1] = 'Hello!'\nprint(spam)\nprint(eggs)\nprint(spam is eggs, id(spam) == id(eggs))\n", "[0, 'Hello!', 2, 3]\n[0, 'Hello!', 2, 3]\nTrue True\n"),
           ("(lambda spam: (lambda eggs: (eggs.__setitem__(1, 'Hello!'), spam, eggs is spam))(spam))([0, 1, 2, 3])[1:]", "([0, 'Hello!', 2, 3], True)"),
           PROG("def eggs(some_parameter):\n    some_parameter.append('Hello')\n\nspam = [1, 2, 3]\neggs(spam)\nprint(spam)\n", "[1, 2, 3, 'Hello']\n"),
           PROG("def f(p):\n    p = p + ['x']\n    return p\n\nspam = [1, 2, 3]\nprint(f(spam), spam)\n", "[1, 2, 3, 'x'] [1, 2, 3]\n"),
           PROG("def f(p):\n    p += ['x']\n\nspam = [1, 2, 3]\nf(spam)\nprint(spam)\n", "[1, 2, 3, 'x']\n"),
           PROG("def f(items=[]):\n    items.append(1)\n    return items\n\nf()\nprint(f())\n", "[1, 1]\n"),
           ("(g := [[0] * 3] * 2, g)[1]", "[[0, 0, 0], [0, 0, 0]]"), ("(g := [[0] * 3] * 2, g[0].__setitem__(0, 9), g, g[0] is g[1])[2:]", "([[9, 0, 0], [9, 0, 0]], True)"),
           ("(g := [[0] * 3 for _ in range(2)], g[0] is g[1])[1]", "False"),
           ("(lambda g: (g[0].__setitem__(0, 9), g, g[0] is g[1])[1:])([[0] * 3] * 2)", "([[9, 0, 0], [9, 0, 0]], True)"),
           ("[x is y for x in [[]] for y in [x]][0]", "True"),
           ("(s := [1, 2], s.append(s), s[2] is s, repr(s))[2:]", "(True, '[1, 2, [...]]')"),
           ("(lambda spam: (lambda cheese: (cheese.__setitem__(1, 42), spam, cheese))(" + CP + ".copy(spam)))(['A', 'B', 'C'])[1:]", "(['A', 'B', 'C'], ['A', 42, 'C'])"),
           ("(lambda s: (" + CP + ".copy(s) is s, " + CP + ".copy(s) == s, s[:] is s, s[:] == s, s.copy() is s, s.copy() == s))([1, [2]])", "(False, True, False, True, False, True)"),
           ("(s := [[1], [2]], c := " + CP + ".copy(s), c[0].append(9), c.append(7), s, c)[4:]", "([[1, 9], [2]], [[1, 9], [2], 7])"),
           ("(s := [[1], [2]], c := " + CP + ".deepcopy(s), c[0].append(9), s, c)[3:]", "([[1], [2]], [[1, 9], [2]])"),
           ("(lambda s: (s.append(s), " + CP + ".deepcopy(s))[1])([1, 2])[2] is None", "False"),
           ("(s := [1, 2], s.append(s), c := " + CP + ".deepcopy(s), c[2] is c, c is s)[3:]", "(True, False)"),
           ("(grid := [[1, 2], [3, 4]], c := [row[:] for row in grid], c[0].__setitem__(0, 9), grid, c)[3:]", "([[1, 2], [3, 4]], [[9, 2], [3, 4]])")]
CHECKS = [c for c in CHECKS if isinstance(c, tuple)]
