"""Makes course_page_template_v9_11_0.html from v9_10_0. Usage: template_patch_v9_11_0.py <in.html> <out.html>
9.11.0: the page draws the 13 visual kinds the chapter 6 (Lists) deck introduced - boxes, classify, facts, hist, keysort, lanes, matrix, mutation, passes, refgraph,
seqtypes, slices, unpack - from the same executed specification (D.visuals[<concept id>], visuals_v*.json) that the deck draws as shapes, so a value on the page is the value the
specification holds. Same conventions as the existing kinds: <div class="vis" id="wv-<concept id>">, a caption, buttons with data- attributes handled in the document click
listener (data-nv="<id>:<action>:<argument>": pick an expression, choose a slice row or an operation, step the frames / passes / steps of a scenario, choose a sort or a name),
sizes in rem, and the same zoom controls (zoomable) on every diagram that is an SVG: the sort and the name-and-object pictures - and now also the range and pairs pictures,
which 9.10.0 drew without them. Also: every chapter 6 agent gets a role icon, and an agent's own section whose label is in the question is ranked higher (the built-in check of chapter 6 failed for 'what is sort method?'). A visual on a sub-subject (level 2) is now offered as well (midsec calls secVis). A visual whose key is not a concept id (the deck-only framing slide) is ignored by the page, as it already was (see the D.visuals loop of the
trace examples, which skips ids that are not nodes; visHTML is only ever asked for a node). zoomable keeps the current view when a stepped picture is redrawn (data-vbkeep)."""
import sys
s = open(sys.argv[1], encoding="utf-8").read()
def rep(old, new, count=1):
    global s
    assert s.count(old) == count, (s.count(old), old[:90])
    s = s.replace(old, new)

NV_JS = r"""// ---------- 9.11.0: the visual kinds of chapter 6, each drawn from the executed specification D.visuals[id] (only function declarations: visHTML runs while the page is built) ----------
function nvKinds(){return ['boxes','classify','facts','hist','keysort','lanes','matrix','mutation','passes','refgraph','seqtypes','slices','unpack']}
function nvIs(k){return nvKinds().indexOf(k)>=0}
function vzWrap(svg){const m=svg.match(/viewBox="0 0 ([0-9.]+) ([0-9.]+)"/);if(!m)return svg;return '<div class="diagram small vz" style="aspect-ratio:'+m[1]+'/'+m[2]+';max-width:'+(m[1]/13)+'rem">'+svg+'</div>'}
function nvSvg(W,H,inner,label,defs){return '<div class="diagram small vz" style="aspect-ratio:'+W+'/'+H+';max-width:'+(W/13)+'rem"><svg class="nvsvg" viewBox="0 0 '+W+' '+H+'" data-vb0="0 0 '+W+' '+H+'" role="img" aria-label="'+esc(label)+'">'+(defs||'')+inner+'</svg></div>'}
function nvPut(id,html){const o=document.getElementById('wv-'+id+'-out');if(!o)return;const old=o.querySelector('.diagram svg');let keep=null;if(old&&old.dataset.vb0&&old.getAttribute('viewBox')!==old.dataset.vb0)keep=[old.dataset.vb0,old.getAttribute('viewBox')];
 o.innerHTML=html;o.querySelectorAll('.diagram.vz').forEach(h=>{const s=h.querySelector('svg');if(s&&keep&&s.dataset.vb0===keep[0])s.dataset.vbkeep=keep[1];zoomable(h)})}
function nvZoomAll(id){document.querySelectorAll('#wv-'+id+' .diagram.vz').forEach(h=>{if(!h.classList.contains('zoomhost'))zoomable(h)})}
function nvTog(id,act,label,on){return '<button class="btn g'+(on?' on':'')+'" data-nv="'+id+':'+act+'" aria-pressed="'+(on?'true':'false')+'">'+label+'</button>'}
function nvNav(id,act,label,aria){return '<button class="btn g" data-nv="'+id+':'+act+'"'+(aria?' aria-label="'+esc(aria)+'"':'')+'>'+label+'</button>'}
function nvHTML(n,v,w){const id=n.id,k=v.kind,T={boxes:'A list as boxes: each item has an index from the front and one from the back',classify:'Operations sorted by what they do to a list',facts:'Expressions Python ran, and what they gave',hist:v.draws+' seeded draws (seed '+v.seed+')',keysort:'How a sort orders items: input, keys, output',lanes:'Each operation on a real list: before, after, and what it returned',matrix:'The screensaver: rows the chapter’s program printed',mutation:'A loop that removes items from the list it walks',passes:'One row for each pass of a loop',refgraph:'Names and the objects they reach',seqtypes:'Which sequence types accept an assignment to an item',slices:'Slices: the indexes each one selects',unpack:'Unpacking: the items each name takes'}[k];
 let ctl='',extra='';
 if(k==='boxes')ctl='<p class="note"><code>len('+esc(v.name)+')</code> is '+v.len+'. The number above a box counts from the front, the one below from the back. Choose an expression to see the box it picks.</p>';
 if(k==='slices')ctl='<p class="note">The filled boxes are the items a slice selects. Choose a row to number them in the order the slice takes them.</p>';
 if(k==='lanes')ctl='<p class="note">Choose an operation to see exactly what left and what arrived.</p>';
 if(k==='keysort')ctl='<div class="row" role="group" aria-label="Choose a sort">'+v.examples.map((E,i)=>nvTog(id,'ex:'+i,esc(E.title),i===0)).join('')+'</div>';
 if(k==='matrix')ctl='<div class="row" role="group" aria-label="Choose a frame of rows">'+nvNav(id,'fr:-1','◀','Previous rows')+nvNav(id,'fr:1','Next rows ▶')+'<span class="note" id="'+w+'-pos" aria-live="polite"></span></div>';
 if(k==='mutation')ctl='<pre class="exs">'+esc(v.code)+'</pre><div class="row" role="group" aria-label="Step through the loop">'+nvNav(id,'mu:reset','⏮','Back to the first pass')+nvNav(id,'mu:-1','◀','Previous pass')+nvNav(id,'mu:1','Next pass ▶')+'<span class="note" id="'+w+'-pos" aria-live="polite"></span></div>';
 if(k==='passes')ctl='<div class="row" role="group" aria-label="Step through the passes">'+nvNav(id,'pa:-1','◀','Previous pass')+nvNav(id,'pa:1','Next pass ▶')+nvNav(id,'pa:all','Show all')+'<span class="note" id="'+w+'-pos" aria-live="polite"></span></div>';
 if(k==='refgraph'){ctl=(v.code?'<details class="nvcode"><summary>The program</summary><pre class="exs">'+esc(v.code)+'</pre></details>':'')+(v.scenarios.length>1?'<div class="row" role="group" aria-label="Choose a scenario">'+v.scenarios.map((S,i)=>nvTog(id,'sc:'+i,esc(S.title),i===0)).join('')+'</div>':'')+'<div class="row" role="group" aria-label="Step through the scenario">'+nvNav(id,'st:-1','◀','Previous step')+nvNav(id,'st:1','Next step ▶')+'<span class="note" id="'+w+'-pos" aria-live="polite"></span></div>'}
 return '<div class="vis nv" id="'+w+'" data-nvk="'+k+'"><div class="wl">'+esc(T)+'</div>'+(v.caption?'<p class="note">'+esc(v.caption)+'</p>':'')+ctl+'<div id="'+w+'-out" aria-live="polite"></div></div>'}
function nvShow(id){const v=D.visuals[id];({boxes:nvBoxes,classify:nvClassify,facts:nvFacts,hist:nvHist,keysort:nvKeysort,lanes:nvLanes,matrix:nvMatrix,mutation:nvMutation,passes:nvPasses,refgraph:nvRefgraph,seqtypes:nvSeqtypes,slices:nvSlices,unpack:nvUnpack})[v.kind](id)}
function nvClick(el){const key=el.dataset.nv,p=key.split(':'),id=p[0],a=p[1],x=p[2],b=document.getElementById('wv-'+id),v=D.visuals[id];if(!b||!v)return;
 const clamp=(k,n)=>Math.max(0,Math.min(n-1,k));
 if(a==='pick'){b.dataset.sel=x;nvShow(id)}
 else if(a==='row'||a==='lane'){b.dataset.sel=b.dataset.sel===x?'':x;nvShow(id)}
 else if(a==='ex'){b.dataset.ex=x;nvShow(id);document.querySelectorAll('#wv-'+id+' [data-nv^="'+id+':ex:"]').forEach(u=>{const on=u.dataset.nv===key;u.classList.toggle('on',on);u.setAttribute('aria-pressed',on)})}
 else if(a==='fr'){b.dataset.f=clamp(+(b.dataset.f||0)+ +x,v.frames.length);nvShow(id)}
 else if(a==='mu'){b.dataset.k=x==='reset'?0:clamp(+(b.dataset.k||0)+ +x,v.passes.length);nvShow(id)}
 else if(a==='pa'){const n=v.tables[0].rows.length,k=+(b.dataset.k===undefined?-1:b.dataset.k);b.dataset.k=x==='all'?-1:Math.max(-1,Math.min(n-1,k+ +x));nvShow(id)}
 else if(a==='sc'){b.dataset.sc=x;b.dataset.st=0;nvShow(id);document.querySelectorAll('#wv-'+id+' [data-nv^="'+id+':sc:"]').forEach(u=>{const on=u.dataset.nv===key;u.classList.toggle('on',on);u.setAttribute('aria-pressed',on)})}
 else if(a==='st'){b.dataset.st=clamp(+(b.dataset.st||0)+ +x,v.scenarios[+(b.dataset.sc||0)].steps.length);nvShow(id)}
 else if(a==='tg'){const [ci,m]=x.split('.').map(Number),t=v.cases[ci].targets[m],box=b.querySelector('[data-uc="'+ci+'"]'),was=el.getAttribute('aria-pressed')==='true';box.querySelectorAll('.unt').forEach(u=>u.setAttribute('aria-pressed','false'));box.querySelectorAll('.upi').forEach((u,i)=>u.classList.toggle('pick',!was&&i>=t.from&&i<t.to));if(!was)el.setAttribute('aria-pressed','true')}
 const again=document.querySelector('[data-nv="'+key+'"]');if(again&&document.activeElement!==again)again.focus()}
function nvBoxes(id){const v=D.visuals[id],b=document.getElementById('wv-'+id),sel=b.dataset.sel||'all',n=v.list.length,hit=new Set();
 v.picks.forEach((p,i)=>{if(sel==='all'||sel===String(i))p.at.forEach(a=>hit.add(a))});
 const cells=v.list.map((t,i)=>'<div class="bxc'+(hit.has(i)?' hit':'')+'"><span class="ix">'+i+'</span><span class="it">'+esc(t)+'</span><span class="nx">'+(i-n)+'</span></div>').join('')+(v.error&&(sel==='all'||sel==='e')?'<div class="bxc ghost" aria-hidden="true"><span class="ix">&nbsp;</span><span class="it">&nbsp;</span><span class="nx">&nbsp;</span></div>':'');
 const li=v.picks.map((p,i)=>'<li><button class="pk'+(sel==='all'||sel===String(i)?' on':'')+'" data-nv="'+id+':pick:'+i+'" aria-pressed="'+(sel===String(i))+'"><code class="pe">'+esc(p.expr)+'</code> <span aria-hidden="true">→</span> <code class="rs">'+esc(p.result)+'</code></button></li>').join('')+(v.error?'<li><button class="pk bad'+(sel==='e'?' on':'')+'" data-nv="'+id+':pick:e" aria-pressed="'+(sel==='e')+'"><code class="pe">'+esc(v.error.expr)+'</code> <span aria-hidden="true">→</span> <code class="rs">'+esc(v.error.message)+'</code></button></li>':'');
 nvPut(id,'<div class="bxrow" role="group" aria-label="The list '+esc(v.name)+'">'+cells+'</div><ul class="pks">'+li+'</ul><div class="row">'+nvTog(id,'pick:all','Show all',sel==='all')+'</div>')}
function nvSlices(id){const v=D.visuals[id],b=document.getElementById('wv-'+id),sel=b.dataset.sel||'',n=v.list.length,st='style="--n:'+n+'"';
 const hdr='<div class="slr hdr" '+st+'><span></span><span class="sls">'+v.list.map((t,i)=>'<span class="sli">'+i+'</span>').join('')+'</span><span></span></div>';
 const rows=v.rows.map((R,r)=>'<button class="slr'+(sel===String(r)?' sel':'')+'" '+st+' data-nv="'+id+':row:'+r+'" aria-pressed="'+(sel===String(r))+'"><code class="slx">'+esc(R.expr)+'</code><span class="sls">'+v.list.map((t,i)=>{const at=R.picked.indexOf(i);return '<span class="slc'+(at>=0?' on':'')+'" data-i="'+i+'"><span class="itx">'+esc(t)+'</span>'+(at>=0&&sel===String(r)?'<sup class="ord" aria-label="taken number '+(at+1)+'">'+(at+1)+'</sup>':'')+'</span>'}).join('')+'</span><span class="slo"><code class="slres">'+esc(R.result)+'</code><i class="slp">'+esc(R.picked_label)+'</i></span></button>').join('');
 nvPut(id,hdr+rows)}
function nvLanes(id){const v=D.visuals[id],b=document.getElementById('wv-'+id),sel=b.dataset.sel||'';
 const cells=(a,marks,c)=>a.map((t,i)=>'<span class="cl'+(marks.indexOf(i)>=0?' '+c:'')+'">'+esc(t)+'</span>').join('');
 const lanes=v.lanes.map((L,i)=>{const on=sel===String(i),left=L.before_marks.map(k=>L.before[k]),came=L.after_marks.map(k=>L.after[k]);
  const det=on?'<span class="ldet">'+(L.same_object?'<code>'+esc(L.name)+'</code> still names the same list object; its items are now different.':'<code>'+esc(L.name)+'</code> still names the original list; the result is a different, new list object.')+(left.length?' Marked before (index '+L.before_marks.join(', ')+'): <code>'+esc(left.join(', '))+'</code>.':'')+(came.length?' Marked after (index '+L.after_marks.join(', ')+'): <code>'+esc(came.join(', '))+'</code>.':'')+'</span>':'';
  return '<button class="lane'+(on?' sel':'')+'" data-nv="'+id+':lane:'+i+'" aria-pressed="'+on+'"><span class="lh"><code class="lop">'+esc(L.op)+'</code><span class="lcat '+(L.category==='in place'?'in':'new')+'">'+esc(L.cat_label)+'</span></span><span class="lbody"><code class="lname">'+esc(L.name)+'</code><span class="nvcells lb">'+cells(L.before,L.before_marks,'rm')+'</span><span class="lar" aria-hidden="true">→</span><span class="nvcells la">'+cells(L.after,L.after_marks,'add')+'</span></span><span class="lft"><span class="lret'+(L.returns===null?' none':'')+'">'+esc(L.ret_label)+'</span><span class="lid '+(L.same_object?'same':'diff')+'">same object: '+(L.same_object?'yes':'no')+'</span></span>'+det+'</button>'}).join('');
 nvPut(id,lanes+v.errors.map(e=>'<div class="lerr"><code>'+esc(e.expr)+'</code> → '+esc(e.message)+'</div>').join(''))}
function nvClassify(id){const v=D.visuals[id];
 nvPut(id,'<div class="cls">'+v.columns.map((c,i)=>'<div class="clc c'+(i%3)+'"><i class="clq">'+esc(c.question)+'</i><b class="clh">'+esc(c.head)+'</b>'+c.chips.map(k=>'<div class="clk"><code class="cke">'+esc(k.expr)+'</code><span class="cle">'+esc(k.evidence)+'</span></div>').join('')+'</div>').join('')+'</div>')}
function nvFacts(id){const v=D.visuals[id];
 nvPut(id,'<div class="fcs">'+v.facts.map(f=>'<div class="fc"><span class="fct">'+esc(f.label)+'</span><code class="fce">'+esc(f.expr)+'</code><code class="fcr'+(/Error:/.test(f.result)?' bad':'')+'">'+esc(f.result)+'</code></div>').join('')+'</div>')}
function nvHist(id){const v=D.visuals[id],mx=Math.max.apply(null,v.bars.map(b=>b.count));
 nvPut(id,'<table class="hst"><tbody>'+v.bars.map(b=>'<tr data-i="'+b.index+'"><th scope="row" class="hl">'+esc(b.text)+'</th><td class="hb"><span class="hbar" style="width:'+(100*b.count/mx)+'%"></span></td><td class="hn">'+b.count+'</td></tr>').join('')+'</tbody></table>')}
function nvSeqtypes(id){const v=D.visuals[id];
 nvPut(id,'<div class="sqs">'+v.types.map(T=>'<div class="sqc '+(T.mutable?'mut':'imm')+'"><code class="sqn">'+esc(T.type)+'</code><code class="sqs2">'+esc(T.sample)+'</code><br><span class="sqm">'+esc(T.mutable_label)+'</span><code class="sqa">'+esc(T.assign)+'</code><code class="sqr">'+esc(T.result)+'</code></div>').join('')+'</div>')}
function nvUnpack(id){const v=D.visuals[id];
 nvPut(id,v.cases.map((c,ci)=>'<div class="upc" data-uc="'+ci+'"><code class="ups">'+esc(c.stmt)+'</code><div class="upg" style="--n:'+c.items.length+'">'+c.items.map((t,i)=>'<span class="cl upi" data-i="'+i+'" style="grid-column:'+(i+1)+';grid-row:1">'+esc(t)+'</span>').join('')+c.targets.map((t,m)=>'<button class="unt'+(t.name[0]==='*'?' star':'')+'" style="grid-column:'+(t.from+1)+' / '+(t.to+1)+';grid-row:2" data-nv="'+id+':tg:'+ci+'.'+m+'" aria-pressed="false"><code class="unn">'+esc(t.name)+'</code><code class="unv">'+esc(t.value)+'</code></button>').join('')+'</div></div>').join('')+(v.error?'<div class="lerr"><code class="uerr">'+esc(v.error.expr)+'</code> → '+esc(v.error.message)+'</div>':'')+'<p class="note">Choose a name to mark the items it took.</p>')}
function nvMatrix(id){const v=D.visuals[id],b=document.getElementById('wv-'+id),f=Math.min(+(b.dataset.f||0),v.frames.length-1),F=v.frames[f],pos=document.getElementById('wv-'+id+'-pos');
 if(pos)pos.textContent='frame '+(f+1)+' of '+v.frames.length;
 nvPut(id,'<div class="mxf"><b class="mxl">'+esc(F.label)+'</b><pre class="mx frame" tabindex="0">'+F.rows.map(r=>'<span class="mxr">'+esc(r)+'</span>').join('')+'</pre></div>'
  +v.hazard.map((H,a)=>'<div class="mxf"><div class="hzl '+(a===0?'g':'b')+'"><span class="hzt">'+esc(H.label)+'</span><span class="hzn">'+esc(H.spaces_label)+'</span></div><pre class="mx '+(a===0?'hzg':'hzb')+'" tabindex="0"><span class="mxr">'+esc(H.row)+'</span></pre></div>').join('')
  +'<div class="wl">One column, pass by pass (column '+v.column+')</div><table class="tt nvt life"><thead><tr>'+v.life_cols.map(c=>'<th scope="col">'+esc(c)+'</th>').join('')+'</tr></thead><tbody>'+v.life.map(r=>'<tr class="'+(r.char==='space'?'':'on')+'"><td>'+r.row+'</td><td>'+esc(r.char)+'</td><td>'+r.counter+'</td></tr>').join('')+'</tbody></table>'
  +'<details class="nvcode"><summary>The program that printed these rows</summary><pre class="exs">'+esc(v.code)+'</pre></details>')}
function nvMutation(id){const v=D.visuals[id],b=document.getElementById('wv-'+id),n=v.passes.length,k=Math.min(+(b.dataset.k||0),n-1),pos=document.getElementById('wv-'+id+'-pos'),cells=(a,cur)=>a.map((t,i)=>'<span class="cl'+(i===cur?' cur':'')+'">'+esc(t)+'</span>').join('');
 if(pos)pos.textContent='pass '+(k+1)+' of '+n;
 nvPut(id,v.passes.map((P,r)=>'<div class="mrow'+(r===k?' now':'')+'" data-pass="'+P.n+'"'+(r>k?' hidden':'')+'><b class="mh">'+esc(P.head)+'</b><span class="nvcells mb" aria-label="the list when the pass began">'+cells(P.before,P.pos)+'</span><span class="mact '+(/removes/.test(P.action)?'rm':'keep')+'">'+esc(P.action)+'</span><span aria-hidden="true">→</span><span class="nvcells ma" aria-label="the list when the pass ended">'+cells(P.after,-1)+'</span></div>').join('')
  +(k>=n-1?'<div class="mfin"><span class="mfl">'+esc(v.final_label)+'</span> · <span class="mfs">'+esc(v.skip_label)+'</span></div><p class="note">The program printed <code class="mfp">'+esc(v.printed)+'</code></p>':''))}
function nvPasses(id){const v=D.visuals[id],b=document.getElementById('wv-'+id),n=v.tables[0].rows.length,k=+(b.dataset.k===undefined?-1:b.dataset.k),pos=document.getElementById('wv-'+id+'-pos');
 if(pos)pos.textContent=k<0?'all '+n+' passes':'pass '+(k+1)+' of '+n;
 nvPut(id,'<div class="nvtabs">'+v.tables.map(T=>'<table class="tt nvt"><caption><code>'+esc(T.header)+'</code></caption><thead><tr>'+T.cols.map(c=>'<th scope="col"><code>'+esc(c)+'</code></th>').join('')+'</tr></thead><tbody>'+T.rows.map((r,ri)=>'<tr class="'+(ri===k?'now':'')+'">'+r.map(c=>'<td><code>'+esc(c)+'</code></td>').join('')+'</tr>').join('')+'</tbody></table>').join('')+'</div><div class="wl">'+esc(v.printed_label)+'</div><div class="out nvprint">'+v.printed.map((l,i)=>'<span class="pl'+(i===k?' now':'')+'">'+esc(l)+'</span>').join('')+'</div><div class="wl">With a start value</div><div class="nvstart"><code class="nse">'+esc(v.start.expr)+'</code> → <code class="nsr">'+esc(v.start.result)+'</code></div>')}
function nvKeysort(id){const v=D.visuals[id],b=document.getElementById('wv-'+id),ex=Math.min(+(b.dataset.ex||0),v.examples.length-1),E=v.examples[ex],n=E.items.length,mx=Math.max.apply(null,E.items.concat(E.result).concat(E.keys||[]).map(t=>String(t).length)),bw=Math.min(100,Math.max(64,Math.ceil(mx*8.4+14))),gap=6,x0=4,W=Math.ceil(x0+n*(bw+gap)),hasK=!!E.keys,yIn=6,yKey=hasK?58:0,yOut=hasK?98:80,H=yOut+34+6,cx=i=>x0+i*(bw+gap)+bw/2,fs=t=>Math.max(9,Math.min(15,(bw-10)/(String(t).length*.62)));
 let s='';
 E.order.forEach((src,pos)=>{s+='<line class="ksln" data-from="'+src+'" data-to="'+pos+'" x1="'+cx(src)+'" y1="'+(hasK?yKey+2:yIn+34)+'" x2="'+cx(pos)+'" y2="'+yOut+'"/>'});
 E.items.forEach((t,i)=>{s+='<g class="ksi" data-i="'+i+'"><rect class="ksb" x="'+(x0+i*(bw+gap))+'" y="'+yIn+'" width="'+bw+'" height="34" rx="7"/><text class="kst" x="'+cx(i)+'" y="'+(yIn+22)+'" text-anchor="middle" style="font-size:'+fs(t)+'px;font-weight:700">'+esc(t)+'</text></g>'});
 if(hasK)E.keys.forEach((t,i)=>{s+='<text class="kss ksk" data-i="'+i+'" x="'+cx(i)+'" y="'+(yKey-4)+'" text-anchor="middle" style="font-size:'+Math.min(13,fs(t))+'px">'+esc(t)+'</text>'});
 E.result.forEach((t,i)=>{s+='<g class="kso" data-i="'+i+'"><rect class="ksb o" x="'+(x0+i*(bw+gap))+'" y="'+yOut+'" width="'+bw+'" height="34" rx="7"/><text class="kst" x="'+cx(i)+'" y="'+(yOut+22)+'" text-anchor="middle" style="font-size:'+fs(t)+'px;font-weight:700">'+esc(t)+'</text></g>'});
 nvPut(id,'<p class="ksx"><code class="kse">'+esc(E.expr)+'</code></p><p class="note">Top row: the input'+(hasK?', with the key of each item in italics under it':'')+'. Bottom row: the output; each line joins an item to its place.</p>'+nvSvg(W,H,s,E.title+': '+E.items.join(', ')+' sorted to '+E.result.join(', '),''))}
// reference graph: names on the left reach boxes; a box holds values, or dots that reach another box
function nvRgPlace(St){const CH=32,FH=40,CWc=8.7,cellW=it=>it.ref?36:Math.max(40,18+CWc*String(it.v).length),objW=o=>(o.type==='list'?(o.items.length?o.items.reduce((a,it)=>a+cellW(it)+4,-4):40):Math.max(44,18+CWc*String(o.v).length))+8;
 const multi=St.scopes.length>1,named=[];St.scopes.forEach((sc,si)=>sc.names.forEach(([n,oid])=>named.push({n:n,oid:oid,si:si})));
 const rows=[];named.forEach(a=>{if(rows.indexOf(a.oid)<0)rows.push(a.oid)});
 const inner=[],collect=oid=>{const o=St.objects[oid];if(o&&o.type==='list')o.items.forEach(it=>{if(it.ref&&inner.indexOf(it.ref)<0&&rows.indexOf(it.ref)<0){inner.push(it.ref);collect(it.ref)}})};rows.slice().forEach(collect);
 const nameW=Math.max(70,Math.max.apply(null,named.map(a=>18+CWc*a.n.length))),TH=26,top0=multi?34:8,objX=10+nameW+46,pos={};let y=top0;
 rows.forEach(oid=>{const k=named.filter(a=>a.oid===oid).length,rh=Math.max(FH+12,k*(TH+6)+6);pos[oid]={x:objX,y:y+(rh-FH)/2,w:objW(St.objects[oid]),rowY:y,rh:rh};y+=rh+4});
 const topW=Math.max.apply(null,rows.map(o=>pos[o].w)),innerX=objX+topW+(inner.length?60:0);let iy=top0;
 inner.forEach(oid=>{pos[oid]={x:innerX,y:iy,w:objW(St.objects[oid])};iy+=FH+14});
 const maxR=Math.max.apply(null,Object.keys(pos).map(o=>pos[o].x+pos[o].w));
 return {multi:multi,named:named,rows:rows,inner:inner,pos:pos,nameW:nameW,TH:TH,CH:CH,FH:FH,cellW:cellW,W:Math.ceil(maxR+16),H:Math.ceil(Math.max(y,iy)+6)}}
function nvRgSvg(id,W,H,L,St,prev){const COL=['#306998','#7A4F00','#14692C'],P=L.pos,names=[];let s='<defs>'+COL.concat(['#306998']).map((c,i)=>'<marker id="mk'+id+i+'" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10z" style="fill:'+c+'"/></marker>').join('')+'</defs>';
 const prevName={};if(prev)prev.scopes.forEach(sc=>sc.names.forEach(([n,o])=>{prevName[n]=o}));
 const changedObj=oid=>!prev||!prev.objects[oid]||JSON.stringify(prev.objects[oid])!==JSON.stringify(St.objects[oid]);
 if(L.multi)St.scopes.forEach((sc,i)=>{s+='<text class="rgsc" x="'+(10+i*130)+'" y="20" style="font-size:13px;font-weight:700;font-style:italic;fill:'+COL[i%3]+'">'+esc(sc.scope)+'</text>'});
 let arrows='',boxes='',tags='';const rc={};
 L.rows.forEach(oid=>{const grp=L.named.filter(a=>a.oid===oid),q=P[oid],gh=grp.length*(L.TH+6)-6,gy=q.rowY+(q.rh-gh)/2;
  grp.forEach((a,j)=>{const ny=gy+j*(L.TH+6),col=COL[a.si%3],chg=prev&&prevName[a.n]!==a.oid;
   tags+='<g class="rgn" data-name="'+esc(a.n)+'" data-oid="'+esc(oid)+'"><rect class="rgnb'+(chg?' chg':'')+'" x="10" y="'+ny+'" width="'+L.nameW+'" height="'+L.TH+'" rx="12" style="stroke:'+col+'"/><text class="rgnt" x="'+(10+L.nameW/2)+'" y="'+(ny+L.TH/2+5)+'" text-anchor="middle" style="fill:'+col+'">'+esc(a.n)+'</text></g>';
   const x1=10+L.nameW,y1=ny+L.TH/2,x2=q.x,y2=q.y+L.FH/2,mx=(x1+x2)/2;
   arrows+='<path class="rga" data-name="'+esc(a.n)+'" data-oid="'+esc(oid)+'" d="M'+x1+' '+y1+' C'+mx+' '+y1+' '+mx+' '+y2+' '+x2+' '+y2+'" style="stroke:'+col+';stroke-width:2" marker-end="url(#mk'+id+(a.si%3)+')"/>'})});
 Object.keys(P).forEach(oid=>{const o=St.objects[oid],q=P[oid],isInner=L.inner.indexOf(oid)>=0,po=prev&&prev.objects[oid];
  let g='<g class="rgo" data-oid="'+esc(oid)+'"><rect class="rgb'+(changedObj(oid)&&prev&&(!po||o.type!=='list')?' chg':'')+'" x="'+q.x+'" y="'+q.y+'" width="'+q.w+'" height="'+L.FH+'" rx="8"/>';
  if(o.type==='list'){if(!o.items.length)g+='<rect class="rgc empty" x="'+(q.x+4)+'" y="'+(q.y+4)+'" width="40" height="'+L.CH+'" rx="5" stroke-dasharray="4 3"/>';
   let cx=q.x+4;o.items.forEach((it,i)=>{const w=L.cellW(it),ch=prev&&po&&po.type==='list'&&JSON.stringify(po.items[i])!==JSON.stringify(it);
    g+='<g class="rgi" data-oid="'+esc(oid)+'" data-i="'+i+'"'+(it.ref?' data-ref="'+esc(it.ref)+'"':'')+'><rect class="rgc'+(isInner?' inn':'')+(ch?' chg':'')+'" x="'+cx+'" y="'+(q.y+4)+'" width="'+w+'" height="'+L.CH+'" rx="5"/>';
    if(it.ref){g+='<circle class="rgd" cx="'+(cx+w/2)+'" cy="'+(q.y+4+L.CH/2)+'" r="5"/>';const t=P[it.ref],rk=oid+'>'+it.ref;rc[rk]=(rc[rk]||0)+1;const dy=22+14*rc[rk];arrows+='<path class="rgr" data-from="'+esc(oid)+'" data-i="'+i+'" data-oid="'+esc(it.ref)+'" d="M'+(cx+w/2)+' '+(q.y+4+L.CH/2)+' C'+(cx+w/2)+' '+(q.y+4+L.CH/2+((t.y+L.FH/2<q.y+4+L.CH/2)?-dy:dy))+' '+(t.x-50)+' '+(t.y+L.FH/2)+' '+t.x+' '+(t.y+L.FH/2)+'" style="stroke:#306998;stroke-width:1.6" marker-end="url(#mk'+id+'3)"/>'}
    else g+='<text class="rgt" x="'+(cx+w/2)+'" y="'+(q.y+4+L.CH/2+5)+'" text-anchor="middle">'+esc(it.v)+'</text>';
    g+='</g>';cx+=w+4})}
  else g+='<text class="rgt rgv" x="'+(q.x+q.w/2)+'" y="'+(q.y+L.FH/2+5)+'" text-anchor="middle">'+esc(o.v)+'</text>';
  boxes+=g+'</g>'});
 return nvSvg(W,H,tags+boxes+arrows,(St.code||'')+'. Names: '+L.named.map(a=>a.n).join(', '),s)}
function nvRefgraph(id){const v=D.visuals[id],b=document.getElementById('wv-'+id),sc=Math.min(+(b.dataset.sc||0),v.scenarios.length-1),S=v.scenarios[sc],st=Math.min(+(b.dataset.st||0),S.steps.length-1),St=S.steps[st],pos=document.getElementById('wv-'+id+'-pos');
 if(!b._rg){b._rgW=[];b._rgH=[];b._rg=v.scenarios.map((Sc,si)=>{let W=0,H=0;const Ls=Sc.steps.map(x=>{const L=nvRgPlace(x);W=Math.max(W,L.W);H=Math.max(H,L.H);return L});b._rgW[si]=W;b._rgH[si]=H;return Ls})}
 if(pos)pos.textContent=(v.scenarios.length>1?S.title+': ':'')+'step '+(st+1)+' of '+S.steps.length;
 nvPut(id,'<code class="rgcap">'+esc(St.code)+'</code>'+nvRgSvg(id,b._rgW[sc],b._rgH[sc],b._rg[sc][st],St,st>0?S.steps[st-1]:null)+(st>0?'<p class="note">Yellow marks what this step changed.</p>':''))}
"""
NV_CSS = r"""/* 9.11.0: the visual kinds of chapter 6 (boxes, classify, facts, hist, keysort, lanes, matrix, mutation, passes, refgraph, seqtypes, slices, unpack); every size in rem so the reader's text-size control scales them, every colour a page token or a tint of one */
.diagram.small.vz{height:auto;min-height:0;width:100%}
.nv{--okd:#14692C;--amb:#7A4F00;--tint:#30699820;--tok:#1A7F3722;--tbad:#B4231822;--tamb:#FFD43B66}
.nv button{font:inherit;color:var(--ink)}
.nvcells{display:inline-flex;flex-wrap:wrap;gap:.25rem;align-items:center}
.nv .cl{display:inline-block;font:700 .95rem "Courier New",monospace;min-width:2.4rem;padding:.2rem .45rem;border:2px solid var(--blue);border-radius:8px;background:var(--tint);color:var(--ink);text-align:center;overflow-wrap:anywhere}
.nv .cl.rm{border-color:var(--bad);background:var(--tbad);color:var(--bad)}.nv .cl.add{border-color:var(--okd);background:var(--tok);color:var(--okd)}.nv .cl.cur{background:#FFD43B;border-color:#8A6A00;color:#1F2933}.nv .cl.pick{background:#FFD43B;border-color:#8A6A00;color:#1F2933}
.nv ul.pks{list-style:none;margin:.4rem 0;padding:0;display:flex;flex-direction:column;gap:.3rem}
.nv button.pk{display:block;width:100%;text-align:left;background:var(--bg);border:2px solid var(--line);border-radius:10px;padding:.3rem .6rem;cursor:pointer}.nv button.pk.on{border-color:#B08900;background:var(--tamb)}.nv button.pk.bad{border-color:var(--bad);color:var(--bad)}.nv button.pk code.rs{font-weight:700}
.nv .bxrow{display:flex;flex-wrap:wrap;gap:.3rem;margin:.5rem 0 .2rem}
.nv .bxc{display:flex;flex-direction:column;align-items:center;min-width:3.2rem}.nv .bxc .ix{font:.85rem "Courier New",monospace;color:var(--mute)}.nv .bxc .nx{font:.85rem "Courier New",monospace;color:var(--blue)}
.nv .bxc .it{display:block;width:100%;font:700 .95rem "Courier New",monospace;padding:.35rem .4rem;border:2px solid var(--blue);border-radius:8px;background:var(--tint);text-align:center;overflow-wrap:anywhere}
.nv .bxc.hit .it{background:#FFD43B;border-color:#8A6A00;color:#1F2933}.nv .bxc.ghost .it{border-style:dashed;border-color:var(--bad);background:transparent}
.nv .slr{display:grid;grid-template-columns:8.5rem minmax(0,1fr) 12rem;gap:.5rem;align-items:center;width:100%;text-align:left;background:var(--bg);border:2px solid var(--line);border-radius:10px;padding:.3rem .5rem;margin:.25rem 0}
.nv button.slr{cursor:pointer}.nv button.slr.sel{border-color:var(--blue);box-shadow:0 0 0 2px var(--blue) inset}.nv .slr.hdr{border-color:transparent;padding-top:0;padding-bottom:0;margin:0}
.nv .sls{display:grid;grid-template-columns:repeat(var(--n),minmax(0,1fr));gap:.2rem}.nv .sli{text-align:center;font:.85rem "Courier New",monospace;color:var(--mute)}
.nv .slc{position:relative;text-align:center;font:.85rem "Courier New",monospace;padding:.25rem .1rem;border:1px solid var(--line);border-radius:6px;background:var(--card);color:var(--mute);overflow-wrap:anywhere}.nv .slc.on{background:var(--blue);border-color:var(--blue);color:#fff;font-weight:700}
.nv .slc .ord{position:absolute;top:-.15rem;right:.2rem;font-size:.75rem;font-weight:700;color:#FFD43B}
.nv .slo{display:flex;flex-direction:column}.nv .slres{font-weight:700;color:var(--okd);overflow-wrap:anywhere}.nv .slp{font-size:.85rem;color:var(--mute)}
.nv .lane{display:block;width:100%;text-align:left;background:var(--bg);border:2px solid var(--line);border-radius:12px;padding:.5rem .7rem;margin:.35rem 0;cursor:pointer}.nv .lane.sel{border-color:var(--blue);box-shadow:0 0 0 2px var(--blue) inset}
.nv .lh{display:flex;flex-wrap:wrap;gap:.3rem .8rem;align-items:baseline}.nv .lop{font-weight:700;color:var(--navy)}.nv .lcat{font-weight:700;font-size:.85rem}.nv .lcat.in{color:var(--okd)}.nv .lcat.new{color:var(--blue)}
.nv .lbody{display:flex;flex-wrap:wrap;gap:.4rem;align-items:center;margin:.35rem 0}.nv .lname{font-weight:700;color:var(--blue)}.nv .lar{font-size:1.2rem;color:var(--mute)}
.nv .lft{display:flex;flex-wrap:wrap;gap:.4rem}.nv .lret,.nv .lid{font-weight:700;font-size:.85rem;padding:.1rem .55rem;border-radius:999px;border:1px solid var(--amb);background:var(--tamb);color:#5A3B00}.nv .lret.none{border-color:var(--line);background:var(--card);color:var(--mute)}.nv .lid.same{border-color:var(--okd);background:var(--tok);color:var(--okd)}.nv .lid.diff{border-color:var(--blue);background:var(--tint);color:var(--blue)}
.nv .ldet{display:block;margin-top:.4rem;font-size:.9rem;color:var(--ink)}.nv .lerr{padding:.35rem .6rem;margin:.3rem 0;border:1px solid var(--bad);border-radius:8px;background:var(--tbad);color:var(--bad);font-weight:700;overflow-wrap:anywhere}
.nv .cls{display:grid;grid-template-columns:repeat(auto-fit,minmax(14rem,1fr));gap:.6rem;margin-top:.4rem}.nv .clc{border:2px solid var(--blue);border-radius:12px;padding:.5rem .6rem;background:var(--card)}.nv .clc.c0{border-color:var(--okd)}.nv .clc.c2{border-color:var(--amb)}
.nv .clq{display:block;color:var(--mute);font-size:.9rem}.nv .clh{display:block;font:700 1.1rem Cambria,Georgia,serif;margin:.1rem 0 .4rem;color:var(--blue)}.nv .clc.c0 .clh{color:var(--okd)}.nv .clc.c2 .clh{color:var(--amb)}
.nv .clk{display:block;border:1px solid var(--line);border-radius:8px;padding:.3rem .5rem;margin:.3rem 0;background:var(--bg)}.nv .clk code{font-weight:700}.nv .cle{display:block;font-size:.85rem;font-style:italic;color:var(--ink)}
.nv .fcs{display:grid;grid-template-columns:repeat(auto-fit,minmax(16rem,1fr));gap:.6rem;margin-top:.4rem}.nv .fc{border-radius:12px;padding:.5rem .7rem;background:var(--card)}.nv .fct{display:block;font-weight:700;font-size:.9rem;color:var(--blue)}.nv .fce{display:block;margin:.2rem 0;color:var(--mute);overflow-wrap:anywhere}.nv .fcr{display:block;font-weight:700;color:var(--okd);overflow-wrap:anywhere}.nv .fcr.bad{color:var(--bad)}
.nv table.hst{width:100%;border-collapse:collapse;margin-top:.4rem}.nv .hst th{text-align:right;font-weight:400;padding:.1rem .5rem .1rem 0;white-space:nowrap;font-size:.9rem}.nv .hst td.hb{width:100%;padding:.1rem 0}.nv .hst .hbar{display:block;height:1rem;background:var(--blue);border-radius:3px;min-width:2px}.nv .hst td.hn{font:700 .9rem "Courier New",monospace;color:var(--blue);padding-left:.4rem}
@media (max-width:700px){.nv .hst th{white-space:normal;font-size:.85rem}}
.nv .mxf{margin:.4rem 0}.nv .mxl{display:block;color:var(--navy)}.nv pre.mx{display:block;margin:.2rem 0;padding:.4rem .6rem;background:var(--code);color:#7EE787;border-radius:8px;font:.8rem/1.25 "Courier New",monospace;overflow-x:auto}.nv .mxr{display:block;white-space:pre}.nv pre.mx.hzg{border:2px solid var(--okd)}.nv pre.mx.hzb{border:2px solid var(--bad);color:#FF9B94}
.nv .hzl{display:flex;justify-content:space-between;gap:.5rem;font-weight:700;font-size:.9rem}.nv .hzl.g{color:var(--okd)}.nv .hzl.b{color:var(--bad)}
.nv table.nvt{border-collapse:collapse;margin:.3rem .6rem .3rem 0}.nv .nvt caption{caption-side:top;text-align:left;font-weight:700;padding-bottom:.2rem}.nv .nvt th{background:var(--navy);color:#fff;padding:.2rem .6rem}.nv .nvt td{padding:.2rem .6rem;background:var(--card);border-bottom:2px solid var(--bg)}.nv .nvt tr.now td,.nv .nvt tr.on td{background:#FFD43BAA}.nv .nvt tr.on td{background:var(--tok)}.nv .nvt tr.now td{background:#FFD43B}
.nv .nvtabs{display:flex;flex-wrap:wrap;gap:.4rem 1rem;align-items:flex-start}.nv .nvprint .pl{display:block}.nv .nvprint .pl.now{background:#FFD43B33;box-shadow:inset 3px 0 0 #FFD43B}.nv .nvstart{display:inline-block;margin:.5rem 0;padding:.3rem .7rem;border:1px solid var(--amb);border-radius:10px;background:var(--tamb);color:#3A2600;font-weight:700;overflow-wrap:anywhere}
.nv .mrow{display:flex;flex-wrap:wrap;gap:.3rem .6rem;align-items:center;padding:.4rem .6rem;margin:.3rem 0;border-radius:10px;background:var(--card)}.nv .mrow[hidden]{display:none}.nv .mrow.now{outline:2px solid var(--blue)}.nv .mh{min-width:10rem;font-family:"Courier New",monospace;font-size:.9rem}.nv .mact{font-weight:700}.nv .mact.rm{color:var(--bad)}.nv .mact.keep{color:var(--okd)}
.nv .mfin{margin:.4rem 0;padding:.5rem .7rem;border:2px solid var(--bad);border-radius:10px;background:var(--tbad);color:var(--bad);font-weight:700}.nv details.nvcode summary{cursor:pointer;color:var(--blue);margin:.3rem 0}
.nv .sqs{display:grid;grid-template-columns:repeat(auto-fit,minmax(12rem,1fr));gap:.6rem;margin-top:.4rem}.nv .sqc{border:2px solid var(--okd);border-radius:12px;padding:.5rem .7rem;background:var(--card)}.nv .sqc.imm{border-color:var(--bad)}.nv .sqn{display:block;font-size:1.15rem;font-weight:700;color:var(--okd)}.nv .sqc.imm .sqn{color:var(--bad)}.nv .sqm{display:inline-block;margin:.25rem 0;padding:.05rem .6rem;border-radius:999px;font-weight:700;font-size:.85rem;border:1px solid var(--okd);background:var(--tok);color:var(--okd)}.nv .sqc.imm .sqm{border-color:var(--bad);background:var(--tbad);color:var(--bad)}.nv .sqa{display:block;font-weight:700;margin-top:.2rem}.nv .sqr{display:block;margin-top:.2rem;font-size:.9rem;color:var(--okd);overflow-wrap:anywhere}.nv .sqc.imm .sqr{color:var(--bad)}.nv .sqs code{overflow-wrap:anywhere}
.nv .upc{margin:.5rem 0 .8rem}.nv .ups{display:block;font-weight:700;margin-bottom:.3rem;color:var(--navy)}.nv .upg{display:grid;grid-template-columns:repeat(var(--n),minmax(0,1fr));gap:.25rem;max-width:34rem}.nv .upg .cl{min-width:0}
.nv button.unt{display:block;text-align:center;background:transparent;border:0;border-top:4px solid var(--okd);border-radius:0 0 6px 6px;padding:.2rem .1rem;cursor:pointer;min-width:0}.nv button.unt.star{border-top-color:var(--amb)}.nv button.unt[aria-pressed="true"]{background:var(--tamb)}.nv .unn{display:block;font-weight:700;color:var(--okd);overflow-wrap:anywhere;font-size:.9rem}.nv .unt.star .unn{color:var(--amb)}.nv .unv{display:block;color:var(--mute);font-size:.8rem;overflow-wrap:anywhere}
.nv .rgcap{display:block;margin:.3rem 0;padding:.3rem .6rem;border-radius:8px;background:var(--code);color:#E6EDF3;font:.95rem "Courier New",monospace;overflow-wrap:anywhere}.nvsvg text{font-family:"Courier New",monospace;font-size:14px;fill:var(--ink)}.nvsvg .rgt{font-weight:700}.nvsvg .rgnt{font-weight:700}.nvsvg .kss{font-size:12px;font-weight:400;font-style:italic;fill:var(--amb)}.nvsvg .ksl{font-family:Calibri,Arial,sans-serif;font-size:12px;fill:var(--mute)}
.nvsvg .rgb{fill:var(--bg);stroke:var(--blue);stroke-width:2}.nvsvg .rgb.chg{fill:#FFD43B55}.nvsvg .rgc{fill:var(--tint);stroke:var(--blue);stroke-width:1.5}.nvsvg .rgc.chg{fill:#FFD43B}.nvsvg .rgc.inn{fill:var(--card)}.nvsvg .rgnb{fill:var(--bg);stroke-width:2}.nvsvg .rgnb.chg{fill:#FFD43B55}.nvsvg .rga,.nvsvg .rgr,.nvsvg .ksln{fill:none}.nvsvg .rgd{fill:#306998}
.nvsvg .ksb{fill:var(--tint);stroke:var(--blue);stroke-width:2}.nvsvg .ksb.o{fill:var(--tok);stroke:var(--okd)}.nvsvg .ksln{stroke:var(--mute);stroke-width:1.6}
.nv .diagram.small.vz{margin-top:.2rem}
@media (max-width:700px){.nv .slc{font-size:.7rem;padding:.25rem 0}.nv .slr{grid-template-columns:minmax(0,1fr)}.nv .slr.hdr>span:first-child,.nv .slr.hdr>span:last-child{display:none}.nv .mh{min-width:0;width:100%}.nv pre.mx{font-size:min(.8rem,calc((100vw - 3.4rem)/43))}}
.nv .zbar{justify-content:flex-start}
"""
# agents of the chapter 6 subjects had the robot icon (the page's own test wants every agent to have a role icon)
rep("[/hazard/i,'\u26A0\uFE0F']];", "[/hazard/i,'\u26A0\uFE0F'],[/position/i,'\U0001F4CD'],[/adding/i,'\u2795'],[/removing/i,'\u2796'],[/combining/i,'\U0001F9F7'],[/searching/i,'\U0001F50D'],[/unpacking/i,'\U0001F381'],[/sequence/i,'\U0001FA9C'],[/references?/i,'\U0001F449'],[/copying/i,'\U0001F4C4'],[/random/i,'\U0001F3B2'],[/programs?/i,'\U0001F3AC']];")
# retrieval: a chunk of the agent's own slice whose label, as a whole phrase, is in the question ranks higher ('what is sort method?' put the Sort method section tenth, behind eight
# passages about sorting in general, so the page's own built-in check of that agent failed in chapter 6)
rep("async function rank(a,q,k){", "function labelBoost(a,c,q){const l=String(c.label||'').toLowerCase().replace(/\\s*\\([^)]*\\)\\s*$/,'').trim();return l.length>=5&&q.toLowerCase().indexOf(l)>=0&&ownsChunk(a,c)?0.1:0}\nasync function rank(a,q,k){")
rep("scored=ch.map((c,i)=>{const raw=sc[i];return {c,raw,score:raw+(ownsChunk(a,c)?0.08:0)}})", "scored=ch.map((c,i)=>{const raw=sc[i];return {c,raw,score:raw+(ownsChunk(a,c)?0.08:0)+labelBoost(a,c,q)}})")
rep("<!doctype html><html lang=\"en\"><head>\n", "<!doctype html><html lang=\"en\"><head>\n<!-- course_page_template version 9.11.0: renderers for the chapter 6 visual kinds (boxes, classify, facts, hist, keysort, lanes, matrix, mutation, passes, refgraph, seqtypes, slices, unpack) and zoom on the range and pairs pictures, added to 9.10.0 -->\n")
# a sub-subject (level 2) can hold a visual too (chapter 6 has seven): 9.10.0 drew visuals only for a top subject and for concepts, so those would not have been on the page
rep("<p>'+linkify(m.body,m.id)+'</p></details></section>'}", "<p>'+linkify(m.body,m.id)+'</p></details>'+secVis(m)+'</section>'}")
rep("</style></head><body>", NV_CSS + "</style></head><body>")
# the zoom of a diagram that is redrawn (a step, a choice) keeps its view
rep("let vb=vb0.slice();const set=()=>svg.setAttribute('viewBox',vb.join(' '));", "let vb=svg.dataset.vbkeep?svg.dataset.vbkeep.split(/\\s+/).map(Number):vb0.slice();const set=()=>svg.setAttribute('viewBox',vb.join(' '));if(svg.dataset.vbkeep){set();delete svg.dataset.vbkeep}")
# the visual dispatch: the new kinds, and the two older SVG pictures inside a zoomable frame
rep("'-out\">'+rangeSVG(v)+'", "'-out\">'+vzWrap(rangeSVG(v))+'")
rep("'-out\">'+pairsSVG(v)+'", "'-out\">'+vzWrap(pairsSVG(v))+'")
rep(" return ''}\nconst STATIC_VIS=['trace','range','pairs','names','debugger','levels','unwind'];", " if(nvIs(v.kind))return nvHTML(n,v,w);\n return ''}\n" + NV_JS + "const STATIC_VIS=['trace','range','pairs','names','debugger','levels','unwind'].concat(nvKinds());")
rep("if(kk==='unwind')unwindShow(id,0);return}", "if(kk==='unwind')unwindShow(id,0);if(nvIs(kk))nvShow(id);if(kk==='range'||kk==='pairs')nvZoomAll(id);return}")
rep(" if(t.dataset.vis){visRun(t.dataset.vis);return}", " if(t.closest&&t.closest('[data-nv]')){nvClick(t.closest('[data-nv]'));return}\n if(t.dataset.vis){visRun(t.dataset.vis);return}")
open(sys.argv[2], "w", encoding="utf-8").write(s)
print("written", sys.argv[2], len(s))
