#!/usr/bin/env python3
"""SEN0414 chapter 6 - builds question_bank_v2_0_0.json from the compact specification below (version 1.0.0).

Each Apply item is a program whose real output is computed here (python3.14) and must equal the stated correct option; the
distractors are written by hand as the plausible wrong readings. Answer positions are assigned from a balanced cycle so that each
of the four positions holds 20-30 per cent of the bank (the checker's rule). Run: python3 question_bank_make_v2_0_0.py
The bank itself is then checked by question_bank_check_v2_0_0.py (chapter 5 checker question_bank_check_v1_2_0.py, copied into this folder).
"""
__version__ = "2.0.0"
import json, os, subprocess, sys
PY = "/root/.local/bin/python3.14"
ITEMS = []


import importlib.util
_spec = importlib.util.spec_from_file_location("corpus6", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "sen0414_ch06_corpus_v1_0_0.py"))
_C = importlib.util.module_from_spec(_spec); _spec.loader.exec_module(_C)
_LABEL = {n[0]: n[1] for n in _C.NODES}
_SEEN = {}


def A(concept, q, code, right, wrong, why):
    # the stem names the concept (the checker refuses a stem shared by two items); a concept's later programs say which one
    _SEEN[concept] = _SEEN.get(concept, 0) + 1
    nth = ["", " second", " third", " fourth"][_SEEN[concept] - 1]
    if q == "What does this program print?":
        q = "%s: what does this%s program print?" % (_LABEL[concept], nth)
    ITEMS.append(dict(concept=concept, level="Apply", q=q, code=code, right=right, wrong=wrong, why=why))


def U(concept, level, q, right, wrong, why):
    ITEMS.append(dict(concept=concept, level=level, q=q, right=right, wrong=wrong, why=why))


# ---------------------------------------------------------------- the list data type
U("ListModel", "Understand", "Which statement describes a list in the chapter?", "An ordered sequence of values in square brackets, whose items may be of different types", ["A set of unique values with no order", "A sequence of characters only", "A fixed pair of two values"], "A list is a value that contains multiple values in an ordered sequence, and its items can be of any type.")
U("ListValues", "Understand", "A variable spam is assigned ['cat', 'bat']. How many values is spam assigned?", "One: the list value, which itself contains two items", ["Two: one for each item of the list", "None: a list cannot be assigned to a variable", "Three: the list and its two items"], "The variable is assigned only one value, the list, although the list contains other values.")
A("List", "What does this program print?", "print(len(['hello', 3.1415, True, None, 42]))", "5", ["4", "3", "42"], "The list has five items of five different types, and len counts the items.")
U("List", "Understand", "What distinguishes [] from the string ''?", "[] is an empty list and '' is an empty string; each contains no values of its own kind", ["[] is the same value as ''", "[] holds one item, the empty string", "[] raises an error when it is printed"], "The chapter says [] is an empty list that contains no values, similar to the empty string.")
A("ListLength", "What does this program print?", "print(len([[1, 2], [3]]))", "2", ["3", "1", "[2, 1]"], "len counts the items of the outer list only, and the outer list holds two lists.")
U("ListLength", "Understand", "A list has 4 items. Which is its last valid index?", "3", ["4", "5", "-5"], "Counting starts at 0, so the last index is the length minus one.")
U("Positions", "Understand", "Which three ways of naming a position in a list does the chapter teach?", "An index from the front, a negative index from the back, and two indexes for a list of lists", ["A key, a value and a pair", "A start, a stop and a step only", "A name, a type and a size"], "The group covers the index, the negative index and the list of lists; slices are in the next group.")
A("Index", "What does this program print?", "spam = ['cat', 'bat', 'rat', 'elephant']\nprint(spam[3])", "elephant", ["rat", "bat", "IndexError"], "The first index is 0, so index 3 is the fourth item.")
U("Index", "Understand", "Why does ['cat', 'bat'][2] raise an IndexError?", "The list has two items, so the valid indexes are 0 and 1", ["Index 2 is reserved by Python", "An index must be a negative number", "A list of strings cannot be indexed"], "The last valid index is the length minus one.")
A("NegativeIndex", "What does this program print?", "spam = ['cat', 'bat', 'rat', 'elephant']\nprint(spam[-3])", "bat", ["rat", "cat", "elephant"], "Index -1 is the last item, -2 the one before it, and -3 is 'bat'.")
U("NegativeIndex", "Understand", "For a list of four items, which negative index is the first one outside the list?", "-5", ["-4", "-1", "-0"], "Valid negative indexes run from -1 to -4, and -5 raises an IndexError.")
A("NestedList", "What does this program print?", "spam = [['cat', 'bat'], [10, 20, 30, 40, 50]]\nprint(spam[1][4])", "50", ["40", "bat", "IndexError"], "spam[1] is the inner list of numbers and its index 4 is the fifth item.")
U("NestedList", "Understand", "In spam[0][1], what does the first index choose?", "Which inner list to use", ["Which item inside the inner list", "The type of the list", "How many lists there are"], "The first index dictates which list value to use, and the second indicates the value within that list.")
U("Slicing", "Understand", "What does a slice of a list give back?", "A new list holding the selected items", ["The selected items as separate values", "A string made of the items", "The same list, changed in place"], "A slice takes several items from a list in one expression and gives them back as a new list.")
A("Slice", "What does this program print?", "spam = ['cat', 'bat', 'rat', 'elephant']\nprint(spam[1:3])", "['bat', 'rat']", ["['bat', 'rat', 'elephant']", "['cat', 'bat', 'rat']", "['rat', 'elephant']"], "A slice starts at the first index and goes up to, but does not include, the second.")
U("Slice", "Understand", "How many items does spam[2:7] have when spam holds ten items?", "5", ["6", "7", "2"], "The length of the slice is the end minus the start.")
A("SliceDefaults", "What does this program print?", "spam = ['cat', 'bat', 'rat', 'elephant']\nprint(spam[:2], spam[2:])", "['cat', 'bat'] ['rat', 'elephant']", ["['cat', 'bat', 'rat'] ['rat', 'elephant']", "['cat', 'bat'] ['bat', 'rat', 'elephant']", "['bat'] ['rat']"], "Leaving out the first index means 0 and leaving out the second means the length; the two slices meet without a gap.")
U("SliceDefaults", "Understand", "Which expression makes a copy of the list spam?", "spam[:]", ["spam[0]", "spam[-1]", "spam[::0]"], "A slice with both numbers left out takes every item and gives a new list.")
A("SliceStep", "What does this program print?", "print([1, 2, 3, 4, 5][::2], [1, 2, 3][::-1])", "[1, 3, 5] [3, 2, 1]", ["[2, 4] [3, 2, 1]", "[1, 3, 5] [1, 2, 3]", "[1, 2] [3, 2]"], "A step of 2 takes every second item and a step of -1 reverses the order.")
U("SliceStep", "Remember", "Which step value raises a ValueError in a slice?", "0", ["1", "-1", "2"], "The slice step cannot be zero.")
# ---------------------------------------------------------------- changing a list
U("ChangingLists", "Understand", "Which operations does the branch on changing a list cover?", "Replacing, adding, removing and combining", ["Searching, sorting and copying", "Looping, unpacking and printing", "Importing, defining and calling"], "The branch covers replacement by assignment, adding, removing and combining lists.")
U("Replacing", "Understand", "When an item of a list is replaced by assignment to its index, what changes?", "The list changes in place; every name that refers to it sees the new item", ["A new list is made and the name moves to it", "Only the name used in the assignment sees the change", "Nothing, until the list is printed"], "Replacement changes the list and not the variable.")
A("ItemAssignment", "What does this program print?", "spam = ['cat', 'bat', 'rat', 'elephant']\nspam[1] = 'aardvark'\nspam[2] = spam[1]\nspam[-1] = 12345\nprint(spam)", "['cat', 'aardvark', 'aardvark', 12345]", ["['cat', 'aardvark', 'rat', 12345]", "['cat', 'aardvark', 'aardvark', 'elephant']", "['cat', 'bat', 'rat', 'elephant']"], "Each assignment replaces one item in place, and the third copies the value of the item at index 1.")
U("ItemAssignment", "Understand", "What does spam[5] = 'x' do when spam has three items?", "Raises an IndexError, because assignment cannot create a new place", ["Adds 'x' at index 5 and fills the gap with None", "Adds 'x' at the end", "Does nothing"], "Assignment to an index replaces an existing item; use append or insert to add.")
U("Adding", "Understand", "Which three methods add items to a list?", "append, insert and extend", ["add, push and put", "append, remove and pop", "insert, sort and index"], "The group explains the three ways to add items.")
A("AppendMethod", "What does this program print?", "spam = ['cat', 'dog', 'bat']\nprint(spam.append('moose'))", "None", ["['cat', 'dog', 'bat', 'moose']", "moose", "3"], "append changes the list in place and returns None, so the first line printed is None.")
U("AppendMethod", "Understand", "Why is spam = spam.append('moose') a mistake?", "append returns None, so the name would be bound to None and the list lost", ["append returns a new list that must be sorted first", "append needs two arguments", "It adds the item twice"], "The return value of append is None, and it modifies the list in place.")
A("InsertMethod", "What does this program print?", "spam = ['cat', 'dog', 'bat']\nspam.insert(1, 'chicken')\nprint(spam)", "['cat', 'chicken', 'dog', 'bat']", ["['cat', 'dog', 'chicken', 'bat']", "['chicken', 'cat', 'dog', 'bat']", "['cat', 'chicken', 'bat']"], "insert puts the value at the given index and moves the later items one place along.")
U("InsertMethod", "Understand", "What happens with spam.insert(100, 'x') on a list of three items?", "The value is added at the end", ["An IndexError is raised", "The list grows to 101 items", "The value is added at the front"], "An index beyond the end places the item at the end.")
A("ExtendMethod", "What does this program print?", "a = [1, 2, 3]\na.extend(['A', 'B'])\nb = [1, 2, 3]\nb.append(['A', 'B'])\nprint(len(a), len(b))", "5 4", ["5 5", "4 4", "4 5"], "extend adds every item of its argument, while append adds the argument as one item.")
U("ExtendMethod", "Understand", "What does [1, 2, 3].extend('ab') produce in the list?", "[1, 2, 3, 'a', 'b'], because the string is an iterable of characters", ["[1, 2, 3, 'ab']", "A TypeError", "[1, 2, 3]"], "extend takes every item of an iterable, and a string yields its characters.")
U("Removing", "Understand", "Which three operations remove items from a list?", "del, remove and pop", ["delete, clear and drop", "del, insert and sort", "remove, append and extend"], "The group explains del, remove and pop.")
A("DelStatement", "What does this program print?", "spam = ['cat', 'bat', 'rat', 'elephant']\ndel spam[1]\nprint(spam)", "['cat', 'rat', 'elephant']", ["['cat', 'bat', 'elephant']", "['bat', 'rat', 'elephant']", "['cat', 'rat']"], "del removes the item at the index and the later items move down.")
U("DelStatement", "Understand", "When is del the right choice to remove an item?", "When the index of the item is known", ["When only the value of the item is known", "When the removed item is needed afterwards", "When the list is empty"], "del is useful when you know the index, remove when you know the value.")
A("RemoveMethod", "What does this program print?", "spam = ['cat', 'bat', 'rat', 'cat', 'hat', 'cat']\nspam.remove('cat')\nprint(spam)", "['bat', 'rat', 'cat', 'hat', 'cat']", ["['bat', 'rat', 'hat']", "['cat', 'bat', 'rat', 'hat', 'cat']", "['bat', 'rat', 'cat', 'hat']"], "remove deletes only the first item equal to the value.")
U("RemoveMethod", "Understand", "What does ['a'].remove('b') do?", "Raises a ValueError, because the value is not in the list", ["Returns None and leaves the list as it is", "Returns -1", "Removes the last item"], "remove raises a ValueError when the value is absent.")
A("PopMethod", "What does this program print?", "spam = ['cat', 'dog', 'bat']\nprint(spam.pop(), spam.pop(0), spam)", "bat cat ['dog']", ["bat dog ['cat']", "cat bat ['dog']", "None None ['dog']"], "pop removes and returns the last item by default and the item at the index when one is given.")
U("PopMethod", "Understand", "What does [].pop() do?", "Raises an IndexError, because there is no item to remove", ["Returns None", "Returns []", "Returns 0"], "pop on an empty list raises an IndexError.")
U("Combining", "Understand", "Which operators combine lists?", "+ joins two lists and * repeats a list", ["& joins and | repeats", "+ repeats and * joins", "and and or"], "The operators of strings also work on lists.")
A("Concatenation", "What does this program print?", "a = [1, 2, 3]\nb = a + ['A', 'B']\nprint(a, b)", "[1, 2, 3] [1, 2, 3, 'A', 'B']", ["[1, 2, 3, 'A', 'B'] [1, 2, 3, 'A', 'B']", "[1, 2, 3] [1, 2, 3]", "[1, 2, 3, 'A', 'B'] [1, 2, 3]"], "The + operator builds a new list and leaves both operands unchanged.")
U("Concatenation", "Understand", "What does [1, 2] + 3 do?", "Raises a TypeError, because both operands must be lists", ["Gives [1, 2, 3]", "Gives [4, 5]", "Gives [1, 2, 3, 3]"], "A list can be concatenated only with another list.")
A("Replication", "What does this program print?", "print([1, 2, 3] * 2, [0] * 3, len([] * 5))", "[1, 2, 3, 1, 2, 3] [0, 0, 0] 0", ["[2, 4, 6] [0, 0, 0] 0", "[1, 2, 3, 1, 2, 3] [0, 0, 0] 5", "[[1, 2, 3], [1, 2, 3]] [0, 0, 0] 0"], "The * operator repeats the items, and an empty list repeated is still empty.")
U("Replication", "Understand", "Why is [0] * 70 a safe way to make 70 counters?", "The items are integers, which cannot be changed through a shared reference", ["Python copies the list 70 times", "Replication makes 70 separate lists", "Integers are lists of one item"], "Replication repeats references, and an immutable item cannot be changed.")
A("AugmentedAssignment", "What does this program print?", "bacon = ['Zophie']\nbacon *= 3\nspam = 'Hello,'\nspam += ' world!'\nprint(bacon, spam)", "['Zophie', 'Zophie', 'Zophie'] Hello, world!", ["['Zophie'] Hello, world!", "['Zophie', 'Zophie', 'Zophie'] Hello,", "['ZophieZophieZophie'] Hello, world!"], "bacon *= 3 means bacon = bacon * 3, and += joins the strings.")
U("AugmentedAssignment", "Analyze", "For a list x, how does x += [1] differ from x = x + [1] when another name y refers to the same list?", "x += [1] changes the shared list, so y sees it; x = x + [1] makes a new list that y does not see", ["Both change the shared list", "Neither changes the shared list", "x = x + [1] changes the shared list, x += [1] does not"], "Augmented assignment on a list extends it in place, while + builds a new list.")
# ---------------------------------------------------------------- searching and ordering
U("SearchingOrdering", "Understand", "What are the two services that this branch offers for a list?", "Asking where a value is and putting the items in order", ["Copying and deleting", "Printing and reading", "Importing and exporting"], "Searching and ordering are the two services asked of a collection more than any other.")
U("Methods", "Understand", "What is a method, in the chapter's words?", "A function that is called on a value", ["A variable that holds a function", "A kind of loop", "A list that holds functions"], "A method is the same thing as a function, except it is called on a value.")
A("Method", "What does this program print?", "try:\n    'hello'.append('world')\nexcept AttributeError as e:\n    print(e)", "'str' object has no attribute 'append'", ["'list' object has no attribute 'append'", "'str' object is immutable", "append() takes 0 arguments"], "append belongs to lists, so the string has no such attribute.")
U("Method", "Understand", "Why does spam.append (without parentheses) append nothing?", "It names the bound method but does not call it", ["It appends None", "It raises a SyntaxError", "It appends the name spam"], "A call needs parentheses.")
U("Searching", "Understand", "What does in answer, and what does index answer?", "in answers yes or no, index answers with a position", ["in answers with a position, index with yes or no", "Both answer with the value", "Both answer with a list"], "The operator tests for presence and the method returns the position.")
A("Membership", "What does this program print?", "spam = ['hello', 'hi', 'howdy', 'heyas']\nprint('howdy' in spam, 'cat' in spam, 'cat' not in spam)", "True False True", ["True True False", "False False True", "True False False"], "in tests whether an item equals the value, and not in gives the opposite.")
U("Membership", "Understand", "What is the difference between 'ab' in 'cabd' and 'ab' in ['cabd']?", "The first tests for a substring and is True; the second tests for an item equal to 'ab' and is False", ["Both are True", "Both are False", "The first is False and the second is True"], "On a string in tests for a substring; on a list it tests for an equal item.")
A("IndexMethod", "What does this program print?", "spam = ['Zophie', 'Pooka', 'Fat-tail', 'Pooka']\nprint(spam.index('Pooka'))", "1", ["3", "2", "ValueError"], "index returns the position of the first match.")
U("IndexMethod", "Understand", "What does spam.index('x') do when 'x' is not in spam?", "Raises a ValueError", ["Returns -1", "Returns None", "Returns the length of the list"], "index raises an error rather than returning a value that could be mistaken for an index.")
A("ShortCircuit", "What does this program print?", "spam = []\nif len(spam) > 0 and spam[0] == 'cat':\n    print('cat')\nelse:\n    print('no cat')", "no cat", ["cat", "IndexError", "None"], "len(spam) > 0 is False, so Python does not evaluate spam[0].")
U("ShortCircuit", "Understand", "Why does spam[0] == 'cat' and len(spam) > 0 still fail on an empty list?", "The guard must come first: the left operand is evaluated before the right", ["and evaluates the right operand first", "len cannot be used with and", "== has no meaning for an empty list"], "Short-circuiting only helps when the test is on the left.")
U("Ordering", "Understand", "What design rule do sort and sorted show?", "A method that changes a list in place returns None; a function that makes a new list returns it", ["Both return the sorted list", "Both change the list in place", "Both return None"], "The group contrasts the in-place method with the function that returns a new list.")
A("SortMethod", "What does this program print?", "spam = [3, 1, 2]\nspam = spam.sort()\nprint(spam)", "None", ["[1, 2, 3]", "[3, 2, 1]", "[3, 1, 2]"], "sort returns None, so the assignment replaces the list with None.")
U("SortMethod", "Understand", "Why does ['Alice', 'ants', 'Bob'].sort() put 'ants' last?", "Strings are ordered by character code and capital letters come before lowercase ones", ["Python sorts by the length of the string", "Python sorts in reverse by default", "'ants' is not a valid string"], "The chapter calls this ASCIIbetical order.")
A("SortKeyReverse", "What does this program print?", "print(sorted(['a', 'z', 'A', 'Z'], key=str.lower))", "['a', 'A', 'z', 'Z']", ["['A', 'Z', 'a', 'z']", "['Z', 'z', 'A', 'a']", "['a', 'z', 'A', 'Z']"], "The key makes the comparison treat every item as lowercase; equal keys keep their original order.")
U("SortKeyReverse", "Understand", "What must be passed as the key argument?", "A function, written without parentheses, such as str.lower", ["A call, such as str.lower()", "A string naming the method", "A Boolean"], "key names the function itself, which is applied to each item before the comparison.")
A("ReverseMethod", "What does this program print?", "spam = ['cat', 'dog', 'moose']\nprint(spam.reverse(), spam)", "None ['moose', 'dog', 'cat']", ["['moose', 'dog', 'cat'] ['moose', 'dog', 'cat']", "None ['cat', 'dog', 'moose']", "['moose', 'dog', 'cat'] ['cat', 'dog', 'moose']"], "reverse changes the list in place and returns None.")
U("ReverseMethod", "Understand", "Which expression gives a reversed copy and leaves the list unchanged?", "spam[::-1]", ["spam.reverse()", "spam.sort(reverse=True)", "spam[-1]"], "A slice with step -1 is a new list in reverse order.")
A("SortedFunction", "What does this program print?", "spam = [3, 1, 2]\nprint(sorted(spam), spam)", "[1, 2, 3] [3, 1, 2]", ["[1, 2, 3] [1, 2, 3]", "None [1, 2, 3]", "[3, 1, 2] [1, 2, 3]"], "sorted returns a new ordered list and leaves the original alone.")
U("SortedFunction", "Understand", "What type is the result of sorted('banana')?", "A list of characters", ["A string", "A tuple", "A set"], "sorted always returns a list.")
# ---------------------------------------------------------------- looping and unpacking
U("LoopsUnpacking", "Understand", "What does this branch say a for loop over a list does?", "It repeats its block once for each item of the list", ["It repeats its block once for each character", "It repeats its block until the list is empty", "It repeats its block twice"], "Technically, a for loop repeats its block once for each item in a list value.")
U("Looping", "Understand", "Which four forms of looping does the group compare?", "The loop over indexes, enumerate, the loop that must not change its list, and the list comprehension", ["while, until, repeat and goto", "map, filter, reduce and zip", "for, if, else and elif"], "The group explains the four forms that matter in practice.")
A("RangeLenLoop", "What does this program print?", "supplies = ['pens', 'staplers', 'binders']\nprint([i for i in range(len(supplies))])", "[0, 1, 2]", ["[1, 2, 3]", "['pens', 'staplers', 'binders']", "[0, 1, 2, 3]"], "range(len(supplies)) yields every index from 0 to the length minus one.")
U("RangeLenLoop", "Understand", "Why does for i in range(len(spam) + 1): print(spam[i]) fail?", "The last value of i is len(spam), which is outside the list", ["range does not accept a sum", "len(spam) is always 0", "print cannot take an index"], "The loop reaches one place too far and raises an IndexError at the last pass.")
A("EnumerateLoop", "What does this program print?", "print(list(enumerate(['a', 'b'], start=1)))", "[(1, 'a'), (2, 'b')]", ["[(0, 'a'), (1, 'b')]", "[('a', 1), ('b', 2)]", "[1, 2]"], "enumerate yields pairs of the count and the item, and start sets the first count.")
U("EnumerateLoop", "Understand", "In for index, item in enumerate(supplies), which comes first?", "The index, then the item", ["The item, then the index", "Both are the same value", "It depends on the list"], "enumerate returns the index and then the item.")
A("MutationWhileIterating", "What does this program print?", "items = ['a', 'b', 'c', 'd']\nfor x in items:\n    items.remove(x)\nprint(items)", "['b', 'd']", ["[]", "['a', 'c']", "['a', 'b', 'c', 'd']"], "Each removal moves later items under the loop's position, so every second item is skipped.")
U("MutationWhileIterating", "Analyze", "Which remedy avoids the problem of removing items during a loop?", "Build a new list with a comprehension, or loop over a copy", ["Loop over the same list but call sort first", "Use a while loop over the same list without any change", "Remove items from the end only with remove"], "The documentation advises looping over a copy or creating a new collection.")
A("ListComprehension", "What does this program print?", "print([x * x for x in range(6) if x % 2 == 0])", "[0, 4, 16]", ["[0, 1, 4, 9, 16, 25]", "[1, 9, 25]", "[0, 2, 4]"], "The if clause keeps the even numbers 0, 2 and 4, and the expression squares them.")
U("ListComprehension", "Understand", "Does a list comprehension change the list it reads?", "No, it builds a new list", ["Yes, it changes the list in place", "Only when it has an if clause", "Only when the variable is reused"], "A comprehension evaluates its expression for each item and appends the result to a new list.")
U("Unpacking", "Understand", "What does unpacking do?", "Assigns the items of a list to several variables in one statement", ["Removes the items from the list", "Sorts the items into variables by name", "Copies the list into one variable"], "Unpacking is the multiple assignment trick and its starred form.")
A("MultipleAssignment", "What does this program print?", "cat = ['fat', 'gray', 'loud']\nsize, color, disposition = cat\nprint(color)", "gray", ["fat", "loud", "['fat', 'gray', 'loud']"], "The names take the items from left to right.")
U("MultipleAssignment", "Understand", "What happens with a, b = [1, 2, 3]?", "A ValueError, because there are more items than names", ["a and b get 1 and 2 and the 3 is dropped", "a gets 1 and b gets [2, 3]", "A TypeError"], "The number of variables and the length of the list must be exactly equal.")
A("StarredUnpacking", "What does this program print?", "first, *rest = [1, 2, 3, 4]\nprint(first, rest)", "1 [2, 3, 4]", ["1 (2, 3, 4)", "1 2", "[1] [2, 3, 4]"], "The starred name collects the leftover items as a list.")
U("StarredUnpacking", "Understand", "What does the starred name receive in a, *m, z = [1, 2]?", "An empty list", ["None", "An error is raised", "The list [1, 2]"], "Two items fill a and z, and nothing is left for the starred name.")
# ---------------------------------------------------------------- sequences and references
U("SequencesReferences", "Understand", "What is the chapter's summary of how variables hold lists?", "A variable holds a reference to the list, not the list itself", ["A variable holds a copy of the list", "A variable holds the length of the list", "A variable holds the first item of the list"], "Variables never contain values; they contain references to values.")
U("SequenceTypes", "Remember", "Which are the sequence data types the chapter names?", "Lists, strings, range objects and tuples", ["Lists, dictionaries, sets and tuples", "Lists, integers, floats and strings", "Lists, files, ranges and functions"], "The Python sequence data types include lists, strings, range objects and tuples.")
A("StringSequence", "What does this program print?", "name = 'Zophie'\nprint(name[0], name[-2], name[0:4], 'Zo' in name)", "Z i Zoph True", ["Z e Zoph True", "Z i Zop True", "Z i Zoph False"], "A string is indexed, sliced and searched like a list of characters.")
U("StringSequence", "Understand", "Which operations work on strings the same way as on lists?", "Indexing, slicing, for loops, len and in", ["append, sort and reverse", "item assignment and del", "extend and insert"], "The sequence operations are shared; the changing methods are not.")
A("MutableImmutable", "What does this program print?", "name = 'Zophie a cat'\ntry:\n    name[7] = 'the'\nexcept TypeError as e:\n    print(e)", "'str' object does not support item assignment", ["'str' object has no attribute 'the'", "list index out of range", "'tuple' object does not support item assignment"], "A string is immutable, so assignment to one of its characters raises a TypeError.")
U("MutableImmutable", "Analyze", "After eggs = ['A', 'B', 'C'] and eggs = ['x', 'y', 'z'], what happened to the first list?", "It was not modified; a new list replaced it under the name eggs", ["It was modified in place", "It was copied into the new list", "It was sorted"], "Reassigning the name binds it to a new list; changing in place needs del and append.")
A("TupleType", "What does this program print?", "print(type(('hello',)).__name__, type(('hello')).__name__)", "tuple str", ["tuple tuple", "str str", "str tuple"], "A tuple of one value needs the trailing comma; without it the parentheses only group.")
U("TupleType", "Understand", "What is the main difference between a tuple and a list?", "A tuple cannot be changed after it is made", ["A tuple is written with square brackets", "A tuple can hold only numbers", "A tuple has no length"], "Tuples, like strings, are immutable.")
U("References", "Understand", "What is the chapter's better metaphor for a variable than a box?", "A paper name tag attached to a value with string", ["A drawer that holds a copy of the value", "A label painted on the value", "A number that counts the uses of the value"], "Variables are paper name tags attached to values.")
A("Aliasing", "What does this program print?", "spam = [0, 1, 2, 3]\neggs = spam\neggs[1] = 'Hello!'\nprint(spam)", "[0, 'Hello!', 2, 3]", ["[0, 1, 2, 3]", "['Hello!', 1, 2, 3]", "[0, 'Hello!']"], "eggs = spam copies only the reference, so both names refer to one list.")
U("Aliasing", "Understand", "After spam = 42, eggs = spam and spam = 99, what is eggs?", "42", ["99", "None", "[42, 99]"], "The reassignment attaches the name spam to a new value; eggs still refers to 42.")
A("ListArguments", "What does this program print?", "def eggs(some_parameter):\n    some_parameter.append('Hello')\n\nspam = [1, 2, 3]\neggs(spam)\nprint(spam)", "[1, 2, 3, 'Hello']", ["[1, 2, 3]", "None", "['Hello']"], "The parameter refers to the caller's list, so the append changes it.")
U("ListArguments", "Analyze", "A function does p = p + ['x'] on its list parameter p. What does the caller's list show?", "No change, because + built a new list and only the parameter's name moved to it", ["The new item, because lists are passed by reference", "A TypeError", "The item added twice"], "Assignment to the parameter does not affect the caller's name.")
A("ReplicationAliasing", "What does this program print?", "g = [[0] * 3] * 2\ng[0][0] = 9\nprint(g)", "[[9, 0, 0], [9, 0, 0]]", ["[[9, 0, 0], [0, 0, 0]]", "[[0, 0, 0], [0, 0, 0]]", "[[9, 9, 9], [0, 0, 0]]"], "The two rows are one inner list referred to twice.")
U("ReplicationAliasing", "Understand", "How can a grid of independent rows be built?", "With a comprehension: [[0] * 3 for _ in range(2)]", ["With [[0] * 3] * 2", "With [0] * 6", "With copy.copy on the first row only"], "The comprehension evaluates [0] * 3 once for every row.")
U("Copying", "Understand", "Which module provides copy.copy and copy.deepcopy?", "copy", ["list", "random", "sys"], "Python provides a module named copy for the purpose.")
A("ShallowCopy", "What does this program print?", "import copy\nspam = ['A', 'B', 'C']\ncheese = copy.copy(spam)\ncheese[1] = 42\nprint(spam, cheese)", "['A', 'B', 'C'] ['A', 42, 'C']", ["['A', 42, 'C'] ['A', 42, 'C']", "['A', 'B', 'C'] ['A', 'B', 'C']", "['A', 42, 'C'] ['A', 'B', 'C']"], "The copy is a separate list, so replacing one of its items does not reach the original.")
U("ShallowCopy", "Analyze", "After c = copy.copy([[1], [2]]) and c[0].append(9), what is the original list?", "[[1, 9], [2]], because the inner list is shared", ["[[1], [2]]", "[[1, 9], [2, 9]]", "[[9], [2]]"], "A shallow copy shares the objects it holds.")
A("DeepCopy", "What does this program print?", "import copy\nspam = [[1], [2]]\nc = copy.deepcopy(spam)\nc[0].append(9)\nprint(spam, c)", "[[1], [2]] [[1, 9], [2]]", ["[[1, 9], [2]] [[1, 9], [2]]", "[[1], [2]] [[1], [2]]", "[[1, 9], [2]] [[1], [2]]"], "The deep copy copies the inner lists, so nothing is shared.")
U("DeepCopy", "Understand", "When is copy.deepcopy needed?", "When the list contains lists or dictionaries that the program will change", ["When the list holds only numbers", "When the list is empty", "Whenever a list is printed"], "The shallow copy is enough for immutable items.")
# ---------------------------------------------------------------- random choices and programs
U("RandomPrograms", "Understand", "What do the four programs of the chapter have in common?", "Each is built around a list", ["Each reads a file", "Each uses a dictionary", "Each uses a class"], "The programs are the test of the chapter: each uses list operations for a purpose.")
U("RandomLists", "Understand", "Which two functions of the random module take a list in the chapter?", "random.choice and random.shuffle", ["random.random and random.seed", "random.randint and random.uniform", "random.sample and random.seed"], "The group explains random.choice and random.shuffle.")
A("RandomChoice", "Which statement about this program is true?", "import random\npets = ['Dog', 'Cat', 'Moose']\nprint(random.choice(pets) in pets, len(pets))", "True 3", ["False 3", "True 2", "True 4"], "choice returns an item of the list and does not change the list.")
U("RandomChoice", "Understand", "What does random.choice([]) raise?", "An IndexError", ["A ValueError", "A KeyError", "Nothing; it returns None"], "There is nothing to choose from in an empty sequence.")
A("RandomShuffle", "What does this program print?", "import random\npeople = ['Alice', 'Bob', 'Carol', 'David']\nprint(random.shuffle(people), sorted(people))", "None ['Alice', 'Bob', 'Carol', 'David']", ["['Alice', 'Bob', 'Carol', 'David'] None", "None None", "None ['David', 'Carol', 'Bob', 'Alice']"], "shuffle reorders the list in place and returns None; sorting shows the same four items.")
U("RandomShuffle", "Understand", "Why does random.shuffle(('a', 'b')) raise a TypeError?", "A tuple cannot be changed in place", ["A tuple has no length", "shuffle needs three items", "Strings only can be shuffled"], "shuffle modifies the list in place and so needs a mutable sequence.")
U("Programs", "Understand", "What do the programs of the group show about checking edge cases?", "They should be tested on the empty list and the one-item list", ["Edge cases need no tests", "Only long lists need tests", "Only the Magic 8 Ball has edge cases"], "Each program is a model for the habit of testing small lists.")
A("MagicEightBall", "What does this program print?", "messages = ['It is certain', 'It is decidedly so', 'Yes definitely']\nprint(len(messages) - 1)", "2", ["3", "1", "0"], "The largest index of a list of three items is 2, the upper bound for randint.")
U("MagicEightBall", "Understand", "What is the benefit of putting the answers in a list?", "Answers can be added or removed without changing other lines", ["The answers are sorted automatically", "The program runs faster", "The answers cannot repeat"], "The chapter says to change fewer lines when strings are added and removed.")
A("MatrixScreensaver", "What does this program print?", "WIDTH = 70\ncolumns = [0] * WIDTH\ncolumns[3] = 5\ncolumns[3] -= 1\nprint(len(columns), columns[3], columns[4])", "70 4 0", ["70 5 0", "71 4 0", "70 4 4"], "The list has one counter per column; the counter at index 3 counted down once.")
U("MatrixScreensaver", "Understand", "In the screensaver, what does a counter above zero mean?", "A stream of digits is running in that column", ["The column is blank", "The program is about to stop", "The column has been printed twice"], "A counter above zero prints a random 0 or 1 and counts down.")
A("CommaCode", "What does this program print?", "def comma_code(items):\n    if len(items) == 0:\n        return ''\n    if len(items) == 1:\n        return items[0]\n    return ', '.join(items[:-1]) + ', and ' + items[-1]\n\nprint(comma_code(['apples', 'bananas', 'tofu', 'cats']))", "apples, bananas, tofu, and cats", ["apples, bananas, tofu, cats", "apples bananas tofu and cats", "and apples, bananas, tofu, cats"], "All items but the last are joined with a comma and a space, then ', and ' and the last item are added.")
U("CommaCode", "Understand", "Which edge case does the chapter ask to test for Comma Code?", "The empty list", ["A list of one hundred items", "A list of numbers", "A list of lists"], "items[-1] on an empty list would raise an IndexError.")
A("CoinFlipStreaks", "What does this program print?", "flips = ['H', 'T', 'T', 'T', 'T', 'T', 'T', 'H']\nprint([flips[i:i + 6] == ['T'] * 6 for i in range(len(flips) - 5)])", "[False, True, False]", ["[True, True, True]", "[False, False, False]", "[False, True]"], "Three windows of six items exist in a list of eight, and only the middle one is all T.")
U("CoinFlipStreaks", "Understand", "Why does the program count an experiment once even if it has several streaks?", "It breaks out of the search at the first streak", ["It sorts the flips first", "It removes the streak from the list", "It runs 100 experiments only"], "Counting once is what the break does.")
# ---------------------------------------------------------------- extra items
A("ListLength", "What does this program print?", "spam = ['cat', 'dog']\nspam.append('bat')\nprint(len(spam))", "3", ["2", "1", "4"], "len is evaluated after the append, so the list has three items.")
A("Index", "What does this program print?", "spam = ['a', 'b', 'c']\nprint(spam[len(spam) - 1] == spam[-1])", "True", ["False", "IndexError", "None"], "The last index len(spam) - 1 and the index -1 name the same item.")
A("Slice", "What does this program print?", "spam = [0, 1, 2, 3, 4, 5]\nprint(spam[2:100], spam[4:2])", "[2, 3, 4, 5] []", ["IndexError", "[2, 3, 4, 5] [4, 3]", "[2, 3, 4, 5, 6, 7] []"], "A slice never raises an error for an end that is too far, and a start after the end gives an empty list.")
A("Membership", "What does this program print?", "print(1 in [1.0], 'ab' in 'cabd', 'ab' in ['cabd'])", "True True False", ["False True False", "True False False", "True True True"], "1 == 1.0, a substring test succeeds, and 'ab' is not an item of the list.")
A("SortMethod", "What does this program print?", "try:\n    [1, 3, 2, 'Alice'].sort()\nexcept TypeError:\n    print('TypeError')", "TypeError", ["[1, 2, 3, 'Alice']", "['Alice', 1, 2, 3]", "None"], "Python cannot compare a number with a string.")
A("PopMethod", "What does this program print?", "try:\n    [].pop()\nexcept IndexError as e:\n    print(e)", "pop from empty list", ["list index out of range", "pop expected 1 argument", "None"], "pop on an empty list raises an IndexError with its own message.")
A("IndexMethod", "What does this program print?", "print(['a', 'b', 'a'].index('a', 1))", "2", ["0", "1", "ValueError"], "The search starts at position 1 and finds the second 'a'.")
A("Aliasing", "What does this program print?", "spam = [1]\neggs = spam\nspam = spam + [2]\nprint(eggs)", "[1]", ["[1, 2]", "[2]", "[]"], "spam + [2] builds a new list, so eggs still refers to the old one.")


def build():
    out = []
    # balanced cycle of answer positions: blocks of eight with each position twice, blocks permuted
    cyc = [0, 1, 2, 3, 2, 3, 0, 1, 1, 0, 3, 2, 3, 2, 1, 0]
    for k, it in enumerate(ITEMS):
        pos = cyc[k % len(cyc)]
        opts = list(it["wrong"]); opts.insert(pos, it["right"])
        d = dict(concept=it["concept"], level=it["level"], q=it["q"])
        if it["level"] == "Apply":
            d["code"] = it["code"]
        d.update(options=opts, answer=pos, why=it["why"])
        out.append(d)
    return out


if __name__ == "__main__":
    bank = build(); bad = 0
    for it in ITEMS:
        if it["level"] != "Apply":
            continue
        r = subprocess.run([PY, "-c", it["code"]], capture_output=True, text=True, stdin=subprocess.DEVNULL, timeout=20)
        got = r.stdout.strip() if r.returncode == 0 else [l for l in r.stderr.strip().splitlines() if l.strip()][-1].split(":")[0]
        if got != it["right"]:
            bad += 1; print("MISMATCH", it["concept"], repr(got), "!=", repr(it["right"]))
    here = os.path.dirname(os.path.abspath(__file__))
    json.dump(bank, open(os.path.join(here, "question_bank_v2_0_0.json"), "w"), indent=1, ensure_ascii=False)
    print(len(bank), "items written;", sum(1 for i in bank if i["level"] == "Apply"), "Apply programs run;", bad, "mismatches")
