"""Visual check for the chapter 4 deck: every value the deck's five diagrams show must be one the specification
produces NOW. The specification is regenerated by running visuals_make under the interpreter given, and each value it
contains - every frame of every recorded moment of the call stack and the text printed by then, every class of every
exception chain, every function of the scope table with the verdict the symbol table gave it, every call of the
parameter table with the result or the exact TypeError text it really raised, and the name each resolution column
really found - is looked for in the text of the deck's slides. A diagram that shows a value the code no longer
produces, or that leaves one of its rows out, is refused.
Usage: visual_check_v1_0_0.py <deck.pptx> <visuals_make.py> <python>     Exits 1 on any mismatch."""
__version__ = "1.0.0"
import html, json, os, re, subprocess, sys, tempfile, zipfile

deck, maker, PY = sys.argv[1], sys.argv[2], sys.argv[3]
tmp = os.path.join(tempfile.mkdtemp(), "v.json")
subprocess.run([PY, maker, tmp], check=True, capture_output=True)
V = json.load(open(tmp))

z = zipfile.ZipFile(deck)
slides = []
for n in sorted([n for n in z.namelist() if re.match(r"ppt/slides/slide\d+\.xml$", n)], key=lambda n: int(re.findall(r"\d+", n)[0])):
    x = z.read(n).decode("utf-8")
    slides.append(re.sub(r"\s+", " ", " ".join(html.unescape(a) for a in re.findall(r"<a:t>([^<]*)</a:t>", x))))
flat = [re.sub(r"\s+", "", s) for s in slides]


def need(label, value):
    v = re.sub(r"\s+", "", str(value))
    return (label, value) if not any(v and v in f for f in flat) else None


wanted = []
S = V["CallStackOrder"]
for i, st in enumerate(S["steps"]):
    wanted.append(("call stack step %d, what happened" % i, ("call " if st["event"] == "call" else "return from ") + st["func"]))
    for fn in st["stack"]:
        wanted.append(("call stack step %d, a frame" % i, fn))
    wanted.append(("call stack step %d, printed so far" % i, st["out"] or "(nothing yet)"))
S = V["ExceptionHierarchy"]
for r in S["rows"]:
    for cls in r["chain"]:
        wanted.append(("exception chain of %s" % r["name"], cls))
S = V["ScopeIdentification"]
for r in S["rows"]:
    wanted.append(("scope rule for %s" % r["function"], r["function"] + " - " + r["condition"]))
    wanted.append(("scope verdict for %s" % r["function"], r["verdict"]))
S = V["PositionalOnlyParameter"]
for r in S["rows"]:
    wanted.append(("parameter-kind call", r["call"]))
    wanted.append(("parameter-kind result of %s" % r["call"], r["result"]))
S = V["NameResolution"]
for r in S["rows"]:
    wanted.append(("name resolution place", r["place"]))
    wanted.append(("name resolution result for %s" % r["place"], "found: " + r["found"]))

bad = [b for b in (need(l, v) for l, v in wanted) if b]
print("%d visual values re-checked against the specification regenerated under %s; %d mismatch(es)"
      % (len(wanted), subprocess.run([PY, "-c", "import platform;print(platform.python_version())"], capture_output=True, text=True).stdout.strip(), len(bad)))
for b in bad:
    print("  REFUSED", b)
sys.exit(1 if bad else 0)
